<?php
/**
 * @file
 * argus_verslagen.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function argus_verslagen_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'huisstijl',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '006f0126-bc0e-4ef8-a3dd-db08be32f980',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'reserveringen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '01c0c62b-9b6d-4659-ae57-2826593a242f',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'kwartaaloverleg',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '02ec22ab-cc62-4eda-97b0-b09be84319c0',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'elektriciteit',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '033ab46e-90f6-4d8d-839a-24e1c6a31f29',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'BSEC',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '03f7bc5b-fd3c-47ab-8cc5-7dcc799a0fc4',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bijzondere prijzen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '04292705-a1d2-4322-b3a0-5f3af1fd7693',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'administratie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '044e9a3a-9cad-49aa-aa12-c75a2b85292d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'nascholingsplan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '058992a9-0bee-49db-b833-b699967b168f',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'namiddagstudie E1 15u30',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0af53ef3-1f5b-4c49-8d4a-528d3b7c174c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'brief na BKR D1',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0c8ad10a-6a51-4f21-a216-be678d5a0c57',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'ontwerp en design',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '0e39b771-b46b-4edc-8dc6-5c57a28de0ef',
    'vocabulary_machine_name' => 'tags',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'afspraken',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '10827774-e7c9-4226-808f-431611118395',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'E1 namiddagstudie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '10cb446e-b9f1-4ccb-b09c-0d48d299e611',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'mechanica',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '117af08f-a022-4541-9972-d7be1796cc21',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => '5e jaar',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '11b2a91b-2a79-407b-9884-68ee5a9aba55',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'staf',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1220f061-139f-4164-b4e2-b9d3b923f90d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'steam',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '12f7ba3f-874a-4bc3-a46b-ca6383799aca',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'logboek',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '13dfe41d-a07d-478c-99d6-20b725e8091c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'vervanging',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '14a2269d-ce5b-4cec-aafc-f4383f3f44f2',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'carrosserie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '15bc730c-479a-40c4-869f-24005f11e811',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'kwartaal overleg- traject kwaliteitszorg',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '16609830-35ed-443c-9191-cc9a3014e838',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'boekhouding',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '16f6c79e-ec0e-4762-ac13-2281cec26d78',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'werken met machines',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '18e000b2-d942-47cb-8f67-d8d0e4b34197',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'techniekdorp',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1badf7a4-c045-45b7-8927-199ef6c3ca2d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'programmeren',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1bd06abc-25b0-434a-be11-702226f9ec13',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'website',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1c6c7705-911c-48b1-bdff-ff78f272dade',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'chrysostomos vervangingen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1c77da70-05bd-4390-a0ab-4b35b6ae1571',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'knelpuntberoep',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1ce4db5f-06e2-4652-9a1b-7d693d6969be',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'IKZ',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2009e0a8-9a04-4839-9903-2d99feffa614',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'schoolontwikkelingsplan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '210f1666-e3ce-413f-b939-9f0771945803',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => '4e jaar',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '21378f9f-27e7-41ff-aa0f-118aa77f182c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'begroting',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2375b9eb-41e4-4229-af3f-5526d36376c0',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'rooster',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '240c7386-6ab0-4c93-92d2-c7fe4c767bf5',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'vervanger strafstudie 2de trimester',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2587c431-391c-4f70-aa12-0fccb515af3c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'beleidsorgaan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '260a2217-9fa8-4dec-bd3c-830fa77c3e4f',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Smartschool',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '290ce68f-66da-4a68-a13a-8174cacb83b4',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'drukken',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '29d76360-81aa-4fee-8dd4-6e6f37c79667',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'peter',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '29d8d136-a0ec-4d46-b73d-6e574ef4cdfa',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'EHBO',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2b03b55b-ef25-4b1d-a8fe-b8f64c5c1ae7',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'vrijdag december zelfevaluatie stappenplan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2bb0e66d-c817-43ba-a0de-2012b51be5dc',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'aankoop',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2d41e9c4-72b6-4923-9255-a6742aac64c3',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'veiligheid',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2fbb04ab-4948-4877-a739-22eac9113587',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => '3D',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '30ba09e4-ece9-43db-95cf-93adcdf10c09',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'ta',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '31386e62-064d-496c-8d8e-8f332da21f89',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'evaluatie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '31550832-6d25-4bf8-8292-4e744ca7964f',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'examen refter',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '320f1c21-a10b-4552-8951-49540745f894',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => '2e jaar',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '33a7873d-94f2-4672-88f6-cf54b77807d8',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'projectgroep',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '346fe68e-8086-434a-9225-e1bf5d679584',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'werkgroep sanctioneringsbeleid',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '35338d4d-761f-490e-ac6e-2fe14919b22e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'E2',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '36b64efc-c23a-4a1b-b034-26ce34a1b1e6',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'mvd',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '380078c3-302a-4942-95cc-2e39dbefd8f8',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'GWP',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '384b899b-8d2b-4728-929e-938f274c1f71',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'evacuatie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '38b2e9a6-d89d-452d-9979-584d993d89b4',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'GWP Londen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3993a230-2caf-46fa-8b3a-4abe70117dcd',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'groep',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3aa26fc7-5e9e-48c0-ab91-4d49229909ce',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'examens',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3ab44230-adf9-4dda-a38f-a5306d30e043',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'kapitaalsaankopen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3d0ba7d7-4dae-49b0-b0ea-163cf519890f',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'rooster ros',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3d5c5de0-f3a0-4db9-b06a-e118f5d3b867',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'werkgroep',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3eca8179-aa1c-4cb8-b2fa-4845a12a720d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'drukken en afwerken',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3ecfd808-fe3d-482a-8349-87d3f2cdfe2a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'ouderavond',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3f8a0c06-e7ba-41a9-8265-1e41f3b4cabf',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'www.kta1-hasselt.be',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3f94690b-8598-4ff7-bbdd-5e911fd6acb9',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'reserveren',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '41101944-ba91-4803-a27f-413e2fc712b4',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'vervanging GWP Berlijn',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '41731ca4-ff1b-4432-b923-c74c30defbda',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'ilb',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4199bd87-34cb-459e-b962-140379f10ce7',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'uurrooster',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '42228c9c-fb3d-4d62-ae7d-ec752d168b03',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'development',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '43b344a3-bb24-49e5-92a5-7ad57bcaa662',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'tkz',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '441401d0-f0ca-4ef1-9217-b2ee9b4ef8b3',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'tadd',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4488ee8d-0161-4796-b8f5-31c54e76cdf9',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'rtc',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '45777d6b-6c6b-4b39-b895-b2bd906e51ca',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'afwezigheden',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '45affada-bb11-4244-8fb8-60ef68df1f84',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'schoolraad',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '45b1ca30-cccf-468d-852a-294d915dd52b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'polderklas',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '468d5f67-2807-4759-8b51-b2aa31e4b2aa',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'vdab',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4708b0eb-7777-4599-b2a0-c8590d70702e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'vaste benoeming',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '470aabec-bc94-42e0-ac21-4b81a543f715',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'PBM',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4a36d6e8-e072-4ad4-8c96-f1edfc05bfea',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'sanctioneringsbeleid',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4ae72c5a-1817-4931-9e0a-d777859bf973',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'permanentie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4bcc730b-e6a5-48cb-b01d-4f50a9c78b6f',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'huiskleuren',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4cca4293-1eb7-454e-a03f-db4317c9cebc',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'uitgesteld',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '503a3837-7aff-4513-890e-74dd205838ee',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'moderne wetenschappen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '530911b8-f9fa-41d1-a445-99c6dabf3a6a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'rijbewijs op school',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '575167d3-d53d-4d06-9d69-c8ab772ed61d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'hrm',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5932a730-68d3-414e-a014-e0b26cd9e258',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => '12u',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '59c7937c-caa4-483f-a224-baf294681990',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => '6e jaar',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5a7a47f1-9691-4ed0-a6ee-81fcab26858b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'todo',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5a7debeb-2042-4897-910c-c714a72a46b8',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bkr',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5aa3dac0-7124-4987-ad0d-90b9a7b90cc9',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'inschrijvingen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5aea3a6c-f1a7-4ac6-bbe9-3b4397d0c63b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'camera',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5b17f623-4f7a-45d0-99b2-625b7352fcfa',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'algemeen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5c1be232-c76f-4510-85e5-390e68364f1c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'ontlenen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5d6ec6b0-5250-4703-aca9-7634b53d4cc5',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'gip',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5e6a4d3d-9d11-4682-8e6d-38a8eea6c1cf',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'laptop',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '60464ebb-7333-407d-97bb-4f01eaab5ccf',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'noodplan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '62eccb2e-28a9-45dc-82ee-2dabdc56db90',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'voorbeeldbericht',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '64468ccd-1794-4008-8eee-dedabeb95313',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'lessentabel',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6511af9b-92d6-4a3f-a46d-c3a21bfa9e3b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'kwalteit',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '677948a0-6d25-4a0c-8594-6d6853e6820f',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'ontwikkeling',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '67c3b093-ad2d-4c7f-8777-2bc6bd212041',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'aankopen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '687d69e2-ae4f-4ff0-b472-a3f45a5a71e0',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'kapitaal',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '68fc57ff-23a7-4acd-9f79-4b849b693a0d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 2015,
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '69978442-9c64-4d30-b45a-e15ec4480797',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'nieuwe leerlingen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6a0c0bc5-99ad-496e-a832-223a7bec123e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'vierjaarlijks overleg',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6a3c42c4-facb-49d1-b87c-3cb4d4055707',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => '4-jaarlijks overleg',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6cc5ec60-71bd-40f0-873a-d785f45658b0',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'IW',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6d67ff84-c97e-4e81-8101-d8502d7a446e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'infoschermLKR',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6e06022f-171d-4d48-aa36-84a00c000e85',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'magazijn',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6f13d1bd-8304-4388-8f7d-d51d2116f548',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'ict',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6f361db0-b2fd-418c-a7b8-8ad6b3fe1423',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'studiekeuze',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7055849a-3bbe-46a9-8c02-72dba8f7bfa0',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'werkgroepen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '705bf36f-902c-4082-83b8-7e0959abbcba',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'hout',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '716669a7-818e-4a02-ae9c-72dc36316132',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'template',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7233072b-b05f-4e9a-aa9d-aff9e7e3ca50',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Alle opleidingen',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '7343c267-bba3-4588-8266-49d2c05d4d83',
    'vocabulary_machine_name' => 'tags',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'metaal bewerken',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '74411332-d103-49d6-bc43-b4e50e7b91a7',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'dienstmededeling',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '74f98291-17a7-4473-9ca9-99632cd448b1',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'nood',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '75269f3a-7c75-4779-8659-be15656f4e7c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'basismechanica',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7962679b-da12-4280-8837-883945fe6d96',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'keuring',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7a54fb06-6872-4b6f-b386-508656b90e31',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'stem',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7b44ce2f-9e71-45c5-ac16-246215f564f9',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'wetenschappen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7c21b9e1-625e-4b89-81a7-e30e133ec65d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'welzijn',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7d03c29b-07c1-45e9-87aa-8c0c6840eefc',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'maandelijks overleg',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7dddbadb-49a7-4c4d-9bf3-f00385e881e6',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'logo',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7f3826ff-c8aa-4e88-b999-c19eb57f9c7a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'beamer',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7fd42088-9091-45cb-b7a8-ffd035e50374',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'herexamen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '816cc06b-d565-4469-9a12-99d5468272d6',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'event',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '82c54515-c5a9-45dc-887f-ca63c9ea3d0d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'IKZ wekelijks overleg',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '83a18c24-3497-4ab4-8ec5-62a76636fd15',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'eindejaarsactiviteiten',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '84138e7f-87b9-44ac-97ab-fd9017edaf7b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'werkgroep-sanctioneringsbeleid',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8467c967-cef1-41d2-9e99-9f7696e52164',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'blokstage',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '84af6235-40fc-4c21-93eb-83dcd2b3afb9',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'beleid',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '85094ad4-bd40-4e5d-8934-115ef6d42ae7',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'lvs',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '869012a9-f165-488d-8cc9-90347daacbc9',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'infoschermLLN',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '87f4da87-8c90-42c5-99ab-4b0e177eb70f',
    'vocabulary_machine_name' => 'tags',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'participatie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '89c0a1c4-8cbe-4660-aab4-00524d15bb8a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'volgorde',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8b3ba8f4-db99-4176-bde6-66a02d1a2add',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'begeleiding',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8bd2f8b7-3bd8-41c7-810b-3ad1c10ccd84',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'strafstudie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8c0493fb-a1fb-406c-98a0-d97bb44e6358',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'preventie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8dda549b-d76f-4fc6-b1c1-730fd0128dc8',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'toezicht ROS',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8ee30c36-3456-4eab-bd0c-4c9071fa7f58',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'leerlingen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8fb7dd0e-b8ca-48c5-bbc7-dfc54ab15b26',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'terugkomdag',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '90a73b5e-6cd7-4363-965c-aed0d90cc2df',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'meter',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '90db27f7-27b3-47a6-819a-be91bfd52dd1',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'schoolreglement',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '91d7c209-d11d-407d-aeed-6196a5cf0d08',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'vrijdag december zelfevaluatie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '922d42a0-5b80-4bef-a1b2-7fa81d9af0d5',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'industriële wetenschappen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '92a7b524-af59-4d4f-b15d-a6bf4fd7977e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => '3e jaar',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '92c6d927-ee15-4a59-8e76-2d50d32c02bf',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'openingsuren',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9426707e-6e7c-4162-926a-f1a12404fac1',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'lijst',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9760ecd8-8456-4f6f-b53d-612596577693',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'traject kwaliteitszorg',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '977b476c-d774-4f20-820d-a46c24107220',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'dm',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '97b6eaf6-620f-4022-8909-3f1626466c92',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'ros',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '97ba9904-6250-40e2-827e-f1257285207b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'communicatie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '97ffe355-03cc-45e4-94fb-1fce215b1a85',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'juni overzicht',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9b1b9d83-534f-493e-aca0-6a098f524188',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'ouders',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9b9effa1-1c59-4318-8b7f-675b1efe1fc9',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'auto',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9c7603e1-58d0-41a1-bd1d-b28ad0db7e10',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'fiets',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9d624825-a33d-4808-b195-5a1b03fb7a6f',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'jfk',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9e5a3106-52ef-48e6-b5bd-e814d1ef8a6a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'feedback',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9f61428d-55e0-4cfd-bf12-bfe5e0ecd812',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'toezicht',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a4932385-0dd0-446b-863e-5038225900e6',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'overzicht',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a5575ef9-18ed-42e1-b878-961a5c3a0b34',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'vervanger',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a56c1530-cd93-4cec-87c8-f1fd7bbcb311',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'argus',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a5f257d5-3770-450d-a011-e868053d82d3',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'opleidingen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a64e3234-814e-4569-a11e-9153b6758fbf',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'preventieregister',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a8ecc315-bd13-40b1-9e07-91352b604da4',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'kwaliteit',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'aaabde6d-0499-49d9-893c-01be179c527e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'communicatieplan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ab771a5a-e665-401c-b783-4c5221c94385',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => '10-dagen regeling',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'aeb5fa4b-d453-4946-82ad-b4e0b13fc56b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'vakantietaken',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'afcc73e0-a6c4-4e5f-a360-abbf67801764',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'namiddagstudie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'afeb0421-e05e-4a6e-94ae-b3ece9ef4e32',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'tekenen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b08380b8-6f7e-4a9d-a0c1-9138cc7bf736',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'IMA',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b15589c6-af00-4eb9-ab69-2efca893c1e7',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'houtbewerking',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b220bdac-4da1-4e8c-9942-86badf49c4a0',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'chrysostomos',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b23c327d-c26e-45bd-800b-1b559e6615fa',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'adhoc',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b342bb34-146b-4228-992c-16ec6bd27bad',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'schoolwerkplan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b36cdc60-eeb5-4ef7-8dcc-de4ef6edf528',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'overleg',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b39e8162-ddc2-4b35-bbd3-cb9060e9aac8',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => '1e jaar',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b3b8ac14-3c56-430e-84ea-ac6f59c7ffa3',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'leden vakgroep 1516',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b514c4dd-4a5d-4ba0-a234-cc4a3824f762',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'vervangingen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b61f0e9c-9c56-4299-80bb-ee6cbbb87588',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'tucht',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b78697e9-6f53-4a30-b43e-0559436f641d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'crisisplan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ba1f6187-fb9e-4596-b13d-2d6f8e624a26',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'examen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ba342504-e1b7-4f8a-b201-0442d927c957',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => '7e jaar',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bb8843c9-05a1-4d35-b9a8-7108e162e8db',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'grafische media',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bb8bbe31-5cba-436e-ac36-15f54470b19d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'brief',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bc02a241-8eee-4d93-841d-5946d7712d76',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'project',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bc676c37-3e7c-4b19-9d26-459be2e218d4',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'pasen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'be306653-eed2-4c59-8a87-6c193be8dc5a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'EMA',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'be3487d5-6feb-48c7-844f-450f7b69fe78',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'crisis',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c031ad19-28bd-416a-8460-025f4ec5e9c7',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'parallellie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c26fca0a-9edd-48a8-a0be-7d44b5c7a96e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'stage',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c39348a8-7d8d-488a-a6e2-58b0f42f11bb',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => '12u  binnenblijver E1',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c7a91568-4f15-4fb3-a5f9-bb8584e7650a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'elektromechanica',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c839d8db-87bf-4f1e-9df9-2d489479cdbb',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'uitgestelde proef',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c8ee0e01-2607-4a33-8824-5d5c794c3a99',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'wekelijks overleg',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c9b8fd52-6147-4fe3-a7f3-161c2f4d0e54',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'SOP',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c9cac7ab-ceef-4035-8a74-c91a4197e227',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'melding',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cd642f04-a06b-4d05-8d7d-115121ce4c44',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => '1A',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ce081407-0f83-46d7-831d-18d1abed091e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'multimedia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cebe6a56-b6a9-4788-8e0d-970e3acc85cb',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'vakantietaak',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd182a89c-9cf7-46fc-a729-50157d109828',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'investering',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd1cee234-4c4f-415a-8803-ce6b9712eb1f',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'financiën',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd1d2092b-07d9-4a86-84d8-679ffb4c54ca',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'EHBO-kistjes',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd1da43a1-6bc6-4e62-86b2-c7fa0a2d12af',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'infrastructuur',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd344fab1-a15d-41aa-b4e0-8b930dee6060',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'functiebeschrijving',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd4e6789e-7cde-4bcc-a26f-899397e9ab8a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'draaiboek',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd5fe0474-2a93-444d-a8c1-553fb3db9752',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'BSO',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd6525de1-de27-4477-ab54-4362a9a89a20',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'jfk nieuw',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd7490d56-b48d-4a52-9e44-bd1c24b89b0b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'informaticabeheer',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd772fa4e-b340-44fd-abdb-35b55811cc9b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => '3de trimester',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd7b842e7-ac93-4567-82af-59eacf7d4ac3',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => '2de trimester',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd8b2fd46-037f-4a86-a207-f480b4c0e3c3',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'voorbeeldbrief',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd927970e-eba1-45a0-8b11-a908e9ede288',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'werken met auto\'s',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'da4376e6-498c-4639-a813-ef14f8853a18',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'nascholing',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e0e38a4c-5815-4e1a-9ed4-49bca0f24eea',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'TSO',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e432e376-abbb-42f0-8049-bbd146d93005',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'boc',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e43f5126-ce95-43ee-831f-da90946e374e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'examen refter toezicht',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e5137d3a-94ee-43a7-80b7-21169e6d6449',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'raad van het GO!',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e528ec47-a207-4cb2-a15b-343bbf0a1953',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'bijzonder prijs',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e60dad2e-2d1c-4be8-89af-579127319a77',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'specialisatie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e6bffa64-59ee-42ea-91ce-247caf7cc713',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'personeel',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e6cd7b02-bf11-46b6-bb52-321bff315eec',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'ilb overleg',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e72351c7-03d4-448b-82b0-d3d072fd3a08',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'werktuigmachines',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'eb941e69-4dd3-4ef1-b6e8-2bb8fdd163d5',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'ZE bundel',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ebf18bb1-38d5-42ac-bd84-837900c1f362',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'getuigenis',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ec2aa0fa-fd4e-4da8-9c00-4efc66d3f026',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'metaalbewerking',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ef282360-1eb2-4d1d-b6d1-38746fc2666a',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'lokalen vrijdag',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'efa486cd-65c3-4b93-8841-a9088a006b49',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'technisch',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f20b4d5b-65ce-4345-90db-fa444185180d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'leerlingvolgsysteem',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f23758d9-ec74-49ce-a72b-17f5dd6d2720',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'swp',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f2878524-f7fc-4869-86bb-7986724d925f',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'praktijk',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f2e0d878-4518-4ede-ac93-fa977addfbaf',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'klas',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f30d7783-fcf8-47fb-b091-711a665034a6',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'oudercontact',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f3d87930-77e9-4025-bc4e-d8a8d1694dfb',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'uitlenen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f63668bc-c16c-4652-814c-fee9cb0e6151',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Dienstmededeling 1516-7',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f72ef87c-7a68-48d3-80fa-3c9f1268d19c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'beroeps',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f9022280-b127-43f4-a4c4-104fde325a61',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'stappenplan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fa400c38-6e4a-4ddc-af67-8275d0142a4b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'eerste graad',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fab79bc0-7778-4d7a-b5ba-13b2adc44a2e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'uitleenmateriaal',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fb2c34c4-4803-433c-bb7d-14aab961224c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'feedbackgroep',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fbb954e0-1ffc-4da4-8a7b-deac3776f8af',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'klassenraad',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fc0f3bf3-2406-4425-b508-8fbab8ce1137',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'raad van het GO',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fdb2b772-fc55-49e7-b54e-b474110e1daf',
    'vocabulary_machine_name' => 'tags',
  );
  return $terms;
}
