<?php
/**
 * @file
 * argus_gip.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function argus_gip_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'title' => 'Geïntegreerde proef',
  'log' => '',
  'status' => 0,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'type' => 'page',
  'language' => 'nl',
  'created' => 1449740433,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '7ad37400-f089-4a11-bf30-d4d1457fb853',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<h1>Status - werkjaar 2015-2016</h1>
<em>(als je het ingeleverde document wil herbekijken, dan kan je klikken op de datum)</em>

<table border="1" cellpadding="5" cellspacing="0" style="width:100%">
	<tbody>
		<tr>
			<td colspan="2" style="background-color:rgb(255, 255, 204); vertical-align:top"><strong>GIP</strong></td>
			<td style="background-color:rgb(255, 255, 204); vertical-align:top">Act. 1<br />
			<strong>22/09/2015</strong><br />
			Opgave GIP<br />
			Dossier</td>
			<td style="background-color:rgb(255, 255, 204); vertical-align:top">Act. 2<br />
			<strong>30/10/2015</strong><br />
			Lijst juryleden<br />
			Dossier</td>
			<td style="background-color:rgb(255, 255, 204); vertical-align:top">Act. 3<br />
			<strong>27/11/2015</strong><br />
			<br />
			Dossier</td>
			<td style="background-color:rgb(255, 255, 204); vertical-align:top">Act. 4<br />
			<strong>11/12/2015</strong><br />
			<br />
			Dossier</td>
			<td style="background-color:rgb(255, 255, 204); vertical-align:top">Act. 5<br />
			<strong>22/01/2016</strong><br />
			<br />
			Dossier</td>
			<td style="background-color:rgb(255, 255, 204); vertical-align:top">Act. 6<br />
			<strong>26/02/2016</strong><br />
			<br />
			Dossier</td>
			<td style="background-color:rgb(255, 255, 204); vertical-align:top">Act. 7<br />
			<strong>11/03/2016</strong><br />
			<br />
			Dossier</td>
			<td style="background-color:rgb(255, 255, 204); vertical-align:top">Act. 8<br />
			<strong>15/04/2016</strong><br />
			<br />
			Dossier</td>
			<td style="background-color:rgb(255, 255, 204); vertical-align:top">Act. 9<br />
			<strong>26/05/2016</strong><br />
			GIP-dossier<br />
			Binnen!</td>
			<td style="background-color:rgb(255, 255, 204); vertical-align:top">Volgorde</td>
		</tr>
		<tr>
			<td style="background-color:rgb(238, 238, 238); vertical-align:top"><strong>6 TSO</strong></td>
			<td style="background-color:rgb(238, 238, 238); vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="background-color:rgb(238, 238, 238); vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="background-color:rgb(238, 238, 238); vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="background-color:rgb(238, 238, 238); vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="background-color:rgb(238, 238, 238); vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="background-color:rgb(238, 238, 238); vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="background-color:rgb(238, 238, 238); vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="background-color:rgb(238, 238, 238); vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="background-color:rgb(238, 238, 238); vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="background-color:rgb(238, 238, 238); vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="background-color:rgb(238, 238, 238); vertical-align:top">&nbsp;</td>
		</tr>
		<tr>
			<td style="background-color:rgb(238, 238, 238); vertical-align:top">6 TIW</td>
			<td style="vertical-align:top">Leekracht A</td>
			<td class="rtecenter" style="vertical-align:top"><a href="/sites/default/files/WPL/GIP/2015-2016/aanvraagformulier_15_sept_2015.pdf">17/12</a></td>
			<td class="rtecenter" style="vertical-align:top"><a href="/sites/default/files/WPL/GIP/2015-2016/timing_gip_deel_1_24_sept_2015.pdf">17/12</a></td>
			<td class="rtecenter" style="vertical-align:top"><a href="/sites/default/files/WPL/GIP/2015-2016/timing_gip_deel_2_27_okt_2015.pdf">17/12</a></td>
			<td class="rtecenter" style="vertical-align:top"><a href="/sites/default/files/WPL/GIP/2015-2016/timing_gip_deel_3_7_dec_2015.pdf">17/12</a></td>
			<td class="rtecenter" style="vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="vertical-align:top"><a href="/sites/default/files/WPL/GIP/2015-2016/berichten904208.zip">29/06</a></td>
			<td class="rtecenter" style="vertical-align:top"><a href="/sites/default/files/WPL/GIP/2015-2016/volgorde_voorstelling_gip_2.docx">02/06</a></td>
		</tr>
		<tr>
			<td style="background-color:rgb(238, 238, 238); vertical-align:top">6 TIF</td>
			<td style="vertical-align:top">Leekracht B</td>
			<td class="rtecenter" style="vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="vertical-align:top">18/01</td>
			<td class="rtecenter" style="vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="vertical-align:top"><a href="/sites/default/files/WPL/GIP/2015-2016/uitvoeringsdossier_gip_6tif.doc">18/01</a></td>
			<td class="rtecenter" style="vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="vertical-align:top"><a href="/sites/default/files/WPL/GIP/2015-2016/uitvoeringsdossier_gip_6tif.pdf">30/06</a></td>
		</tr>
		<tr>
			<td style="background-color:rgb(238, 238, 238); vertical-align:top">6 TEM</td>
			<td style="vertical-align:top">Leekracht C</td>
			<td class="rtecenter" style="vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="vertical-align:top">21/01</td>
			<td class="rtecenter" style="vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="vertical-align:top"><a href="http://argus.kta1-hasselt.be/sites/default/files/WPL/GIP/2015-2016/informatieplan_gip_6tem.doc">21/01 </a></td>
			<td class="rtecenter" style="vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="vertical-align:top"><a href="/sites/default/files/WPL/GIP/2015-2016/informatieplan_gip_6tem_0.doc">15/03</a></td>
			<td class="rtecenter" style="vertical-align:top"><a href="/sites/default/files/WPL/GIP/2015-2016/informatieplan_gip_6tem_1.doc">15/04</a></td>
			<td class="rtecenter" style="vertical-align:top"><a href="/sites/default/files/WPL/GIP/2015-2016/informatieplan_gip_6tem_2.doc">29/05</a></td>
			<td class="rtecenter" style="vertical-align:top"><a href="/sites/default/files/WPL/GIP/2015-2016/volgorde_voorstelling_gip_6tem.docx">08/06</a></td>
		</tr>
		<tr>
			<td style="background-color:rgb(238, 238, 238); vertical-align:top">6 TMM</td>
			<td style="vertical-align:top">Leekracht D</td>
			<td class="rtecenter" style="vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="vertical-align:top">28/12</td>
			<td class="rtecenter" style="vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="vertical-align:top"><a href="/sites/default/files/WPL/GIP/2015-2016/uitvoeringsdossier_6tmm_-_1516_1.1.docx">28/12</a></td>
			<td class="rtecenter" style="vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="vertical-align:top"><a href="/sites/default/files/WPL/GIP/2015-2016/uitvoeringsdossier_6tmm_-_1516_1.docx">08/06</a></td>
			<td class="rtecenter" style="vertical-align:top">&nbsp;</td>
		</tr>
		<tr>
			<td style="background-color:rgb(238, 238, 238); vertical-align:top"><strong>6 BSO</strong></td>
			<td style="background-color:rgb(238, 238, 238); vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="background-color:rgb(238, 238, 238); vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="background-color:rgb(238, 238, 238); vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="background-color:rgb(238, 238, 238); vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="background-color:rgb(238, 238, 238); vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="background-color:rgb(238, 238, 238); vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="background-color:rgb(238, 238, 238); vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="background-color:rgb(238, 238, 238); vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="background-color:rgb(238, 238, 238); vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="background-color:rgb(238, 238, 238); vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="background-color:rgb(238, 238, 238); vertical-align:top">&nbsp;</td>
		</tr>
		<tr>
			<td style="background-color:rgb(238, 238, 238); vertical-align:top">6 BAU</td>
			<td style="vertical-align:top">Leekracht A</td>
			<td class="rtecenter" style="vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="vertical-align:top">18/01</td>
			<td class="rtecenter" style="vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="vertical-align:top"><a href="http://argus.kta1-hasselt.be/sites/default/files/WPL/GIP/2015-2016/uitvoeringsdossier_eindwerk_bso_2015-20161.doc_1.pdf">18/01 </a></td>
			<td class="rtecenter" style="vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="vertical-align:top"><a href="/sites/default/files/WPL/GIP/2015-2016/uitvoeringsdossier_eindwerk_bso_2015-20161.doc_1_0.pdf">20/03</a></td>
			<td class="rtecenter" style="vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="vertical-align:top"><a href="/sites/default/files/WPL/GIP/2015-2016/uitvoeringsdossier_eindwerk_bso_2015-20161.doc_1_1.pdf">07/06</a></td>
			<td class="rtecenter" style="vertical-align:top"><a href="/sites/default/files/WPL/GIP/2015-2016/volgorde_voorstelling_gip_1.docx">07/06</a></td>
		</tr>
		<tr>
			<td style="background-color:rgb(238, 238, 238); vertical-align:top">6 BCA1+2</td>
			<td style="vertical-align:top">Leekracht B</td>
			<td class="rtecenter" style="vertical-align:top"><a href="/sites/default/files/WPL/GIP/2015-2016/inhoudsopgave_gip_6bca_1_en_6bca2_2015_2016.doc">22/09</a></td>
			<td class="rtecenter" style="vertical-align:top">13/11</td>
			<td class="rtecenter" style="vertical-align:top"><a href="/sites/default/files/WPL/GIP/2015-2016/6bca-oktober.pdf">16/11</a></td>
			<td class="rtecenter" style="vertical-align:top"><a href="/sites/default/files/WPL/GIP/2015-2016/update_gip_6bca12.zip">08/01</a></td>
			<td class="rtecenter" style="vertical-align:top">&nbsp;</td>
			<td class="rtecenter" style="vertical-align:top"><a href="/sites/default/files/WPL/GIP/2015-2016/aangevuld_uitvoeringsdossier_gip_6_bso_carrosserie_12_schooljaar_2015_3_2016-1.pdf">29/02</a></td>
			<td class="rtecenter" style="vertical-align:top"><a href="/sites/default/files/WPL/GIP/2015-2016/aangevuld_uitvoeringsdossier_gip_6_bso_carrosserie_1en2_schooljaar_2015_2016.pdf">14/03</a></td>
			<td class="rtecenter" style="vertical-align:top"><a href="/sites/default/files/WPL/GIP/2015-2016/berichten841566.zip">15/04</a></td>
			<td class="rtecenter" style="vertical-align:top"><a href="/sites/default/files/WPL/GIP/2015-2016/berichten888440.zip">09/06</a></td>
			<td class="rtecenter" style="vertical-align:top"><a href="/sites/default/files/WPL/GIP/2015-2016/volgorde_voorstelling_gip_6bso_carrosserie_1_en_2.docx">06/06</a></td>
		</tr>
	</tbody>
</table>

<h1>Nuttige links</h1>

<ul>
	<li>Voor de GIP-coördinator:
	<ul>
		<li><a href="#" target="_blank">Externe juryleden</a></li>
		<li><a href="#">Evaluatieformulier TSO - GIP-coördinator</a></li>
		<li><a href="#">Evaluatieformulier BSO - GIP-coördinator</a></li>
		<li><a href="/wie-is-wie?rid[]=226" target="_blank">GIP-coördinatoren</a></li>
		<li><a href="#">Informatieplan TSO - GIP-coördinator</a></li>
		<li><a href="#">Informatieplan BSO - GIP-coördinator</a></li>
		<li><a href="#">Vademecum - GIP-coördinator</a></li>
		<li><a href="#">form_bespreking_product_gip.doc</a></li>
		<li><a href="#">volgorde_voorstelling_gip.docx</a></li>
	</ul>
	</li>
	<li>Voor de technische adviseur:
	<ul>
		<li><a href="#">gip_2015-2016.accdb</a></li>
		<li><a href="#">Brief externe juryleden (december) - TA</a></li>
		<li><a href="#">Formulier "attest" GIP - TA</a></li>
		<li><a href="#">Formulier bespreking productevaluatie - TA</a></li>
		<li><a href="#">Formulier inventaris GIP - TA</a></li>
		<li><a href="#">planning_gip_dag_2015-2016.docx</a></li>
	</ul>
	</li>
</ul>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_tags' => array(
    'und' => array(
      0 => array(
        'tid' => '5e6a4d3d-9d11-4682-8e6d-38a8eea6c1cf',
        'uuid' => '5e6a4d3d-9d11-4682-8e6d-38a8eea6c1cf',
      ),
    ),
  ),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'path' => array(
    'pathauto' => FALSE,
    'alias' => 'GIP',
  ),
  'webform' => array(
    'confirmation' => '',
    'confirmation_format' => NULL,
    'redirect_url' => '<confirmation>',
    'block' => 0,
    'allow_draft' => 0,
    'auto_save' => 0,
    'confidential' => 0,
    'submit_notice' => 1,
    'submit_text' => '',
    'next_serial' => 1,
    'submit_limit' => -1,
    'submit_interval' => -1,
    'total_submit_limit' => -1,
    'total_submit_interval' => -1,
    'progressbar_page_number' => 0,
    'progressbar_percent' => 0,
    'progressbar_bar' => 1,
    'progressbar_pagebreak_labels' => 1,
    'progressbar_include_confirmation' => 1,
    'progressbar_label_first' => 'Begin',
    'progressbar_label_confirmation' => 'Voltooid',
    'preview' => 0,
    'preview_next_button_label' => '',
    'preview_prev_button_label' => '',
    'preview_title' => '',
    'preview_message' => '',
    'preview_message_format' => NULL,
    'preview_excluded_components' => array(),
    'status' => 1,
    'record_exists' => FALSE,
    'roles' => array(
      0 => 1,
      1 => 2,
    ),
    'emails' => array(),
    'components' => array(),
    'conditionals' => array(),
  ),
  'comment_count' => 0,
  'domains' => array(
    1 => 1,
  ),
  'domain_site' => FALSE,
  'subdomains' => array(
    0 => 'argus',
  ),
  'num_revisions' => 1,
  'current_revision_id' => 63439,
  'is_current' => TRUE,
  'is_pending' => TRUE,
  'revision_moderation' => FALSE,
  'date' => '2015-12-10 10:40:33 +0100',
  'user_uuid' => '5e23f66a-32c6-4312-b7cc-2ce2429725c9',
);

  return $nodes;
}
