<?php
/*
 * Copyright (C) 2017 bartgysens
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* Drupal Hooks */

/**
 * Implements hook_ctools_plugin_api().
 */
function argus_sticker_onwettige_afwezigheid_ctools_plugin_api($module = NULL, $api = NULL) {
	if ($module == "field_group" && $api == "field_group") {
		return array (
				"version" => "1" 
		);
	}
}

/**
 * Implements hook_node_info().
 */
function argus_sticker_onwettige_afwezigheid_node_info() {
	$items = array (
			'msl_oa_sticker' => array (
					'name' => t ( 'MSL - Sticker onwettige afwezigheid' ),
					'base' => 'node_content',
					'description' => t ( 'Bij de procedure omtrent Onwettige Afwezigheden hoort het opvolgen van de afwezigheden door middel van het plakken van een <em>rode sticker</em>. Dit past binnen de Maatregelen bij Schending van de Leefregels - MSL.' ),
					'has_title' => '1',
					'title_label' => t ( 'Title' ),
					'help' => '' 
			) 
	);
	drupal_alter ( 'node_info', $items );
	return $items;
}

/**
 * Implement hook_form()
 */
function argus_sticker_onwettige_afwezigheid_form($node, $form_state) {
	return node_content_form ( $node, $form_state );
}

/**
 * Implementation of hook_views_api().
 */
function argus_sticker_onwettige_afwezigheid_views_api() {
	return array (
			'api' => 3.0,
			'path' => drupal_get_path ( 'module', 'argus_sticker_onwettige_afwezigheid' ) 
	) // replace demo with your content type
;
}