<?php
/*
 * Copyright (C) 2017 bartgysens
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* Drupal Hooks */

/**
 * Implements hook_ctools_plugin_api().
 */
function argus_jaarkalender_ctools_plugin_api($module = NULL, $api = NULL) {
	if ($module == "feeds" && $api == "feeds_importer_default") {
		return array (
				"version" => "1" 
		);
	}
	if ($module == "ds" && $api == "ds") {
		return array (
				"version" => "1"
		);
	}
}

/**
 * Implements hook_node_info().
 */
function argus_jaarkalender_node_info() {
	$items = array (
			'event_jaarkalender' => array (
					'name' => t ( 'Event - jaarkalender' ),
					'base' => 'node_content',
					'description' => t ( 'Inhoudstype voor events in de jaarkalender.' ),
					'has_title' => '1',
					'title_label' => t ( 'Title' ),
					'help' => '' 
			) 
	);
	drupal_alter ( 'node_info', $items );
	return $items;
}

/**
 * Implement hook_form()
 */
function argus_jaarkalender_form($node, $form_state) {
	return node_content_form ( $node, $form_state );
}

/**
 * Implementation of hook_views_api().
 */
function argus_jaarkalender_views_api() {
	return array (
			'api' => 3.0,
			'path' => drupal_get_path ( 'module', 'argus_jaarkalender' ) 
	) // replace demo with your content type
;
}

/**
 * Implementation of hook_views_default_views().
 *
 * Views export creates code that you have to paste in this function.
 *
 * Administration > Structure > Views : click the button behind the view you need and export
 * /admin/structure/views
 */
function argus_jaarkalender_views_default_views() {
	$view = new view ();
	$view->name = 'Jaarkalender';
	$view->description = '';
	$view->tag = 'default';
	$view->base_table = 'node';
	$view->human_name = 'Jaarkalender';
	$view->core = 7;
	$view->api_version = '3.0';
	$view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */
	
	/* Display: Master */
	$handler = $view->new_display ( 'default', 'Master', 'default' );
	$handler->display->display_options ['title'] = 'Jaarkalender';
	$handler->display->display_options ['use_more_always'] = FALSE;
	$handler->display->display_options ['use_more_text'] = 'meer';
	$handler->display->display_options ['access'] ['type'] = 'role';
	$roles = array ();
	$roleNames = array (
			'administrator',
			'personeelslid' 
	);
	foreach ( $roleNames as $role ) {
		$rid = user_role_load_by_name ( $role );
		if (! $rid) {
			$newRole = new stdClass ();
			$newRole->name = $role;
			user_role_save ( $newRole );
			
			$rid = user_role_load_by_name ( $role );
		}
		
		$roles [] = $rid->rid;
	}
	$handler->display->display_options ['access'] ['role'] = $roles;
	$handler->display->display_options ['cache'] ['type'] = 'views_content_cache';
	$handler->display->display_options ['cache'] ['results_min_lifespan'] = '-1';
	$handler->display->display_options ['cache'] ['results_max_lifespan'] = '518400';
	$handler->display->display_options ['cache'] ['output_min_lifespan'] = '-1';
	$handler->display->display_options ['cache'] ['output_max_lifespan'] = '518400';
	$handler->display->display_options ['cache'] ['keys'] = array (
			'comment' => array (
					'changed' => 0 
			),
			'node' => array (
					'event_jaarkalender' => 'event_jaarkalender' 
			),
			'node_only' => array (
					'node_changed' => 'node_changed' 
			) 
	);
	$handler->display->display_options ['query'] ['type'] = 'views_query';
	$handler->display->display_options ['exposed_form'] ['type'] = 'better_exposed_filters';
	$handler->display->display_options ['exposed_form'] ['options'] ['submit_button'] = 'Toepassen';
	$handler->display->display_options ['exposed_form'] ['options'] ['reset_button'] = TRUE;
	$handler->display->display_options ['exposed_form'] ['options'] ['reset_button_label'] = 'Opnieuw instellen';
	$handler->display->display_options ['exposed_form'] ['options'] ['exposed_sorts_label'] = 'Sorteren op';
	$handler->display->display_options ['exposed_form'] ['options'] ['expose_sort_order'] = FALSE;
	$handler->display->display_options ['exposed_form'] ['options'] ['sort_asc_label'] = 'Oplopend';
	$handler->display->display_options ['exposed_form'] ['options'] ['sort_desc_label'] = 'Aflopend';
	$handler->display->display_options ['exposed_form'] ['options'] ['autosubmit'] = FALSE;
	$handler->display->display_options ['exposed_form'] ['options'] ['bef'] = array (
			'general' => array (
					'allow_secondary' => 0,
					'secondary_label' => 'Uitgebreide opties',
					'collapsible_label' => NULL,
					'combine_rewrite' => NULL,
					'reset_label' => NULL,
					'bef_filter_description' => NULL,
					'any_label' => NULL,
					'filter_rewrite_values' => NULL 
			),
			'type' => array (
					'bef_format' => 'bef',
					'more_options' => array (
							'bef_select_all_none' => 0,
							'bef_collapsible' => 0,
							'is_secondary' => 0,
							'any_label' => '',
							'bef_filter_description' => '',
							'tokens' => array (
									'available' => array (
											0 => 'global_types',
											'secondary_label' => NULL,
											'collapsible_label' => NULL,
											'combine_rewrite' => NULL,
											'reset_label' => NULL,
											'bef_filter_description' => NULL,
											'any_label' => NULL,
											'filter_rewrite_values' => NULL 
									),
									'secondary_label' => NULL,
									'collapsible_label' => NULL,
									'combine_rewrite' => NULL,
									'reset_label' => NULL,
									'bef_filter_description' => NULL,
									'any_label' => NULL,
									'filter_rewrite_values' => NULL 
							),
							'rewrite' => array (
									'filter_rewrite_values' => '',
									'secondary_label' => NULL,
									'collapsible_label' => NULL,
									'combine_rewrite' => NULL,
									'reset_label' => NULL,
									'bef_filter_description' => NULL,
									'any_label' => NULL 
							),
							'secondary_label' => NULL,
							'collapsible_label' => NULL,
							'combine_rewrite' => NULL,
							'reset_label' => NULL,
							'filter_rewrite_values' => NULL 
					),
					'secondary_label' => NULL,
					'collapsible_label' => NULL,
					'combine_rewrite' => NULL,
					'reset_label' => NULL,
					'bef_filter_description' => NULL,
					'any_label' => NULL,
					'filter_rewrite_values' => NULL 
			),
			'secondary_label' => NULL,
			'collapsible_label' => NULL,
			'combine_rewrite' => NULL,
			'reset_label' => NULL,
			'bef_filter_description' => NULL,
			'any_label' => NULL,
			'filter_rewrite_values' => NULL 
	);
	$handler->display->display_options ['pager'] ['type'] = 'none';
	$handler->display->display_options ['pager'] ['options'] ['offset'] = '0';
	$handler->display->display_options ['style_plugin'] = 'calendar_style';
	$handler->display->display_options ['style_options'] ['name_size'] = '3';
	$handler->display->display_options ['style_options'] ['mini'] = '0';
	$handler->display->display_options ['style_options'] ['with_weekno'] = '0';
	$handler->display->display_options ['style_options'] ['multiday_theme'] = '1';
	$handler->display->display_options ['style_options'] ['theme_style'] = '1';
	$handler->display->display_options ['style_options'] ['max_items'] = '0';
	$handler->display->display_options ['row_plugin'] = 'fields';
	/* Veld: Inhoud: Titel */
	$handler->display->display_options ['fields'] ['title'] ['id'] = 'title';
	$handler->display->display_options ['fields'] ['title'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['title'] ['field'] = 'title';
	$handler->display->display_options ['fields'] ['title'] ['alter'] ['word_boundary'] = FALSE;
	$handler->display->display_options ['fields'] ['title'] ['alter'] ['ellipsis'] = FALSE;
	/* Veld: Inhoud: Datum */
	$handler->display->display_options ['fields'] ['field_pb_event_datum'] ['id'] = 'field_pb_event_datum';
	$handler->display->display_options ['fields'] ['field_pb_event_datum'] ['table'] = 'field_data_field_pb_event_datum';
	$handler->display->display_options ['fields'] ['field_pb_event_datum'] ['field'] = 'field_pb_event_datum';
	$handler->display->display_options ['fields'] ['field_pb_event_datum'] ['settings'] = array (
			'format_type' => 'long',
			'fromto' => 'both',
			'multiple_number' => '',
			'multiple_from' => '',
			'multiple_to' => '',
			'show_remaining_days' => 0,
			'show_repeat_rule' => 'show' 
	);
	/* Veld: Inhoud: Datum */
	$handler->display->display_options ['fields'] ['field_ev_datum_1'] ['id'] = 'field_ev_datum_1';
	$handler->display->display_options ['fields'] ['field_ev_datum_1'] ['table'] = 'field_data_field_ev_datum';
	$handler->display->display_options ['fields'] ['field_ev_datum_1'] ['field'] = 'field_ev_datum';
	$handler->display->display_options ['fields'] ['field_ev_datum_1'] ['settings'] = array (
			'format_type' => 'long',
			'fromto' => 'both',
			'multiple_number' => '',
			'multiple_from' => '',
			'multiple_to' => '',
			'show_remaining_days' => 0,
			'show_repeat_rule' => 'show' 
	);
	$handler->display->display_options ['fields'] ['field_ev_datum_1'] ['delta_offset'] = '0';
	$handler->display->display_options ['filter_groups'] ['operator'] = 'OR';
	/* Filtercriterium: Inhoud: Gepubliceerd */
	$handler->display->display_options ['filters'] ['status'] ['id'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['status'] ['field'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['value'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['expose'] ['operator'] = FALSE;
	/* Filtercriterium: Inhoud: Type */
	$handler->display->display_options ['filters'] ['type'] ['id'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['type'] ['field'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['value'] = array (
			'event_jaarkalender' => 'event_jaarkalender',
			'event_nascholing' => 'event_nascholing',
			'event_pedagogische_activiteit' => 'event_pedagogische_activiteit',
			'event_preventiebeleid' => 'event_preventiebeleid' 
	);
	$handler->display->display_options ['filters'] ['type'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['type'] ['expose'] ['operator_id'] = 'type_op';
	$handler->display->display_options ['filters'] ['type'] ['expose'] ['operator'] = 'type_op';
	$handler->display->display_options ['filters'] ['type'] ['expose'] ['identifier'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['expose'] ['remember'] = TRUE;
	$handler->display->display_options ['filters'] ['type'] ['expose'] ['multiple'] = TRUE;
	$handler->display->display_options ['filters'] ['type'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['filters'] ['type'] ['expose'] ['reduce'] = TRUE;
	$handler->display->display_options ['filters'] ['type'] ['group_info'] ['identifier'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['group_info'] ['multiple'] = TRUE;
	$handler->display->display_options ['filters'] ['type'] ['group_info'] ['remember'] = 1;
	$handler->display->display_options ['filters'] ['type'] ['group_info'] ['default_group'] = '4';
	$handler->display->display_options ['filters'] ['type'] ['group_info'] ['default_group_multiple'] = array (
			3 => '3' 
	);
	$handler->display->display_options ['filters'] ['type'] ['group_info'] ['group_items'] = array (
			1 => array (
					'title' => 'Nascholingen',
					'operator' => 'in',
					'value' => array (
							'event_nascholing' => 'event_nascholing' 
					) 
			),
			2 => array (
					'title' => 'Pedagogische activiteit',
					'operator' => 'in',
					'value' => array (
							'event_pedagogische_activiteit' => 'event_pedagogische_activiteit' 
					) 
			),
			3 => array (
					'title' => 'Personeel',
					'operator' => 'in',
					'value' => array (
							'event_jaarkalender' => 'event_jaarkalender' 
					) 
			),
			4 => array (
					'title' => 'Preventiebeleid',
					'operator' => 'in',
					'value' => array (
							'event_preventiebeleid' => 'event_preventiebeleid' 
					) 
			) 
	);
	/* Filtercriterium: Inhoud: Goedkeuring (field_ev_goedkeuring) */
	$handler->display->display_options ['filters'] ['field_ev_goedkeuring_value_1'] ['id'] = 'field_ev_goedkeuring_value_1';
	$handler->display->display_options ['filters'] ['field_ev_goedkeuring_value_1'] ['table'] = 'field_data_field_ev_goedkeuring';
	$handler->display->display_options ['filters'] ['field_ev_goedkeuring_value_1'] ['field'] = 'field_ev_goedkeuring_value';
	$handler->display->display_options ['filters'] ['field_ev_goedkeuring_value_1'] ['value'] = array (
			'Toegestaan' => 'Toegestaan' 
	);
	$handler->display->display_options ['filters'] ['field_ev_goedkeuring_value_1'] ['reduce_duplicates'] = TRUE;
	
	/* Display: Jaarkalender */
	$handler = $view->new_display ( 'page', 'Jaarkalender', 'events_jaarkalender' );
	$handler->display->display_options ['defaults'] ['use_ajax'] = FALSE;
	$handler->display->display_options ['defaults'] ['exposed_form'] = FALSE;
	$handler->display->display_options ['exposed_form'] ['type'] = 'better_exposed_filters';
	$handler->display->display_options ['exposed_form'] ['options'] ['submit_button'] = 'Toepassen';
	$handler->display->display_options ['exposed_form'] ['options'] ['reset_button'] = TRUE;
	$handler->display->display_options ['exposed_form'] ['options'] ['reset_button_label'] = 'Opnieuw instellen';
	$handler->display->display_options ['exposed_form'] ['options'] ['exposed_sorts_label'] = 'Sorteren op';
	$handler->display->display_options ['exposed_form'] ['options'] ['expose_sort_order'] = FALSE;
	$handler->display->display_options ['exposed_form'] ['options'] ['sort_asc_label'] = 'Oplopend';
	$handler->display->display_options ['exposed_form'] ['options'] ['sort_desc_label'] = 'Aflopend';
	$handler->display->display_options ['exposed_form'] ['options'] ['autosubmit'] = TRUE;
	$handler->display->display_options ['exposed_form'] ['options'] ['bef'] = array (
			'general' => array (
					'allow_secondary' => 0,
					'secondary_label' => 'Uitgebreide opties' 
			),
			'type' => array (
					'bef_format' => 'bef',
					'more_options' => array (
							'bef_select_all_none' => '1',
							'bef_collapsible' => 0,
							'is_secondary' => 0,
							'any_label' => '',
							'bef_filter_description' => '',
							'tokens' => array (
									'available' => array (
											0 => 'global_types' 
									) 
							),
							'rewrite' => array (
									'filter_rewrite_values' => '' 
							) 
					) 
			) 
	);
	$handler->display->display_options ['defaults'] ['pager'] = FALSE;
	$handler->display->display_options ['pager'] ['type'] = 'none';
	$handler->display->display_options ['pager'] ['options'] ['offset'] = '0';
	$handler->display->display_options ['defaults'] ['style_plugin'] = FALSE;
	$handler->display->display_options ['style_plugin'] = 'fullcalendar';
	$handler->display->display_options ['style_options'] ['defaultView'] = 'basicWeek';
	$handler->display->display_options ['style_options'] ['firstDay'] = '1';
	$handler->display->display_options ['style_options'] ['right'] = 'month basicWeek basicDay';
	$handler->display->display_options ['style_options'] ['timeformat'] = 'HH:mm{ - HH:mm}';
	$handler->display->display_options ['style_options'] ['advanced'] = TRUE;
	$handler->display->display_options ['style_options'] ['axisFormat'] = 'HH:mm';
	$handler->display->display_options ['style_options'] ['timeformatMonth'] = 'HH:mm{ - HH:mm}';
	$handler->display->display_options ['style_options'] ['timeformatWeek'] = 'HH:mm{ - HH:mm}';
	$handler->display->display_options ['style_options'] ['titleformatWeek'] = 'd MMM [ yyyy]{ - d [ MMM] yyyy}';
	$handler->display->display_options ['style_options'] ['columnformatWeek'] = 'ddd d/M';
	$handler->display->display_options ['style_options'] ['timeformatDay'] = 'HH:mm{ - HH:mm}';
	$handler->display->display_options ['style_options'] ['titleformatDay'] = 'dddd, d MMM, yyyy';
	$handler->display->display_options ['style_options'] ['columnformatDay'] = 'dddd d/M';
	$handler->display->display_options ['style_options'] ['theme'] = FALSE;
	$handler->display->display_options ['style_options'] ['fullcalendar_options'] ['firstHour'] = 7;
	$handler->display->display_options ['style_options'] ['fullcalendar_options'] ['minTime'] = 7;
	$handler->display->display_options ['style_options'] ['fullcalendar_options'] ['maxTime'] = 23;
	$handler->display->display_options ['style_options'] ['fullcalendar_options'] ['slotMinutes'] = 15;
	$handler->display->display_options ['style_options'] ['fullcalendar_options'] ['defaultEventMinutes'] = 15;
	$handler->display->display_options ['style_options'] ['fullcalendar_options'] ['disableDragging'] = TRUE;
	$handler->display->display_options ['style_options'] ['fullcalendar_options'] ['disableResizing'] = TRUE;
	$handler->display->display_options ['defaults'] ['style_options'] = FALSE;
	$handler->display->display_options ['defaults'] ['row_plugin'] = FALSE;
	$handler->display->display_options ['defaults'] ['row_options'] = FALSE;
	$handler->display->display_options ['exposed_block'] = TRUE;
	$handler->display->display_options ['defaults'] ['header'] = FALSE;
	/* Kop: Algemeen: Tekstveld */
	$handler->display->display_options ['header'] ['area'] ['id'] = 'area';
	$handler->display->display_options ['header'] ['area'] ['table'] = 'views';
	$handler->display->display_options ['header'] ['area'] ['field'] = 'area';
	$handler->display->display_options ['header'] ['area'] ['content'] = '<span class="argus_jaarkalender-view-legend" style="background-color: #d97d03;"></span> jaarkalender - <span class="argus_jaarkalender-view-legend" style="background-color: #cf2d2c;"></span> preventie - <span class="argus_jaarkalender-view-legend" style="background-color: #758f24;"></span> nascholing - <span class="argus_jaarkalender-view-legend" style="background-color: #414e2d;"></span> pedagogische activiteit - <span class="argus_jaarkalender-view-legend" style="background-color: #045595;"></span> opruim speelplaats - <span class="argus_jaarkalender-view-legend" style="background-color: #840d0b;"></span> interne kwaliteitszorg';
	$handler->display->display_options ['header'] ['area'] ['format'] = 'full_html';
	$handler->display->display_options ['defaults'] ['footer'] = FALSE;
	/* Voet: Algemeen: Tekstveld */
	$handler->display->display_options ['footer'] ['area'] ['id'] = 'area';
	$handler->display->display_options ['footer'] ['area'] ['table'] = 'views';
	$handler->display->display_options ['footer'] ['area'] ['field'] = 'area';
	$handler->display->display_options ['footer'] ['area'] ['content'] = '<span class="argus_jaarkalender-view-legend" style="background-color: #d97d03;"></span> jaarkalender - <span class="argus_jaarkalender-view-legend" style="background-color: #cf2d2c;"></span> preventie - <span class="argus_jaarkalender-view-legend" style="background-color: #758f24;"></span> nascholing - <span class="argus_jaarkalender-view-legend" style="background-color: #414e2d;"></span> pedagogische activiteit - <span class="argus_jaarkalender-view-legend" style="background-color: #045595;"></span> opruim speelplaats - <span class="argus_jaarkalender-view-legend" style="background-color: #840d0b;"></span> interne kwaliteitszorg';
	$handler->display->display_options ['footer'] ['area'] ['format'] = 'full_html';
	$handler->display->display_options ['defaults'] ['fields'] = FALSE;
	/* Veld: Inhoud: Titel */
	$handler->display->display_options ['fields'] ['title'] ['id'] = 'title';
	$handler->display->display_options ['fields'] ['title'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['title'] ['field'] = 'title';
	$handler->display->display_options ['fields'] ['title'] ['alter'] ['word_boundary'] = FALSE;
	$handler->display->display_options ['fields'] ['title'] ['alter'] ['ellipsis'] = FALSE;
	/* Veld: Inhoud: Datum */
	$handler->display->display_options ['fields'] ['field_pb_event_datum'] ['id'] = 'field_pb_event_datum';
	$handler->display->display_options ['fields'] ['field_pb_event_datum'] ['table'] = 'field_data_field_pb_event_datum';
	$handler->display->display_options ['fields'] ['field_pb_event_datum'] ['field'] = 'field_pb_event_datum';
	$handler->display->display_options ['fields'] ['field_pb_event_datum'] ['settings'] = array (
			'format_type' => 'long',
			'fromto' => 'both',
			'multiple_number' => '',
			'multiple_from' => '',
			'multiple_to' => '',
			'show_remaining_days' => 0,
			'show_repeat_rule' => 'show' 
	);
	/* Veld: Inhoud: Datum */
	$handler->display->display_options ['fields'] ['field_ev_datum_1'] ['id'] = 'field_ev_datum_1';
	$handler->display->display_options ['fields'] ['field_ev_datum_1'] ['table'] = 'field_data_field_ev_datum';
	$handler->display->display_options ['fields'] ['field_ev_datum_1'] ['field'] = 'field_ev_datum';
	$handler->display->display_options ['fields'] ['field_ev_datum_1'] ['settings'] = array (
			'format_type' => 'long',
			'fromto' => 'both',
			'multiple_number' => '',
			'multiple_from' => '',
			'multiple_to' => '',
			'show_remaining_days' => 0,
			'show_repeat_rule' => 'show' 
	);
	$handler->display->display_options ['fields'] ['field_ev_datum_1'] ['delta_offset'] = '0';
	/* Veld: Inhoud: Volgende audit */
	$handler->display->display_options ['fields'] ['field_ikz_auditplanning'] ['id'] = 'field_ikz_auditplanning';
	$handler->display->display_options ['fields'] ['field_ikz_auditplanning'] ['table'] = 'field_data_field_ikz_auditplanning';
	$handler->display->display_options ['fields'] ['field_ikz_auditplanning'] ['field'] = 'field_ikz_auditplanning';
	$handler->display->display_options ['fields'] ['field_ikz_auditplanning'] ['settings'] = array (
			'format_type' => 'long',
			'fromto' => 'both',
			'multiple_number' => '',
			'multiple_from' => '',
			'multiple_to' => '',
			'show_remaining_days' => 0,
			'show_repeat_rule' => 'show',
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	$handler->display->display_options ['defaults'] ['filter_groups'] = FALSE;
	$handler->display->display_options ['filter_groups'] ['operator'] = 'OR';
	$handler->display->display_options ['defaults'] ['filters'] = FALSE;
	/* Filtercriterium: Inhoud: Gepubliceerd */
	$handler->display->display_options ['filters'] ['status'] ['id'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['status'] ['field'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['value'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['expose'] ['operator'] = FALSE;
	/* Filtercriterium: Inhoud: Type */
	$handler->display->display_options ['filters'] ['type'] ['id'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['type'] ['field'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['value'] = array (
			'event_jaarkalender' => 'event_jaarkalender',
			'event_nascholing' => 'event_nascholing',
			'event_opruim_speelplaats' => 'event_opruim_speelplaats',
			'event_pedagogische_activiteit' => 'event_pedagogische_activiteit',
			'event_preventiebeleid' => 'event_preventiebeleid',
			'ikz_procedure' => 'ikz_procedure' 
	);
	$handler->display->display_options ['filters'] ['type'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['type'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['type'] ['expose'] ['operator_id'] = 'type_op';
	$handler->display->display_options ['filters'] ['type'] ['expose'] ['operator'] = 'type_op';
	$handler->display->display_options ['filters'] ['type'] ['expose'] ['identifier'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['expose'] ['required'] = TRUE;
	$handler->display->display_options ['filters'] ['type'] ['expose'] ['remember'] = TRUE;
	$handler->display->display_options ['filters'] ['type'] ['expose'] ['multiple'] = TRUE;
	$handler->display->display_options ['filters'] ['type'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['filters'] ['type'] ['expose'] ['reduce'] = TRUE;
	$handler->display->display_options ['filters'] ['type'] ['group_info'] ['identifier'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['group_info'] ['multiple'] = TRUE;
	$handler->display->display_options ['filters'] ['type'] ['group_info'] ['remember'] = 1;
	$handler->display->display_options ['filters'] ['type'] ['group_info'] ['default_group'] = '4';
	$handler->display->display_options ['filters'] ['type'] ['group_info'] ['default_group_multiple'] = array (
			3 => '3' 
	);
	$handler->display->display_options ['filters'] ['type'] ['group_info'] ['group_items'] = array (
			1 => array (
					'title' => 'Nascholingen',
					'operator' => 'in',
					'value' => array (
							'event_nascholing' => 'event_nascholing' 
					) 
			),
			2 => array (
					'title' => 'Pedagogische activiteit',
					'operator' => 'in',
					'value' => array (
							'event_pedagogische_activiteit' => 'event_pedagogische_activiteit' 
					) 
			),
			3 => array (
					'title' => 'Personeel',
					'operator' => 'in',
					'value' => array (
							'event_jaarkalender' => 'event_jaarkalender' 
					) 
			),
			4 => array (
					'title' => 'Preventiebeleid',
					'operator' => 'in',
					'value' => array (
							'event_preventiebeleid' => 'event_preventiebeleid' 
					) 
			) 
	);
	/* Filtercriterium: Inhoud: Goedkeuring (field_ev_goedkeuring) */
	$handler->display->display_options ['filters'] ['field_ev_goedkeuring_value'] ['id'] = 'field_ev_goedkeuring_value';
	$handler->display->display_options ['filters'] ['field_ev_goedkeuring_value'] ['table'] = 'field_data_field_ev_goedkeuring';
	$handler->display->display_options ['filters'] ['field_ev_goedkeuring_value'] ['field'] = 'field_ev_goedkeuring_value';
	$handler->display->display_options ['filters'] ['field_ev_goedkeuring_value'] ['operator'] = 'not';
	$handler->display->display_options ['filters'] ['field_ev_goedkeuring_value'] ['value'] = array (
			'Nieuw' => 'Nieuw',
			'In behandeling' => 'In behandeling',
			'Geannuleerd' => 'Geannuleerd' 
	);
	$handler->display->display_options ['filters'] ['field_ev_goedkeuring_value'] ['reduce_duplicates'] = TRUE;
	$handler->display->display_options ['qtip_instance'] = 'standaard';
	$handler->display->display_options ['path'] = 'jaarkalender';
	$handler->display->display_options ['menu'] ['type'] = 'normal';
	$handler->display->display_options ['menu'] ['title'] = 'Jaarkalender';
	$handler->display->display_options ['menu'] ['weight'] = '0';
	if (menu_load ( 'menu-modules' )) {
		$menu = 'menu-modules';
	} else {
		$menu = 'navigation';
	}
	$handler->display->display_options ['menu'] ['name'] = $menu;
	$handler->display->display_options ['menu'] ['context'] = 0;
	$handler->display->display_options ['menu'] ['context_only_inline'] = 0;
	
	/* Display: Jaarkalender - alternatief (bij lange laadtijden) */
	$handler = $view->new_display ( 'page', 'Jaarkalender - alternatief (bij lange laadtijden)', 'events_jaarkalender_alternative' );
	$handler->display->display_options ['defaults'] ['pager'] = FALSE;
	$handler->display->display_options ['pager'] ['type'] = 'date_views_pager';
	$handler->display->display_options ['pager'] ['options'] ['skip_empty_pages'] = 0;
	$handler->display->display_options ['defaults'] ['style_plugin'] = FALSE;
	$handler->display->display_options ['style_plugin'] = 'calendar_style';
	$handler->display->display_options ['style_options'] ['name_size'] = '3';
	$handler->display->display_options ['style_options'] ['mini'] = '0';
	$handler->display->display_options ['style_options'] ['with_weekno'] = '0';
	$handler->display->display_options ['style_options'] ['multiday_theme'] = '1';
	$handler->display->display_options ['style_options'] ['theme_style'] = '1';
	$handler->display->display_options ['style_options'] ['max_items'] = '0';
	$handler->display->display_options ['defaults'] ['style_options'] = FALSE;
	$handler->display->display_options ['defaults'] ['row_plugin'] = FALSE;
	$handler->display->display_options ['row_plugin'] = 'calendar_entity';
	$handler->display->display_options ['row_options'] ['colors'] ['legend'] = 'type';
	$handler->display->display_options ['row_options'] ['colors'] ['calendar_colors_type'] = array (
			'aankoopdossier' => '#ffffff',
			'article' => '#ffffff',
			'attest' => '#ffffff',
			'page' => '#ffffff',
			'event_jaarkalender' => '#cc0000',
			'event_nascholing' => '#0003fc',
			'event_pedagogische_activiteit' => '#0af500',
			'event_preventiebeleid' => '#e8d000',
			'ikz_afkortingen' => '#ffffff',
			'ikz_documenten' => '#ffffff',
			'ikz_document' => '#ffffff',
			'ikz_procedure' => '#ffffff',
			'klas' => '#ffffff',
			'lvs_deliberatie' => '#ffffff',
			'lvs_melding' => '#ffffff',
			'lokaal' => '#ffffff',
			'msl_begeleidingsovereenkomst' => '#ffffff',
			'msl_oa_sticker' => '#ffffff',
			'msl_volgkaart' => '#ffffff',
			'msl_volgkaart_evaluatie' => '#ffffff',
			'maatregelen' => '#ffffff',
			'merk' => '#ffffff',
			'printer' => '#ffffff',
			'printer_accessoire' => '#ffffff',
			'schoolgeld_betalingen' => '#ffffff',
			'schoolgeld_kosten' => '#ffffff',
			'sleutel' => '#ffffff',
			'support_ticket' => '#ffffff',
			'technische_melding' => '#ffffff',
			'uurrooster_les' => '#ffffff',
			'uurrooster_periode' => '#ffffff',
			'vak' => '#ffffff',
			'vakgroep' => '#ffffff',
			'webform' => '#ffffff' 
	);
	$handler->display->display_options ['defaults'] ['row_options'] = FALSE;
	$handler->display->display_options ['defaults'] ['fields'] = FALSE;
	/* Veld: Inhoud: Titel */
	$handler->display->display_options ['fields'] ['title'] ['id'] = 'title';
	$handler->display->display_options ['fields'] ['title'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['title'] ['field'] = 'title';
	$handler->display->display_options ['fields'] ['title'] ['alter'] ['word_boundary'] = FALSE;
	$handler->display->display_options ['fields'] ['title'] ['alter'] ['ellipsis'] = FALSE;
	$handler->display->display_options ['defaults'] ['arguments'] = FALSE;
	/* Contextueel filter: Datum: Datum (node) */
	$handler->display->display_options ['arguments'] ['date_argument'] ['id'] = 'date_argument';
	$handler->display->display_options ['arguments'] ['date_argument'] ['table'] = 'node';
	$handler->display->display_options ['arguments'] ['date_argument'] ['field'] = 'date_argument';
	$handler->display->display_options ['arguments'] ['date_argument'] ['default_action'] = 'default';
	$handler->display->display_options ['arguments'] ['date_argument'] ['exception'] ['title'] = 'Alle';
	$handler->display->display_options ['arguments'] ['date_argument'] ['default_argument_type'] = 'date';
	$handler->display->display_options ['arguments'] ['date_argument'] ['summary'] ['format'] = 'default_summary';
	$handler->display->display_options ['arguments'] ['date_argument'] ['granularity_reset'] = 0;
	$handler->display->display_options ['arguments'] ['date_argument'] ['date_fields'] = array (
			'field_data_field_pb_event_datum.field_pb_event_datum_value' => 'field_data_field_pb_event_datum.field_pb_event_datum_value',
			'field_data_field_ev_datum.field_ev_datum_value' => 'field_data_field_ev_datum.field_ev_datum_value' 
	);
	$handler->display->display_options ['qtip_instance'] = 'standaard';
	$handler->display->display_options ['path'] = 'jaarkalender-alternatief';
	$handler->display->display_options ['menu'] ['title'] = 'Jaarkalender2';
	$handler->display->display_options ['menu'] ['weight'] = '0';
	$handler->display->display_options ['menu'] ['context'] = 0;
	$handler->display->display_options ['menu'] ['context_only_inline'] = 0;
	$translatables ['Jaarkalender'] = array (
			t ( 'Master' ),
			t ( 'Jaarkalender' ),
			t ( 'meer' ),
			t ( 'Toepassen' ),
			t ( 'Opnieuw instellen' ),
			t ( 'Sorteren op' ),
			t ( 'Oplopend' ),
			t ( 'Aflopend' ),
			t ( 'Uitgebreide opties' ),
			t ( 'Titel' ),
			t ( 'Datum' ),
			t ( '<span class="argus_jaarkalender-view-legend" style="background-color: #d97d03;"></span> jaarkalender - <span class="argus_jaarkalender-view-legend" style="background-color: #cf2d2c;"></span> preventie - <span class="argus_jaarkalender-view-legend" style="background-color: #758f24;"></span> nascholing - <span class="argus_jaarkalender-view-legend" style="background-color: #414e2d;"></span> pedagogische activiteit - <span class="argus_jaarkalender-view-legend" style="background-color: #045595;"></span> opruim speelplaats - <span class="argus_jaarkalender-view-legend" style="background-color: #840d0b;"></span> interne kwaliteitszorg' ),
			t ( 'Volgende audit' ),
			t ( 'Jaarkalender - alternatief (bij lange laadtijden)' ),
			t ( 'Alle' ) 
	);
	
	$views [$view->name] = $view;
	return $views;
}
