<?php
/*
 * Copyright (C) 2017 bartgysens
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* Drupal Hooks */

/**
 * Implements hook_node_info().
 */
function argus_contracten_node_info() {
	$items = array (
			'contract' => array (
					'name' => t ( 'Contract' ),
					'base' => 'node_content',
					'description' => t ( 'Je kan de <em>contracten</em> in je organisatie netjes inventariseren en beheren via deze module.' ),
					'has_title' => '1',
					'title_label' => t ( 'Product / dienst' ),
					'help' => '' 
			) 
	);
	drupal_alter ( 'node_info', $items );
	return $items;
}

/**
 * Implement hook_form()
 */
function argus_contracten_form($node, $form_state) {
	return node_content_form ( $node, $form_state );
}

/**
 * Implementation of hook_views_api().
 */
function argus_contracten_views_api() {
	return array (
			'api' => 3.0,
			'path' => drupal_get_path ( 'module', 'argus_contracten' ) 
	) // replace demo with your content type
;
}

/**
 * Implementation of hook_views_default_views().
 *
 * Views export creates code that you have to paste in this function.
 *
 * Administration > Structure > Views : click the button behind the view you need and export
 * /admin/structure/views
 */
function argus_contracten_views_default_views() {
	$view = new view ();
	$view->name = 'contracten';
	$view->description = '';
	$view->tag = 'default';
	$view->base_table = 'node';
	$view->human_name = 'Contracten';
	$view->core = 7;
	$view->api_version = '3.0';
	$view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */
	
	/* Display: Master */
	$handler = $view->new_display ( 'default', 'Master', 'default' );
	$handler->display->display_options ['title'] = 'Contracten';
	$handler->display->display_options ['use_more_always'] = FALSE;
	$handler->display->display_options ['use_more_text'] = 'meer';
	$handler->display->display_options ['access'] ['type'] = 'role';
	
	$roles = array ();
	$roleNames = array (
			'administrator',
			'directie',
			'boekhouding' 
	);
	foreach ( $roleNames as $role ) {
		$rid = user_role_load_by_name ( $role );
		if (! $rid) {
			$newRole = new stdClass ();
			$newRole->name = $role;
			user_role_save ( $newRole );
			
			$rid = user_role_load_by_name ( $role );
		}
		
		$roles [] = $rid->rid;
	}
	$handler->display->display_options ['access'] ['role'] = $roles;
	
	$handler->display->display_options ['cache'] ['type'] = 'views_content_cache';
	$handler->display->display_options ['cache'] ['results_min_lifespan'] = '-1';
	$handler->display->display_options ['cache'] ['results_max_lifespan'] = '518400';
	$handler->display->display_options ['cache'] ['output_min_lifespan'] = '-1';
	$handler->display->display_options ['cache'] ['output_max_lifespan'] = '518400';
	$handler->display->display_options ['cache'] ['keys'] = array (
			'comment' => array (
					'changed' => 0 
			),
			'node' => array (
					'contract' => 'contract' 
			),
			'node_only' => array (
					'node_changed' => 'node_changed' 
			) 
	);
	$handler->display->display_options ['query'] ['type'] = 'views_query';
	$handler->display->display_options ['exposed_form'] ['type'] = 'basic';
	$handler->display->display_options ['exposed_form'] ['options'] ['submit_button'] = 'Toepassen';
	$handler->display->display_options ['exposed_form'] ['options'] ['reset_button_label'] = 'Opnieuw instellen';
	$handler->display->display_options ['exposed_form'] ['options'] ['exposed_sorts_label'] = 'Sorteren op';
	$handler->display->display_options ['exposed_form'] ['options'] ['sort_asc_label'] = 'Oplopend';
	$handler->display->display_options ['exposed_form'] ['options'] ['sort_desc_label'] = 'Aflopend';
	$handler->display->display_options ['pager'] ['type'] = 'full';
	$handler->display->display_options ['pager'] ['options'] ['items_per_page'] = '50';
	$handler->display->display_options ['pager'] ['options'] ['expose'] ['items_per_page_label'] = 'Items per pagina';
	$handler->display->display_options ['pager'] ['options'] ['expose'] ['items_per_page_options_all_label'] = '- Alle -';
	$handler->display->display_options ['pager'] ['options'] ['expose'] ['offset_label'] = 'Startpunt';
	$handler->display->display_options ['pager'] ['options'] ['tags'] ['first'] = '« eerste';
	$handler->display->display_options ['pager'] ['options'] ['tags'] ['previous'] = '‹ vorige';
	$handler->display->display_options ['pager'] ['options'] ['tags'] ['next'] = 'volgende ›';
	$handler->display->display_options ['pager'] ['options'] ['tags'] ['last'] = 'laatste »';
	$handler->display->display_options ['style_plugin'] = 'table';
	$handler->display->display_options ['style_options'] ['columns'] = array (
			'title' => 'title',
			'field_contractnummer' => 'field_contractnummer',
			'field_klantnummer' => 'field_klantnummer',
			'field_looptijd' => 'field_looptijd',
			'field_bedrag' => 'field_bedrag',
			'field_betalingstermijn' => 'field_betalingstermijn',
			'field_opzegdatum' => 'field_opzegdatum',
			'field_opzegtermijn' => 'field_opzegtermijn',
			'field_verlengingsmethode' => 'field_verlengingsmethode' 
	);
	$handler->display->display_options ['style_options'] ['default'] = '-1';
	$handler->display->display_options ['style_options'] ['info'] = array (
			'title' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_contractnummer' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_klantnummer' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_looptijd' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_bedrag' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_betalingstermijn' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_opzegdatum' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_opzegtermijn' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_verlengingsmethode' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			) 
	);
	/* Kop: Algemeen: Samenvatting van het resultaat */
	$handler->display->display_options ['header'] ['result'] ['id'] = 'result';
	$handler->display->display_options ['header'] ['result'] ['table'] = 'views';
	$handler->display->display_options ['header'] ['result'] ['field'] = 'result';
	$handler->display->display_options ['header'] ['result'] ['content'] = 'Getoond @start - @end van @total';
	/* Kop: Algemeen: Tekstveld */
	$handler->display->display_options ['header'] ['area'] ['id'] = 'area';
	$handler->display->display_options ['header'] ['area'] ['table'] = 'views';
	$handler->display->display_options ['header'] ['area'] ['field'] = 'area';
	$handler->display->display_options ['header'] ['area'] ['content'] = '<a href="/node/add/contract">Een contract toevoegen</a>';
	$handler->display->display_options ['header'] ['area'] ['format'] = 'filtered_html';
	/* Voet: Algemeen: Samenvatting van het resultaat */
	$handler->display->display_options ['footer'] ['result'] ['id'] = 'result';
	$handler->display->display_options ['footer'] ['result'] ['table'] = 'views';
	$handler->display->display_options ['footer'] ['result'] ['field'] = 'result';
	$handler->display->display_options ['footer'] ['result'] ['content'] = 'Getoond @start - @end van @total';
	/* Veld: Inhoud: Titel */
	$handler->display->display_options ['fields'] ['title'] ['id'] = 'title';
	$handler->display->display_options ['fields'] ['title'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['title'] ['field'] = 'title';
	$handler->display->display_options ['fields'] ['title'] ['label'] = 'Product / dienst';
	$handler->display->display_options ['fields'] ['title'] ['alter'] ['word_boundary'] = FALSE;
	$handler->display->display_options ['fields'] ['title'] ['alter'] ['ellipsis'] = FALSE;
	/* Veld: Inhoud: Contractnummer */
	$handler->display->display_options ['fields'] ['field_contractnummer'] ['id'] = 'field_contractnummer';
	$handler->display->display_options ['fields'] ['field_contractnummer'] ['table'] = 'field_data_field_contractnummer';
	$handler->display->display_options ['fields'] ['field_contractnummer'] ['field'] = 'field_contractnummer';
	/* Veld: Inhoud: Klantnummer */
	$handler->display->display_options ['fields'] ['field_klantnummer'] ['id'] = 'field_klantnummer';
	$handler->display->display_options ['fields'] ['field_klantnummer'] ['table'] = 'field_data_field_klantnummer';
	$handler->display->display_options ['fields'] ['field_klantnummer'] ['field'] = 'field_klantnummer';
	/* Veld: Inhoud: Looptijd */
	$handler->display->display_options ['fields'] ['field_looptijd'] ['id'] = 'field_looptijd';
	$handler->display->display_options ['fields'] ['field_looptijd'] ['table'] = 'field_data_field_looptijd';
	$handler->display->display_options ['fields'] ['field_looptijd'] ['field'] = 'field_looptijd';
	$handler->display->display_options ['fields'] ['field_looptijd'] ['settings'] = array (
			'format_type' => 'datum_kort_',
			'fromto' => 'both',
			'multiple_number' => '',
			'multiple_from' => '',
			'multiple_to' => '',
			'show_remaining_days' => 0,
			'show_repeat_rule' => 'show' 
	);
	/* Veld: Inhoud: Bedrag */
	$handler->display->display_options ['fields'] ['field_bedrag'] ['id'] = 'field_bedrag';
	$handler->display->display_options ['fields'] ['field_bedrag'] ['table'] = 'field_data_field_bedrag';
	$handler->display->display_options ['fields'] ['field_bedrag'] ['field'] = 'field_bedrag';
	$handler->display->display_options ['fields'] ['field_bedrag'] ['settings'] = array (
			'thousand_separator' => '',
			'decimal_separator' => '.',
			'scale' => '2',
			'prefix_suffix' => '1' 
	);
	/* Veld: Inhoud: Betalingstermijn */
	$handler->display->display_options ['fields'] ['field_betalingstermijn'] ['id'] = 'field_betalingstermijn';
	$handler->display->display_options ['fields'] ['field_betalingstermijn'] ['table'] = 'field_data_field_betalingstermijn';
	$handler->display->display_options ['fields'] ['field_betalingstermijn'] ['field'] = 'field_betalingstermijn';
	$handler->display->display_options ['fields'] ['field_betalingstermijn'] ['settings'] = array (
			'thousand_separator' => '',
			'prefix_suffix' => '1' 
	);
	/* Veld: Inhoud: Opzegdatum */
	$handler->display->display_options ['fields'] ['field_opzegdatum'] ['id'] = 'field_opzegdatum';
	$handler->display->display_options ['fields'] ['field_opzegdatum'] ['table'] = 'field_data_field_opzegdatum';
	$handler->display->display_options ['fields'] ['field_opzegdatum'] ['field'] = 'field_opzegdatum';
	$handler->display->display_options ['fields'] ['field_opzegdatum'] ['settings'] = array (
			'format_type' => 'datum_kort_',
			'fromto' => 'both',
			'multiple_number' => '',
			'multiple_from' => '',
			'multiple_to' => '',
			'show_remaining_days' => 0,
			'show_repeat_rule' => 'show' 
	);
	/* Veld: Inhoud: Opzegtermijn */
	$handler->display->display_options ['fields'] ['field_opzegtermijn'] ['id'] = 'field_opzegtermijn';
	$handler->display->display_options ['fields'] ['field_opzegtermijn'] ['table'] = 'field_data_field_opzegtermijn';
	$handler->display->display_options ['fields'] ['field_opzegtermijn'] ['field'] = 'field_opzegtermijn';
	$handler->display->display_options ['fields'] ['field_opzegtermijn'] ['settings'] = array (
			'thousand_separator' => '',
			'prefix_suffix' => '1' 
	);
	/* Veld: Inhoud: Verlengingsmethode */
	$handler->display->display_options ['fields'] ['field_verlengingsmethode'] ['id'] = 'field_verlengingsmethode';
	$handler->display->display_options ['fields'] ['field_verlengingsmethode'] ['table'] = 'field_data_field_verlengingsmethode';
	$handler->display->display_options ['fields'] ['field_verlengingsmethode'] ['field'] = 'field_verlengingsmethode';
	/* Sorteercriterium: Inhoud: Titel */
	$handler->display->display_options ['sorts'] ['title'] ['id'] = 'title';
	$handler->display->display_options ['sorts'] ['title'] ['table'] = 'node';
	$handler->display->display_options ['sorts'] ['title'] ['field'] = 'title';
	$handler->display->display_options ['sorts'] ['title'] ['order'] = 'DESC';
	/* Filtercriterium: Inhoud: Gepubliceerd */
	$handler->display->display_options ['filters'] ['status'] ['id'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['status'] ['field'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['value'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['expose'] ['operator'] = FALSE;
	/* Filtercriterium: Inhoud: Type */
	$handler->display->display_options ['filters'] ['type'] ['id'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['type'] ['field'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['value'] = array (
			'contract' => 'contract' 
	);
	$handler->display->display_options ['filters'] ['type'] ['group'] = 1;
	/* Filtercriterium: Inhoud: Titel */
	$handler->display->display_options ['filters'] ['title'] ['id'] = 'title';
	$handler->display->display_options ['filters'] ['title'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['title'] ['field'] = 'title';
	$handler->display->display_options ['filters'] ['title'] ['operator'] = 'contains';
	$handler->display->display_options ['filters'] ['title'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['title'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['title'] ['expose'] ['operator_id'] = 'title_op';
	$handler->display->display_options ['filters'] ['title'] ['expose'] ['label'] = 'Product / dienst';
	$handler->display->display_options ['filters'] ['title'] ['expose'] ['operator'] = 'title_op';
	$handler->display->display_options ['filters'] ['title'] ['expose'] ['identifier'] = 'title';
	$handler->display->display_options ['filters'] ['title'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['filters'] ['title'] ['expose'] ['autocomplete_items'] = '10';
	$handler->display->display_options ['filters'] ['title'] ['expose'] ['autocomplete_min_chars'] = '0';
	$handler->display->display_options ['filters'] ['title'] ['expose'] ['autocomplete_field'] = 'title';
	$handler->display->display_options ['filters'] ['title'] ['expose'] ['autocomplete_raw_suggestion'] = '1';
	$handler->display->display_options ['filters'] ['title'] ['expose'] ['autocomplete_raw_dropdown'] = '1';
	$handler->display->display_options ['filters'] ['title'] ['expose'] ['autocomplete_dependent'] = 0;
	/* Filtercriterium: Inhoud: Contractnummer (field_contractnummer) */
	$handler->display->display_options ['filters'] ['field_contractnummer_value'] ['id'] = 'field_contractnummer_value';
	$handler->display->display_options ['filters'] ['field_contractnummer_value'] ['table'] = 'field_data_field_contractnummer';
	$handler->display->display_options ['filters'] ['field_contractnummer_value'] ['field'] = 'field_contractnummer_value';
	$handler->display->display_options ['filters'] ['field_contractnummer_value'] ['operator'] = 'contains';
	$handler->display->display_options ['filters'] ['field_contractnummer_value'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['field_contractnummer_value'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_contractnummer_value'] ['expose'] ['operator_id'] = 'field_contractnummer_value_op';
	$handler->display->display_options ['filters'] ['field_contractnummer_value'] ['expose'] ['label'] = 'Contractnummer';
	$handler->display->display_options ['filters'] ['field_contractnummer_value'] ['expose'] ['operator'] = 'field_contractnummer_value_op';
	$handler->display->display_options ['filters'] ['field_contractnummer_value'] ['expose'] ['identifier'] = 'field_contractnummer_value';
	$handler->display->display_options ['filters'] ['field_contractnummer_value'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['filters'] ['field_contractnummer_value'] ['expose'] ['autocomplete_items'] = '10';
	$handler->display->display_options ['filters'] ['field_contractnummer_value'] ['expose'] ['autocomplete_min_chars'] = '0';
	$handler->display->display_options ['filters'] ['field_contractnummer_value'] ['expose'] ['autocomplete_field'] = 'field_contractnummer';
	$handler->display->display_options ['filters'] ['field_contractnummer_value'] ['expose'] ['autocomplete_raw_suggestion'] = '1';
	$handler->display->display_options ['filters'] ['field_contractnummer_value'] ['expose'] ['autocomplete_raw_dropdown'] = '1';
	$handler->display->display_options ['filters'] ['field_contractnummer_value'] ['expose'] ['autocomplete_dependent'] = 0;
	/* Filtercriterium: Inhoud: Klantnummer (field_klantnummer) */
	$handler->display->display_options ['filters'] ['field_klantnummer_value'] ['id'] = 'field_klantnummer_value';
	$handler->display->display_options ['filters'] ['field_klantnummer_value'] ['table'] = 'field_data_field_klantnummer';
	$handler->display->display_options ['filters'] ['field_klantnummer_value'] ['field'] = 'field_klantnummer_value';
	$handler->display->display_options ['filters'] ['field_klantnummer_value'] ['operator'] = 'contains';
	$handler->display->display_options ['filters'] ['field_klantnummer_value'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['field_klantnummer_value'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_klantnummer_value'] ['expose'] ['operator_id'] = 'field_klantnummer_value_op';
	$handler->display->display_options ['filters'] ['field_klantnummer_value'] ['expose'] ['label'] = 'Klantnummer';
	$handler->display->display_options ['filters'] ['field_klantnummer_value'] ['expose'] ['operator'] = 'field_klantnummer_value_op';
	$handler->display->display_options ['filters'] ['field_klantnummer_value'] ['expose'] ['identifier'] = 'field_klantnummer_value';
	$handler->display->display_options ['filters'] ['field_klantnummer_value'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['filters'] ['field_klantnummer_value'] ['expose'] ['autocomplete_items'] = '10';
	$handler->display->display_options ['filters'] ['field_klantnummer_value'] ['expose'] ['autocomplete_min_chars'] = '0';
	$handler->display->display_options ['filters'] ['field_klantnummer_value'] ['expose'] ['autocomplete_field'] = 'field_klantnummer';
	$handler->display->display_options ['filters'] ['field_klantnummer_value'] ['expose'] ['autocomplete_raw_suggestion'] = '1';
	$handler->display->display_options ['filters'] ['field_klantnummer_value'] ['expose'] ['autocomplete_raw_dropdown'] = '1';
	$handler->display->display_options ['filters'] ['field_klantnummer_value'] ['expose'] ['autocomplete_dependent'] = 0;
	
	/* Display: Overzicht */
	$handler = $view->new_display ( 'page', 'Overzicht', 'contracts_overview' );
	$handler->display->display_options ['exposed_block'] = TRUE;
	$handler->display->display_options ['defaults'] ['header'] = FALSE;
	/* Kop: Algemeen: Samenvatting van het resultaat */
	$handler->display->display_options ['header'] ['result'] ['id'] = 'result';
	$handler->display->display_options ['header'] ['result'] ['table'] = 'views';
	$handler->display->display_options ['header'] ['result'] ['field'] = 'result';
	$handler->display->display_options ['header'] ['result'] ['content'] = 'Getoond @start - @end van @total';
	/* Kop: Algemeen: Tekstveld */
	$handler->display->display_options ['header'] ['area'] ['id'] = 'area';
	$handler->display->display_options ['header'] ['area'] ['table'] = 'views';
	$handler->display->display_options ['header'] ['area'] ['field'] = 'area';
	$handler->display->display_options ['header'] ['area'] ['empty'] = TRUE;
	$handler->display->display_options ['header'] ['area'] ['content'] = '<a href="/node/add/contract">Een contract toevoegen</a>';
	$handler->display->display_options ['header'] ['area'] ['format'] = 'filtered_html';
	$handler->display->display_options ['qtip_instance'] = 'standaard';
	$handler->display->display_options ['path'] = 'contracten';
	$handler->display->display_options ['menu'] ['type'] = 'normal';
	$handler->display->display_options ['menu'] ['title'] = 'Contracten';
	if (menu_load ( 'menu-modules' )) {
		$menu = 'menu-modules';
	} else {
		$menu = 'navigation';
	}
	$handler->display->display_options ['menu'] ['name'] = $menu;
	$translatables ['contracten'] = array (
			t ( 'Master' ),
			t ( 'Contracten' ),
			t ( 'meer' ),
			t ( 'Toepassen' ),
			t ( 'Opnieuw instellen' ),
			t ( 'Sorteren op' ),
			t ( 'Oplopend' ),
			t ( 'Aflopend' ),
			t ( 'Items per pagina' ),
			t ( '- Alle -' ),
			t ( 'Startpunt' ),
			t ( '« eerste' ),
			t ( '‹ vorige' ),
			t ( 'volgende ›' ),
			t ( 'laatste »' ),
			t ( 'Getoond @start - @end van @total' ),
			t ( '<a href="/node/add/contract">Een contract toevoegen</a>' ),
			t ( 'Product / dienst' ),
			t ( 'Contractnummer' ),
			t ( 'Klantnummer' ),
			t ( 'Looptijd' ),
			t ( 'Bedrag' ),
			t ( 'Betalingstermijn' ),
			t ( 'Opzegdatum' ),
			t ( 'Opzegtermijn' ),
			t ( 'Verlengingsmethode' ),
			t ( 'Overzicht' ) 
	);
	
	$views [$view->name] = $view;
	return $views;
}