<?php
/*
 * Copyright (C) 2017 bartgysens
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* Drupal Hooks */

/**
 * Implements hook_node_info().
 */
function argus_volgkaarten_node_info() {
	$items = array (
			'msl_volgkaart' => array (
					'name' => t ( 'MSL - Volgkaart' ),
					'base' => 'node_content',
					'description' => t ( 'De <em>volgkaart</em> is het instrument om het gedrag van een leerling te volgen tijdens een schoolweek. Deze volgkaart is steeds verbonden aan een begeleidingsovereenkomst en heeft een strikte opvolgingsprocedure (zie Interne Kwaliteitszorg).' ),
					'has_title' => '1',
					'title_label' => t ( 'Titel' ),
					'help' => '' 
			) 
	);
	drupal_alter ( 'node_info', $items );
	return $items;
}

/**
 * Implement hook_form()
 */
function argus_volgkaarten_form($node, $form_state) {
	return node_content_form ( $node, $form_state );
}

/**
 * Implementation of hook_views_api().
 */
function argus_volgkaarten_views_api() {
	return array (
			'api' => 3.0,
			'path' => drupal_get_path ( 'module', 'argus_volgkaarten' ) 
	) // replace demo with your content type
;
}