<?php
/*
 * Copyright (C) 2017 bartgysens
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* Drupal Hooks */

/**
 * Implements hook_node_info().
 */
function argus_merken_node_info() {
	$items = array (
			'merk' => array (
					'name' => t ( 'Merk' ),
					'base' => 'node_content',
					'description' => t ( 'Allerlei <em>merknamen</em> voor verschillende toepassingsgebieden.' ),
					'has_title' => '1',
					'title_label' => t ( 'Merknaam' ),
					'help' => '' 
			) 
	);
	drupal_alter ( 'node_info', $items );
	return $items;
}

/**
 * Implement hook_form()
 */
function argus_merken_form($node, $form_state) {
	return node_content_form ( $node, $form_state );
}

/**
 * Implementation of hook_views_api().
 */
function argus_merken_views_api() {
	return array (
			'api' => 3.0,
			'path' => drupal_get_path ( 'module', 'argus_merken' ) 
	) // replace demo with your content type
;
}

/**
 * Implementation of hook_views_default_views().
 *
 * Views export creates code that you have to paste in this function.
 *
 * Administration > Structure > Views : click the button behind the view you need and export
 * /admin/structure/views
 */
function argus_merken_views_default_views() {
	$view = new view ();
	$view->name = 'merken';
	$view->description = '';
	$view->tag = 'default';
	$view->base_table = 'node';
	$view->human_name = 'Merken';
	$view->core = 7;
	$view->api_version = '3.0';
	$view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */
	
	/* Display: Master */
	$handler = $view->new_display ( 'default', 'Master', 'default' );
	$handler->display->display_options ['title'] = 'Merken';
	$handler->display->display_options ['use_more_always'] = FALSE;
	$handler->display->display_options ['use_more_text'] = 'meer';
	$handler->display->display_options ['access'] ['type'] = 'perm';
	$handler->display->display_options ['cache'] ['type'] = 'views_content_cache';
	$handler->display->display_options ['cache'] ['results_min_lifespan'] = '-1';
	$handler->display->display_options ['cache'] ['results_max_lifespan'] = '518400';
	$handler->display->display_options ['cache'] ['output_min_lifespan'] = '-1';
	$handler->display->display_options ['cache'] ['output_max_lifespan'] = '518400';
	$handler->display->display_options ['cache'] ['keys'] = array (
			'comment' => array (
					'changed' => 0 
			),
			'node' => array (
					'merk' => 'merk' 
			),
			'node_only' => array (
					'node_changed' => 'node_changed' 
			) 
	);
	$handler->display->display_options ['query'] ['type'] = 'views_query';
	$handler->display->display_options ['exposed_form'] ['type'] = 'basic';
	$handler->display->display_options ['exposed_form'] ['options'] ['submit_button'] = 'Toepassen';
	$handler->display->display_options ['exposed_form'] ['options'] ['reset_button_label'] = 'Opnieuw instellen';
	$handler->display->display_options ['exposed_form'] ['options'] ['exposed_sorts_label'] = 'Sorteren op';
	$handler->display->display_options ['exposed_form'] ['options'] ['sort_asc_label'] = 'Oplopend';
	$handler->display->display_options ['exposed_form'] ['options'] ['sort_desc_label'] = 'Aflopend';
	$handler->display->display_options ['exposed_form'] ['options'] ['autosubmit'] = FALSE;
	$handler->display->display_options ['pager'] ['type'] = 'full';
	$handler->display->display_options ['pager'] ['options'] ['items_per_page'] = '10';
	$handler->display->display_options ['pager'] ['options'] ['expose'] ['items_per_page_label'] = 'Items per pagina';
	$handler->display->display_options ['pager'] ['options'] ['expose'] ['items_per_page_options_all_label'] = '- Alle -';
	$handler->display->display_options ['pager'] ['options'] ['expose'] ['offset_label'] = 'Startpunt';
	$handler->display->display_options ['pager'] ['options'] ['tags'] ['first'] = '« eerste';
	$handler->display->display_options ['pager'] ['options'] ['tags'] ['previous'] = '‹ vorige';
	$handler->display->display_options ['pager'] ['options'] ['tags'] ['next'] = 'volgende ›';
	$handler->display->display_options ['pager'] ['options'] ['tags'] ['last'] = 'laatste »';
	$handler->display->display_options ['style_plugin'] = 'table';
	$handler->display->display_options ['style_options'] ['columns'] = array (
			'title' => 'title',
			'field_merk_toepassingsdomein' => 'field_merk_toepassingsdomein' 
	);
	$handler->display->display_options ['style_options'] ['default'] = '-1';
	$handler->display->display_options ['style_options'] ['info'] = array (
			'title' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_merk_toepassingsdomein' => array (
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			) 
	);
	$handler->display->display_options ['style_options'] ['sticky'] = TRUE;
	/* Veld: Inhoud: Titel */
	$handler->display->display_options ['fields'] ['title'] ['id'] = 'title';
	$handler->display->display_options ['fields'] ['title'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['title'] ['field'] = 'title';
	$handler->display->display_options ['fields'] ['title'] ['label'] = 'Merknaam';
	$handler->display->display_options ['fields'] ['title'] ['alter'] ['make_link'] = TRUE;
	$handler->display->display_options ['fields'] ['title'] ['alter'] ['path'] = 'merk/[title]';
	/* Veld: Inhoud: Toepassingsdomein */
	$handler->display->display_options ['fields'] ['field_merk_toepassingsdomein'] ['id'] = 'field_merk_toepassingsdomein';
	$handler->display->display_options ['fields'] ['field_merk_toepassingsdomein'] ['table'] = 'field_data_field_merk_toepassingsdomein';
	$handler->display->display_options ['fields'] ['field_merk_toepassingsdomein'] ['field'] = 'field_merk_toepassingsdomein';
	$handler->display->display_options ['fields'] ['field_merk_toepassingsdomein'] ['delta_offset'] = '0';
	/* Sorteercriterium: Inhoud: Titel */
	$handler->display->display_options ['sorts'] ['title'] ['id'] = 'title';
	$handler->display->display_options ['sorts'] ['title'] ['table'] = 'node';
	$handler->display->display_options ['sorts'] ['title'] ['field'] = 'title';
	/* Filtercriterium: Inhoud: Gepubliceerd */
	$handler->display->display_options ['filters'] ['status'] ['id'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['status'] ['field'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['value'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['expose'] ['operator'] = FALSE;
	/* Filtercriterium: Inhoud: Type */
	$handler->display->display_options ['filters'] ['type'] ['id'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['type'] ['field'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['value'] = array (
			'merk' => 'merk' 
	);
	$handler->display->display_options ['filters'] ['type'] ['group'] = 1;
	/* Filtercriterium: Inhoud: Toepassingsdomein (field_merk_toepassingsdomein) */
	$handler->display->display_options ['filters'] ['field_merk_toepassingsdomein_value'] ['id'] = 'field_merk_toepassingsdomein_value';
	$handler->display->display_options ['filters'] ['field_merk_toepassingsdomein_value'] ['table'] = 'field_data_field_merk_toepassingsdomein';
	$handler->display->display_options ['filters'] ['field_merk_toepassingsdomein_value'] ['field'] = 'field_merk_toepassingsdomein_value';
	$handler->display->display_options ['filters'] ['field_merk_toepassingsdomein_value'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_merk_toepassingsdomein_value'] ['expose'] ['operator_id'] = 'field_merk_toepassingsdomein_value_op';
	$handler->display->display_options ['filters'] ['field_merk_toepassingsdomein_value'] ['expose'] ['label'] = 'Toepassingsdomein (field_merk_toepassingsdomein)';
	$handler->display->display_options ['filters'] ['field_merk_toepassingsdomein_value'] ['expose'] ['operator'] = 'field_merk_toepassingsdomein_value_op';
	$handler->display->display_options ['filters'] ['field_merk_toepassingsdomein_value'] ['expose'] ['identifier'] = 'field_merk_toepassingsdomein_value';
	$handler->display->display_options ['filters'] ['field_merk_toepassingsdomein_value'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['filters'] ['field_merk_toepassingsdomein_value'] ['reduce_duplicates'] = TRUE;
	$handler->display->display_options ['qtip_instance'] = 'standaard';
	
	/* Display: Overzicht */
	$handler = $view->new_display ( 'page', 'Overzicht', 'merk_overzicht' );
	$handler->display->display_options ['display_description'] = 'Overzicht van alle merken waarvoor producten bestaan.';
	$handler->display->display_options ['exposed_block'] = TRUE;
	$handler->display->display_options ['path'] = 'merken';
	$handler->display->display_options ['menu'] ['type'] = 'normal';
	$handler->display->display_options ['menu'] ['title'] = 'Merken';
	$handler->display->display_options ['menu'] ['weight'] = '0';
	$handler->display->display_options ['menu'] ['context'] = 0;
	$handler->display->display_options ['menu'] ['context_only_inline'] = 0;
	if (menu_load ( 'menu-modules' )) {
		$menu = 'menu-modules';
	} else {
		$menu = 'navigation';
	}
	$handler->display->display_options ['menu'] ['name'] = $menu;
	
	/* Display: Merken: selectielijst */
	$handler = $view->new_display ( 'entityreference', 'Merken: selectielijst', 'entityreference_1' );
	$handler->display->display_options ['defaults'] ['title'] = FALSE;
	$handler->display->display_options ['title'] = 'Merken: selectielijst';
	$handler->display->display_options ['display_description'] = 'Geselecteerde lijst van merken binnen een bepaald toepassingsdomein.';
	$handler->display->display_options ['pager'] ['type'] = 'some';
	$handler->display->display_options ['defaults'] ['style_plugin'] = FALSE;
	$handler->display->display_options ['style_plugin'] = 'entityreference_style';
	$handler->display->display_options ['style_options'] ['search_fields'] = array (
			'title' => 'title',
			'field_merk_toepassingsdomein' => 'field_merk_toepassingsdomein' 
	);
	$handler->display->display_options ['defaults'] ['style_options'] = FALSE;
	$handler->display->display_options ['defaults'] ['row_plugin'] = FALSE;
	$handler->display->display_options ['row_plugin'] = 'entityreference_fields';
	$handler->display->display_options ['defaults'] ['row_options'] = FALSE;
	$handler->display->display_options ['defaults'] ['fields'] = FALSE;
	/* Veld: Inhoud: Titel */
	$handler->display->display_options ['fields'] ['title'] ['id'] = 'title';
	$handler->display->display_options ['fields'] ['title'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['title'] ['field'] = 'title';
	$handler->display->display_options ['fields'] ['title'] ['label'] = '';
	$handler->display->display_options ['fields'] ['title'] ['alter'] ['make_link'] = TRUE;
	$handler->display->display_options ['fields'] ['title'] ['alter'] ['path'] = 'merk/[title]';
	$handler->display->display_options ['fields'] ['title'] ['element_label_colon'] = FALSE;
	/* Veld: Inhoud: Toepassingsdomein */
	$handler->display->display_options ['fields'] ['field_merk_toepassingsdomein'] ['id'] = 'field_merk_toepassingsdomein';
	$handler->display->display_options ['fields'] ['field_merk_toepassingsdomein'] ['table'] = 'field_data_field_merk_toepassingsdomein';
	$handler->display->display_options ['fields'] ['field_merk_toepassingsdomein'] ['field'] = 'field_merk_toepassingsdomein';
	$handler->display->display_options ['fields'] ['field_merk_toepassingsdomein'] ['label'] = '';
	$handler->display->display_options ['fields'] ['field_merk_toepassingsdomein'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['field_merk_toepassingsdomein'] ['element_label_colon'] = FALSE;
	$handler->display->display_options ['fields'] ['field_merk_toepassingsdomein'] ['delta_offset'] = '0';
	$handler->display->display_options ['defaults'] ['filter_groups'] = FALSE;
	$handler->display->display_options ['defaults'] ['filters'] = FALSE;
	/* Filtercriterium: Inhoud: Gepubliceerd */
	$handler->display->display_options ['filters'] ['status'] ['id'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['status'] ['field'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['value'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['expose'] ['operator'] = FALSE;
	/* Filtercriterium: Inhoud: Type */
	$handler->display->display_options ['filters'] ['type'] ['id'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['type'] ['field'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['value'] = array (
			'merk' => 'merk' 
	);
	$handler->display->display_options ['filters'] ['type'] ['group'] = 1;
	/* Filtercriterium: Inhoud: Toepassingsdomein (field_merk_toepassingsdomein) */
	$handler->display->display_options ['filters'] ['field_merk_toepassingsdomein_value'] ['id'] = 'field_merk_toepassingsdomein_value';
	$handler->display->display_options ['filters'] ['field_merk_toepassingsdomein_value'] ['table'] = 'field_data_field_merk_toepassingsdomein';
	$handler->display->display_options ['filters'] ['field_merk_toepassingsdomein_value'] ['field'] = 'field_merk_toepassingsdomein_value';
	$handler->display->display_options ['filters'] ['field_merk_toepassingsdomein_value'] ['value'] = array (
			'ICT' => 'ICT' 
	);
	$handler->display->display_options ['filters'] ['field_merk_toepassingsdomein_value'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_merk_toepassingsdomein_value'] ['expose'] ['operator_id'] = 'field_merk_toepassingsdomein_value_op';
	$handler->display->display_options ['filters'] ['field_merk_toepassingsdomein_value'] ['expose'] ['label'] = 'Toepassingsdomein: ICT';
	$handler->display->display_options ['filters'] ['field_merk_toepassingsdomein_value'] ['expose'] ['operator'] = 'field_merk_toepassingsdomein_value_op';
	$handler->display->display_options ['filters'] ['field_merk_toepassingsdomein_value'] ['expose'] ['identifier'] = 'field_merk_toepassingsdomein_value';
	$handler->display->display_options ['filters'] ['field_merk_toepassingsdomein_value'] ['expose'] ['multiple'] = TRUE;
	$handler->display->display_options ['filters'] ['field_merk_toepassingsdomein_value'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['filters'] ['field_merk_toepassingsdomein_value'] ['reduce_duplicates'] = TRUE;
	$translatables ['merken'] = array (
			t ( 'Master' ),
			t ( 'Merken' ),
			t ( 'meer' ),
			t ( 'Toepassen' ),
			t ( 'Opnieuw instellen' ),
			t ( 'Sorteren op' ),
			t ( 'Oplopend' ),
			t ( 'Aflopend' ),
			t ( 'Items per pagina' ),
			t ( '- Alle -' ),
			t ( 'Startpunt' ),
			t ( '« eerste' ),
			t ( '‹ vorige' ),
			t ( 'volgende ›' ),
			t ( 'laatste »' ),
			t ( 'Merknaam' ),
			t ( 'Toepassingsdomein' ),
			t ( 'Toepassingsdomein (field_merk_toepassingsdomein)' ),
			t ( 'Overzicht' ),
			t ( 'Overzicht van alle merken waarvoor producten bestaan.' ),
			t ( 'Merken: selectielijst' ),
			t ( 'Geselecteerde lijst van merken binnen een bepaald toepassingsdomein.' ),
			t ( 'Toepassingsdomein: ICT' ) 
	);
	
	$views [$view->name] = $view;
	return $views;
}