<?php
/*
 * Copyright (C) 2017 bartgysens
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* Drupal Hooks */

/**
 * Implements hook_ctools_plugin_api().
 */
function argus_register_van_feiten_door_derden_ctools_plugin_api($module = NULL, $api = NULL) {
	if ($module == "field_group" && $api == "field_group") {
		return array (
				"version" => "1" 
		);
	}
}

/**
 * Implements hook_node_info()
 */
function argus_register_van_feiten_door_derden_node_info() {
	return array (
			'register_van_feiten_door_derden' => array (
					'name' => t ( 'Register van feiten door derden' ),
					'base' => 'node_content',
					'description' => t ( 'De werkgever beschikt over een instrument om de risicoanalyse van feiten veroorzaakt door derden te maken, nl. het <em>registeren van feiten door derden</em>. Dit register is een preventiedocument dat eigen is aan de materie van geweld, pesterijen en ongewenst seksueel gedrag op het werk.' ),
					'has_title' => '1',
					'title_label' => t ( 'Title' ),
					'help' => '' 
			) 
	);
}

/**
 * Implement hook_form()
 */
function argus_register_van_feiten_door_derden_form($node, $form_state) {
	return node_content_form ( $node, $form_state );
}

/**
 * Implementation of hook_views_api().
 */
function argus_register_van_feiten_door_derden_views_api() {
	return array (
			'api' => 3.0,
			'path' => drupal_get_path ( 'module', 'argus_register_van_feiten_door_derden' ) 
	); // replace demo with your content type

}