<?php
/*
 * Copyright (C) 2017 bartgysens
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* Drupal Hooks */

/**
 * Implements argus_beleidsplannen_menu().
 */
function argus_beleidsplannen_menu() {
	if (menu_load ( 'menu-modules' )) {
		$menu = 'menu-modules';
	} else {
		$menu = 'navigation';
	}
	
	$items = array ();
	$items ['beleidsplannen'] = array (
			'title' => t ( 'Beleidsplannen' ),
			'type' => MENU_NORMAL_ITEM,
			'menu_name' => $menu,
			'access arguments' => array (
					'access argus_beleidsplannen content' 
			),
			'expanded' => true 
	);
	$items ['beleidsplannen/structuur'] = array (
			'title' => 'Beleidsplannen - Structuur',
			'description' => 'Bekijk de boomstructuur van de beleidsplannen.',
			'page callback' => 'argus_beleidsplannen_structure',
			'access arguments' => array (
					'access argus_beleidsplannen content' 
			),
			'menu_name' => $menu 
	);
	
	$items ['schoolontwikkelingsplan'] = array (
			'title' => t ( 'Schoolontwikkelingsplan' ),
			'page callback' => 'argus_beleidsplannen_sop',
			'type' => MENU_NORMAL_ITEM,
			'menu_name' => $menu,
			'access arguments' => array (
					'access argus_beleidsplannen content' 
			),
			'expanded' => true 
	);
	
	$items ['jaaractieplan'] = array (
			'title' => t ( 'Jaaractieplan' ),
			'page callback' => 'argus_beleidsplannen_jap',
			'type' => MENU_NORMAL_ITEM,
			'menu_name' => $menu,
			'access arguments' => array (
					'access argus_beleidsplannen content' 
			),
			'expanded' => true 
	);
	return $items;
}

/**
 * Implements hook_permission().
 */
function argus_beleidsplannen_permission() {
	return array (
			'access argus_beleidsplannen content' => array (
					'title' => t ( 'Bekijken' ) 
			) 
	);
}

/**
 * Implements hook_ctools_plugin_api().
 */
function argus_beleidsplannen_ctools_plugin_api($module = NULL, $api = NULL) {
	if ($module == "field_group" && $api == "field_group") {
		return array (
				"version" => "1" 
		);
	}
}

/**
 * Implements hook_node_info()
 */
function argus_beleidsplannen_node_info() {
	// Replace demo with your content type definitions
	return array (
			'beleidsplan' => array (
					'name' => t ( 'Beleidsplan' ),
					'base' => 'node_content',
					'description' => t ( 'Maak een <em>beleidsplan</em> op basis van een vaste structuur en bouw een boomstructuur op om je beleid in kaart te brengen.' ),
					'has_title' => '1',
					'title_label' => t ( 'Onderwerp' ),
					'help' => '' 
			) 
	);
}

/**
 * Implement hook_form()
 */
function argus_beleidsplannen_form($node, $form_state) {
	return node_content_form ( $node, $form_state );
}

/**
 * Implementation of hook_views_api().
 */
function argus_beleidsplannen_views_api() {
	return array (
			'api' => 3.0,
			'path' => drupal_get_path ( 'module', 'argus_beleidsplannen' ) 
	);
}

/**
 * Implement hook_theme()
 */
function argus_beleidsplannen_theme() {
	return array (
			'argus_beleidsplannen_structure' => array (
					'template' => 'templates/argus_beleidsplannen--structure' 
			),
			'node__beleidsplan' => array (
					'render element' => 'content',
					'base hook' => 'node',
					'template' => 'node--beleidsplan',
					'path' => drupal_get_path ( 'module', 'argus_beleidsplannen' ) . '/templates' 
			),
			'edit-model-action' => array (
					'template' => 'templates/argus_beleidsplannen--edit-model-action' 
			),
			'argus_beleidsplannen_jap' => array (
					'template' => 'templates/argus_beleidsplannen--jaaractieplan' 
			),
			'argus_beleidsplannen_sop' => array (
					'template' => 'templates/argus_beleidsplannen--schoolontwikkelingsplan' 
			),
	);
}

/**
 * Hook preprocess for node
 *
 * @param type $variables        	
 */
function argus_beleidsplannen_preprocess_node(&$variables) {
	switch ($variables ['type']) {
		case 'beleidsplan' :
			if (user_access ( 'access argus_beleidsplannen content' )) {
				
				drupal_add_css ( drupal_get_path ( 'module', 'argus_beleidsplannen' ) . '/css/argus_beleidsplannen.css' );
				drupal_add_library ( 'system', 'drupal.collapse' );
				
				/* Set some global parameters */
				$node = $variables ['elements'] ['#node'];
				$variables ['node'] = $node;
				$variables ['nid'] = $node->nid;
				
				$params = explode ( '/', current_path () );
				if (array_key_exists ( 2, $params )) {
					$modus = $params [2];
				} else {
					$modus = '';
				}
				$variables ['modus'] = $modus;
				
				switch ($modus) {
					case 'actieplan' :
						drupal_add_js ( drupal_get_path ( 'module', 'argus_beleidsplannen' ) . '/js/argus_beleidsplannen_actieplan.js' );
						drupal_add_library ( 'system', 'ui.datepicker' );
				
						if (array_key_exists ( 'submit', $_POST )) {
								
							for ($cntr = 0; $cntr < $_POST['argus_beleidsplannen_cntr']; $cntr++){
								if (array_key_exists('argus_beleidsplannen_' . $cntr . '_aid', $_POST)){
									$aid = $_POST ['argus_beleidsplannen_' . $cntr . '_aid'];
										
									$delete_action = false;
									if (is_numeric ( $aid )) {
										if ($_POST ['argus_beleidsplannen_' . $cntr . '_action_description'] == '{delete}') {
											node_delete ( $aid );
											$delete_action = true;
										} else {
											$action = node_load ( $aid );
										}
									} else {
										$action = new stdClass ();
										$action->type = 'actie';
										$action->language = LANGUAGE_NONE;
										$action->status = 1;
										$action->promote = 0;
										$action->comment = 0;
										node_object_prepare ( $action );
											
										global $user;
										$action->uid = $user->uid;
										$action->field_referentie [LANGUAGE_NONE] [0] ['value'] = $node->nid . '-' . $_POST ['argus_beleidsplannen_' . $cntr . '_ref'] . '-' . $cntr;
										$action->field_beleidsplan [LANGUAGE_NONE] [0] ['target_id'] = $node->nid;
											
										/* Send user a Smartschool message (only new actions) */
										if (module_exists ( 'argus_sms_api' )) {
											$body = '<u>Herinnering</u><br /><br />Betreft: <strong>ACTIE BELEIDSPLAN ' . $node->title . '</strong><br />Leerling: <strong>' . argus_get_user_realname ( $_POST ['argus_beleidsplannen_' . $cntr . '_action_executor'] ) . '</strong><br />Te doen: <strong>' . $_POST ['argus_beleidsplannen_' . $cntr . '_action_description'] . '</strong><br />';
											// argus_sms_api_send_msg ( 'argus_beleidsplannen_new_action', $_POST ['argus_beleidsplannen_' . $ref . '_action_executor'] [$k], 0, $user->uid, 'Nieuwe actie aangemaakt voor beleidsplan: ' . $node->title, $body );
										}
									}
										
									if (!$delete_action){
										$action->body [LANGUAGE_NONE] [0] ['value'] = $_POST ['argus_beleidsplannen_' . $cntr . '_action_description'];
										$action->field_deadline [LANGUAGE_NONE] [0] ['value'] = date_format(date_create_from_format('d/m/Y', $_POST ['argus_beleidsplannen_'.$cntr.'_action_deadline']), 'Y-m-d');
										$action->field_status [LANGUAGE_NONE] [0] ['value'] = $_POST ['argus_beleidsplannen_' . $cntr . '_action_status'];
										$action->field_bedrag [LANGUAGE_NONE] [0] ['value'] = $_POST ['argus_beleidsplannen_' . $cntr . '_action_budget'];
										$action->field_gebruiker [LANGUAGE_NONE] [0] ['target_id'] = $_POST ['argus_beleidsplannen_' . $cntr . '_action_executor'];
										$action->title = 'Actie voor ' . argus_get_user_realname( $_POST ['argus_beleidsplannen_' . $cntr . '_action_executor'] ) . ' ihkv. het beleidsplan "' . $node->title . '" tegen ' . $_POST ['argus_beleidsplannen_'.$cntr.'_action_deadline'];
				
										$k = 0;
										$c = 0;
										foreach (list_allowed_values( field_info_field( 'field_integratie_r_ok' ) ) as $o ){
											if (array_key_exists('argus_beleidsplannen_'. $cntr . '_action_rok_'. $k, $_POST)){
												if ($_POST['argus_beleidsplannen_'. $cntr . '_action_rok_'. $k ]){
													$action->field_integratie_r_ok [LANGUAGE_NONE] [$c] ['value'] = $o;
													$c++;
												}
											}
											$k++;
										}
				
										node_save ( $action );
									}
								}
							}
						}
				
						break;
					default:
						drupal_add_js ( "https://www.google.com/jsapi?autoload={'modules':[{'name':'visualization','version':'1','packages':['corechart']}]}" );
						drupal_add_js ( drupal_get_path ( 'module', 'argus_beleidsplannen' ) . '/js/argus_beleidsplannen.js' );
				}
				
				$variables ['actions'] = array ();
				$variables ['action_plan'] = array();
				foreach ( $variables ['field_beleidsplan_op_doelst'] as $k => $d ) {
					$ref = md5 ( $d ['value'] );
					$query = 'SELECT r.entity_id AS id, field_referentie_value AS ref FROM {field_data_field_referentie} AS r INNER JOIN {field_data_field_deadline} AS d ON d.entity_id = r.entity_id WHERE r.field_referentie_value LIKE :od ORDER BY d.field_deadline_value ASC';
					$results = db_query ( $query, array (
							':od' => $node->nid . '-' . $ref . '-%' 
					) )->fetchAllKeyed( 0, 1 );
					
					$variables ['actions'][$ref] = array();
					foreach ($results as $aid => $aref){
						$action = node_load($aid);
						
						$a = array(
								'id' => $aid,
								'description' => $action->body [LANGUAGE_NONE] [0] ['value'],
								'gebruiker' => $action->field_gebruiker [LANGUAGE_NONE] [0] ['target_id'],
								'budget' => $action->field_bedrag [LANGUAGE_NONE] [0] ['value'],
								'status' => $action->field_status [LANGUAGE_NONE] [0] ['value'],
								'deadline' => format_date(strtotime($action->field_deadline [LANGUAGE_NONE] [0] ['value']),'custom', 'd/m/Y'),
								'cntr' => $k+1,
								'rok_opt' => array(),
						);
						
						if (array_key_exists(LANGUAGE_NONE, $action->field_integratie_r_ok)){
							foreach($action->field_integratie_r_ok[LANGUAGE_NONE] as $rok_opt){
								$a['rok_opt'][] = $rok_opt['value'];
							}
						}
						
						$variables ['actions'][$ref][] = $a;
						
						$variables ['action_plan'][$action->field_deadline [LANGUAGE_NONE] [0] ['value']][] = $a;
					}
				}
				
				ksort($variables ['action_plan']);
				
				// Preprocess fields.
				field_attach_preprocess ( 'node', $node, $variables ['elements'], $variables );
			} else {
				drupal_access_denied ();
				exit ();
			}
			break;
	}
}

/**
 * Page callback mapped to the url /beleidsplannen/structure
 *
 * @return array
 */
function argus_beleidsplannen_structure() {
	drupal_add_css ( drupal_get_path ( 'module', 'argus_beleidsplannen' ) . '/css/argus_beleidsplannen.css' );
	
	/* Load Google Charts API */
	drupal_add_js ( "https://www.gstatic.com/charts/loader.js" );
	
	drupal_add_js ( drupal_get_path ( 'module', 'argus_beleidsplannen' ) . '/js/argus_beleidsplannen_structure.js' );
	
	$data = array ();
	
	$query = 'SELECT n.nid AS id, p.field_beleidsplan_overkoepelend_target_id AS parent, n.title AS title, ikznr.field_ikz_nummer_value AS ikznr FROM {node} AS n
			LEFT JOIN {field_data_field_ikz_nummer} AS ikznr ON ikznr.entity_id = n.nid 
			LEFT JOIN {field_data_field_beleidsplan_overkoepelend} AS p ON p.entity_id = n.nid 
			WHERE n.type = :type ORDER BY p.field_beleidsplan_overkoepelend_target_id ASC
			';
	$results = db_query ( $query, array (
			':type' => 'beleidsplan' 
	) )->fetchAllAssoc ( 'id', PDO::FETCH_ASSOC );
	
	foreach ( $results as $id => $bp ) {
		$data [] = array (
				array (
						'v' => $bp ['id'],
						'f' => '<a href="' . drupal_get_path_alias ( '/node/' . $bp ['id'] ) . '">' . $bp ['title'] . '</a><br />IKZ-rev. ' . $bp ['ikznr'] 
				),
				$bp ['parent'],
				$bp ['title'] 
		);
	}
	
	return theme ( 'argus_beleidsplannen_structure', array (
			'data' => json_encode ( $data ) 
	) );
}

/**
 * Page callback mapped to the url /jaaractieplan
 *
 * @return array
 */
function argus_beleidsplannen_jap() {
	drupal_add_css ( drupal_get_path ( 'module', 'argus_beleidsplannen' ) . '/css/argus_beleidsplannen.css' );
	
	// Get all beleidsplannen
	$query = 'SELECT n.nid AS id, n.title AS title, od.field_beleidsplan_op_doelst_value AS od FROM {node} AS n INNER JOIN {field_data_field_beleidsplan_op_doelst} AS od ON od.entity_id = n.nid WHERE n.type = :type';
	$results = db_query ( $query, array (
			':type' => 'beleidsplan',
	) )->fetchAll();
	
	$variables ['actions'] = array();
	$cntr = 0;
	
	$schoolyear = 2018;
	
	$variables ['startdate'] = 0;
	$variables ['enddate'] = 0;
	foreach ($results as $bp){
		$query = 'SELECT r.entity_id AS id, field_referentie_value AS ref FROM {field_data_field_referentie} AS r INNER JOIN {field_data_field_deadline} AS d ON d.entity_id = r.entity_id WHERE r.field_referentie_value LIKE :od ORDER BY d.field_deadline_value ASC';
		$results = db_query ( $query, array (
				':od' => $bp->id . '-' . $ref . '-%',
		) )->fetchAllKeyed( 0, 1 );
		
		// Get all actions
		$ref = md5 ( $bp->od );
		$query = 'SELECT r.entity_id AS id, field_referentie_value AS ref FROM {field_data_field_referentie} AS r INNER JOIN {field_data_field_deadline} AS d ON d.entity_id = r.entity_id WHERE r.field_referentie_value LIKE :od AND d.field_deadline_value BETWEEN :startdate AND :enddate ORDER BY d.field_deadline_value ASC';
		$results = db_query ( $query, array (
				':od' => $bp->id . '-' . $ref . '-%',
				':startdate' => $schoolyear . '-09-01',
				':enddate' => ($schoolyear+1) . '-09-01',
		) )->fetchAllKeyed( 0, 1 );
		
		foreach ($results as $aid => $aref){
			$action = node_load($aid);
			
			$a = array(
					'id' => $aid,
					'bp_id' => $bp->id,
					'bp_title' => $bp->title,
					'description' => $action->body [LANGUAGE_NONE] [0] ['value'],
					'gebruiker' => $action->field_gebruiker [LANGUAGE_NONE] [0] ['target_id'],
					'budget' => $action->field_bedrag [LANGUAGE_NONE] [0] ['value'],
					'status' => $action->field_status [LANGUAGE_NONE] [0] ['value'],
					'deadline' => format_date(strtotime($action->field_deadline [LANGUAGE_NONE] [0] ['value']),'custom', 'd/m/Y'),
					'cntr' => $cntr++,
					'od' => $bp->od,
					'rok_opt' => array(),
			);
			
			if (array_key_exists(LANGUAGE_NONE, $action->field_integratie_r_ok)){
				foreach($action->field_integratie_r_ok[LANGUAGE_NONE] as $rok_opt){
					$a['rok_opt'][] = $rok_opt['value'];
				}
			}
			
			$variables ['actions'][$action->field_deadline [LANGUAGE_NONE] [0] ['value']][] = $a;
		}
	}
	
	ksort($variables ['actions']);
	
	return theme ( 'argus_beleidsplannen_jap', $variables );
}

/**
 * Page callback mapped to the url /schoolontwikkelingsplan
 *
 * @return array
 */
function argus_beleidsplannen_sop() {
	drupal_add_css ( drupal_get_path ( 'module', 'argus_beleidsplannen' ) . '/css/argus_beleidsplannen.css' );
	
	// Get all beleidsplannen
	$query = 'SELECT n.nid AS id, n.title AS title, od.field_beleidsplan_op_doelst_value AS od FROM {node} AS n INNER JOIN {field_data_field_beleidsplan_op_doelst} AS od ON od.entity_id = n.nid WHERE n.type = :type';
	$results = db_query ( $query, array (
			':type' => 'beleidsplan',
	) )->fetchAll();
	
	$variables ['actions'] = array();
	$cntr = 0;
	foreach ($results as $bp){
		
		// Get all actions
		$ref = md5 ( $bp->od );
		$query = 'SELECT r.entity_id AS id, field_referentie_value AS ref FROM {field_data_field_referentie} AS r INNER JOIN {field_data_field_deadline} AS d ON d.entity_id = r.entity_id WHERE r.field_referentie_value LIKE :od ORDER BY d.field_deadline_value ASC';
		$results = db_query ( $query, array (
				':od' => $bp->id . '-' . $ref . '-%'
		) )->fetchAllKeyed( 0, 1 );
		
		foreach ($results as $aid => $aref){
			$action = node_load($aid);
			
			$a = array(
					'id' => $aid,
					'bp_id' => $bp->id,
					'bp_title' => $bp->title,
					'description' => $action->body [LANGUAGE_NONE] [0] ['value'],
					'gebruiker' => $action->field_gebruiker [LANGUAGE_NONE] [0] ['target_id'],
					'budget' => $action->field_bedrag [LANGUAGE_NONE] [0] ['value'],
					'status' => $action->field_status [LANGUAGE_NONE] [0] ['value'],
					'deadline' => format_date(strtotime($action->field_deadline [LANGUAGE_NONE] [0] ['value']),'custom', 'd/m/Y'),
					'cntr' => $cntr++,
					'od' => $bp->od,
					'rok_opt' => array(),
			);
			
			if (array_key_exists(LANGUAGE_NONE, $action->field_integratie_r_ok)){
				foreach($action->field_integratie_r_ok[LANGUAGE_NONE] as $rok_opt){
					$a['rok_opt'][] = $rok_opt['value'];
				}
			}
			
			$variables ['actions'][$action->field_deadline [LANGUAGE_NONE] [0] ['value']][] = $a;
		}
	}
	
	ksort($variables ['actions']);
	
	return theme ( 'argus_beleidsplannen_sop', $variables );
}

/**
 * Implementation of hook_views_default_views().
 *
 * Views export creates code that you have to paste in this function.
 *
 * Administration > Structure > Views : click the button behind the view you need and export
 * /admin/structure/views
 */
function argus_beleidsplannen_views_default_views() {
	$export = array ();
	
	$view = new view ();
	$view->name = 'beleidsplannen';
	$view->description = '';
	$view->tag = 'default';
	$view->base_table = 'node';
	$view->human_name = 'Beleidsplannen';
	$view->core = 7;
	$view->api_version = '3.0';
	$view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */
	
	/* Display: Master */
	$handler = $view->new_display ( 'default', 'Master', 'default' );
	$handler->display->display_options ['title'] = 'Beleidsplannen';
	$handler->display->display_options ['use_more_always'] = FALSE;
	$handler->display->display_options ['use_more_text'] = 'meer';
	$handler->display->display_options ['group_by'] = TRUE;
	$handler->display->display_options ['access'] ['type'] = 'role';
	$handler->display->display_options ['access'] ['role'] = array ();
	$handler->display->display_options ['cache'] ['type'] = 'views_content_cache';
	$handler->display->display_options ['cache'] ['results_min_lifespan'] = '-1';
	$handler->display->display_options ['cache'] ['results_max_lifespan'] = '518400';
	$handler->display->display_options ['cache'] ['output_min_lifespan'] = '-1';
	$handler->display->display_options ['cache'] ['output_max_lifespan'] = '518400';
	$handler->display->display_options ['cache'] ['keys'] = array (
			'comment' => array (
					'changed' => 'changed' 
			),
			'node' => array (
					'beleidsplan' => 'beleidsplan' 
			),
			'node_only' => array (
					'node_changed' => 'node_changed' 
			) 
	);
	$handler->display->display_options ['query'] ['type'] = 'views_query';
	$handler->display->display_options ['exposed_form'] ['type'] = 'better_exposed_filters';
	$handler->display->display_options ['exposed_form'] ['options'] ['submit_button'] = 'Toepassen';
	$handler->display->display_options ['exposed_form'] ['options'] ['reset_button'] = TRUE;
	$handler->display->display_options ['exposed_form'] ['options'] ['reset_button_label'] = 'Opnieuw instellen';
	$handler->display->display_options ['exposed_form'] ['options'] ['exposed_sorts_label'] = 'Sorteren op';
	$handler->display->display_options ['exposed_form'] ['options'] ['sort_asc_label'] = 'Oplopend';
	$handler->display->display_options ['exposed_form'] ['options'] ['sort_desc_label'] = 'Aflopend';
	$handler->display->display_options ['exposed_form'] ['options'] ['autosubmit'] = TRUE;
	$handler->display->display_options ['exposed_form'] ['options'] ['bef'] = array (
			'general' => array (
					'input_required' => 0,
					'text_input_required' => array (
							'text_input_required' => array (
									'value' => 'Selecteer een van de filters en klik op \'Toepassen\' om het resultaat te zien',
									'format' => 'filtered_html' 
							) 
					),
					'allow_secondary' => 0,
					'secondary_label' => 'Uitgebreide opties',
					'secondary_collapse_override' => '0' 
			),
			'realname' => array (
					'bef_format' => 'default',
					'more_options' => array (
							'autosubmit' => 0,
							'is_secondary' => 0,
							'any_label' => '',
							'bef_filter_description' => '',
							'tokens' => array (
									'available' => array (
											0 => 'global_types' 
									) 
							),
							'rewrite' => array (
									'filter_rewrite_values' => '' 
							) 
					) 
			),
			'realname_1' => array (
					'bef_format' => 'default',
					'more_options' => array (
							'autosubmit' => 0,
							'is_secondary' => 0,
							'any_label' => '',
							'bef_filter_description' => '',
							'tokens' => array (
									'available' => array (
											0 => 'global_types' 
									) 
							),
							'rewrite' => array (
									'filter_rewrite_values' => '' 
							) 
					) 
			),
			'realname_2' => array (
					'bef_format' => 'default',
					'more_options' => array (
							'autosubmit' => 0,
							'is_secondary' => 0,
							'any_label' => '',
							'bef_filter_description' => '',
							'tokens' => array (
									'available' => array (
											0 => 'global_types' 
									) 
							),
							'rewrite' => array (
									'filter_rewrite_values' => '' 
							) 
					) 
			),
			'field_ikz_nummer_value' => array (
					'bef_format' => 'default',
					'more_options' => array (
							'autosubmit' => 0,
							'is_secondary' => 0,
							'any_label' => '',
							'bef_filter_description' => '',
							'tokens' => array (
									'available' => array (
											0 => 'global_types' 
									) 
							),
							'rewrite' => array (
									'filter_rewrite_values' => '' 
							) 
					) 
			),
			'field_beleidsplan_niveau_value' => array (
					'bef_format' => 'bef',
					'more_options' => array (
							'bef_select_all_none' => 0,
							'bef_collapsible' => 0,
							'autosubmit' => 0,
							'is_secondary' => 0,
							'any_label' => '',
							'bef_filter_description' => '',
							'tokens' => array (
									'available' => array (
											0 => 'global_types' 
									) 
							),
							'rewrite' => array (
									'filter_rewrite_values' => '' 
							) 
					) 
			) 
	);
	$handler->display->display_options ['pager'] ['type'] = 'none';
	$handler->display->display_options ['pager'] ['options'] ['offset'] = '0';
	$handler->display->display_options ['style_plugin'] = 'table';
	$handler->display->display_options ['style_options'] ['columns'] = array (
			'nid' => 'nid',
			'title' => 'title',
			'field_voorzitter' => 'field_voorzitter',
			'field_personeelsleden' => 'field_personeelsleden',
			'field_ikz_auditor' => 'field_ikz_auditor',
			'field_beleidsplan_niveau' => 'field_beleidsplan_niveau',
			'field_ikz_nummer' => 'field_ikz_nummer',
			'field_ikz_revisie' => 'field_ikz_revisie',
			'nothing' => 'nothing',
			'edit_node' => 'edit_node' 
	);
	$handler->display->display_options ['style_options'] ['default'] = '-1';
	$handler->display->display_options ['style_options'] ['info'] = array (
			'nid' => array (
					'sortable' => 0,
					'default_sort_order' => 'asc',
					'align' => '',
					'separator' => '',
					'empty_column' => 0 
			),
			'title' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_voorzitter' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_personeelsleden' => array (
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_ikz_auditor' => array (
					'align' => '',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_beleidsplan_niveau' => array (
					'sortable' => 0,
					'default_sort_order' => 'asc',
					'align' => '',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_ikz_nummer' => array (
					'sortable' => 0,
					'default_sort_order' => 'asc',
					'align' => '',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_ikz_revisie' => array (
					'sortable' => 0,
					'default_sort_order' => 'asc',
					'align' => '',
					'separator' => '',
					'empty_column' => 0 
			),
			'nothing' => array (
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'edit_node' => array (
					'align' => 'views-align-right',
					'separator' => '',
					'empty_column' => 0 
			) 
	);
	/* Kop: Algemeen: Tekstveld */
	$handler->display->display_options ['header'] ['area'] ['id'] = 'area';
	$handler->display->display_options ['header'] ['area'] ['table'] = 'views';
	$handler->display->display_options ['header'] ['area'] ['field'] = 'area';
	$handler->display->display_options ['header'] ['area'] ['empty'] = TRUE;
	$handler->display->display_options ['header'] ['area'] ['content'] = '<a href="/node/add/beleidsplan">Een nieuw beleidsplan toevoegen</a>';
	$handler->display->display_options ['header'] ['area'] ['format'] = 'filtered_html';
	/* Voet: Algemeen: Samenvatting van het resultaat */
	$handler->display->display_options ['footer'] ['result'] ['id'] = 'result';
	$handler->display->display_options ['footer'] ['result'] ['table'] = 'views';
	$handler->display->display_options ['footer'] ['result'] ['field'] = 'result';
	$handler->display->display_options ['footer'] ['result'] ['content'] = 'Getoond @start - @end van @total';
	/* Voet: Algemeen: Tekstveld */
	$handler->display->display_options ['footer'] ['area'] ['id'] = 'area';
	$handler->display->display_options ['footer'] ['area'] ['table'] = 'views';
	$handler->display->display_options ['footer'] ['area'] ['field'] = 'area';
	$handler->display->display_options ['footer'] ['area'] ['content'] = '<a href="/node/add/beleidsplan">Een nieuw beleidsplan toevoegen</a>';
	$handler->display->display_options ['footer'] ['area'] ['format'] = 'filtered_html';
	/* Relatie: auditor */
	$handler->display->display_options ['relationships'] ['field_ikz_auditor_target_id'] ['id'] = 'field_ikz_auditor_target_id';
	$handler->display->display_options ['relationships'] ['field_ikz_auditor_target_id'] ['table'] = 'field_data_field_ikz_auditor';
	$handler->display->display_options ['relationships'] ['field_ikz_auditor_target_id'] ['field'] = 'field_ikz_auditor_target_id';
	$handler->display->display_options ['relationships'] ['field_ikz_auditor_target_id'] ['ui_name'] = 'auditor';
	$handler->display->display_options ['relationships'] ['field_ikz_auditor_target_id'] ['label'] = 'auditor';
	/* Relatie: voorzitter */
	$handler->display->display_options ['relationships'] ['field_voorzitter_target_id'] ['id'] = 'field_voorzitter_target_id';
	$handler->display->display_options ['relationships'] ['field_voorzitter_target_id'] ['table'] = 'field_data_field_voorzitter';
	$handler->display->display_options ['relationships'] ['field_voorzitter_target_id'] ['field'] = 'field_voorzitter_target_id';
	$handler->display->display_options ['relationships'] ['field_voorzitter_target_id'] ['ui_name'] = 'voorzitter';
	$handler->display->display_options ['relationships'] ['field_voorzitter_target_id'] ['label'] = 'voorzitter';
	/* Relatie: leden */
	$handler->display->display_options ['relationships'] ['field_personeelsleden_target_id'] ['id'] = 'field_personeelsleden_target_id';
	$handler->display->display_options ['relationships'] ['field_personeelsleden_target_id'] ['table'] = 'field_data_field_personeelsleden';
	$handler->display->display_options ['relationships'] ['field_personeelsleden_target_id'] ['field'] = 'field_personeelsleden_target_id';
	$handler->display->display_options ['relationships'] ['field_personeelsleden_target_id'] ['ui_name'] = 'leden';
	$handler->display->display_options ['relationships'] ['field_personeelsleden_target_id'] ['label'] = 'leden';
	/* Veld: Inhoud: Nid */
	$handler->display->display_options ['fields'] ['nid'] ['id'] = 'nid';
	$handler->display->display_options ['fields'] ['nid'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['nid'] ['field'] = 'nid';
	$handler->display->display_options ['fields'] ['nid'] ['label'] = '';
	$handler->display->display_options ['fields'] ['nid'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['nid'] ['element_label_colon'] = FALSE;
	/* Veld: Inhoud: Titel */
	$handler->display->display_options ['fields'] ['title'] ['id'] = 'title';
	$handler->display->display_options ['fields'] ['title'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['title'] ['field'] = 'title';
	$handler->display->display_options ['fields'] ['title'] ['alter'] ['word_boundary'] = FALSE;
	$handler->display->display_options ['fields'] ['title'] ['alter'] ['ellipsis'] = FALSE;
	/* Veld: Veld: Voorzitter */
	$handler->display->display_options ['fields'] ['field_voorzitter'] ['id'] = 'field_voorzitter';
	$handler->display->display_options ['fields'] ['field_voorzitter'] ['table'] = 'field_data_field_voorzitter';
	$handler->display->display_options ['fields'] ['field_voorzitter'] ['field'] = 'field_voorzitter';
	$handler->display->display_options ['fields'] ['field_voorzitter'] ['settings'] = array (
			'bypass_access' => 0,
			'link' => '1',
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Inhoud: Leden */
	$handler->display->display_options ['fields'] ['field_personeelsleden'] ['id'] = 'field_personeelsleden';
	$handler->display->display_options ['fields'] ['field_personeelsleden'] ['table'] = 'field_data_field_personeelsleden';
	$handler->display->display_options ['fields'] ['field_personeelsleden'] ['field'] = 'field_personeelsleden';
	$handler->display->display_options ['fields'] ['field_personeelsleden'] ['settings'] = array (
			'bypass_access' => 0,
			'link' => '1',
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	$handler->display->display_options ['fields'] ['field_personeelsleden'] ['group_column'] = 'entity_id';
	$handler->display->display_options ['fields'] ['field_personeelsleden'] ['delta_offset'] = '0';
	$handler->display->display_options ['fields'] ['field_personeelsleden'] ['separator'] = ' - ';
	/* Veld: Inhoud: Auditor */
	$handler->display->display_options ['fields'] ['field_ikz_auditor'] ['id'] = 'field_ikz_auditor';
	$handler->display->display_options ['fields'] ['field_ikz_auditor'] ['table'] = 'field_data_field_ikz_auditor';
	$handler->display->display_options ['fields'] ['field_ikz_auditor'] ['field'] = 'field_ikz_auditor';
	$handler->display->display_options ['fields'] ['field_ikz_auditor'] ['label'] = '';
	$handler->display->display_options ['fields'] ['field_ikz_auditor'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['field_ikz_auditor'] ['element_label_colon'] = FALSE;
	$handler->display->display_options ['fields'] ['field_ikz_auditor'] ['settings'] = array (
			'bypass_access' => 0,
			'link' => '1',
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	$handler->display->display_options ['fields'] ['field_ikz_auditor'] ['group_column'] = 'entity_id';
	$handler->display->display_options ['fields'] ['field_ikz_auditor'] ['delta_offset'] = '0';
	/* Veld: Inhoud: Niveau */
	$handler->display->display_options ['fields'] ['field_beleidsplan_niveau'] ['id'] = 'field_beleidsplan_niveau';
	$handler->display->display_options ['fields'] ['field_beleidsplan_niveau'] ['table'] = 'field_data_field_beleidsplan_niveau';
	$handler->display->display_options ['fields'] ['field_beleidsplan_niveau'] ['field'] = 'field_beleidsplan_niveau';
	$handler->display->display_options ['fields'] ['field_beleidsplan_niveau'] ['label'] = '';
	$handler->display->display_options ['fields'] ['field_beleidsplan_niveau'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['field_beleidsplan_niveau'] ['element_label_colon'] = FALSE;
	$handler->display->display_options ['fields'] ['field_beleidsplan_niveau'] ['settings'] = array (
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Inhoud: Nummer */
	$handler->display->display_options ['fields'] ['field_ikz_nummer'] ['id'] = 'field_ikz_nummer';
	$handler->display->display_options ['fields'] ['field_ikz_nummer'] ['table'] = 'field_data_field_ikz_nummer';
	$handler->display->display_options ['fields'] ['field_ikz_nummer'] ['field'] = 'field_ikz_nummer';
	$handler->display->display_options ['fields'] ['field_ikz_nummer'] ['label'] = '';
	$handler->display->display_options ['fields'] ['field_ikz_nummer'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['field_ikz_nummer'] ['element_label_colon'] = FALSE;
	$handler->display->display_options ['fields'] ['field_ikz_nummer'] ['settings'] = array (
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Inhoud: Revisie */
	$handler->display->display_options ['fields'] ['field_ikz_revisie'] ['id'] = 'field_ikz_revisie';
	$handler->display->display_options ['fields'] ['field_ikz_revisie'] ['table'] = 'field_data_field_ikz_revisie';
	$handler->display->display_options ['fields'] ['field_ikz_revisie'] ['field'] = 'field_ikz_revisie';
	$handler->display->display_options ['fields'] ['field_ikz_revisie'] ['label'] = '';
	$handler->display->display_options ['fields'] ['field_ikz_revisie'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['field_ikz_revisie'] ['element_label_colon'] = FALSE;
	$handler->display->display_options ['fields'] ['field_ikz_revisie'] ['settings'] = array (
			'thousand_separator' => '',
			'prefix_suffix' => '1',
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Algemeen: Aangepaste tekst */
	$handler->display->display_options ['fields'] ['nothing'] ['id'] = 'nothing';
	$handler->display->display_options ['fields'] ['nothing'] ['table'] = 'views';
	$handler->display->display_options ['fields'] ['nothing'] ['field'] = 'nothing';
	$handler->display->display_options ['fields'] ['nothing'] ['label'] = 'IKZ';
	$handler->display->display_options ['fields'] ['nothing'] ['alter'] ['text'] = 'Nr. [field_ikz_nummer], rev. [field_ikz_revisie]<br />
Auditor: [field_ikz_auditor]<br />
<small>[field_beleidsplan_niveau]</small>';
	/* Veld: Inhoud: Bewerkingslink */
	$handler->display->display_options ['fields'] ['edit_node'] ['id'] = 'edit_node';
	$handler->display->display_options ['fields'] ['edit_node'] ['table'] = 'views_entity_node';
	$handler->display->display_options ['fields'] ['edit_node'] ['field'] = 'edit_node';
	$handler->display->display_options ['fields'] ['edit_node'] ['label'] = 'Acties';
	/* Sorteercriterium: Inhoud: Titel */
	$handler->display->display_options ['sorts'] ['title'] ['id'] = 'title';
	$handler->display->display_options ['sorts'] ['title'] ['table'] = 'node';
	$handler->display->display_options ['sorts'] ['title'] ['field'] = 'title';
	/* Filtercriterium: Inhoud: Gepubliceerd */
	$handler->display->display_options ['filters'] ['status'] ['id'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['status'] ['field'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['value'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['expose'] ['operator'] = FALSE;
	/* Filtercriterium: Inhoud: Type */
	$handler->display->display_options ['filters'] ['type'] ['id'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['type'] ['field'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['value'] = array (
			'beleidsplan' => 'beleidsplan' 
	);
	$handler->display->display_options ['filters'] ['type'] ['group'] = 1;
	/* Filtercriterium: Inhoud: Titel */
	$handler->display->display_options ['filters'] ['title'] ['id'] = 'title';
	$handler->display->display_options ['filters'] ['title'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['title'] ['field'] = 'title';
	$handler->display->display_options ['filters'] ['title'] ['operator'] = 'contains';
	$handler->display->display_options ['filters'] ['title'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['title'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['title'] ['expose'] ['operator_id'] = 'title_op';
	$handler->display->display_options ['filters'] ['title'] ['expose'] ['label'] = 'Onderwerp';
	$handler->display->display_options ['filters'] ['title'] ['expose'] ['operator'] = 'title_op';
	$handler->display->display_options ['filters'] ['title'] ['expose'] ['identifier'] = 'title';
	$handler->display->display_options ['filters'] ['title'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['filters'] ['title'] ['expose'] ['autocomplete_items'] = '10';
	$handler->display->display_options ['filters'] ['title'] ['expose'] ['autocomplete_min_chars'] = '0';
	$handler->display->display_options ['filters'] ['title'] ['expose'] ['autocomplete_field'] = 'title';
	$handler->display->display_options ['filters'] ['title'] ['expose'] ['autocomplete_raw_suggestion'] = '1';
	$handler->display->display_options ['filters'] ['title'] ['expose'] ['autocomplete_raw_dropdown'] = '1';
	$handler->display->display_options ['filters'] ['title'] ['expose'] ['autocomplete_dependent'] = 0;
	/* Filtercriterium: Echte naam: Naam */
	$handler->display->display_options ['filters'] ['realname_1'] ['id'] = 'realname_1';
	$handler->display->display_options ['filters'] ['realname_1'] ['table'] = 'realname';
	$handler->display->display_options ['filters'] ['realname_1'] ['field'] = 'realname';
	$handler->display->display_options ['filters'] ['realname_1'] ['relationship'] = 'field_voorzitter_target_id';
	$handler->display->display_options ['filters'] ['realname_1'] ['operator'] = 'contains';
	$handler->display->display_options ['filters'] ['realname_1'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['realname_1'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['realname_1'] ['expose'] ['operator_id'] = 'realname_1_op';
	$handler->display->display_options ['filters'] ['realname_1'] ['expose'] ['label'] = 'Voorzitter';
	$handler->display->display_options ['filters'] ['realname_1'] ['expose'] ['operator'] = 'realname_1_op';
	$handler->display->display_options ['filters'] ['realname_1'] ['expose'] ['identifier'] = 'realname_1';
	$handler->display->display_options ['filters'] ['realname_1'] ['expose'] ['remember_roles'] = array ();
	
	$handler->display->display_options ['filters'] ['realname_1'] ['expose'] ['autocomplete_items'] = '10';
	$handler->display->display_options ['filters'] ['realname_1'] ['expose'] ['autocomplete_min_chars'] = '0';
	$handler->display->display_options ['filters'] ['realname_1'] ['expose'] ['autocomplete_raw_suggestion'] = '1';
	$handler->display->display_options ['filters'] ['realname_1'] ['expose'] ['autocomplete_raw_dropdown'] = '1';
	$handler->display->display_options ['filters'] ['realname_1'] ['expose'] ['autocomplete_dependent'] = 0;
	/* Filtercriterium: Echte naam: Naam */
	$handler->display->display_options ['filters'] ['realname_2'] ['id'] = 'realname_2';
	$handler->display->display_options ['filters'] ['realname_2'] ['table'] = 'realname';
	$handler->display->display_options ['filters'] ['realname_2'] ['field'] = 'realname';
	$handler->display->display_options ['filters'] ['realname_2'] ['relationship'] = 'field_personeelsleden_target_id';
	$handler->display->display_options ['filters'] ['realname_2'] ['operator'] = 'contains';
	$handler->display->display_options ['filters'] ['realname_2'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['realname_2'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['realname_2'] ['expose'] ['operator_id'] = 'realname_2_op';
	$handler->display->display_options ['filters'] ['realname_2'] ['expose'] ['label'] = 'Leden';
	$handler->display->display_options ['filters'] ['realname_2'] ['expose'] ['operator'] = 'realname_2_op';
	$handler->display->display_options ['filters'] ['realname_2'] ['expose'] ['identifier'] = 'realname_2';
	$handler->display->display_options ['filters'] ['realname_2'] ['expose'] ['remember_roles'] = array ();
	
	$handler->display->display_options ['filters'] ['realname_2'] ['expose'] ['autocomplete_items'] = '10';
	$handler->display->display_options ['filters'] ['realname_2'] ['expose'] ['autocomplete_min_chars'] = '0';
	$handler->display->display_options ['filters'] ['realname_2'] ['expose'] ['autocomplete_raw_suggestion'] = '1';
	$handler->display->display_options ['filters'] ['realname_2'] ['expose'] ['autocomplete_raw_dropdown'] = '1';
	$handler->display->display_options ['filters'] ['realname_2'] ['expose'] ['autocomplete_dependent'] = 0;
	/* Filtercriterium: Echte naam: Naam */
	$handler->display->display_options ['filters'] ['realname'] ['id'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['table'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['field'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['relationship'] = 'field_ikz_auditor_target_id';
	$handler->display->display_options ['filters'] ['realname'] ['operator'] = 'contains';
	$handler->display->display_options ['filters'] ['realname'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['realname'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['operator_id'] = 'realname_op';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['label'] = 'Auditor';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['operator'] = 'realname_op';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['identifier'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['remember_roles'] = array ();
	
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_items'] = '10';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_min_chars'] = '0';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_raw_suggestion'] = '1';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_raw_dropdown'] = '1';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_dependent'] = 0;
	/* Filtercriterium: Inhoud: Nummer (field_ikz_nummer) */
	$handler->display->display_options ['filters'] ['field_ikz_nummer_value'] ['id'] = 'field_ikz_nummer_value';
	$handler->display->display_options ['filters'] ['field_ikz_nummer_value'] ['table'] = 'field_data_field_ikz_nummer';
	$handler->display->display_options ['filters'] ['field_ikz_nummer_value'] ['field'] = 'field_ikz_nummer_value';
	$handler->display->display_options ['filters'] ['field_ikz_nummer_value'] ['operator'] = 'contains';
	$handler->display->display_options ['filters'] ['field_ikz_nummer_value'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['field_ikz_nummer_value'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_ikz_nummer_value'] ['expose'] ['operator_id'] = 'field_ikz_nummer_value_op';
	$handler->display->display_options ['filters'] ['field_ikz_nummer_value'] ['expose'] ['label'] = 'Nummer';
	$handler->display->display_options ['filters'] ['field_ikz_nummer_value'] ['expose'] ['operator'] = 'field_ikz_nummer_value_op';
	$handler->display->display_options ['filters'] ['field_ikz_nummer_value'] ['expose'] ['identifier'] = 'field_ikz_nummer_value';
	$handler->display->display_options ['filters'] ['field_ikz_nummer_value'] ['expose'] ['remember_roles'] = array ();
	
	$handler->display->display_options ['filters'] ['field_ikz_nummer_value'] ['expose'] ['autocomplete_items'] = '10';
	$handler->display->display_options ['filters'] ['field_ikz_nummer_value'] ['expose'] ['autocomplete_min_chars'] = '0';
	$handler->display->display_options ['filters'] ['field_ikz_nummer_value'] ['expose'] ['autocomplete_field'] = 'field_ikz_nummer';
	$handler->display->display_options ['filters'] ['field_ikz_nummer_value'] ['expose'] ['autocomplete_raw_suggestion'] = '1';
	$handler->display->display_options ['filters'] ['field_ikz_nummer_value'] ['expose'] ['autocomplete_raw_dropdown'] = '1';
	$handler->display->display_options ['filters'] ['field_ikz_nummer_value'] ['expose'] ['autocomplete_dependent'] = 0;
	/* Filtercriterium: Inhoud: Niveau (field_beleidsplan_niveau) */
	$handler->display->display_options ['filters'] ['field_beleidsplan_niveau_value'] ['id'] = 'field_beleidsplan_niveau_value';
	$handler->display->display_options ['filters'] ['field_beleidsplan_niveau_value'] ['table'] = 'field_data_field_beleidsplan_niveau';
	$handler->display->display_options ['filters'] ['field_beleidsplan_niveau_value'] ['field'] = 'field_beleidsplan_niveau_value';
	$handler->display->display_options ['filters'] ['field_beleidsplan_niveau_value'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['field_beleidsplan_niveau_value'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_beleidsplan_niveau_value'] ['expose'] ['operator_id'] = 'field_beleidsplan_niveau_value_op';
	$handler->display->display_options ['filters'] ['field_beleidsplan_niveau_value'] ['expose'] ['label'] = 'Niveau';
	$handler->display->display_options ['filters'] ['field_beleidsplan_niveau_value'] ['expose'] ['operator'] = 'field_beleidsplan_niveau_value_op';
	$handler->display->display_options ['filters'] ['field_beleidsplan_niveau_value'] ['expose'] ['identifier'] = 'field_beleidsplan_niveau_value';
	$handler->display->display_options ['filters'] ['field_beleidsplan_niveau_value'] ['expose'] ['multiple'] = TRUE;
	$handler->display->display_options ['filters'] ['field_beleidsplan_niveau_value'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['qtip_tooltips'] = array (
			'nothing' => array (
					'show' => '1',
					'tooltip' => 'Interne Kwaliteitszorg' 
			) 
	);
	$handler->display->display_options ['qtip_instance'] = 'standaard';
	
	/* Display: Overzicht */
	$handler = $view->new_display ( 'page', 'Overzicht', 'beleidsplannen_overzicht' );
	$handler->display->display_options ['exposed_block'] = TRUE;
	$handler->display->display_options ['defaults'] ['fields'] = FALSE;
	/* Veld: Inhoud: Nid */
	$handler->display->display_options ['fields'] ['nid'] ['id'] = 'nid';
	$handler->display->display_options ['fields'] ['nid'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['nid'] ['field'] = 'nid';
	$handler->display->display_options ['fields'] ['nid'] ['label'] = '';
	$handler->display->display_options ['fields'] ['nid'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['nid'] ['element_label_colon'] = FALSE;
	/* Veld: Inhoud: Overkoepelend beleidsplan */
	$handler->display->display_options ['fields'] ['field_beleidsplan_overkoepelend'] ['id'] = 'field_beleidsplan_overkoepelend';
	$handler->display->display_options ['fields'] ['field_beleidsplan_overkoepelend'] ['table'] = 'field_data_field_beleidsplan_overkoepelend';
	$handler->display->display_options ['fields'] ['field_beleidsplan_overkoepelend'] ['field'] = 'field_beleidsplan_overkoepelend';
	$handler->display->display_options ['fields'] ['field_beleidsplan_overkoepelend'] ['label'] = '';
	$handler->display->display_options ['fields'] ['field_beleidsplan_overkoepelend'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['field_beleidsplan_overkoepelend'] ['alter'] ['alter_text'] = TRUE;
	$handler->display->display_options ['fields'] ['field_beleidsplan_overkoepelend'] ['alter'] ['text'] = 'onderdeel van <a href="/node/[field_beleidsplan_overkoepelend-target_id]">[field_beleidsplan_overkoepelend]</a>';
	$handler->display->display_options ['fields'] ['field_beleidsplan_overkoepelend'] ['element_label_colon'] = FALSE;
	$handler->display->display_options ['fields'] ['field_beleidsplan_overkoepelend'] ['settings'] = array (
			'bypass_access' => 0,
			'link' => 0,
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	$handler->display->display_options ['fields'] ['field_beleidsplan_overkoepelend'] ['group_column'] = 'entity_id';
	/* Veld: Inhoud: Titel */
	$handler->display->display_options ['fields'] ['title'] ['id'] = 'title';
	$handler->display->display_options ['fields'] ['title'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['title'] ['field'] = 'title';
	$handler->display->display_options ['fields'] ['title'] ['alter'] ['alter_text'] = TRUE;
	$handler->display->display_options ['fields'] ['title'] ['alter'] ['text'] = '<strong><a href="/node/[nid]">[title]</a></strong><br /><small>[field_beleidsplan_overkoepelend]</small>';
	$handler->display->display_options ['fields'] ['title'] ['alter'] ['word_boundary'] = FALSE;
	$handler->display->display_options ['fields'] ['title'] ['alter'] ['ellipsis'] = FALSE;
	$handler->display->display_options ['fields'] ['title'] ['link_to_node'] = FALSE;
	/* Veld: Veld: Voorzitter */
	$handler->display->display_options ['fields'] ['field_voorzitter'] ['id'] = 'field_voorzitter';
	$handler->display->display_options ['fields'] ['field_voorzitter'] ['table'] = 'field_data_field_voorzitter';
	$handler->display->display_options ['fields'] ['field_voorzitter'] ['field'] = 'field_voorzitter';
	$handler->display->display_options ['fields'] ['field_voorzitter'] ['settings'] = array (
			'bypass_access' => 0,
			'link' => '1',
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Inhoud: Leden */
	$handler->display->display_options ['fields'] ['field_personeelsleden'] ['id'] = 'field_personeelsleden';
	$handler->display->display_options ['fields'] ['field_personeelsleden'] ['table'] = 'field_data_field_personeelsleden';
	$handler->display->display_options ['fields'] ['field_personeelsleden'] ['field'] = 'field_personeelsleden';
	$handler->display->display_options ['fields'] ['field_personeelsleden'] ['settings'] = array (
			'bypass_access' => 0,
			'link' => '1',
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	$handler->display->display_options ['fields'] ['field_personeelsleden'] ['group_column'] = 'entity_id';
	$handler->display->display_options ['fields'] ['field_personeelsleden'] ['delta_offset'] = '0';
	$handler->display->display_options ['fields'] ['field_personeelsleden'] ['separator'] = ' - ';
	/* Veld: Inhoud: Auditor */
	$handler->display->display_options ['fields'] ['field_ikz_auditor'] ['id'] = 'field_ikz_auditor';
	$handler->display->display_options ['fields'] ['field_ikz_auditor'] ['table'] = 'field_data_field_ikz_auditor';
	$handler->display->display_options ['fields'] ['field_ikz_auditor'] ['field'] = 'field_ikz_auditor';
	$handler->display->display_options ['fields'] ['field_ikz_auditor'] ['label'] = '';
	$handler->display->display_options ['fields'] ['field_ikz_auditor'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['field_ikz_auditor'] ['element_label_colon'] = FALSE;
	$handler->display->display_options ['fields'] ['field_ikz_auditor'] ['settings'] = array (
			'bypass_access' => 0,
			'link' => '1',
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	$handler->display->display_options ['fields'] ['field_ikz_auditor'] ['group_column'] = 'entity_id';
	$handler->display->display_options ['fields'] ['field_ikz_auditor'] ['delta_offset'] = '0';
	/* Veld: Inhoud: Niveau */
	$handler->display->display_options ['fields'] ['field_beleidsplan_niveau'] ['id'] = 'field_beleidsplan_niveau';
	$handler->display->display_options ['fields'] ['field_beleidsplan_niveau'] ['table'] = 'field_data_field_beleidsplan_niveau';
	$handler->display->display_options ['fields'] ['field_beleidsplan_niveau'] ['field'] = 'field_beleidsplan_niveau';
	$handler->display->display_options ['fields'] ['field_beleidsplan_niveau'] ['label'] = '';
	$handler->display->display_options ['fields'] ['field_beleidsplan_niveau'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['field_beleidsplan_niveau'] ['element_label_colon'] = FALSE;
	$handler->display->display_options ['fields'] ['field_beleidsplan_niveau'] ['settings'] = array (
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Inhoud: Nummer */
	$handler->display->display_options ['fields'] ['field_ikz_nummer'] ['id'] = 'field_ikz_nummer';
	$handler->display->display_options ['fields'] ['field_ikz_nummer'] ['table'] = 'field_data_field_ikz_nummer';
	$handler->display->display_options ['fields'] ['field_ikz_nummer'] ['field'] = 'field_ikz_nummer';
	$handler->display->display_options ['fields'] ['field_ikz_nummer'] ['label'] = '';
	$handler->display->display_options ['fields'] ['field_ikz_nummer'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['field_ikz_nummer'] ['element_label_colon'] = FALSE;
	$handler->display->display_options ['fields'] ['field_ikz_nummer'] ['settings'] = array (
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Inhoud: Revisie */
	$handler->display->display_options ['fields'] ['field_ikz_revisie'] ['id'] = 'field_ikz_revisie';
	$handler->display->display_options ['fields'] ['field_ikz_revisie'] ['table'] = 'field_data_field_ikz_revisie';
	$handler->display->display_options ['fields'] ['field_ikz_revisie'] ['field'] = 'field_ikz_revisie';
	$handler->display->display_options ['fields'] ['field_ikz_revisie'] ['label'] = '';
	$handler->display->display_options ['fields'] ['field_ikz_revisie'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['field_ikz_revisie'] ['element_label_colon'] = FALSE;
	$handler->display->display_options ['fields'] ['field_ikz_revisie'] ['settings'] = array (
			'thousand_separator' => '',
			'prefix_suffix' => '1',
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Algemeen: Aangepaste tekst */
	$handler->display->display_options ['fields'] ['nothing'] ['id'] = 'nothing';
	$handler->display->display_options ['fields'] ['nothing'] ['table'] = 'views';
	$handler->display->display_options ['fields'] ['nothing'] ['field'] = 'nothing';
	$handler->display->display_options ['fields'] ['nothing'] ['label'] = 'IKZ';
	$handler->display->display_options ['fields'] ['nothing'] ['alter'] ['text'] = 'Nr. [field_ikz_nummer], rev. [field_ikz_revisie]<br />
Auditor: [field_ikz_auditor]<br />
<small>[field_beleidsplan_niveau]</small>';
	/* Veld: Inhoud: Bewerkingslink */
	$handler->display->display_options ['fields'] ['edit_node'] ['id'] = 'edit_node';
	$handler->display->display_options ['fields'] ['edit_node'] ['table'] = 'views_entity_node';
	$handler->display->display_options ['fields'] ['edit_node'] ['field'] = 'edit_node';
	$handler->display->display_options ['fields'] ['edit_node'] ['label'] = 'Acties';
	$handler->display->display_options ['qtip_instance'] = 'standaard';
	$handler->display->display_options ['path'] = 'beleidsplannen';
	$handler->display->display_options ['menu'] ['type'] = 'normal';
	$handler->display->display_options ['menu'] ['title'] = 'Beleidsplannen';
	if (menu_load ( 'menu-modules' )) {
		$menu = 'menu-modules';
	} else {
		$menu = 'navigation';
	}
	$handler->display->display_options ['menu'] ['name'] = $menu;
	
	/* Display: Selectie (per niveau) */
	$handler = $view->new_display ( 'entityreference', 'Selectie (per niveau)', 'beleidsplannen_selectie_per_niveau' );
	$handler->display->display_options ['defaults'] ['title'] = FALSE;
	$handler->display->display_options ['defaults'] ['group_by'] = FALSE;
	$handler->display->display_options ['defaults'] ['exposed_form'] = FALSE;
	$handler->display->display_options ['exposed_form'] ['type'] = 'basic';
	$handler->display->display_options ['exposed_form'] ['options'] ['submit_button'] = 'Toepassen';
	$handler->display->display_options ['exposed_form'] ['options'] ['reset_button'] = TRUE;
	$handler->display->display_options ['exposed_form'] ['options'] ['reset_button_label'] = 'Opnieuw instellen';
	$handler->display->display_options ['exposed_form'] ['options'] ['exposed_sorts_label'] = 'Sorteren op';
	$handler->display->display_options ['exposed_form'] ['options'] ['sort_asc_label'] = 'Oplopend';
	$handler->display->display_options ['exposed_form'] ['options'] ['sort_desc_label'] = 'Aflopend';
	$handler->display->display_options ['exposed_form'] ['options'] ['autosubmit'] = TRUE;
	$handler->display->display_options ['pager'] ['type'] = 'none';
	$handler->display->display_options ['defaults'] ['style_plugin'] = FALSE;
	$handler->display->display_options ['style_plugin'] = 'entityreference_style';
	$handler->display->display_options ['style_options'] ['grouping'] = array (
			0 => array (
					'field' => 'field_beleidsplan_niveau',
					'rendered' => '1',
					'rendered_strip' => 0 
			) 
	);
	$handler->display->display_options ['style_options'] ['search_fields'] = array (
			'title' => 'title',
			'nid' => 0,
			'field_beleidsplan_niveau' => 0 
	);
	$handler->display->display_options ['defaults'] ['style_options'] = FALSE;
	$handler->display->display_options ['defaults'] ['row_plugin'] = FALSE;
	$handler->display->display_options ['row_plugin'] = 'entityreference_fields';
	$handler->display->display_options ['defaults'] ['row_options'] = FALSE;
	$handler->display->display_options ['defaults'] ['header'] = FALSE;
	$handler->display->display_options ['defaults'] ['footer'] = FALSE;
	$handler->display->display_options ['defaults'] ['relationships'] = FALSE;
	$handler->display->display_options ['defaults'] ['fields'] = FALSE;
	/* Veld: Inhoud: Nid */
	$handler->display->display_options ['fields'] ['nid'] ['id'] = 'nid';
	$handler->display->display_options ['fields'] ['nid'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['nid'] ['field'] = 'nid';
	$handler->display->display_options ['fields'] ['nid'] ['label'] = '';
	$handler->display->display_options ['fields'] ['nid'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['nid'] ['element_label_colon'] = FALSE;
	/* Veld: Inhoud: Niveau */
	$handler->display->display_options ['fields'] ['field_beleidsplan_niveau'] ['id'] = 'field_beleidsplan_niveau';
	$handler->display->display_options ['fields'] ['field_beleidsplan_niveau'] ['table'] = 'field_data_field_beleidsplan_niveau';
	$handler->display->display_options ['fields'] ['field_beleidsplan_niveau'] ['field'] = 'field_beleidsplan_niveau';
	$handler->display->display_options ['fields'] ['field_beleidsplan_niveau'] ['label'] = '';
	$handler->display->display_options ['fields'] ['field_beleidsplan_niveau'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['field_beleidsplan_niveau'] ['element_label_colon'] = FALSE;
	$handler->display->display_options ['fields'] ['field_beleidsplan_niveau'] ['settings'] = array (
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Inhoud: Titel */
	$handler->display->display_options ['fields'] ['title'] ['id'] = 'title';
	$handler->display->display_options ['fields'] ['title'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['title'] ['field'] = 'title';
	$handler->display->display_options ['fields'] ['title'] ['label'] = '';
	$handler->display->display_options ['fields'] ['title'] ['alter'] ['word_boundary'] = FALSE;
	$handler->display->display_options ['fields'] ['title'] ['alter'] ['ellipsis'] = FALSE;
	$handler->display->display_options ['fields'] ['title'] ['element_label_colon'] = FALSE;
	$handler->display->display_options ['fields'] ['title'] ['link_to_node'] = FALSE;
	$handler->display->display_options ['defaults'] ['sorts'] = FALSE;
	/* Sorteercriterium: Inhoud: Niveau (field_beleidsplan_niveau) */
	$handler->display->display_options ['sorts'] ['field_beleidsplan_niveau_value'] ['id'] = 'field_beleidsplan_niveau_value';
	$handler->display->display_options ['sorts'] ['field_beleidsplan_niveau_value'] ['table'] = 'field_data_field_beleidsplan_niveau';
	$handler->display->display_options ['sorts'] ['field_beleidsplan_niveau_value'] ['field'] = 'field_beleidsplan_niveau_value';
	/* Sorteercriterium: Inhoud: Titel */
	$handler->display->display_options ['sorts'] ['title'] ['id'] = 'title';
	$handler->display->display_options ['sorts'] ['title'] ['table'] = 'node';
	$handler->display->display_options ['sorts'] ['title'] ['field'] = 'title';
	$handler->display->display_options ['defaults'] ['filter_groups'] = FALSE;
	$handler->display->display_options ['defaults'] ['filters'] = FALSE;
	/* Filtercriterium: Inhoud: Gepubliceerd */
	$handler->display->display_options ['filters'] ['status'] ['id'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['status'] ['field'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['value'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['expose'] ['operator'] = FALSE;
	/* Filtercriterium: Inhoud: Type */
	$handler->display->display_options ['filters'] ['type'] ['id'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['type'] ['field'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['value'] = array (
			'beleidsplan' => 'beleidsplan' 
	);
	$handler->display->display_options ['filters'] ['type'] ['group'] = 1;
	$handler->display->display_options ['qtip_instance'] = 'standaard';
	$translatables ['beleidsplannen'] = array (
			t ( 'Master' ),
			t ( 'Beleidsplannen' ),
			t ( 'meer' ),
			t ( 'Toepassen' ),
			t ( 'Opnieuw instellen' ),
			t ( 'Sorteren op' ),
			t ( 'Oplopend' ),
			t ( 'Aflopend' ),
			t ( 'Selecteer een van de filters en klik op \'Toepassen\' om het resultaat te zien' ),
			t ( 'Uitgebreide opties' ),
			t ( '<a href="/node/add/beleidsplan">Een nieuw beleidsplan toevoegen</a>' ),
			t ( 'Getoond @start - @end van @total' ),
			t ( 'auditor' ),
			t ( 'voorzitter' ),
			t ( 'leden' ),
			t ( 'Titel' ),
			t ( 'Voorzitter' ),
			t ( 'Leden' ),
			t ( 'IKZ' ),
			t ( 'Nr. [field_ikz_nummer], rev. [field_ikz_revisie]<br />
Auditor: [field_ikz_auditor]<br />
<small>[field_beleidsplan_niveau]</small>' ),
			t ( 'Acties' ),
			t ( 'Onderwerp' ),
			t ( 'Auditor' ),
			t ( 'Nummer' ),
			t ( 'Niveau' ),
			t ( 'Overzicht' ),
			t ( 'onderdeel van <a href="/node/[field_beleidsplan_overkoepelend-target_id]">[field_beleidsplan_overkoepelend]</a>' ),
			t ( '<strong><a href="/node/[nid]">[title]</a></strong><br /><small>[field_beleidsplan_overkoepelend]</small>' ),
			t ( 'Selectie (per niveau)' ) 
	);
	$export ['beleidsplannen'] = $view;
	
	return $export;
}

/* Supporting function */
/**
 * Output html used as model for generating actions
 *        	
 */
function argus_beleidsplannen_model_action($body = '', $deadline = NULL, $executor = NULL, $budget = 0, $status = 'nieuw', $rok_opts = array(), $aid = '{aid}', $ref = '{ref}', $cntr = '{cntr}', $class = '{class}') {
	global $user;
	
	if (is_null ( $executor )) {
		$executor = $user->uid;
	}
	
	$executor_roles = array (
			88,
			87,
			225 
	);
	$query = 'SELECT ur.uid FROM {users_roles} AS ur INNER JOIN {users} AS u ON u.uid = ur.uid INNER JOIN {field_data_field_user_sms_naam} AS un ON un.entity_id = ur.uid INNER JOIN {field_data_field_user_sms_voornaam} AS uf ON uf.entity_id = ur.uid WHERE ur.rid in (:rids) AND u.status = 1 ORDER BY un.field_user_sms_naam_value ASC, uf.field_user_sms_voornaam_value ASC';
	$executors = db_query ( $query, array (
			':rids' => $executor_roles 
	) )->fetchCol ();
	
	if (is_null ( $deadline )) {
		$deadline = format_date ( time (), 'custom', 'd/m/Y' );
	}
	
	return theme ( 'edit-model-action', array (
			'body' => $body,
			'deadline' => $deadline,
			'ref' => $ref,
			'aid' => $aid,
			'status' => $status,
			'rok_opts' => $rok_opts,
			'executors' => $executors,
			'executor' => $executor,
			'budget' => $budget,
			'cntr' => $cntr,
			'class' => $class
	) );
}