<?php
/**
 * @file
 * argus_beleidsplannen.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function argus_beleidsplannen_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_beleidsplan_doelstellingen'.
  $field_bases['field_beleidsplan_doelstellingen'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_beleidsplan_doelstellingen',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  // Exported field_base: 'field_beleidsplan_niveau'.
  $field_bases['field_beleidsplan_niveau'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_beleidsplan_niveau',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'Directie - Schoolniveau (macro)' => 'Directie - Schoolniveau (macro)',
        'Middenkader  - Coördinatieniveau (meso)' => 'Middenkader  - Coördinatieniveau (meso)',
        'Werknemers - Klas-/vak-/groepsniveau (micro)' => 'Werknemers - Klas-/vak-/groepsniveau (micro)',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_beleidsplan_overkoepelend'.
  $field_bases['field_beleidsplan_overkoepelend'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_beleidsplan_overkoepelend',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'target_id' => array(
        0 => 'target_id',
      ),
    ),
    'locked' => 0,
    'module' => 'entityreference',
    'settings' => array(
      'handler' => 'views',
      'handler_settings' => array(
        'behaviors' => array(
          'views-select-list' => array(
            'status' => 0,
          ),
        ),
        'view' => array(
          'args' => array(),
          'display_name' => 'beleidsplannen_selectie_per_niveau',
          'view_name' => 'beleidsplannen',
        ),
      ),
      'target_type' => 'node',
    ),
    'translatable' => 0,
    'type' => 'entityreference',
  );

  // Exported field_base: 'field_beleidsplan_planning'.
  $field_bases['field_beleidsplan_planning'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_beleidsplan_planning',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'text_with_summary',
  );

  return $field_bases;
}
