<?php
/**
 * @file
 * argus_preventieregister.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function argus_preventieregister_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: menu-modules_a-documenten:node/65776.
  $menu_links['menu-modules_a-documenten:node/65776'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/65776',
    'router_path' => 'node/%',
    'link_title' => 'A Documenten',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_a-documenten:node/65776',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_preventieregister:node/31032',
  );
  // Exported menu link: menu-modules_a01-bestelbon---aankoopprocedure:node/31033.
  $menu_links['menu-modules_a01-bestelbon---aankoopprocedure:node/31033'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/31033',
    'router_path' => 'node/%',
    'link_title' => 'A01 Bestelbon - Aankoopprocedure',
    'options' => array(
      'alter' => TRUE,
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-modules_a01-bestelbon---aankoopprocedure:node/31033',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_a-documenten:node/65776',
  );
  // Exported menu link: menu-modules_a02-ce-attesten-en-conformiteitsattesten:node/31034.
  $menu_links['menu-modules_a02-ce-attesten-en-conformiteitsattesten:node/31034'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/31034',
    'router_path' => 'node/%',
    'link_title' => 'A02 CE-attesten en Conformiteitsattesten',
    'options' => array(
      'alter' => TRUE,
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-modules_a02-ce-attesten-en-conformiteitsattesten:node/31034',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_a-documenten:node/65776',
  );
  // Exported menu link: menu-modules_a03-globaal-preventieplan:node/31337.
  $menu_links['menu-modules_a03-globaal-preventieplan:node/31337'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/31337',
    'router_path' => 'node/%',
    'link_title' => 'A03 Globaal preventieplan',
    'options' => array(
      'alter' => TRUE,
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-modules_a03-globaal-preventieplan:node/31337',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_a-documenten:node/65776',
  );
  // Exported menu link: menu-modules_a04-interventiedossier:node/31338.
  $menu_links['menu-modules_a04-interventiedossier:node/31338'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/31338',
    'router_path' => 'node/%',
    'link_title' => 'A04 Interventiedossier',
    'options' => array(
      'alter' => TRUE,
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-modules_a04-interventiedossier:node/31338',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_a-documenten:node/65776',
  );
  // Exported menu link: menu-modules_a05-identificatiedocument:node/31352.
  $menu_links['menu-modules_a05-identificatiedocument:node/31352'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/31352',
    'router_path' => 'node/%',
    'link_title' => 'A05 Identificatiedocument',
    'options' => array(
      'alter' => TRUE,
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-modules_a05-identificatiedocument:node/31352',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_a-documenten:node/65776',
  );
  // Exported menu link: menu-modules_a06-jaaractieplan:node/31353.
  $menu_links['menu-modules_a06-jaaractieplan:node/31353'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/31353',
    'router_path' => 'node/%',
    'link_title' => 'A06 Jaaractieplan',
    'options' => array(
      'alter' => TRUE,
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-modules_a06-jaaractieplan:node/31353',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_a-documenten:node/65776',
  );
  // Exported menu link: menu-modules_a07-noodprocedures:node/31354.
  $menu_links['menu-modules_a07-noodprocedures:node/31354'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/31354',
    'router_path' => 'node/%',
    'link_title' => 'A07 Noodprocedures',
    'options' => array(
      'alter' => TRUE,
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-modules_a07-noodprocedures:node/31354',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_a-documenten:node/65776',
  );
  // Exported menu link: menu-modules_a08-onderhoudssteekkaarten:node/31355.
  $menu_links['menu-modules_a08-onderhoudssteekkaarten:node/31355'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/31355',
    'router_path' => 'node/%',
    'link_title' => 'A08 Onderhoudssteekkaarten',
    'options' => array(
      'alter' => TRUE,
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-modules_a08-onderhoudssteekkaarten:node/31355',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_a-documenten:node/65776',
  );
  // Exported menu link: menu-modules_a09-onthaalbrochure:node/31359.
  $menu_links['menu-modules_a09-onthaalbrochure:node/31359'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/31359',
    'router_path' => 'node/%',
    'link_title' => 'A09 Onthaalbrochure',
    'options' => array(
      'alter' => TRUE,
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-modules_a09-onthaalbrochure:node/31359',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_a-documenten:node/65776',
  );
  // Exported menu link: menu-modules_a10-opleidingen:node/31361.
  $menu_links['menu-modules_a10-opleidingen:node/31361'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/31361',
    'router_path' => 'node/%',
    'link_title' => 'A10 Opleidingen',
    'options' => array(
      'alter' => TRUE,
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-modules_a10-opleidingen:node/31361',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -41,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_a-documenten:node/65776',
  );
  // Exported menu link: menu-modules_a11-preventiebeleidsverklaring:node/31362.
  $menu_links['menu-modules_a11-preventiebeleidsverklaring:node/31362'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/31362',
    'router_path' => 'node/%',
    'link_title' => 'A11 Preventiebeleidsverklaring',
    'options' => array(
      'alter' => TRUE,
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-modules_a11-preventiebeleidsverklaring:node/31362',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -40,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_a-documenten:node/65776',
  );
  // Exported menu link: menu-modules_a12-veiligheidsinstructiekaarten:node/31363.
  $menu_links['menu-modules_a12-veiligheidsinstructiekaarten:node/31363'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/31363',
    'router_path' => 'node/%',
    'link_title' => 'A12 Veiligheidsinstructiekaarten',
    'options' => array(
      'alter' => TRUE,
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-modules_a12-veiligheidsinstructiekaarten:node/31363',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -39,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_a-documenten:node/65776',
  );
  // Exported menu link: menu-modules_a13-legionella-veteranenziekte:node/31364.
  $menu_links['menu-modules_a13-legionella-veteranenziekte:node/31364'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/31364',
    'router_path' => 'node/%',
    'link_title' => 'A13 Legionella (Veteranenziekte)',
    'options' => array(
      'alter' => TRUE,
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-modules_a13-legionella-veteranenziekte:node/31364',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -38,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_a-documenten:node/65776',
  );
  // Exported menu link: menu-modules_a14-werken-met-derden:node/31370.
  $menu_links['menu-modules_a14-werken-met-derden:node/31370'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/31370',
    'router_path' => 'node/%',
    'link_title' => 'A14 Werken met derden',
    'options' => array(
      'alter' => TRUE,
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-modules_a14-werken-met-derden:node/31370',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -37,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_a-documenten:node/65776',
  );
  // Exported menu link: menu-modules_a15-stagedoende-jongeren:node/31371.
  $menu_links['menu-modules_a15-stagedoende-jongeren:node/31371'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/31371',
    'router_path' => 'node/%',
    'link_title' => 'A15 Stagedoende jongeren',
    'options' => array(
      'alter' => TRUE,
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-modules_a15-stagedoende-jongeren:node/31371',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -31,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_a-documenten:node/65776',
  );
  // Exported menu link: menu-modules_a16-clb:node/31372.
  $menu_links['menu-modules_a16-clb:node/31372'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/31372',
    'router_path' => 'node/%',
    'link_title' => 'A16 CLB',
    'options' => array(
      'alter' => TRUE,
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-modules_a16-clb:node/31372',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -35,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_a-documenten:node/65776',
  );
  // Exported menu link: menu-modules_a17-arbeidsreglementen:node/31373.
  $menu_links['menu-modules_a17-arbeidsreglementen:node/31373'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/31373',
    'router_path' => 'node/%',
    'link_title' => 'A17 Arbeidsreglementen',
    'options' => array(
      'alter' => TRUE,
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-modules_a17-arbeidsreglementen:node/31373',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -34,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_a-documenten:node/65776',
  );
  // Exported menu link: menu-modules_a181-explosieveiligheidsdocument:node/31374.
  $menu_links['menu-modules_a181-explosieveiligheidsdocument:node/31374'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/31374',
    'router_path' => 'node/%',
    'link_title' => 'A18.1 Explosieveiligheidsdocument',
    'options' => array(
      'alter' => TRUE,
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-modules_a181-explosieveiligheidsdocument:node/31374',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -33,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_a-documenten:node/65776',
  );
  // Exported menu link: menu-modules_a182-zoneringsdossier:node/65765.
  $menu_links['menu-modules_a182-zoneringsdossier:node/65765'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/65765',
    'router_path' => 'node/%',
    'link_title' => 'A18.2 Zoneringsdossier',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_a182-zoneringsdossier:node/65765',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -32,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_a-documenten:node/65776',
  );
  // Exported menu link: menu-modules_a191-rookbeleid:node/65766.
  $menu_links['menu-modules_a191-rookbeleid:node/65766'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/65766',
    'router_path' => 'node/%',
    'link_title' => 'A19.1 Rookbeleid',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_a191-rookbeleid:node/65766',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -31,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_a-documenten:node/65776',
  );
  // Exported menu link: menu-modules_a192-beleid-alcohol-en-andere-drugs:node/65767.
  $menu_links['menu-modules_a192-beleid-alcohol-en-andere-drugs:node/65767'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/65767',
    'router_path' => 'node/%',
    'link_title' => 'A19.2 Beleid alcohol en andere drugs',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_a192-beleid-alcohol-en-andere-drugs:node/65767',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -30,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_a-documenten:node/65776',
  );
  // Exported menu link: menu-modules_a20-dossier-elektrische-installatie:node/65768.
  $menu_links['menu-modules_a20-dossier-elektrische-installatie:node/65768'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/65768',
    'router_path' => 'node/%',
    'link_title' => 'A20 Dossier elektrische installatie',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_a20-dossier-elektrische-installatie:node/65768',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -29,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_a-documenten:node/65776',
  );
  // Exported menu link: menu-modules_a21-register-van-feiten-door-derden:node/65769.
  $menu_links['menu-modules_a21-register-van-feiten-door-derden:node/65769'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/65769',
    'router_path' => 'node/%',
    'link_title' => 'A21 Register van feiten door derden',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_a21-register-van-feiten-door-derden:node/65769',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -28,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_a-documenten:node/65776',
  );
  // Exported menu link: menu-modules_a22-evacuatieplannen:node/65770.
  $menu_links['menu-modules_a22-evacuatieplannen:node/65770'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/65770',
    'router_path' => 'node/%',
    'link_title' => 'A22 Evacuatieplannen',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_a22-evacuatieplannen:node/65770',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -27,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_a-documenten:node/65776',
  );
  // Exported menu link: menu-modules_a23-brandbestrijdingsdienst:node/65771.
  $menu_links['menu-modules_a23-brandbestrijdingsdienst:node/65771'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/65771',
    'router_path' => 'node/%',
    'link_title' => 'A23 Brandbestrijdingsdienst',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_a23-brandbestrijdingsdienst:node/65771',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -26,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_a-documenten:node/65776',
  );
  // Exported menu link: menu-modules_a24-brandpreventiedossier:node/65772.
  $menu_links['menu-modules_a24-brandpreventiedossier:node/65772'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/65772',
    'router_path' => 'node/%',
    'link_title' => 'A24 Brandpreventiedossier',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_a24-brandpreventiedossier:node/65772',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -25,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_a-documenten:node/65776',
  );
  // Exported menu link: menu-modules_a25-andere:node/69649.
  $menu_links['menu-modules_a25-andere:node/69649'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/69649',
    'router_path' => 'node/%',
    'link_title' => 'A25 Andere',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_a25-andere:node/69649',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'menu-modules_a-documenten:node/65776',
  );
  // Exported menu link: menu-modules_b-inventarisatie:node/65777.
  $menu_links['menu-modules_b-inventarisatie:node/65777'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/65777',
    'router_path' => 'node/%',
    'link_title' => 'B Inventarisatie',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_b-inventarisatie:node/65777',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_preventieregister:node/31032',
  );
  // Exported menu link: menu-modules_b01-asbest:node/31375.
  $menu_links['menu-modules_b01-asbest:node/31375'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/31375',
    'router_path' => 'node/%',
    'link_title' => 'B01 Asbest',
    'options' => array(
      'alter' => TRUE,
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-modules_b01-asbest:node/31375',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_b-inventarisatie:node/65777',
  );
  // Exported menu link: menu-modules_b02-ehbo-registratie:node/65904.
  $menu_links['menu-modules_b02-ehbo-registratie:node/65904'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/65904',
    'router_path' => 'node/%',
    'link_title' => 'B02 EHBO-registratie',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_b02-ehbo-registratie:node/65904',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_b-inventarisatie:node/65777',
  );
  // Exported menu link: menu-modules_b03-gevaarlijke-stoffen-en-preparaten:node/44746.
  $menu_links['menu-modules_b03-gevaarlijke-stoffen-en-preparaten:node/44746'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/44746',
    'router_path' => 'node/%',
    'link_title' => 'B03 Gevaarlijke stoffen en preparaten',
    'options' => array(
      'alter' => TRUE,
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-modules_b03-gevaarlijke-stoffen-en-preparaten:node/44746',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_b-inventarisatie:node/65777',
  );
  // Exported menu link: menu-modules_b04-arbeidsmiddelen-pbm-en-cbm:node/65906.
  $menu_links['menu-modules_b04-arbeidsmiddelen-pbm-en-cbm:node/65906'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/65906',
    'router_path' => 'node/%',
    'link_title' => 'B04 Arbeidsmiddelen, PBM en CBM',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_b04-arbeidsmiddelen-pbm-en-cbm:node/65906',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_b-inventarisatie:node/65777',
  );
  // Exported menu link: menu-modules_b05-ongevallen:node/66395.
  $menu_links['menu-modules_b05-ongevallen:node/66395'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/66395',
    'router_path' => 'node/%',
    'link_title' => 'B05 Ongevallen',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_b05-ongevallen:node/66395',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'menu-modules_b-inventarisatie:node/65777',
  );
  // Exported menu link: menu-modules_b06-controlelijsten:node/66396.
  $menu_links['menu-modules_b06-controlelijsten:node/66396'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/66396',
    'router_path' => 'node/%',
    'link_title' => 'B06 Controlelijsten',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_b06-controlelijsten:node/66396',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'menu-modules_b-inventarisatie:node/65777',
  );
  // Exported menu link: menu-modules_c-keuringen-en-periodieke-controles:node/65778.
  $menu_links['menu-modules_c-keuringen-en-periodieke-controles:node/65778'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/65778',
    'router_path' => 'node/%',
    'link_title' => 'C Keuringen en periodieke controles',
    'options' => array(
      'alter' => TRUE,
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-modules_c-keuringen-en-periodieke-controles:node/65778',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_preventieregister:node/31032',
  );
  // Exported menu link: menu-modules_c01-brandalarminstallaties:node/66428.
  $menu_links['menu-modules_c01-brandalarminstallaties:node/66428'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/66428',
    'router_path' => 'node/%',
    'link_title' => 'C01 Brandalarminstallaties',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_c01-brandalarminstallaties:node/66428',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'menu-modules_c-keuringen-en-periodieke-controles:node/65778',
  );
  // Exported menu link: menu-modules_c02-beschermingsmiddelen-tegen-brand:node/66440.
  $menu_links['menu-modules_c02-beschermingsmiddelen-tegen-brand:node/66440'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/66440',
    'router_path' => 'node/%',
    'link_title' => 'C02 Beschermingsmiddelen tegen brand',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_c02-beschermingsmiddelen-tegen-brand:node/66440',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'menu-modules_c-keuringen-en-periodieke-controles:node/65778',
  );
  // Exported menu link: menu-modules_c04-hefwerktuigen:node/66446.
  $menu_links['menu-modules_c04-hefwerktuigen:node/66446'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/66446',
    'router_path' => 'node/%',
    'link_title' => 'C04 Hefwerktuigen',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_c04-hefwerktuigen:node/66446',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'menu-modules_c-keuringen-en-periodieke-controles:node/65778',
  );
  // Exported menu link: menu-modules_c05-elektrische-installatie-hoogspanning:node/66451.
  $menu_links['menu-modules_c05-elektrische-installatie-hoogspanning:node/66451'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/66451',
    'router_path' => 'node/%',
    'link_title' => 'C05 Elektrische installatie: hoogspanning',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_c05-elektrische-installatie-hoogspanning:node/66451',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'menu-modules_c-keuringen-en-periodieke-controles:node/65778',
  );
  // Exported menu link: menu-modules_c06-elektrische-installatie-laagspanning:node/66452.
  $menu_links['menu-modules_c06-elektrische-installatie-laagspanning:node/66452'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/66452',
    'router_path' => 'node/%',
    'link_title' => 'C06 Elektrische installatie: laagspanning',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_c06-elektrische-installatie-laagspanning:node/66452',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'menu-modules_c-keuringen-en-periodieke-controles:node/65778',
  );
  // Exported menu link: menu-modules_c07-gasinstallatie:node/66487.
  $menu_links['menu-modules_c07-gasinstallatie:node/66487'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/66487',
    'router_path' => 'node/%',
    'link_title' => 'C07 Gasinstallatie',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_c07-gasinstallatie:node/66487',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'menu-modules_c-keuringen-en-periodieke-controles:node/65778',
  );
  // Exported menu link: menu-modules_c09-ladders-en-verplaatsbare-trappen:node/66489.
  $menu_links['menu-modules_c09-ladders-en-verplaatsbare-trappen:node/66489'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/66489',
    'router_path' => 'node/%',
    'link_title' => 'C09 Ladders en verplaatsbare trappen',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_c09-ladders-en-verplaatsbare-trappen:node/66489',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'menu-modules_c-keuringen-en-periodieke-controles:node/65778',
  );
  // Exported menu link: menu-modules_c10-liften:node/66488.
  $menu_links['menu-modules_c10-liften:node/66488'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/66488',
    'router_path' => 'node/%',
    'link_title' => 'C10 Liften',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_c10-liften:node/66488',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'menu-modules_c-keuringen-en-periodieke-controles:node/65778',
  );
  // Exported menu link: menu-modules_c11-luchtcompressoren:node/67005.
  $menu_links['menu-modules_c11-luchtcompressoren:node/67005'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/67005',
    'router_path' => 'node/%',
    'link_title' => 'C11 Luchtcompressoren',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_c11-luchtcompressoren:node/67005',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'menu-modules_c-keuringen-en-periodieke-controles:node/65778',
  );
  // Exported menu link: menu-modules_c12-pbm-en-cbm:node/67007.
  $menu_links['menu-modules_c12-pbm-en-cbm:node/67007'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/67007',
    'router_path' => 'node/%',
    'link_title' => 'C12 PBM en CBM',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_c12-pbm-en-cbm:node/67007',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'menu-modules_c-keuringen-en-periodieke-controles:node/65778',
  );
  // Exported menu link: menu-modules_c13-rook--en-gasdetectoren:node/67008.
  $menu_links['menu-modules_c13-rook--en-gasdetectoren:node/67008'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/67008',
    'router_path' => 'node/%',
    'link_title' => 'C13 Rook- en gasdetectoren',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_c13-rook--en-gasdetectoren:node/67008',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'menu-modules_c-keuringen-en-periodieke-controles:node/65778',
  );
  // Exported menu link: menu-modules_c14-stellingen:node/67010.
  $menu_links['menu-modules_c14-stellingen:node/67010'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/67010',
    'router_path' => 'node/%',
    'link_title' => 'C14 Stellingen',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_c14-stellingen:node/67010',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'menu-modules_c-keuringen-en-periodieke-controles:node/65778',
  );
  // Exported menu link: menu-modules_c16-veiligheidsverlichting:node/67022.
  $menu_links['menu-modules_c16-veiligheidsverlichting:node/67022'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/67022',
    'router_path' => 'node/%',
    'link_title' => 'C16 Veiligheidsverlichting',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_c16-veiligheidsverlichting:node/67022',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'menu-modules_c-keuringen-en-periodieke-controles:node/65778',
  );
  // Exported menu link: menu-modules_c172-verwarmingsinstallaties-aardgas:node/67963.
  $menu_links['menu-modules_c172-verwarmingsinstallaties-aardgas:node/67963'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/67963',
    'router_path' => 'node/%',
    'link_title' => 'C17.2 Verwarmingsinstallaties: (aard)gas',
    'options' => array(
      'alter' => TRUE,
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-modules_c172-verwarmingsinstallaties-aardgas:node/67963',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'menu-modules_c-keuringen-en-periodieke-controles:node/65778',
  );
  // Exported menu link: menu-modules_c18-lasmateriaal:node/67965.
  $menu_links['menu-modules_c18-lasmateriaal:node/67965'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/67965',
    'router_path' => 'node/%',
    'link_title' => 'C18 Lasmateriaal',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_c18-lasmateriaal:node/67965',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'menu-modules_c-keuringen-en-periodieke-controles:node/65778',
  );
  // Exported menu link: menu-modules_c21-andere:node/67966.
  $menu_links['menu-modules_c21-andere:node/67966'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/67966',
    'router_path' => 'node/%',
    'link_title' => 'C21 Andere',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_c21-andere:node/67966',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'menu-modules_c-keuringen-en-periodieke-controles:node/65778',
  );
  // Exported menu link: menu-modules_d-vergunningen:node/65779.
  $menu_links['menu-modules_d-vergunningen:node/65779'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/65779',
    'router_path' => 'node/%',
    'link_title' => 'D Vergunningen',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_d-vergunningen:node/65779',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_preventieregister:node/31032',
  );
  // Exported menu link: menu-modules_d01-keukens:node/68208.
  $menu_links['menu-modules_d01-keukens:node/68208'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/68208',
    'router_path' => 'node/%',
    'link_title' => 'D01 Keukens',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_d01-keukens:node/68208',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_d-vergunningen:node/65779',
  );
  // Exported menu link: menu-modules_d02-milieuvergunning:node/68209.
  $menu_links['menu-modules_d02-milieuvergunning:node/68209'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/68209',
    'router_path' => 'node/%',
    'link_title' => 'D02 Milieuvergunning',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_d02-milieuvergunning:node/68209',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_d-vergunningen:node/65779',
  );
  // Exported menu link: menu-modules_d05-farmaceutische-producten:node/68290.
  $menu_links['menu-modules_d05-farmaceutische-producten:node/68290'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/68290',
    'router_path' => 'node/%',
    'link_title' => 'D05 Farmaceutische producten',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_d05-farmaceutische-producten:node/68290',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_d-vergunningen:node/65779',
  );
  // Exported menu link: menu-modules_d06-andere:node/65773.
  $menu_links['menu-modules_d06-andere:node/65773'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/65773',
    'router_path' => 'node/%',
    'link_title' => 'D06 Andere',
    'options' => array(
      'alter' => TRUE,
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-modules_d06-andere:node/65773',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_d-vergunningen:node/65779',
  );
  // Exported menu link: menu-modules_e-verslagen:node/65780.
  $menu_links['menu-modules_e-verslagen:node/65780'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/65780',
    'router_path' => 'node/%',
    'link_title' => 'E Verslagen',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_e-verslagen:node/65780',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_preventieregister:node/31032',
  );
  // Exported menu link: menu-modules_e01-evacuatieoefening:node/68312.
  $menu_links['menu-modules_e01-evacuatieoefening:node/68312'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/68312',
    'router_path' => 'node/%',
    'link_title' => 'E01 Evacuatieoefening',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_e01-evacuatieoefening:node/68312',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'menu-modules_e-verslagen:node/65780',
  );
  // Exported menu link: menu-modules_e02-jaarverslag:node/68459.
  $menu_links['menu-modules_e02-jaarverslag:node/68459'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/68459',
    'router_path' => 'node/%',
    'link_title' => 'E02 Jaarverslag',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_e02-jaarverslag:node/68459',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'menu-modules_e-verslagen:node/65780',
  );
  // Exported menu link: menu-modules_e03-brandveiligheidsverslag---brandrisico:node/68460.
  $menu_links['menu-modules_e03-brandveiligheidsverslag---brandrisico:node/68460'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/68460',
    'router_path' => 'node/%',
    'link_title' => 'E03 Brandveiligheidsverslag - Brandrisico',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_e03-brandveiligheidsverslag---brandrisico:node/68460',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'menu-modules_e-verslagen:node/65780',
  );
  // Exported menu link: menu-modules_e04-indienststellings--en-buitengebruikstellingsverslagen:node/68580.
  $menu_links['menu-modules_e04-indienststellings--en-buitengebruikstellingsverslagen:node/68580'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/68580',
    'router_path' => 'node/%',
    'link_title' => 'E04 Indienststellings- en buitengebruikstellingsverslagen',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_e04-indienststellings--en-buitengebruikstellingsverslagen:node/68580',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'menu-modules_e-verslagen:node/65780',
  );
  // Exported menu link: menu-modules_e05-inspectieverslagen:node/68820.
  $menu_links['menu-modules_e05-inspectieverslagen:node/68820'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/68820',
    'router_path' => 'node/%',
    'link_title' => 'E05 Inspectieverslagen',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_e05-inspectieverslagen:node/68820',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'menu-modules_e-verslagen:node/65780',
  );
  // Exported menu link: menu-modules_e06-basiscomit--tussencomit:node/68821.
  $menu_links['menu-modules_e06-basiscomit--tussencomit:node/68821'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/68821',
    'router_path' => 'node/%',
    'link_title' => 'E06 Basiscomité / Tussencomité',
    'options' => array(
      'alter' => TRUE,
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-modules_e06-basiscomit--tussencomit:node/68821',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'menu-modules_e-verslagen:node/65780',
  );
  // Exported menu link: menu-modules_e07-preventieverslagen-idpbw:node/68827.
  $menu_links['menu-modules_e07-preventieverslagen-idpbw:node/68827'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/68827',
    'router_path' => 'node/%',
    'link_title' => 'E07 Preventieverslagen IDPBW',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_e07-preventieverslagen-idpbw:node/68827',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'menu-modules_e-verslagen:node/65780',
  );
  // Exported menu link: menu-modules_e08-preventieverslagen-edpbw:node/68826.
  $menu_links['menu-modules_e08-preventieverslagen-edpbw:node/68826'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/68826',
    'router_path' => 'node/%',
    'link_title' => 'E08 Preventieverslagen EDPBW',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_e08-preventieverslagen-edpbw:node/68826',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'menu-modules_e-verslagen:node/65780',
  );
  // Exported menu link: menu-modules_e09-andere:node/68824.
  $menu_links['menu-modules_e09-andere:node/68824'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/68824',
    'router_path' => 'node/%',
    'link_title' => 'E09 Andere',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_e09-andere:node/68824',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'menu-modules_e-verslagen:node/65780',
  );
  // Exported menu link: menu-modules_logboek---preventie:verslagen/logboek/preventie.
  $menu_links['menu-modules_logboek---preventie:verslagen/logboek/preventie'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'verslagen/logboek/preventie',
    'router_path' => 'verslagen/%',
    'link_title' => 'Logboek - preventie',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-modules_logboek---preventie:verslagen/logboek/preventie',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_preventieregister:node/31032',
  );
  // Exported menu link: menu-modules_preventieregister:node/31032.
  $menu_links['menu-modules_preventieregister:node/31032'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => 'node/31032',
    'router_path' => 'node/%',
    'link_title' => 'Preventieregister',
    'options' => array(
      'alter' => TRUE,
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => 'icon_safety',
        'style' => '',
      ),
      'identifier' => 'menu-modules_preventieregister:node/31032',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'menu-modules_veiligheid--welzijn:<nolink>',
  );
  // Exported menu link: menu-modules_veiligheid--welzijn:<nolink>.
  $menu_links['menu-modules_veiligheid--welzijn:<nolink>'] = array(
    'menu_name' => 'menu-modules',
    'link_path' => '<nolink>',
    'router_path' => '<nolink>',
    'link_title' => 'Veiligheid & welzijn',
    'options' => array(
      'alter' => TRUE,
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-modules_veiligheid--welzijn:<nolink>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 8,
    'customized' => 1,
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('A Documenten');
  t('A01 Bestelbon - Aankoopprocedure');
  t('A02 CE-attesten en Conformiteitsattesten');
  t('A03 Globaal preventieplan');
  t('A04 Interventiedossier');
  t('A05 Identificatiedocument');
  t('A06 Jaaractieplan');
  t('A07 Noodprocedures');
  t('A08 Onderhoudssteekkaarten');
  t('A09 Onthaalbrochure');
  t('A10 Opleidingen');
  t('A11 Preventiebeleidsverklaring');
  t('A12 Veiligheidsinstructiekaarten');
  t('A13 Legionella (Veteranenziekte)');
  t('A14 Werken met derden');
  t('A15 Stagedoende jongeren');
  t('A16 CLB');
  t('A17 Arbeidsreglementen');
  t('A18.1 Explosieveiligheidsdocument');
  t('A18.2 Zoneringsdossier');
  t('A19.1 Rookbeleid');
  t('A19.2 Beleid alcohol en andere drugs');
  t('A20 Dossier elektrische installatie');
  t('A21 Register van feiten door derden');
  t('A22 Evacuatieplannen');
  t('A23 Brandbestrijdingsdienst');
  t('A24 Brandpreventiedossier');
  t('A25 Andere');
  t('B Inventarisatie');
  t('B01 Asbest');
  t('B02 EHBO-registratie');
  t('B03 Gevaarlijke stoffen en preparaten');
  t('B04 Arbeidsmiddelen, PBM en CBM');
  t('B05 Ongevallen');
  t('B06 Controlelijsten');
  t('C Keuringen en periodieke controles');
  t('C01 Brandalarminstallaties');
  t('C02 Beschermingsmiddelen tegen brand');
  t('C04 Hefwerktuigen');
  t('C05 Elektrische installatie: hoogspanning');
  t('C06 Elektrische installatie: laagspanning');
  t('C07 Gasinstallatie');
  t('C09 Ladders en verplaatsbare trappen');
  t('C10 Liften');
  t('C11 Luchtcompressoren');
  t('C12 PBM en CBM');
  t('C13 Rook- en gasdetectoren');
  t('C14 Stellingen');
  t('C16 Veiligheidsverlichting');
  t('C17.2 Verwarmingsinstallaties: (aard)gas');
  t('C18 Lasmateriaal');
  t('C21 Andere');
  t('D Vergunningen');
  t('D01 Keukens');
  t('D02 Milieuvergunning');
  t('D05 Farmaceutische producten');
  t('D06 Andere');
  t('E Verslagen');
  t('E01 Evacuatieoefening');
  t('E02 Jaarverslag');
  t('E03 Brandveiligheidsverslag - Brandrisico');
  t('E04 Indienststellings- en buitengebruikstellingsverslagen');
  t('E05 Inspectieverslagen');
  t('E06 Basiscomité / Tussencomité');
  t('E07 Preventieverslagen IDPBW');
  t('E08 Preventieverslagen EDPBW');
  t('E09 Andere');
  t('Logboek - preventie');
  t('Preventieregister');
  t('Veiligheid & welzijn');

  return $menu_links;
}
