<?php
/*
 * Copyright (C) 2017 bartgysens
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* Drupal Hooks */

/**
 * Implements hook_ctools_plugin_api().
 */
function argus_aankoopdossiers_ctools_plugin_api($module = NULL, $api = NULL) {
	if ($module == "field_group" && $api == "field_group") {
		return array (
				"version" => "1" 
		);
	}
}

/**
 * Implements hook_node_info()
 */
function argus_aankoopdossiers_node_info() {
	return array (
			'aankoopdossier' => array (
					'name' => t ( 'Aankoopdossier' ),
					'base' => 'node_content',
					'description' => t ( 'Beheer de <em>aankoopdossiers</em> voor investeringen, kapitaalsaankopen en ander diensten en materialen.' ),
					'has_title' => '1',
					'title_label' => t ( 'Dossiernaam' ),
					'help' => ''
			) 
	);
}

/**
 * Implement hook_form()
 */
function argus_aankoopdossiers_form($node, $form_state) {
	return node_content_form ( $node, $form_state );
}

/**
 * Implementation of hook_views_api().
 */
function argus_aankoopdossiers_views_api() {
	return array (
			'api' => 3.0,
			'path' => drupal_get_path ( 'module', 'argus_aankoopdossiers' ) 
	);
}

// 3.
// Views export creates code that you have to paste in this function.
/**
 * Implementation of hook_views_default_views().
 */
function argus_aankoopdossiers_views_default_views() {
	$view = new view ();
	$view->name = 'aankoopdossiers';
	$view->description = '';
	$view->tag = 'default';
	$view->base_table = 'node';
	$view->human_name = 'Aankoopdossiers';
	$view->core = 7;
	$view->api_version = '3.0';
	$view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */
	
	/* Display: Master */
	$handler = $view->new_display ( 'default', 'Master', 'default' );
	$handler->display->display_options ['title'] = 'Aankoopdossiers';
	$handler->display->display_options ['use_more_always'] = FALSE;
	$handler->display->display_options ['use_more_text'] = 'meer';
	$handler->display->display_options ['access'] ['type'] = 'perm';
	$handler->display->display_options ['cache'] ['type'] = 'views_content_cache';
	$handler->display->display_options ['cache'] ['results_min_lifespan'] = '-1';
	$handler->display->display_options ['cache'] ['results_max_lifespan'] = '518400';
	$handler->display->display_options ['cache'] ['output_min_lifespan'] = '-1';
	$handler->display->display_options ['cache'] ['output_max_lifespan'] = '518400';
	$handler->display->display_options ['cache'] ['keys'] = array (
			'comment' => array (
					'changed' => 0 
			),
			'node' => array (
					'aankoopdossier' => 'aankoopdossier' 
			),
			'node_only' => array (
					'node_changed' => 'node_changed' 
			) 
	);
	$handler->display->display_options ['query'] ['type'] = 'views_query';
	$handler->display->display_options ['exposed_form'] ['type'] = 'better_exposed_filters';
	$handler->display->display_options ['exposed_form'] ['options'] ['submit_button'] = 'Toepassen';
	$handler->display->display_options ['exposed_form'] ['options'] ['reset_button'] = TRUE;
	$handler->display->display_options ['exposed_form'] ['options'] ['reset_button_label'] = 'Opnieuw instellen';
	$handler->display->display_options ['exposed_form'] ['options'] ['exposed_sorts_label'] = 'Sorteren op';
	$handler->display->display_options ['exposed_form'] ['options'] ['sort_asc_label'] = 'Oplopend';
	$handler->display->display_options ['exposed_form'] ['options'] ['sort_desc_label'] = 'Aflopend';
	$handler->display->display_options ['exposed_form'] ['options'] ['autosubmit'] = FALSE;
	$handler->display->display_options ['exposed_form'] ['options'] ['bef'] = array (
			'general' => array (
					'allow_secondary' => 0,
					'secondary_label' => 'Uitgebreide opties' 
			),
			'field_aankoop_status_value' => array (
					'bef_format' => 'bef',
					'more_options' => array (
							'bef_select_all_none' => 0,
							'bef_collapsible' => 0,
							'is_secondary' => 0,
							'any_label' => '',
							'bef_filter_description' => '',
							'tokens' => array (
									'available' => array (
											0 => 'global_types' 
									) 
							),
							'rewrite' => array (
									'filter_rewrite_values' => '' 
							) 
					) 
			),
			'field_aankoop_vakgroep_target_id_entityreference_filter' => array (
					'bef_format' => 'bef',
					'more_options' => array (
							'bef_select_all_none' => 0,
							'bef_collapsible' => '1',
							'is_secondary' => 0,
							'any_label' => '',
							'bef_filter_description' => '',
							'tokens' => array (
									'available' => array (
											0 => 'global_types' 
									) 
							),
							'rewrite' => array (
									'filter_rewrite_values' => '' 
							) 
					) 
			) 
	);
	$handler->display->display_options ['pager'] ['type'] = 'full';
	$handler->display->display_options ['pager'] ['options'] ['items_per_page'] = '50';
	$handler->display->display_options ['pager'] ['options'] ['expose'] ['items_per_page_label'] = 'Items per pagina';
	$handler->display->display_options ['pager'] ['options'] ['expose'] ['items_per_page_options_all_label'] = '- Alle -';
	$handler->display->display_options ['pager'] ['options'] ['expose'] ['offset_label'] = 'Startpunt';
	$handler->display->display_options ['pager'] ['options'] ['tags'] ['first'] = '« eerste';
	$handler->display->display_options ['pager'] ['options'] ['tags'] ['previous'] = '‹ vorige';
	$handler->display->display_options ['pager'] ['options'] ['tags'] ['next'] = 'volgende ›';
	$handler->display->display_options ['pager'] ['options'] ['tags'] ['last'] = 'laatste »';
	$handler->display->display_options ['style_plugin'] = 'table';
	$handler->display->display_options ['style_options'] ['columns'] = array (
			'field_aankoop_budget' => 'field_aankoop_budget',
			'field_aankoop_factuurbedrag' => 'field_aankoop_factuurbedrag',
			'expression' => 'expression',
			'title' => 'title',
			'field_aankoop_status' => 'field_aankoop_status',
			'created' => 'created',
			'timestamp' => 'timestamp',
			'field_aankoop_vakgroep' => 'field_aankoop_vakgroep',
			'field_aankoop_budget_1' => 'field_aankoop_budget_1',
			'field_aankoop_factuurbedrag_1' => 'field_aankoop_factuurbedrag_1',
			'field_aankoop_conclusie' => 'field_aankoop_conclusie',
			'field_aankoop_vergelijking' => 'field_aankoop_vergelijking' 
	);
	$handler->display->display_options ['style_options'] ['default'] = '-1';
	$handler->display->display_options ['style_options'] ['info'] = array (
			'field_aankoop_budget' => array (
					'sortable' => 1,
					'default_sort_order' => 'asc',
					'align' => 'views-align-right',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_aankoop_factuurbedrag' => array (
					'sortable' => 1,
					'default_sort_order' => 'asc',
					'align' => 'views-align-right',
					'separator' => '',
					'empty_column' => 0 
			),
			'expression' => array (
					'align' => 'views-align-right',
					'separator' => '',
					'empty_column' => 0 
			),
			'title' => array (
					'sortable' => 1,
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_aankoop_status' => array (
					'sortable' => 1,
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'created' => array (
					'sortable' => 1,
					'default_sort_order' => 'asc',
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			),
			'timestamp' => array (
					'sortable' => 1,
					'default_sort_order' => 'asc',
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_aankoop_vakgroep' => array (
					'sortable' => 1,
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_aankoop_budget_1' => array (
					'sortable' => 1,
					'default_sort_order' => 'asc',
					'align' => 'views-align-right',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_aankoop_factuurbedrag_1' => array (
					'sortable' => 1,
					'default_sort_order' => 'asc',
					'align' => 'views-align-right',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_aankoop_conclusie' => array (
					'sortable' => 1,
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_aankoop_vergelijking' => array (
					'sortable' => 0,
					'default_sort_order' => 'asc',
					'align' => '',
					'separator' => '',
					'empty_column' => 0 
			) 
	);
	$handler->display->display_options ['style_options'] ['sticky'] = TRUE;
	/* Kop: Algemeen: Tekstveld */
	$handler->display->display_options ['header'] ['area'] ['id'] = 'area';
	$handler->display->display_options ['header'] ['area'] ['table'] = 'views';
	$handler->display->display_options ['header'] ['area'] ['field'] = 'area';
	$handler->display->display_options ['header'] ['area'] ['empty'] = TRUE;
	$handler->display->display_options ['header'] ['area'] ['content'] = '<a href="/node/add/aankoopdossier">Een nieuw aankoopdossier toevoegen</a>';
	$handler->display->display_options ['header'] ['area'] ['format'] = 'filtered_html';
	/* Voet: Algemeen: Samenvatting van het resultaat */
	$handler->display->display_options ['footer'] ['result'] ['id'] = 'result';
	$handler->display->display_options ['footer'] ['result'] ['table'] = 'views';
	$handler->display->display_options ['footer'] ['result'] ['field'] = 'result';
	$handler->display->display_options ['footer'] ['result'] ['content'] = 'Getoond @start - @end van @total';
	/* Voet: Algemeen: Tekstveld */
	$handler->display->display_options ['footer'] ['area'] ['id'] = 'area';
	$handler->display->display_options ['footer'] ['area'] ['table'] = 'views';
	$handler->display->display_options ['footer'] ['area'] ['field'] = 'area';
	$handler->display->display_options ['footer'] ['area'] ['content'] = '<a href="/node/add/aankoopdossier">Een nieuw aankoopdossier toevoegen</a>';
	$handler->display->display_options ['footer'] ['area'] ['format'] = 'filtered_html';
	/* Veld: Inhoud: Budget */
	$handler->display->display_options ['fields'] ['field_aankoop_budget'] ['id'] = 'field_aankoop_budget';
	$handler->display->display_options ['fields'] ['field_aankoop_budget'] ['table'] = 'field_data_field_aankoop_budget';
	$handler->display->display_options ['fields'] ['field_aankoop_budget'] ['field'] = 'field_aankoop_budget';
	$handler->display->display_options ['fields'] ['field_aankoop_budget'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['field_aankoop_budget'] ['settings'] = array (
			'thousand_separator' => '',
			'decimal_separator' => '.',
			'scale' => '2',
			'prefix_suffix' => 0 
	);
	/* Veld: Inhoud: Factuurbedrag */
	$handler->display->display_options ['fields'] ['field_aankoop_factuurbedrag'] ['id'] = 'field_aankoop_factuurbedrag';
	$handler->display->display_options ['fields'] ['field_aankoop_factuurbedrag'] ['table'] = 'field_data_field_aankoop_factuurbedrag';
	$handler->display->display_options ['fields'] ['field_aankoop_factuurbedrag'] ['field'] = 'field_aankoop_factuurbedrag';
	$handler->display->display_options ['fields'] ['field_aankoop_factuurbedrag'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['field_aankoop_factuurbedrag'] ['alter'] ['text'] = '[field_aankoop_factuurbedrag]<br>
(=[field_aankoop_budget]-[field_aankoop_factuurbedrag])';
	$handler->display->display_options ['fields'] ['field_aankoop_factuurbedrag'] ['settings'] = array (
			'thousand_separator' => '',
			'decimal_separator' => '.',
			'scale' => '2',
			'prefix_suffix' => 0 
	);
	/* Veld: Algemeen: Wiskundige expressie */
	$handler->display->display_options ['fields'] ['expression'] ['id'] = 'expression';
	$handler->display->display_options ['fields'] ['expression'] ['table'] = 'views';
	$handler->display->display_options ['fields'] ['expression'] ['field'] = 'expression';
	$handler->display->display_options ['fields'] ['expression'] ['label'] = 'Verschil';
	$handler->display->display_options ['fields'] ['expression'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['expression'] ['set_precision'] = TRUE;
	$handler->display->display_options ['fields'] ['expression'] ['precision'] = '2';
	$handler->display->display_options ['fields'] ['expression'] ['decimal'] = ',';
	$handler->display->display_options ['fields'] ['expression'] ['separator'] = '';
	$handler->display->display_options ['fields'] ['expression'] ['expression'] = '[field_aankoop_budget] - [field_aankoop_factuurbedrag]';
	/* Veld: Inhoud: Titel */
	$handler->display->display_options ['fields'] ['title'] ['id'] = 'title';
	$handler->display->display_options ['fields'] ['title'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['title'] ['field'] = 'title';
	$handler->display->display_options ['fields'] ['title'] ['label'] = 'Betreft';
	$handler->display->display_options ['fields'] ['title'] ['alter'] ['word_boundary'] = FALSE;
	$handler->display->display_options ['fields'] ['title'] ['alter'] ['ellipsis'] = FALSE;
	/* Veld: Inhoud: Status */
	$handler->display->display_options ['fields'] ['field_aankoop_status'] ['id'] = 'field_aankoop_status';
	$handler->display->display_options ['fields'] ['field_aankoop_status'] ['table'] = 'field_data_field_aankoop_status';
	$handler->display->display_options ['fields'] ['field_aankoop_status'] ['field'] = 'field_aankoop_status';
	/* Veld: Inhoud: Datum van inzending */
	$handler->display->display_options ['fields'] ['created'] ['id'] = 'created';
	$handler->display->display_options ['fields'] ['created'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['created'] ['field'] = 'created';
	$handler->display->display_options ['fields'] ['created'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['created'] ['date_format'] = 'datum_kort_';
	$handler->display->display_options ['fields'] ['created'] ['second_date_format'] = 'long';
	/* Veld: Inhoudsrevisie: Wijzigingsdatum */
	$handler->display->display_options ['fields'] ['timestamp'] ['id'] = 'timestamp';
	$handler->display->display_options ['fields'] ['timestamp'] ['table'] = 'node_revision';
	$handler->display->display_options ['fields'] ['timestamp'] ['field'] = 'timestamp';
	$handler->display->display_options ['fields'] ['timestamp'] ['label'] = 'Datum';
	$handler->display->display_options ['fields'] ['timestamp'] ['alter'] ['alter_text'] = TRUE;
	$handler->display->display_options ['fields'] ['timestamp'] ['alter'] ['text'] = '[timestamp]<br><small>[created]</small>';
	$handler->display->display_options ['fields'] ['timestamp'] ['date_format'] = 'datum_kort_';
	$handler->display->display_options ['fields'] ['timestamp'] ['second_date_format'] = 'long';
	/* Veld: Inhoud: Vakgroep */
	$handler->display->display_options ['fields'] ['field_aankoop_vakgroep'] ['id'] = 'field_aankoop_vakgroep';
	$handler->display->display_options ['fields'] ['field_aankoop_vakgroep'] ['table'] = 'field_data_field_aankoop_vakgroep';
	$handler->display->display_options ['fields'] ['field_aankoop_vakgroep'] ['field'] = 'field_aankoop_vakgroep';
	$handler->display->display_options ['fields'] ['field_aankoop_vakgroep'] ['settings'] = array (
			'link' => 0 
	);
	/* Veld: Inhoud: Budget */
	$handler->display->display_options ['fields'] ['field_aankoop_budget_1'] ['id'] = 'field_aankoop_budget_1';
	$handler->display->display_options ['fields'] ['field_aankoop_budget_1'] ['table'] = 'field_data_field_aankoop_budget';
	$handler->display->display_options ['fields'] ['field_aankoop_budget_1'] ['field'] = 'field_aankoop_budget';
	$handler->display->display_options ['fields'] ['field_aankoop_budget_1'] ['settings'] = array (
			'thousand_separator' => '',
			'decimal_separator' => '.',
			'scale' => '2',
			'prefix_suffix' => 1 
	);
	/* Veld: Inhoud: Factuurbedrag */
	$handler->display->display_options ['fields'] ['field_aankoop_factuurbedrag_1'] ['id'] = 'field_aankoop_factuurbedrag_1';
	$handler->display->display_options ['fields'] ['field_aankoop_factuurbedrag_1'] ['table'] = 'field_data_field_aankoop_factuurbedrag';
	$handler->display->display_options ['fields'] ['field_aankoop_factuurbedrag_1'] ['field'] = 'field_aankoop_factuurbedrag';
	$handler->display->display_options ['fields'] ['field_aankoop_factuurbedrag_1'] ['label'] = 'Effectief';
	$handler->display->display_options ['fields'] ['field_aankoop_factuurbedrag_1'] ['alter'] ['alter_text'] = TRUE;
	$handler->display->display_options ['fields'] ['field_aankoop_factuurbedrag_1'] ['alter'] ['text'] = '[field_aankoop_factuurbedrag_1]<br><small>(€[expression])</small>';
	$handler->display->display_options ['fields'] ['field_aankoop_factuurbedrag_1'] ['settings'] = array (
			'thousand_separator' => '',
			'decimal_separator' => '.',
			'scale' => '2',
			'prefix_suffix' => 1 
	);
	/* Veld: Inhoud: Leveranciers */
	$handler->display->display_options ['fields'] ['field_aankoop_leveranciers'] ['id'] = 'field_aankoop_leveranciers';
	$handler->display->display_options ['fields'] ['field_aankoop_leveranciers'] ['table'] = 'field_data_field_aankoop_leveranciers';
	$handler->display->display_options ['fields'] ['field_aankoop_leveranciers'] ['field'] = 'field_aankoop_leveranciers';
	$handler->display->display_options ['fields'] ['field_aankoop_leveranciers'] ['settings'] = array (
			'link' => '1' 
	);
	$handler->display->display_options ['fields'] ['field_aankoop_leveranciers'] ['delta_offset'] = '0';
	/* Veld: Inhoud: Vergelijking */
	$handler->display->display_options ['fields'] ['field_aankoop_vergelijking'] ['id'] = 'field_aankoop_vergelijking';
	$handler->display->display_options ['fields'] ['field_aankoop_vergelijking'] ['table'] = 'field_data_field_aankoop_vergelijking';
	$handler->display->display_options ['fields'] ['field_aankoop_vergelijking'] ['field'] = 'field_aankoop_vergelijking';
	$handler->display->display_options ['fields'] ['field_aankoop_vergelijking'] ['label'] = '';
	$handler->display->display_options ['fields'] ['field_aankoop_vergelijking'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['field_aankoop_vergelijking'] ['element_label_colon'] = FALSE;
	/* Veld: Inhoud: Conclusie */
	$handler->display->display_options ['fields'] ['field_aankoop_conclusie'] ['id'] = 'field_aankoop_conclusie';
	$handler->display->display_options ['fields'] ['field_aankoop_conclusie'] ['table'] = 'field_data_field_aankoop_conclusie';
	$handler->display->display_options ['fields'] ['field_aankoop_conclusie'] ['field'] = 'field_aankoop_conclusie';
	/* Sorteercriterium: Inhoud: Datum van inzending */
	$handler->display->display_options ['sorts'] ['created'] ['id'] = 'created';
	$handler->display->display_options ['sorts'] ['created'] ['table'] = 'node';
	$handler->display->display_options ['sorts'] ['created'] ['field'] = 'created';
	$handler->display->display_options ['sorts'] ['created'] ['order'] = 'DESC';
	/* Filtercriterium: Inhoud: Gepubliceerd */
	$handler->display->display_options ['filters'] ['status'] ['id'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['status'] ['field'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['value'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['expose'] ['operator'] = FALSE;
	/* Filtercriterium: Inhoud: Type */
	$handler->display->display_options ['filters'] ['type'] ['id'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['type'] ['field'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['value'] = array (
			'aankoopdossier' => 'aankoopdossier' 
	);
	$handler->display->display_options ['filters'] ['type'] ['group'] = 1;
	/* Filtercriterium: Inhoud: Status (field_aankoop_status) */
	$handler->display->display_options ['filters'] ['field_aankoop_status_value'] ['id'] = 'field_aankoop_status_value';
	$handler->display->display_options ['filters'] ['field_aankoop_status_value'] ['table'] = 'field_data_field_aankoop_status';
	$handler->display->display_options ['filters'] ['field_aankoop_status_value'] ['field'] = 'field_aankoop_status_value';
	$handler->display->display_options ['filters'] ['field_aankoop_status_value'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['field_aankoop_status_value'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_aankoop_status_value'] ['expose'] ['operator_id'] = 'field_aankoop_status_value_op';
	$handler->display->display_options ['filters'] ['field_aankoop_status_value'] ['expose'] ['label'] = 'Status';
	$handler->display->display_options ['filters'] ['field_aankoop_status_value'] ['expose'] ['operator'] = 'field_aankoop_status_value_op';
	$handler->display->display_options ['filters'] ['field_aankoop_status_value'] ['expose'] ['identifier'] = 'field_aankoop_status_value';
	$handler->display->display_options ['filters'] ['field_aankoop_status_value'] ['expose'] ['remember'] = TRUE;
	$handler->display->display_options ['filters'] ['field_aankoop_status_value'] ['expose'] ['multiple'] = TRUE;
	$handler->display->display_options ['filters'] ['field_aankoop_status_value'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['filters'] ['field_aankoop_status_value'] ['reduce_duplicates'] = TRUE;
	/* Filtercriterium: Inhoud: Vakgroep (field_aankoop_vakgroep) (reference filter) */
	$handler->display->display_options ['filters'] ['field_aankoop_vakgroep_target_id_entityreference_filter'] ['id'] = 'field_aankoop_vakgroep_target_id_entityreference_filter';
	$handler->display->display_options ['filters'] ['field_aankoop_vakgroep_target_id_entityreference_filter'] ['table'] = 'field_data_field_aankoop_vakgroep';
	$handler->display->display_options ['filters'] ['field_aankoop_vakgroep_target_id_entityreference_filter'] ['field'] = 'field_aankoop_vakgroep_target_id_entityreference_filter';
	$handler->display->display_options ['filters'] ['field_aankoop_vakgroep_target_id_entityreference_filter'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_aankoop_vakgroep_target_id_entityreference_filter'] ['expose'] ['operator_id'] = 'field_aankoop_vakgroep_target_id_entityreference_filter_op';
	$handler->display->display_options ['filters'] ['field_aankoop_vakgroep_target_id_entityreference_filter'] ['expose'] ['label'] = 'Vakgroep';
	$handler->display->display_options ['filters'] ['field_aankoop_vakgroep_target_id_entityreference_filter'] ['expose'] ['operator'] = 'field_aankoop_vakgroep_target_id_entityreference_filter_op';
	$handler->display->display_options ['filters'] ['field_aankoop_vakgroep_target_id_entityreference_filter'] ['expose'] ['identifier'] = 'field_aankoop_vakgroep_target_id_entityreference_filter';
	$handler->display->display_options ['filters'] ['field_aankoop_vakgroep_target_id_entityreference_filter'] ['expose'] ['multiple'] = TRUE;
	$handler->display->display_options ['filters'] ['field_aankoop_vakgroep_target_id_entityreference_filter'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['filters'] ['field_aankoop_vakgroep_target_id_entityreference_filter'] ['reference_display'] = 'vakgroepen:vakgroepen';
	
	/* Display: Overzicht */
	$handler = $view->new_display ( 'page', 'Overzicht', 'aankoopdossiers_overzicht' );
	$handler->display->display_options ['display_description'] = 'Toon een interactieve lijst van alle dossiers.';
	$handler->display->display_options ['defaults'] ['cache'] = FALSE;
	$handler->display->display_options ['cache'] ['type'] = 'views_content_cache';
	$handler->display->display_options ['cache'] ['results_min_lifespan'] = '-1';
	$handler->display->display_options ['cache'] ['results_max_lifespan'] = '518400';
	$handler->display->display_options ['cache'] ['output_min_lifespan'] = '-1';
	$handler->display->display_options ['cache'] ['output_max_lifespan'] = '518400';
	$handler->display->display_options ['cache'] ['keys'] = array (
			'comment' => array (
					'changed' => 0 
			),
			'node' => array (
					'aankoopdossier' => 'aankoopdossier' 
			),
			'node_only' => array (
					'node_changed' => 'node_changed' 
			) 
	);
	$handler->display->display_options ['defaults'] ['exposed_form'] = FALSE;
	$handler->display->display_options ['exposed_form'] ['type'] = 'better_exposed_filters';
	$handler->display->display_options ['exposed_form'] ['options'] ['submit_button'] = 'Toepassen';
	$handler->display->display_options ['exposed_form'] ['options'] ['reset_button'] = TRUE;
	$handler->display->display_options ['exposed_form'] ['options'] ['reset_button_label'] = 'Opnieuw instellen';
	$handler->display->display_options ['exposed_form'] ['options'] ['exposed_sorts_label'] = 'Sorteren op';
	$handler->display->display_options ['exposed_form'] ['options'] ['sort_asc_label'] = 'Oplopend';
	$handler->display->display_options ['exposed_form'] ['options'] ['sort_desc_label'] = 'Aflopend';
	$handler->display->display_options ['exposed_form'] ['options'] ['autosubmit'] = FALSE;
	$handler->display->display_options ['exposed_form'] ['options'] ['bef'] = array (
			'general' => array (
					'allow_secondary' => 0,
					'secondary_label' => 'Uitgebreide opties' 
			),
			'field_aankoop_status_value' => array (
					'bef_format' => 'bef',
					'more_options' => array (
							'bef_select_all_none' => 0,
							'bef_collapsible' => 0,
							'is_secondary' => 0,
							'any_label' => '',
							'bef_filter_description' => '',
							'tokens' => array (
									'available' => array (
											0 => 'global_types' 
									) 
							),
							'rewrite' => array (
									'filter_rewrite_values' => '' 
							) 
					) 
			),
			'field_aankoop_vakgroep_target_id_entityreference_filter' => array (
					'bef_format' => 'bef',
					'more_options' => array (
							'bef_select_all_none' => 0,
							'bef_collapsible' => '1',
							'is_secondary' => 0,
							'any_label' => '',
							'bef_filter_description' => '',
							'tokens' => array (
									'available' => array (
											0 => 'global_types' 
									) 
							),
							'rewrite' => array (
									'filter_rewrite_values' => '' 
							) 
					) 
			),
			'field_aankoop_preventieregister_value' => array (
					'bef_format' => 'bef',
					'more_options' => array (
							'bef_select_all_none' => 0,
							'bef_collapsible' => 0,
							'is_secondary' => 0,
							'any_label' => '',
							'bef_filter_description' => '',
							'tokens' => array (
									'available' => array (
											0 => 'global_types' 
									) 
							),
							'rewrite' => array (
									'filter_rewrite_values' => '' 
							) 
					) 
			) 
	);
	$handler->display->display_options ['exposed_block'] = TRUE;
	$handler->display->display_options ['defaults'] ['fields'] = FALSE;
	/* Veld: Inhoud: Budget */
	$handler->display->display_options ['fields'] ['field_aankoop_budget'] ['id'] = 'field_aankoop_budget';
	$handler->display->display_options ['fields'] ['field_aankoop_budget'] ['table'] = 'field_data_field_aankoop_budget';
	$handler->display->display_options ['fields'] ['field_aankoop_budget'] ['field'] = 'field_aankoop_budget';
	$handler->display->display_options ['fields'] ['field_aankoop_budget'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['field_aankoop_budget'] ['settings'] = array (
			'thousand_separator' => '',
			'decimal_separator' => '.',
			'scale' => '2',
			'prefix_suffix' => 0 
	);
	/* Veld: Inhoud: Factuurbedrag */
	$handler->display->display_options ['fields'] ['field_aankoop_factuurbedrag'] ['id'] = 'field_aankoop_factuurbedrag';
	$handler->display->display_options ['fields'] ['field_aankoop_factuurbedrag'] ['table'] = 'field_data_field_aankoop_factuurbedrag';
	$handler->display->display_options ['fields'] ['field_aankoop_factuurbedrag'] ['field'] = 'field_aankoop_factuurbedrag';
	$handler->display->display_options ['fields'] ['field_aankoop_factuurbedrag'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['field_aankoop_factuurbedrag'] ['alter'] ['text'] = '[field_aankoop_factuurbedrag]<br>
(=[field_aankoop_budget]-[field_aankoop_factuurbedrag])';
	$handler->display->display_options ['fields'] ['field_aankoop_factuurbedrag'] ['settings'] = array (
			'thousand_separator' => '',
			'decimal_separator' => '.',
			'scale' => '2',
			'prefix_suffix' => 0 
	);
	/* Veld: Algemeen: Wiskundige expressie */
	$handler->display->display_options ['fields'] ['expression'] ['id'] = 'expression';
	$handler->display->display_options ['fields'] ['expression'] ['table'] = 'views';
	$handler->display->display_options ['fields'] ['expression'] ['field'] = 'expression';
	$handler->display->display_options ['fields'] ['expression'] ['label'] = 'Verschil';
	$handler->display->display_options ['fields'] ['expression'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['expression'] ['set_precision'] = TRUE;
	$handler->display->display_options ['fields'] ['expression'] ['precision'] = '2';
	$handler->display->display_options ['fields'] ['expression'] ['decimal'] = ',';
	$handler->display->display_options ['fields'] ['expression'] ['separator'] = '';
	$handler->display->display_options ['fields'] ['expression'] ['expression'] = '[field_aankoop_budget] - [field_aankoop_factuurbedrag]';
	/* Veld: Inhoud: Titel */
	$handler->display->display_options ['fields'] ['title'] ['id'] = 'title';
	$handler->display->display_options ['fields'] ['title'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['title'] ['field'] = 'title';
	$handler->display->display_options ['fields'] ['title'] ['label'] = 'Betreft';
	$handler->display->display_options ['fields'] ['title'] ['alter'] ['word_boundary'] = FALSE;
	$handler->display->display_options ['fields'] ['title'] ['alter'] ['ellipsis'] = FALSE;
	/* Veld: Inhoud: Status */
	$handler->display->display_options ['fields'] ['field_aankoop_status'] ['id'] = 'field_aankoop_status';
	$handler->display->display_options ['fields'] ['field_aankoop_status'] ['table'] = 'field_data_field_aankoop_status';
	$handler->display->display_options ['fields'] ['field_aankoop_status'] ['field'] = 'field_aankoop_status';
	/* Veld: Inhoud: Datum van inzending */
	$handler->display->display_options ['fields'] ['created'] ['id'] = 'created';
	$handler->display->display_options ['fields'] ['created'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['created'] ['field'] = 'created';
	$handler->display->display_options ['fields'] ['created'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['created'] ['date_format'] = 'datum_kort_';
	$handler->display->display_options ['fields'] ['created'] ['second_date_format'] = 'long';
	/* Veld: Inhoudsrevisie: Wijzigingsdatum */
	$handler->display->display_options ['fields'] ['timestamp'] ['id'] = 'timestamp';
	$handler->display->display_options ['fields'] ['timestamp'] ['table'] = 'node_revision';
	$handler->display->display_options ['fields'] ['timestamp'] ['field'] = 'timestamp';
	$handler->display->display_options ['fields'] ['timestamp'] ['label'] = 'Datum';
	$handler->display->display_options ['fields'] ['timestamp'] ['alter'] ['alter_text'] = TRUE;
	$handler->display->display_options ['fields'] ['timestamp'] ['alter'] ['text'] = '[timestamp]<br><small>[created]</small>';
	$handler->display->display_options ['fields'] ['timestamp'] ['date_format'] = 'datum_kort_';
	$handler->display->display_options ['fields'] ['timestamp'] ['second_date_format'] = 'long';
	/* Veld: Inhoud: Vakgroep */
	$handler->display->display_options ['fields'] ['field_aankoop_vakgroep'] ['id'] = 'field_aankoop_vakgroep';
	$handler->display->display_options ['fields'] ['field_aankoop_vakgroep'] ['table'] = 'field_data_field_aankoop_vakgroep';
	$handler->display->display_options ['fields'] ['field_aankoop_vakgroep'] ['field'] = 'field_aankoop_vakgroep';
	$handler->display->display_options ['fields'] ['field_aankoop_vakgroep'] ['settings'] = array (
			'link' => 0 
	);
	/* Veld: Inhoud: Budget */
	$handler->display->display_options ['fields'] ['field_aankoop_budget_1'] ['id'] = 'field_aankoop_budget_1';
	$handler->display->display_options ['fields'] ['field_aankoop_budget_1'] ['table'] = 'field_data_field_aankoop_budget';
	$handler->display->display_options ['fields'] ['field_aankoop_budget_1'] ['field'] = 'field_aankoop_budget';
	$handler->display->display_options ['fields'] ['field_aankoop_budget_1'] ['settings'] = array (
			'thousand_separator' => '',
			'decimal_separator' => '.',
			'scale' => '2',
			'prefix_suffix' => '1' 
	);
	/* Veld: Inhoud: Factuurbedrag */
	$handler->display->display_options ['fields'] ['field_aankoop_factuurbedrag_1'] ['id'] = 'field_aankoop_factuurbedrag_1';
	$handler->display->display_options ['fields'] ['field_aankoop_factuurbedrag_1'] ['table'] = 'field_data_field_aankoop_factuurbedrag';
	$handler->display->display_options ['fields'] ['field_aankoop_factuurbedrag_1'] ['field'] = 'field_aankoop_factuurbedrag';
	$handler->display->display_options ['fields'] ['field_aankoop_factuurbedrag_1'] ['label'] = 'Effectief';
	$handler->display->display_options ['fields'] ['field_aankoop_factuurbedrag_1'] ['alter'] ['alter_text'] = TRUE;
	$handler->display->display_options ['fields'] ['field_aankoop_factuurbedrag_1'] ['alter'] ['text'] = '[field_aankoop_factuurbedrag_1]<br><small>(€[expression])</small>';
	$handler->display->display_options ['fields'] ['field_aankoop_factuurbedrag_1'] ['settings'] = array (
			'thousand_separator' => '',
			'decimal_separator' => '.',
			'scale' => '2',
			'prefix_suffix' => '1' 
	);
	/* Veld: Inhoud: Leveranciers */
	$handler->display->display_options ['fields'] ['field_aankoop_leveranciers'] ['id'] = 'field_aankoop_leveranciers';
	$handler->display->display_options ['fields'] ['field_aankoop_leveranciers'] ['table'] = 'field_data_field_aankoop_leveranciers';
	$handler->display->display_options ['fields'] ['field_aankoop_leveranciers'] ['field'] = 'field_aankoop_leveranciers';
	$handler->display->display_options ['fields'] ['field_aankoop_leveranciers'] ['settings'] = array (
			'link' => '1' 
	);
	$handler->display->display_options ['fields'] ['field_aankoop_leveranciers'] ['delta_offset'] = '0';
	/* Veld: Inhoud: Vergelijking */
	$handler->display->display_options ['fields'] ['field_aankoop_vergelijking'] ['id'] = 'field_aankoop_vergelijking';
	$handler->display->display_options ['fields'] ['field_aankoop_vergelijking'] ['table'] = 'field_data_field_aankoop_vergelijking';
	$handler->display->display_options ['fields'] ['field_aankoop_vergelijking'] ['field'] = 'field_aankoop_vergelijking';
	$handler->display->display_options ['fields'] ['field_aankoop_vergelijking'] ['label'] = '';
	$handler->display->display_options ['fields'] ['field_aankoop_vergelijking'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['field_aankoop_vergelijking'] ['element_label_colon'] = FALSE;
	/* Veld: Inhoud: Conclusie */
	$handler->display->display_options ['fields'] ['field_aankoop_conclusie'] ['id'] = 'field_aankoop_conclusie';
	$handler->display->display_options ['fields'] ['field_aankoop_conclusie'] ['table'] = 'field_data_field_aankoop_conclusie';
	$handler->display->display_options ['fields'] ['field_aankoop_conclusie'] ['field'] = 'field_aankoop_conclusie';
	$handler->display->display_options ['fields'] ['field_aankoop_conclusie'] ['alter'] ['max_length'] = '100';
	$handler->display->display_options ['fields'] ['field_aankoop_conclusie'] ['alter'] ['more_link'] = TRUE;
	$handler->display->display_options ['fields'] ['field_aankoop_conclusie'] ['alter'] ['more_link_text'] = 'meer';
	$handler->display->display_options ['fields'] ['field_aankoop_conclusie'] ['alter'] ['trim'] = TRUE;
	$handler->display->display_options ['fields'] ['field_aankoop_conclusie'] ['settings'] = array (
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	$handler->display->display_options ['defaults'] ['filter_groups'] = FALSE;
	$handler->display->display_options ['defaults'] ['filters'] = FALSE;
	/* Filtercriterium: Inhoud: Gepubliceerd */
	$handler->display->display_options ['filters'] ['status'] ['id'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['status'] ['field'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['value'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['expose'] ['operator'] = FALSE;
	/* Filtercriterium: Inhoud: Type */
	$handler->display->display_options ['filters'] ['type'] ['id'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['type'] ['field'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['value'] = array (
			'aankoopdossier' => 'aankoopdossier' 
	);
	$handler->display->display_options ['filters'] ['type'] ['group'] = 1;
	/* Filtercriterium: Inhoud: Status (field_aankoop_status) */
	$handler->display->display_options ['filters'] ['field_aankoop_status_value'] ['id'] = 'field_aankoop_status_value';
	$handler->display->display_options ['filters'] ['field_aankoop_status_value'] ['table'] = 'field_data_field_aankoop_status';
	$handler->display->display_options ['filters'] ['field_aankoop_status_value'] ['field'] = 'field_aankoop_status_value';
	$handler->display->display_options ['filters'] ['field_aankoop_status_value'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['field_aankoop_status_value'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_aankoop_status_value'] ['expose'] ['operator_id'] = 'field_aankoop_status_value_op';
	$handler->display->display_options ['filters'] ['field_aankoop_status_value'] ['expose'] ['label'] = 'Status';
	$handler->display->display_options ['filters'] ['field_aankoop_status_value'] ['expose'] ['operator'] = 'field_aankoop_status_value_op';
	$handler->display->display_options ['filters'] ['field_aankoop_status_value'] ['expose'] ['identifier'] = 'field_aankoop_status_value';
	$handler->display->display_options ['filters'] ['field_aankoop_status_value'] ['expose'] ['remember'] = TRUE;
	$handler->display->display_options ['filters'] ['field_aankoop_status_value'] ['expose'] ['multiple'] = TRUE;
	$handler->display->display_options ['filters'] ['field_aankoop_status_value'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['filters'] ['field_aankoop_status_value'] ['reduce_duplicates'] = TRUE;
	/* Filtercriterium: Inhoud: Opnemen in het preventieregister (field_aankoop_preventieregister) */
	$handler->display->display_options ['filters'] ['field_aankoop_preventieregister_value'] ['id'] = 'field_aankoop_preventieregister_value';
	$handler->display->display_options ['filters'] ['field_aankoop_preventieregister_value'] ['table'] = 'field_data_field_aankoop_preventieregister';
	$handler->display->display_options ['filters'] ['field_aankoop_preventieregister_value'] ['field'] = 'field_aankoop_preventieregister_value';
	$handler->display->display_options ['filters'] ['field_aankoop_preventieregister_value'] ['value'] = array (
			'all' => 'all',
			1 => '1' 
	);
	$handler->display->display_options ['filters'] ['field_aankoop_preventieregister_value'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['field_aankoop_preventieregister_value'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_aankoop_preventieregister_value'] ['expose'] ['operator_id'] = 'field_aankoop_preventieregister_value_op';
	$handler->display->display_options ['filters'] ['field_aankoop_preventieregister_value'] ['expose'] ['label'] = 'Opnemen in het preventieregister';
	$handler->display->display_options ['filters'] ['field_aankoop_preventieregister_value'] ['expose'] ['operator'] = 'field_aankoop_preventieregister_value_op';
	$handler->display->display_options ['filters'] ['field_aankoop_preventieregister_value'] ['expose'] ['identifier'] = 'field_aankoop_preventieregister_value';
	$handler->display->display_options ['filters'] ['field_aankoop_preventieregister_value'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['filters'] ['field_aankoop_preventieregister_value'] ['expose'] ['reduce'] = TRUE;
	$handler->display->display_options ['filters'] ['field_aankoop_preventieregister_value'] ['group_info'] ['label'] = 'Opnemen in het preventieregister (field_aankoop_preventieregister)';
	$handler->display->display_options ['filters'] ['field_aankoop_preventieregister_value'] ['group_info'] ['identifier'] = 'field_aankoop_preventieregister_value';
	$handler->display->display_options ['filters'] ['field_aankoop_preventieregister_value'] ['group_info'] ['remember'] = FALSE;
	$handler->display->display_options ['filters'] ['field_aankoop_preventieregister_value'] ['group_info'] ['group_items'] = array (
			1 => array (),
			2 => array (),
			3 => array () 
	);
	$handler->display->display_options ['filters'] ['field_aankoop_preventieregister_value'] ['reduce_duplicates'] = TRUE;
	/* Filtercriterium: Inhoud: Vakgroep (field_aankoop_vakgroep) (reference filter) */
	$handler->display->display_options ['filters'] ['field_aankoop_vakgroep_target_id_entityreference_filter'] ['id'] = 'field_aankoop_vakgroep_target_id_entityreference_filter';
	$handler->display->display_options ['filters'] ['field_aankoop_vakgroep_target_id_entityreference_filter'] ['table'] = 'field_data_field_aankoop_vakgroep';
	$handler->display->display_options ['filters'] ['field_aankoop_vakgroep_target_id_entityreference_filter'] ['field'] = 'field_aankoop_vakgroep_target_id_entityreference_filter';
	$handler->display->display_options ['filters'] ['field_aankoop_vakgroep_target_id_entityreference_filter'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['field_aankoop_vakgroep_target_id_entityreference_filter'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_aankoop_vakgroep_target_id_entityreference_filter'] ['expose'] ['operator_id'] = 'field_aankoop_vakgroep_target_id_entityreference_filter_op';
	$handler->display->display_options ['filters'] ['field_aankoop_vakgroep_target_id_entityreference_filter'] ['expose'] ['label'] = 'Vakgroep';
	$handler->display->display_options ['filters'] ['field_aankoop_vakgroep_target_id_entityreference_filter'] ['expose'] ['operator'] = 'field_aankoop_vakgroep_target_id_entityreference_filter_op';
	$handler->display->display_options ['filters'] ['field_aankoop_vakgroep_target_id_entityreference_filter'] ['expose'] ['identifier'] = 'field_aankoop_vakgroep_target_id_entityreference_filter';
	$handler->display->display_options ['filters'] ['field_aankoop_vakgroep_target_id_entityreference_filter'] ['expose'] ['multiple'] = TRUE;
	$handler->display->display_options ['filters'] ['field_aankoop_vakgroep_target_id_entityreference_filter'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['filters'] ['field_aankoop_vakgroep_target_id_entityreference_filter'] ['reference_display'] = 'vakgroepen:vakgroepen';
	$handler->display->display_options ['path'] = 'aankoopdossiers';
	$handler->display->display_options ['menu'] ['type'] = 'normal';
	$handler->display->display_options ['menu'] ['title'] = 'Aankoopdossiers';
	
	if (menu_load('menu-modules')){
		$menu = 'menu-modules';
	} else {
		$menu = 'navigation';
	}
	$handler->display->display_options ['menu'] ['name'] = $menu;
	$translatables ['aankoopdossiers'] = array (
			t ( 'Master' ),
			t ( 'Aankoopdossiers' ),
			t ( 'meer' ),
			t ( 'Toepassen' ),
			t ( 'Opnieuw instellen' ),
			t ( 'Sorteren op' ),
			t ( 'Oplopend' ),
			t ( 'Aflopend' ),
			t ( 'Uitgebreide opties' ),
			t ( 'Items per pagina' ),
			t ( '- Alle -' ),
			t ( 'Startpunt' ),
			t ( '« eerste' ),
			t ( '‹ vorige' ),
			t ( 'volgende ›' ),
			t ( 'laatste »' ),
			t ( '<a href="/node/add/aankoopdossier">Een nieuw aankoopdossier toevoegen</a>' ),
			t ( 'Getoond @start - @end van @total' ),
			t ( 'Budget' ),
			t ( 'Factuurbedrag' ),
			t ( '[field_aankoop_factuurbedrag]<br>
(=[field_aankoop_budget]-[field_aankoop_factuurbedrag])' ),
			t ( 'Verschil' ),
			t ( ',' ),
			t ( 'Betreft' ),
			t ( 'Status' ),
			t ( 'Datum van inzending' ),
			t ( 'Datum' ),
			t ( '[timestamp]<br><small>[created]</small>' ),
			t ( 'Vakgroep' ),
			t ( 'Effectief' ),
			t ( '[field_aankoop_factuurbedrag_1]<br><small>(€[expression])</small>' ),
			t ( 'Leveranciers' ),
			t ( 'Conclusie' ),
			t ( 'Overzicht' ),
			t ( 'Toon een interactieve lijst van alle dossiers.' ),
			t ( 'Opnemen in het preventieregister' ),
			t ( 'Opnemen in het preventieregister (field_aankoop_preventieregister)' ) 
	);
	
	$views [$view->name] = $view;
	return $views;
}