<?php
/*
 * Copyright (C) 2017 bartgysens
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* Drupal Hooks */

/**
 * Implements hook_ctools_plugin_api().
 */
function argus_hrm_overuren_ctools_plugin_api($module = NULL, $api = NULL) {
	if ($module == "field_group" && $api == "field_group") {
		return array (
				"version" => "1" 
		);
	}
}

/**
 * Implements hook_node_info()
 */
function argus_hrm_overuren_node_info() {
	// Replace demo with your content type definitions
	$items = array (
			'hrm_overuren' => array (
					'name' => t ( 'HRM - Overuren' ),
					'base' => 'node_content',
					'description' => t ( 'Beheer je <em>overuren</em> van personeelsleden in twee eenvoudige stappen: registratie en terugname.' ),
					'has_title' => '1',
					'title_label' => t ( 'Title' ),
					'help' => '' 
			) 
	);
	drupal_alter ( 'node_info', $items );
	return $items;
}

/**
 * Implement hook_form()
 */
function argus_hrm_overuren_form($node, $form_state) {
	return node_content_form ( $node, $form_state );
}

/**
 * Implementation of hook_views_api().
 */
function argus_hrm_overuren_views_api() {
	return array (
			'api' => 3.0,
			'path' => drupal_get_path ( 'module', 'argus_hrm_overuren' ) 
	) // replace demo with your content type
;
}

/**
 * Implementation of hook_views_default_views().
 *
 * Views export creates code that you have to paste in this function.
 *
 * Administration > Structure > Views : click the button behind the view you need and export
 * /admin/structure/views
 */
function argus_hrm_overuren_views_default_views() {
	$view = new view ();
	$view->name = 'hrm_overuren';
	$view->description = '';
	$view->tag = 'default';
	$view->base_table = 'node';
	$view->human_name = 'HRM - Overuren';
	$view->core = 7;
	$view->api_version = '3.0';
	$view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */
	
	/* Display: Master */
	$handler = $view->new_display ( 'default', 'Master', 'default' );
	$handler->display->display_options ['title'] = 'Overuren';
	$handler->display->display_options ['use_more_always'] = FALSE;
	$handler->display->display_options ['use_more_text'] = 'meer';
	$handler->display->display_options ['access'] ['type'] = 'role';
	$handler->display->display_options ['access'] ['role'] = array ();
	$handler->display->display_options ['cache'] ['type'] = 'views_content_cache';
	$handler->display->display_options ['cache'] ['results_min_lifespan'] = '-1';
	$handler->display->display_options ['cache'] ['results_max_lifespan'] = '518400';
	$handler->display->display_options ['cache'] ['output_min_lifespan'] = '-1';
	$handler->display->display_options ['cache'] ['output_max_lifespan'] = '518400';
	$handler->display->display_options ['cache'] ['keys'] = array (
			'comment' => array (
					'changed' => 0 
			),
			'node' => array (
					'hrm_overuren' => 'hrm_overuren' 
			),
			'node_only' => array (
					'node_changed' => 'node_changed' 
			) 
	);
	$handler->display->display_options ['query'] ['type'] = 'views_query';
	$handler->display->display_options ['exposed_form'] ['type'] = 'better_exposed_filters';
	$handler->display->display_options ['exposed_form'] ['options'] ['submit_button'] = 'Toepassen';
	$handler->display->display_options ['exposed_form'] ['options'] ['reset_button'] = TRUE;
	$handler->display->display_options ['exposed_form'] ['options'] ['reset_button_label'] = 'Opnieuw instellen';
	$handler->display->display_options ['exposed_form'] ['options'] ['exposed_sorts_label'] = 'Sorteren op';
	$handler->display->display_options ['exposed_form'] ['options'] ['sort_asc_label'] = 'Oplopend';
	$handler->display->display_options ['exposed_form'] ['options'] ['sort_desc_label'] = 'Aflopend';
	$handler->display->display_options ['exposed_form'] ['options'] ['autosubmit'] = TRUE;
	$handler->display->display_options ['exposed_form'] ['options'] ['bef'] = array (
			'general' => array (
					'input_required' => 0,
					'text_input_required' => array (
							'text_input_required' => array (
									'value' => 'Selecteer een van de filters en klik op \'Toepassen\' om het resultaat te zien',
									'format' => 'filtered_html' 
							) 
					),
					'allow_secondary' => 0,
					'secondary_label' => 'Uitgebreide opties',
					'secondary_collapse_override' => '0' 
			),
			'realname' => array (
					'bef_format' => 'default',
					'more_options' => array (
							'autosubmit' => 0,
							'is_secondary' => 0,
							'any_label' => '',
							'bef_filter_description' => '',
							'tokens' => array (
									'available' => array (
											0 => 'global_types' 
									) 
							),
							'rewrite' => array (
									'filter_rewrite_values' => '' 
							) 
					) 
			),
			'field_hrm_overuren_status_value' => array (
					'bef_format' => 'bef',
					'more_options' => array (
							'bef_select_all_none' => 0,
							'bef_collapsible' => 0,
							'autosubmit' => 0,
							'is_secondary' => 0,
							'any_label' => '',
							'bef_filter_description' => '',
							'tokens' => array (
									'available' => array (
											0 => 'global_types' 
									) 
							),
							'rewrite' => array (
									'filter_rewrite_values' => '' 
							) 
					) 
			),
			'field_datum_value' => array (
					'bef_format' => 'bef_datepicker',
					'more_options' => array (
							'autosubmit' => 0,
							'is_secondary' => 0,
							'any_label' => '',
							'bef_filter_description' => '',
							'tokens' => array (
									'available' => array (
											0 => 'global_types' 
									) 
							),
							'rewrite' => array (
									'filter_rewrite_values' => '' 
							),
							'datepicker_options' => '' 
					) 
			) 
	);
	$handler->display->display_options ['pager'] ['type'] = 'full';
	$handler->display->display_options ['pager'] ['options'] ['items_per_page'] = '50';
	$handler->display->display_options ['pager'] ['options'] ['expose'] ['items_per_page_label'] = 'Items per pagina';
	$handler->display->display_options ['pager'] ['options'] ['expose'] ['items_per_page_options_all_label'] = '- Alle -';
	$handler->display->display_options ['pager'] ['options'] ['expose'] ['offset_label'] = 'Startpunt';
	$handler->display->display_options ['pager'] ['options'] ['tags'] ['first'] = '« eerste';
	$handler->display->display_options ['pager'] ['options'] ['tags'] ['previous'] = '‹ vorige';
	$handler->display->display_options ['pager'] ['options'] ['tags'] ['next'] = 'volgende ›';
	$handler->display->display_options ['pager'] ['options'] ['tags'] ['last'] = 'laatste »';
	$handler->display->display_options ['style_plugin'] = 'views_aggregator';
	$handler->display->display_options ['style_options'] ['columns'] = array (
			'nid' => 'nid',
			'counter' => 'counter',
			'realname' => 'realname',
			'field_datum' => 'field_datum',
			'field_hrm_overuren_uitv_aantal' => 'field_hrm_overuren_uitv_aantal',
			'field_hrm_overuren_status' => 'field_hrm_overuren_status',
			'field_hrm_overuren_terug_aantal' => 'field_hrm_overuren_terug_aantal',
			'expression' => 'expression',
			'edit_node' => 'edit_node' 
	);
	$handler->display->display_options ['style_options'] ['default'] = '-1';
	$handler->display->display_options ['style_options'] ['info'] = array (
			'nid' => array (
					'sortable' => 0,
					'default_sort_order' => 'asc',
					'align' => '',
					'separator' => '',
					'empty_column' => 0,
					'has_aggr' => 0,
					'aggr' => array (
							'views_aggregator_first' => 'views_aggregator_first' 
					),
					'aggr_par' => '',
					'has_aggr_column' => 0,
					'aggr_column' => 'views_aggregator_sum',
					'aggr_par_column' => '' 
			),
			'counter' => array (
					'sortable' => 0,
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0,
					'has_aggr' => 0,
					'aggr' => array (
							'views_aggregator_first' => 'views_aggregator_first' 
					),
					'aggr_par' => '',
					'has_aggr_column' => 0,
					'aggr_column' => 'views_aggregator_sum',
					'aggr_par_column' => '' 
			),
			'realname' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0,
					'has_aggr' => 0,
					'aggr' => array (
							'views_aggregator_first' => 'views_aggregator_first' 
					),
					'aggr_par' => '',
					'has_aggr_column' => 0,
					'aggr_column' => 'views_aggregator_sum',
					'aggr_par_column' => '' 
			),
			'field_datum' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0,
					'has_aggr' => 0,
					'aggr' => array (
							'views_aggregator_first' => 'views_aggregator_first' 
					),
					'aggr_par' => '',
					'has_aggr_column' => 0,
					'aggr_column' => 'views_aggregator_sum',
					'aggr_par_column' => '' 
			),
			'field_hrm_overuren_uitv_aantal' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0,
					'has_aggr' => 0,
					'aggr' => array (
							'views_aggregator_first' => 'views_aggregator_first' 
					),
					'aggr_par' => '',
					'has_aggr_column' => '1',
					'aggr_column' => 'views_aggregator_sum',
					'aggr_par_column' => '' 
			),
			'field_hrm_overuren_status' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0,
					'has_aggr' => 0,
					'aggr' => array (
							'views_aggregator_first' => 'views_aggregator_first' 
					),
					'aggr_par' => '',
					'has_aggr_column' => 0,
					'aggr_column' => 'views_aggregator_sum',
					'aggr_par_column' => '' 
			),
			'field_hrm_overuren_terug_aantal' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0,
					'has_aggr' => 0,
					'aggr' => array (
							'views_aggregator_first' => 'views_aggregator_first' 
					),
					'aggr_par' => '',
					'has_aggr_column' => '1',
					'aggr_column' => 'views_aggregator_sum',
					'aggr_par_column' => '' 
			),
			'expression' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0,
					'has_aggr' => 0,
					'aggr' => array (
							'views_aggregator_first' => 'views_aggregator_first' 
					),
					'aggr_par' => '',
					'has_aggr_column' => '1',
					'aggr_column' => 'views_aggregator_sum',
					'aggr_par_column' => '' 
			),
			'edit_node' => array (
					'sortable' => 0,
					'default_sort_order' => 'asc',
					'align' => 'views-align-right',
					'separator' => '',
					'empty_column' => 0,
					'has_aggr' => 0,
					'aggr' => array (
							'views_aggregator_first' => 'views_aggregator_first' 
					),
					'aggr_par' => '',
					'has_aggr_column' => 0,
					'aggr_column' => 'views_aggregator_sum',
					'aggr_par_column' => '' 
			) 
	);
	$handler->display->display_options ['style_options'] ['column_aggregation'] ['totals_per_page'] = '1';
	$handler->display->display_options ['style_options'] ['column_aggregation'] ['totals_row_position'] = array (
			1 => 0,
			2 => '2' 
	);
	$handler->display->display_options ['style_options'] ['column_aggregation'] ['precision'] = '2';
	/* Kop: Algemeen: Tekstveld */
	$handler->display->display_options ['header'] ['area'] ['id'] = 'area';
	$handler->display->display_options ['header'] ['area'] ['table'] = 'views';
	$handler->display->display_options ['header'] ['area'] ['field'] = 'area';
	$handler->display->display_options ['header'] ['area'] ['empty'] = TRUE;
	$handler->display->display_options ['header'] ['area'] ['content'] = '<a href="/node/add/hrm-overuren">Een aanvraag "overuren" toevoegen</a>';
	$handler->display->display_options ['header'] ['area'] ['format'] = 'filtered_html';
	/* Voet: Algemeen: Samenvatting van het resultaat */
	$handler->display->display_options ['footer'] ['result'] ['id'] = 'result';
	$handler->display->display_options ['footer'] ['result'] ['table'] = 'views';
	$handler->display->display_options ['footer'] ['result'] ['field'] = 'result';
	$handler->display->display_options ['footer'] ['result'] ['content'] = 'Getoond @start - @end van @total';
	/* Voet: Algemeen: Tekstveld */
	$handler->display->display_options ['footer'] ['area'] ['id'] = 'area';
	$handler->display->display_options ['footer'] ['area'] ['table'] = 'views';
	$handler->display->display_options ['footer'] ['area'] ['field'] = 'area';
	$handler->display->display_options ['footer'] ['area'] ['content'] = '<a href="/node/add/hrm-overuren">Een aanvraag "overuren" toevoegen</a>';
	$handler->display->display_options ['footer'] ['area'] ['format'] = 'filtered_html';
	/* Relatie: auteur */
	$handler->display->display_options ['relationships'] ['uid'] ['id'] = 'uid';
	$handler->display->display_options ['relationships'] ['uid'] ['table'] = 'node';
	$handler->display->display_options ['relationships'] ['uid'] ['field'] = 'uid';
	$handler->display->display_options ['relationships'] ['uid'] ['ui_name'] = 'auteur';
	/* Veld: Inhoud: Nid */
	$handler->display->display_options ['fields'] ['nid'] ['id'] = 'nid';
	$handler->display->display_options ['fields'] ['nid'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['nid'] ['field'] = 'nid';
	$handler->display->display_options ['fields'] ['nid'] ['label'] = '';
	$handler->display->display_options ['fields'] ['nid'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['nid'] ['element_label_colon'] = FALSE;
	/* Veld: Algemeen: Resultatenteller weergeven */
	$handler->display->display_options ['fields'] ['counter'] ['id'] = 'counter';
	$handler->display->display_options ['fields'] ['counter'] ['table'] = 'views';
	$handler->display->display_options ['fields'] ['counter'] ['field'] = 'counter';
	$handler->display->display_options ['fields'] ['counter'] ['label'] = 'Nr.';
	$handler->display->display_options ['fields'] ['counter'] ['counter_start'] = '1';
	$handler->display->display_options ['fields'] ['counter'] ['reverse'] = 0;
	/* Veld: Echte naam: Werkelijke naam */
	$handler->display->display_options ['fields'] ['realname'] ['id'] = 'realname';
	$handler->display->display_options ['fields'] ['realname'] ['table'] = 'realname';
	$handler->display->display_options ['fields'] ['realname'] ['field'] = 'realname';
	$handler->display->display_options ['fields'] ['realname'] ['relationship'] = 'uid';
	$handler->display->display_options ['fields'] ['realname'] ['label'] = 'Aanvrager';
	/* Veld: Inhoud: Periode van toepassing */
	$handler->display->display_options ['fields'] ['field_datum'] ['id'] = 'field_datum';
	$handler->display->display_options ['fields'] ['field_datum'] ['table'] = 'field_data_field_datum';
	$handler->display->display_options ['fields'] ['field_datum'] ['field'] = 'field_datum';
	$handler->display->display_options ['fields'] ['field_datum'] ['label'] = 'Datum';
	$handler->display->display_options ['fields'] ['field_datum'] ['settings'] = array (
			'format_type' => 'long',
			'custom_date_format' => '',
			'fromto' => 'both',
			'multiple_number' => '',
			'multiple_from' => '',
			'multiple_to' => '',
			'show_remaining_days' => 0,
			'show_repeat_rule' => 'show',
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Inhoud: Aantal */
	$handler->display->display_options ['fields'] ['field_hrm_overuren_uitv_aantal'] ['id'] = 'field_hrm_overuren_uitv_aantal';
	$handler->display->display_options ['fields'] ['field_hrm_overuren_uitv_aantal'] ['table'] = 'field_data_field_hrm_overuren_uitv_aantal';
	$handler->display->display_options ['fields'] ['field_hrm_overuren_uitv_aantal'] ['field'] = 'field_hrm_overuren_uitv_aantal';
	$handler->display->display_options ['fields'] ['field_hrm_overuren_uitv_aantal'] ['label'] = 'Aangevraagd';
	$handler->display->display_options ['fields'] ['field_hrm_overuren_uitv_aantal'] ['settings'] = array (
			'thousand_separator' => '',
			'decimal_separator' => '.',
			'scale' => '2',
			'prefix_suffix' => '1',
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Inhoud: Status */
	$handler->display->display_options ['fields'] ['field_hrm_overuren_status'] ['id'] = 'field_hrm_overuren_status';
	$handler->display->display_options ['fields'] ['field_hrm_overuren_status'] ['table'] = 'field_data_field_hrm_overuren_status';
	$handler->display->display_options ['fields'] ['field_hrm_overuren_status'] ['field'] = 'field_hrm_overuren_status';
	$handler->display->display_options ['fields'] ['field_hrm_overuren_status'] ['settings'] = array (
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Inhoud: Aantal */
	$handler->display->display_options ['fields'] ['field_hrm_overuren_terug_aantal'] ['id'] = 'field_hrm_overuren_terug_aantal';
	$handler->display->display_options ['fields'] ['field_hrm_overuren_terug_aantal'] ['table'] = 'field_data_field_hrm_overuren_terug_aantal';
	$handler->display->display_options ['fields'] ['field_hrm_overuren_terug_aantal'] ['field'] = 'field_hrm_overuren_terug_aantal';
	$handler->display->display_options ['fields'] ['field_hrm_overuren_terug_aantal'] ['label'] = 'Terugname';
	$handler->display->display_options ['fields'] ['field_hrm_overuren_terug_aantal'] ['settings'] = array (
			'thousand_separator' => '',
			'decimal_separator' => '.',
			'scale' => '2',
			'prefix_suffix' => '1',
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Algemeen: Wiskundige expressie */
	$handler->display->display_options ['fields'] ['expression'] ['id'] = 'expression';
	$handler->display->display_options ['fields'] ['expression'] ['table'] = 'views';
	$handler->display->display_options ['fields'] ['expression'] ['field'] = 'expression';
	$handler->display->display_options ['fields'] ['expression'] ['label'] = 'Rest';
	$handler->display->display_options ['fields'] ['expression'] ['set_precision'] = TRUE;
	$handler->display->display_options ['fields'] ['expression'] ['precision'] = '2';
	$handler->display->display_options ['fields'] ['expression'] ['suffix'] = ' uren';
	$handler->display->display_options ['fields'] ['expression'] ['expression'] = '[field_hrm_overuren_uitv_aantal]-[field_hrm_overuren_terug_aantal]';
	/* Veld: Inhoud: Bewerkingslink */
	$handler->display->display_options ['fields'] ['edit_node'] ['id'] = 'edit_node';
	$handler->display->display_options ['fields'] ['edit_node'] ['table'] = 'views_entity_node';
	$handler->display->display_options ['fields'] ['edit_node'] ['field'] = 'edit_node';
	$handler->display->display_options ['fields'] ['edit_node'] ['label'] = '';
	$handler->display->display_options ['fields'] ['edit_node'] ['element_label_colon'] = FALSE;
	/* Sorteercriterium: Inhoud: Datum van inzending */
	$handler->display->display_options ['sorts'] ['created'] ['id'] = 'created';
	$handler->display->display_options ['sorts'] ['created'] ['table'] = 'node';
	$handler->display->display_options ['sorts'] ['created'] ['field'] = 'created';
	$handler->display->display_options ['sorts'] ['created'] ['order'] = 'DESC';
	/* Filtercriterium: Inhoud: Gepubliceerd */
	$handler->display->display_options ['filters'] ['status'] ['id'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['status'] ['field'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['value'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['expose'] ['operator'] = FALSE;
	/* Filtercriterium: Inhoud: Type */
	$handler->display->display_options ['filters'] ['type'] ['id'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['type'] ['field'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['value'] = array (
			'hrm_overuren' => 'hrm_overuren' 
	);
	/* Filtercriterium: Echte naam: Naam */
	$handler->display->display_options ['filters'] ['realname'] ['id'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['table'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['field'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['relationship'] = 'field_personeelslid_target_id';
	$handler->display->display_options ['filters'] ['realname'] ['operator'] = 'contains';
	$handler->display->display_options ['filters'] ['realname'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['operator_id'] = 'realname_op';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['label'] = 'Personeelslid';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['operator'] = 'realname_op';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['identifier'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_items'] = '10';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_min_chars'] = '0';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_raw_suggestion'] = '1';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_raw_dropdown'] = '1';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_dependent'] = 0;
	/* Filtercriterium: Inhoud: Status (field_hrm_overuren_status) */
	$handler->display->display_options ['filters'] ['field_hrm_overuren_status_value'] ['id'] = 'field_hrm_overuren_status_value';
	$handler->display->display_options ['filters'] ['field_hrm_overuren_status_value'] ['table'] = 'field_data_field_hrm_overuren_status';
	$handler->display->display_options ['filters'] ['field_hrm_overuren_status_value'] ['field'] = 'field_hrm_overuren_status_value';
	$handler->display->display_options ['filters'] ['field_hrm_overuren_status_value'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_hrm_overuren_status_value'] ['expose'] ['operator_id'] = 'field_hrm_overuren_status_value_op';
	$handler->display->display_options ['filters'] ['field_hrm_overuren_status_value'] ['expose'] ['label'] = 'Status';
	$handler->display->display_options ['filters'] ['field_hrm_overuren_status_value'] ['expose'] ['operator'] = 'field_hrm_overuren_status_value_op';
	$handler->display->display_options ['filters'] ['field_hrm_overuren_status_value'] ['expose'] ['identifier'] = 'field_hrm_overuren_status_value';
	$handler->display->display_options ['filters'] ['field_hrm_overuren_status_value'] ['expose'] ['multiple'] = TRUE;
	$handler->display->display_options ['filters'] ['field_hrm_overuren_status_value'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['filters'] ['field_hrm_overuren_status_value'] ['reduce_duplicates'] = TRUE;
	/* Filtercriterium: Inhoud: Periode van toepassing - startdatum (field_datum) */
	$handler->display->display_options ['filters'] ['field_datum_value'] ['id'] = 'field_datum_value';
	$handler->display->display_options ['filters'] ['field_datum_value'] ['table'] = 'field_data_field_datum';
	$handler->display->display_options ['filters'] ['field_datum_value'] ['field'] = 'field_datum_value';
	$handler->display->display_options ['filters'] ['field_datum_value'] ['operator'] = 'between';
	$handler->display->display_options ['filters'] ['field_datum_value'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_datum_value'] ['expose'] ['operator_id'] = 'field_datum_value_op';
	$handler->display->display_options ['filters'] ['field_datum_value'] ['expose'] ['label'] = 'Datum';
	$handler->display->display_options ['filters'] ['field_datum_value'] ['expose'] ['operator'] = 'field_datum_value_op';
	$handler->display->display_options ['filters'] ['field_datum_value'] ['expose'] ['identifier'] = 'field_datum_value';
	$handler->display->display_options ['filters'] ['field_datum_value'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['filters'] ['field_datum_value'] ['form_type'] = 'date_popup';
	$handler->display->display_options ['filters'] ['field_datum_value'] ['default_date'] = 'now -1 year';
	$handler->display->display_options ['qtip_instance'] = 'standaard';
	
	/* Display: Overzicht */
	$handler = $view->new_display ( 'page', 'Overzicht', 'hrm_overuren_overview' );
	$handler->display->display_options ['defaults'] ['exposed_form'] = FALSE;
	$handler->display->display_options ['exposed_form'] ['type'] = 'better_exposed_filters';
	$handler->display->display_options ['exposed_form'] ['options'] ['submit_button'] = 'Toepassen';
	$handler->display->display_options ['exposed_form'] ['options'] ['reset_button'] = TRUE;
	$handler->display->display_options ['exposed_form'] ['options'] ['reset_button_label'] = 'Opnieuw instellen';
	$handler->display->display_options ['exposed_form'] ['options'] ['exposed_sorts_label'] = 'Sorteren op';
	$handler->display->display_options ['exposed_form'] ['options'] ['sort_asc_label'] = 'Oplopend';
	$handler->display->display_options ['exposed_form'] ['options'] ['sort_desc_label'] = 'Aflopend';
	$handler->display->display_options ['exposed_form'] ['options'] ['autosubmit'] = TRUE;
	$handler->display->display_options ['exposed_form'] ['options'] ['bef'] = array (
			'general' => array (
					'input_required' => 0,
					'text_input_required' => array (
							'text_input_required' => array (
									'value' => 'Selecteer een van de filters en klik op \'Toepassen\' om het resultaat te zien',
									'format' => 'filtered_html' 
							) 
					),
					'allow_secondary' => 0,
					'secondary_label' => 'Uitgebreide opties',
					'secondary_collapse_override' => '0' 
			),
			'realname' => array (
					'bef_format' => 'default',
					'more_options' => array (
							'autosubmit' => 0,
							'is_secondary' => 0,
							'any_label' => '',
							'bef_filter_description' => '',
							'tokens' => array (
									'available' => array (
											0 => 'global_types' 
									) 
							),
							'rewrite' => array (
									'filter_rewrite_values' => '' 
							) 
					) 
			),
			'field_hrm_overuren_status_value' => array (
					'bef_format' => 'bef',
					'more_options' => array (
							'bef_select_all_none' => 0,
							'bef_collapsible' => 0,
							'autosubmit' => 0,
							'is_secondary' => 0,
							'any_label' => '',
							'bef_filter_description' => '',
							'tokens' => array (
									'available' => array (
											0 => 'global_types' 
									) 
							),
							'rewrite' => array (
									'filter_rewrite_values' => '' 
							) 
					) 
			) 
	);
	$handler->display->display_options ['exposed_block'] = TRUE;
	$handler->display->display_options ['defaults'] ['filter_groups'] = FALSE;
	$handler->display->display_options ['defaults'] ['filters'] = FALSE;
	/* Filtercriterium: Inhoud: Gepubliceerd */
	$handler->display->display_options ['filters'] ['status'] ['id'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['status'] ['field'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['value'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['expose'] ['operator'] = FALSE;
	/* Filtercriterium: Inhoud: Type */
	$handler->display->display_options ['filters'] ['type'] ['id'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['type'] ['field'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['value'] = array (
			'hrm_overuren' => 'hrm_overuren' 
	);
	/* Filtercriterium: Echte naam: Naam */
	$handler->display->display_options ['filters'] ['realname'] ['id'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['table'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['field'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['relationship'] = 'uid';
	$handler->display->display_options ['filters'] ['realname'] ['operator'] = 'contains';
	$handler->display->display_options ['filters'] ['realname'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['operator_id'] = 'realname_op';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['label'] = 'Personeelslid';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['operator'] = 'realname_op';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['identifier'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_items'] = '10';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_min_chars'] = '0';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_field'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_raw_suggestion'] = '1';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_raw_dropdown'] = '1';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_dependent'] = 0;
	/* Filtercriterium: Inhoud: Status (field_hrm_overuren_status) */
	$handler->display->display_options ['filters'] ['field_hrm_overuren_status_value'] ['id'] = 'field_hrm_overuren_status_value';
	$handler->display->display_options ['filters'] ['field_hrm_overuren_status_value'] ['table'] = 'field_data_field_hrm_overuren_status';
	$handler->display->display_options ['filters'] ['field_hrm_overuren_status_value'] ['field'] = 'field_hrm_overuren_status_value';
	$handler->display->display_options ['filters'] ['field_hrm_overuren_status_value'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_hrm_overuren_status_value'] ['expose'] ['operator_id'] = 'field_hrm_overuren_status_value_op';
	$handler->display->display_options ['filters'] ['field_hrm_overuren_status_value'] ['expose'] ['label'] = 'Status';
	$handler->display->display_options ['filters'] ['field_hrm_overuren_status_value'] ['expose'] ['operator'] = 'field_hrm_overuren_status_value_op';
	$handler->display->display_options ['filters'] ['field_hrm_overuren_status_value'] ['expose'] ['identifier'] = 'field_hrm_overuren_status_value';
	$handler->display->display_options ['filters'] ['field_hrm_overuren_status_value'] ['expose'] ['multiple'] = TRUE;
	$handler->display->display_options ['filters'] ['field_hrm_overuren_status_value'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['filters'] ['field_hrm_overuren_status_value'] ['reduce_duplicates'] = TRUE;
	$handler->display->display_options ['qtip_instance'] = 'standaard';
	$handler->display->display_options ['path'] = 'hrm/overuren';
	$handler->display->display_options ['menu'] ['type'] = 'normal';
	$handler->display->display_options ['menu'] ['title'] = 'Overuren';
	$handler->display->display_options ['menu'] ['weight'] = '0';
	if (menu_load ( 'menu-modules' )) {
		$menu = 'menu-modules';
	} else {
		$menu = 'navigation';
	}
	$handler->display->display_options ['menu'] ['name'] = $menu;
	$handler->display->display_options ['menu'] ['context'] = 0;
	$handler->display->display_options ['menu'] ['context_only_inline'] = 0;
	$translatables ['hrm_overuren'] = array (
			t ( 'Master' ),
			t ( 'Overuren' ),
			t ( 'meer' ),
			t ( 'Toepassen' ),
			t ( 'Opnieuw instellen' ),
			t ( 'Sorteren op' ),
			t ( 'Oplopend' ),
			t ( 'Aflopend' ),
			t ( 'Selecteer een van de filters en klik op \'Toepassen\' om het resultaat te zien' ),
			t ( 'Uitgebreide opties' ),
			t ( 'Items per pagina' ),
			t ( '- Alle -' ),
			t ( 'Startpunt' ),
			t ( '« eerste' ),
			t ( '‹ vorige' ),
			t ( 'volgende ›' ),
			t ( 'laatste »' ),
			t ( '<a href="/node/add/hrm-overuren">Een aanvraag "overuren" toevoegen</a>' ),
			t ( 'Getoond @start - @end van @total' ),
			t ( 'auteur' ),
			t ( 'Nr.' ),
			t ( 'Aanvrager' ),
			t ( 'Datum' ),
			t ( 'Aangevraagd' ),
			t ( 'Status' ),
			t ( 'Terugname' ),
			t ( 'Rest' ),
			t ( '.' ),
			t ( ',' ),
			t ( ' uren' ),
			t ( 'Personeelslid' ),
			t ( 'Overzicht' ) 
	);
	
	$views [$view->name] = $view;
	return $views;
}