<?php
/*
 * Copyright (C) 2017 bartgysens
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* Drupal Hooks */

/**
 * Implements hook_ctools_plugin_api().
 */
function argus_vakken_ctools_plugin_api($module = NULL, $api = NULL) {
	if ($module == "field_group" && $api == "field_group") {
		return array (
				"version" => "1" 
		);
	}
}

/**
 * Implements hook_node_info().
 */
function argus_vakken_node_info() {
	$items = array (
			'vak' => array (
					'name' => t ( 'Vak' ),
					'base' => 'node_content',
					'description' => t ( 'Beheer de <em>vakken</em> die onderricht worden.' ),
					'has_title' => '1',
					'title_label' => t ( 'Title' ),
					'help' => '' 
			) 
	);
	drupal_alter ( 'node_info', $items );
	return $items;
}

/**
 * Implement hook_form()
 */
function argus_vakken_form($node, $form_state) {
	return node_content_form ( $node, $form_state );
}

/**
 * Implementation of hook_views_api().
 */
function argus_vakken_views_api() {
	return array (
			'api' => 3.0,
			'path' => drupal_get_path ( 'module', 'argus_vakken' ) 
	); // replace demo with your content type

}

/**
 * Implementation of hook_views_default_views().
 *
 * Views export creates code that you have to paste in this function.
 *
 * Administration > Structure > Views : click the button behind the view you need and export
 * /admin/structure/views
 */
function argus_vakken_views_default_views() {
	$view = new view ();
	$view->name = 'vakken';
	$view->description = '';
	$view->tag = 'default';
	$view->base_table = 'node';
	$view->human_name = 'Vakken';
	$view->core = 7;
	$view->api_version = '3.0';
	$view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */
	
	/* Display: Master */
	$handler = $view->new_display ( 'default', 'Master', 'default' );
	$handler->display->display_options ['title'] = 'Vakken';
	$handler->display->display_options ['use_more_always'] = FALSE;
	$handler->display->display_options ['use_more_text'] = 'meer';
	$handler->display->display_options ['access'] ['type'] = 'perm';
	$handler->display->display_options ['cache'] ['type'] = 'views_content_cache';
	$handler->display->display_options ['cache'] ['results_min_lifespan'] = '-1';
	$handler->display->display_options ['cache'] ['results_max_lifespan'] = '518400';
	$handler->display->display_options ['cache'] ['output_min_lifespan'] = '-1';
	$handler->display->display_options ['cache'] ['output_max_lifespan'] = '518400';
	$handler->display->display_options ['cache'] ['keys'] = array (
			'comment' => array (
					'changed' => 0 
			),
			'node' => array (
					'vak' => 'vak' 
			),
			'node_only' => array (
					'node_changed' => 'node_changed' 
			) 
	);
	$handler->display->display_options ['query'] ['type'] = 'views_query';
	$handler->display->display_options ['exposed_form'] ['type'] = 'basic';
	$handler->display->display_options ['exposed_form'] ['options'] ['submit_button'] = 'Toepassen';
	$handler->display->display_options ['exposed_form'] ['options'] ['reset_button'] = TRUE;
	$handler->display->display_options ['exposed_form'] ['options'] ['reset_button_label'] = 'Opnieuw instellen';
	$handler->display->display_options ['exposed_form'] ['options'] ['exposed_sorts_label'] = 'Sorteren op';
	$handler->display->display_options ['exposed_form'] ['options'] ['sort_asc_label'] = 'Oplopend';
	$handler->display->display_options ['exposed_form'] ['options'] ['sort_desc_label'] = 'Aflopend';
	$handler->display->display_options ['exposed_form'] ['options'] ['autosubmit'] = FALSE;
	$handler->display->display_options ['pager'] ['type'] = 'full';
	$handler->display->display_options ['pager'] ['options'] ['items_per_page'] = '25';
	$handler->display->display_options ['pager'] ['options'] ['offset'] = '0';
	$handler->display->display_options ['pager'] ['options'] ['id'] = '0';
	$handler->display->display_options ['pager'] ['options'] ['quantity'] = '9';
	$handler->display->display_options ['pager'] ['options'] ['expose'] ['items_per_page_label'] = 'Items per pagina';
	$handler->display->display_options ['pager'] ['options'] ['expose'] ['items_per_page_options_all_label'] = '- Alle -';
	$handler->display->display_options ['pager'] ['options'] ['expose'] ['offset_label'] = 'Startpunt';
	$handler->display->display_options ['pager'] ['options'] ['tags'] ['first'] = '« eerste';
	$handler->display->display_options ['pager'] ['options'] ['tags'] ['previous'] = '‹ vorige';
	$handler->display->display_options ['pager'] ['options'] ['tags'] ['next'] = 'volgende ›';
	$handler->display->display_options ['pager'] ['options'] ['tags'] ['last'] = 'laatste »';
	$handler->display->display_options ['style_plugin'] = 'table';
	$handler->display->display_options ['style_options'] ['columns'] = array (
			'nid' => 'nid',
			'field_vak_afkorting' => 'field_vak_afkorting',
			'field_vak_beschrijving' => 'field_vak_beschrijving',
			'field_vak_lokaal' => 'field_vak_lokaal',
			'field_vak_skore_id' => 'field_vak_skore_id',
			'field_vak_untis_id' => 'field_vak_untis_id' 
	);
	$handler->display->display_options ['style_options'] ['default'] = 'field_vak_afkorting';
	$handler->display->display_options ['style_options'] ['info'] = array (
			'nid' => array (
					'sortable' => 0,
					'default_sort_order' => 'asc',
					'align' => '',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_vak_afkorting' => array (
					'sortable' => 1,
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_vak_beschrijving' => array (
					'sortable' => 1,
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_vak_lokaal' => array (
					'sortable' => 1,
					'default_sort_order' => 'asc',
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_vak_skore_id' => array (
					'sortable' => 1,
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_vak_untis_id' => array (
					'sortable' => 1,
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			) 
	);
	/* Veld: Inhoud: Nid */
	$handler->display->display_options ['fields'] ['nid'] ['id'] = 'nid';
	$handler->display->display_options ['fields'] ['nid'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['nid'] ['field'] = 'nid';
	$handler->display->display_options ['fields'] ['nid'] ['label'] = '';
	$handler->display->display_options ['fields'] ['nid'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['nid'] ['element_label_colon'] = FALSE;
	/* Veld: Inhoud: Afkorting */
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['id'] = 'field_vak_afkorting';
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['table'] = 'field_data_field_vak_afkorting';
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['field'] = 'field_vak_afkorting';
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['alter'] ['make_link'] = TRUE;
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['alter'] ['path'] = 'node/[nid]';
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['alter'] ['absolute'] = TRUE;
	/* Veld: Inhoud: Beschrijving */
	$handler->display->display_options ['fields'] ['field_vak_beschrijving'] ['id'] = 'field_vak_beschrijving';
	$handler->display->display_options ['fields'] ['field_vak_beschrijving'] ['table'] = 'field_data_field_vak_beschrijving';
	$handler->display->display_options ['fields'] ['field_vak_beschrijving'] ['field'] = 'field_vak_beschrijving';
	/* Veld: Inhoud: Lokaal */
	$handler->display->display_options ['fields'] ['field_vak_lokaal'] ['id'] = 'field_vak_lokaal';
	$handler->display->display_options ['fields'] ['field_vak_lokaal'] ['table'] = 'field_data_field_vak_lokaal';
	$handler->display->display_options ['fields'] ['field_vak_lokaal'] ['field'] = 'field_vak_lokaal';
	$handler->display->display_options ['fields'] ['field_vak_lokaal'] ['settings'] = array (
			'link' => 1 
	);
	/* Veld: Inhoud: ID (Skore) */
	$handler->display->display_options ['fields'] ['field_vak_skore_id'] ['id'] = 'field_vak_skore_id';
	$handler->display->display_options ['fields'] ['field_vak_skore_id'] ['table'] = 'field_data_field_vak_skore_id';
	$handler->display->display_options ['fields'] ['field_vak_skore_id'] ['field'] = 'field_vak_skore_id';
	/* Veld: Inhoud: ID (Untis) */
	$handler->display->display_options ['fields'] ['field_vak_untis_id'] ['id'] = 'field_vak_untis_id';
	$handler->display->display_options ['fields'] ['field_vak_untis_id'] ['table'] = 'field_data_field_vak_untis_id';
	$handler->display->display_options ['fields'] ['field_vak_untis_id'] ['field'] = 'field_vak_untis_id';
	/* Sorteercriterium: Inhoud: Afkorting (field_vak_afkorting) */
	$handler->display->display_options ['sorts'] ['field_vak_afkorting_value'] ['id'] = 'field_vak_afkorting_value';
	$handler->display->display_options ['sorts'] ['field_vak_afkorting_value'] ['table'] = 'field_data_field_vak_afkorting';
	$handler->display->display_options ['sorts'] ['field_vak_afkorting_value'] ['field'] = 'field_vak_afkorting_value';
	/* Filtercriterium: Inhoud: Gepubliceerd */
	$handler->display->display_options ['filters'] ['status'] ['id'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['status'] ['field'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['value'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['expose'] ['operator'] = FALSE;
	/* Filtercriterium: Inhoud: Type */
	$handler->display->display_options ['filters'] ['type'] ['id'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['type'] ['field'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['value'] = array (
			'vak' => 'vak' 
	);
	/* Filtercriterium: Inhoud: Afkorting (field_vak_afkorting) */
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['id'] = 'field_vak_afkorting_value';
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['table'] = 'field_data_field_vak_afkorting';
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['field'] = 'field_vak_afkorting_value';
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['operator'] = 'contains';
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['expose'] ['operator_id'] = 'field_vak_afkorting_value_op';
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['expose'] ['label'] = 'Afkorting';
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['expose'] ['operator'] = 'field_vak_afkorting_value_op';
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['expose'] ['identifier'] = 'field_vak_afkorting_value';
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['expose'] ['remember_roles'] = array ();
	/* Filtercriterium: Inhoud: Beschrijving (field_vak_beschrijving) */
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['id'] = 'field_vak_beschrijving_value';
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['table'] = 'field_data_field_vak_beschrijving';
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['field'] = 'field_vak_beschrijving_value';
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['operator'] = 'contains';
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['expose'] ['operator_id'] = 'field_vak_beschrijving_value_op';
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['expose'] ['label'] = 'Beschrijving';
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['expose'] ['operator'] = 'field_vak_beschrijving_value_op';
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['expose'] ['identifier'] = 'field_vak_beschrijving_value';
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['expose'] ['remember_roles'] = array ();
	/* Filtercriterium: Inhoud: Lokaal (field_vak_lokaal) */
	$handler->display->display_options ['filters'] ['field_vak_lokaal_target_id'] ['id'] = 'field_vak_lokaal_target_id';
	$handler->display->display_options ['filters'] ['field_vak_lokaal_target_id'] ['table'] = 'field_data_field_vak_lokaal';
	$handler->display->display_options ['filters'] ['field_vak_lokaal_target_id'] ['field'] = 'field_vak_lokaal_target_id';
	$handler->display->display_options ['filters'] ['field_vak_lokaal_target_id'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_vak_lokaal_target_id'] ['expose'] ['operator_id'] = 'field_vak_lokaal_target_id_op';
	$handler->display->display_options ['filters'] ['field_vak_lokaal_target_id'] ['expose'] ['label'] = 'Lokaal';
	$handler->display->display_options ['filters'] ['field_vak_lokaal_target_id'] ['expose'] ['operator'] = 'field_vak_lokaal_target_id_op';
	$handler->display->display_options ['filters'] ['field_vak_lokaal_target_id'] ['expose'] ['identifier'] = 'field_vak_lokaal_target_id';
	$handler->display->display_options ['filters'] ['field_vak_lokaal_target_id'] ['expose'] ['remember_roles'] = array ();
	
	/* Display: Vakken */
	$handler = $view->new_display ( 'page', 'Vakken', 'vak_overzicht' );
	$handler->display->display_options ['display_description'] = 'Overzicht van alle vakken die onderricht worden.';
	$handler->display->display_options ['exposed_block'] = TRUE;
	$handler->display->display_options ['defaults'] ['fields'] = FALSE;
	/* Veld: Inhoud: Nid */
	$handler->display->display_options ['fields'] ['nid'] ['id'] = 'nid';
	$handler->display->display_options ['fields'] ['nid'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['nid'] ['field'] = 'nid';
	$handler->display->display_options ['fields'] ['nid'] ['label'] = '';
	$handler->display->display_options ['fields'] ['nid'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['nid'] ['element_label_colon'] = FALSE;
	/* Veld: Inhoud: Afkorting */
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['id'] = 'field_vak_afkorting';
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['table'] = 'field_data_field_vak_afkorting';
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['field'] = 'field_vak_afkorting';
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['alter'] ['make_link'] = TRUE;
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['alter'] ['path'] = 'node/[nid]';
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['alter'] ['absolute'] = TRUE;
	/* Veld: Inhoud: Beschrijving */
	$handler->display->display_options ['fields'] ['field_vak_beschrijving'] ['id'] = 'field_vak_beschrijving';
	$handler->display->display_options ['fields'] ['field_vak_beschrijving'] ['table'] = 'field_data_field_vak_beschrijving';
	$handler->display->display_options ['fields'] ['field_vak_beschrijving'] ['field'] = 'field_vak_beschrijving';
	/* Veld: Inhoud: Lokaal */
	$handler->display->display_options ['fields'] ['field_vak_lokaal'] ['id'] = 'field_vak_lokaal';
	$handler->display->display_options ['fields'] ['field_vak_lokaal'] ['table'] = 'field_data_field_vak_lokaal';
	$handler->display->display_options ['fields'] ['field_vak_lokaal'] ['field'] = 'field_vak_lokaal';
	$handler->display->display_options ['fields'] ['field_vak_lokaal'] ['settings'] = array (
			'link' => 1 
	);
	/* Veld: Inhoud: ID (Skore) */
	$handler->display->display_options ['fields'] ['field_vak_skore_id'] ['id'] = 'field_vak_skore_id';
	$handler->display->display_options ['fields'] ['field_vak_skore_id'] ['table'] = 'field_data_field_vak_skore_id';
	$handler->display->display_options ['fields'] ['field_vak_skore_id'] ['field'] = 'field_vak_skore_id';
	/* Veld: Inhoud: ID (Untis) */
	$handler->display->display_options ['fields'] ['field_vak_untis_id'] ['id'] = 'field_vak_untis_id';
	$handler->display->display_options ['fields'] ['field_vak_untis_id'] ['table'] = 'field_data_field_vak_untis_id';
	$handler->display->display_options ['fields'] ['field_vak_untis_id'] ['field'] = 'field_vak_untis_id';
	$handler->display->display_options ['defaults'] ['filter_groups'] = FALSE;
	$handler->display->display_options ['defaults'] ['filters'] = FALSE;
	/* Filtercriterium: Inhoud: Gepubliceerd */
	$handler->display->display_options ['filters'] ['status'] ['id'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['status'] ['field'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['value'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['expose'] ['operator'] = FALSE;
	/* Filtercriterium: Inhoud: Type */
	$handler->display->display_options ['filters'] ['type'] ['id'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['type'] ['field'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['value'] = array (
			'vak' => 'vak' 
	);
	/* Filtercriterium: Inhoud: Afkorting (field_vak_afkorting) */
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['id'] = 'field_vak_afkorting_value';
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['table'] = 'field_data_field_vak_afkorting';
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['field'] = 'field_vak_afkorting_value';
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['operator'] = 'contains';
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['expose'] ['operator_id'] = 'field_vak_afkorting_value_op';
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['expose'] ['label'] = 'Afkorting';
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['expose'] ['operator'] = 'field_vak_afkorting_value_op';
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['expose'] ['identifier'] = 'field_vak_afkorting_value';
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['expose'] ['remember_roles'] = array ();
	/* Filtercriterium: Inhoud: Beschrijving (field_vak_beschrijving) */
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['id'] = 'field_vak_beschrijving_value';
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['table'] = 'field_data_field_vak_beschrijving';
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['field'] = 'field_vak_beschrijving_value';
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['operator'] = 'contains';
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['expose'] ['operator_id'] = 'field_vak_beschrijving_value_op';
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['expose'] ['label'] = 'Beschrijving';
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['expose'] ['operator'] = 'field_vak_beschrijving_value_op';
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['expose'] ['identifier'] = 'field_vak_beschrijving_value';
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['expose'] ['remember_roles'] = array ();
	/* Filtercriterium: Inhoud: Lokaal (field_vak_lokaal) */
	$handler->display->display_options ['filters'] ['field_vak_lokaal_target_id'] ['id'] = 'field_vak_lokaal_target_id';
	$handler->display->display_options ['filters'] ['field_vak_lokaal_target_id'] ['table'] = 'field_data_field_vak_lokaal';
	$handler->display->display_options ['filters'] ['field_vak_lokaal_target_id'] ['field'] = 'field_vak_lokaal_target_id';
	$handler->display->display_options ['filters'] ['field_vak_lokaal_target_id'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_vak_lokaal_target_id'] ['expose'] ['operator_id'] = 'field_vak_lokaal_target_id_op';
	$handler->display->display_options ['filters'] ['field_vak_lokaal_target_id'] ['expose'] ['label'] = 'Lokaal';
	$handler->display->display_options ['filters'] ['field_vak_lokaal_target_id'] ['expose'] ['operator'] = 'field_vak_lokaal_target_id_op';
	$handler->display->display_options ['filters'] ['field_vak_lokaal_target_id'] ['expose'] ['identifier'] = 'field_vak_lokaal_target_id';
	$handler->display->display_options ['filters'] ['field_vak_lokaal_target_id'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['path'] = 'vakken/overzicht';
	$handler->display->display_options ['menu'] ['type'] = 'normal';
	$handler->display->display_options ['menu'] ['title'] = 'Vakken';
	if (menu_load ( 'menu-modules' )) {
		$menu = 'menu-modules';
	} else {
		$menu = 'navigation';
	}
	$handler->display->display_options ['menu'] ['name'] = $menu;
	
	/* Display: Selectielijst: vakken */
	$handler = $view->new_display ( 'entityreference', 'Selectielijst: vakken', 'entityreference_vakken' );
	$handler->display->display_options ['defaults'] ['title'] = FALSE;
	$handler->display->display_options ['pager'] ['type'] = 'none';
	$handler->display->display_options ['pager'] ['options'] ['offset'] = '0';
	$handler->display->display_options ['defaults'] ['style_plugin'] = FALSE;
	$handler->display->display_options ['style_plugin'] = 'entityreference_style';
	$handler->display->display_options ['style_options'] ['search_fields'] = array (
			'field_vak_afkorting' => 'field_vak_afkorting',
			'field_vak_beschrijving' => 0 
	);
	$handler->display->display_options ['defaults'] ['style_options'] = FALSE;
	$handler->display->display_options ['defaults'] ['row_plugin'] = FALSE;
	$handler->display->display_options ['row_plugin'] = 'entityreference_fields';
	$handler->display->display_options ['defaults'] ['row_options'] = FALSE;
	$handler->display->display_options ['defaults'] ['fields'] = FALSE;
	/* Veld: Inhoud: Afkorting */
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['id'] = 'field_vak_afkorting';
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['table'] = 'field_data_field_vak_afkorting';
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['field'] = 'field_vak_afkorting';
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['label'] = '';
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['alter'] ['make_link'] = TRUE;
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['alter'] ['path'] = 'node/[nid]';
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['alter'] ['absolute'] = TRUE;
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['element_label_colon'] = FALSE;
	/* Veld: Inhoud: Beschrijving */
	$handler->display->display_options ['fields'] ['field_vak_beschrijving'] ['id'] = 'field_vak_beschrijving';
	$handler->display->display_options ['fields'] ['field_vak_beschrijving'] ['table'] = 'field_data_field_vak_beschrijving';
	$handler->display->display_options ['fields'] ['field_vak_beschrijving'] ['field'] = 'field_vak_beschrijving';
	$handler->display->display_options ['fields'] ['field_vak_beschrijving'] ['label'] = '';
	$handler->display->display_options ['fields'] ['field_vak_beschrijving'] ['element_label_colon'] = FALSE;
	$handler->display->display_options ['defaults'] ['filter_groups'] = FALSE;
	$handler->display->display_options ['defaults'] ['filters'] = FALSE;
	/* Filtercriterium: Inhoud: Gepubliceerd */
	$handler->display->display_options ['filters'] ['status'] ['id'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['status'] ['field'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['value'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['expose'] ['operator'] = FALSE;
	/* Filtercriterium: Inhoud: Type */
	$handler->display->display_options ['filters'] ['type'] ['id'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['type'] ['field'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['value'] = array (
			'vak' => 'vak' 
	);
	$handler->display->display_options ['filters'] ['type'] ['group'] = 1;
	$handler->display->display_options ['qtip_instance'] = 'standaard';
	
	/* Display: Vakken - adminoverzicht */
	$handler = $view->new_display ( 'page', 'Vakken - adminoverzicht', 'page_1' );
	$handler->display->display_options ['display_description'] = 'Administratieoverzicht van alle vakken die onderricht worden.';
	$handler->display->display_options ['exposed_block'] = TRUE;
	$handler->display->display_options ['defaults'] ['fields'] = FALSE;
	/* Veld: Inhoud: Nid */
	$handler->display->display_options ['fields'] ['nid'] ['id'] = 'nid';
	$handler->display->display_options ['fields'] ['nid'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['nid'] ['field'] = 'nid';
	$handler->display->display_options ['fields'] ['nid'] ['label'] = '';
	$handler->display->display_options ['fields'] ['nid'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['nid'] ['element_label_colon'] = FALSE;
	/* Veld: Inhoud: Afkorting */
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['id'] = 'field_vak_afkorting';
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['table'] = 'field_data_field_vak_afkorting';
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['field'] = 'field_vak_afkorting';
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['alter'] ['make_link'] = TRUE;
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['alter'] ['path'] = 'node/[nid]';
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['alter'] ['absolute'] = TRUE;
	/* Veld: Inhoud: Beschrijving */
	$handler->display->display_options ['fields'] ['field_vak_beschrijving'] ['id'] = 'field_vak_beschrijving';
	$handler->display->display_options ['fields'] ['field_vak_beschrijving'] ['table'] = 'field_data_field_vak_beschrijving';
	$handler->display->display_options ['fields'] ['field_vak_beschrijving'] ['field'] = 'field_vak_beschrijving';
	/* Veld: Inhoud: Lokaal */
	$handler->display->display_options ['fields'] ['field_vak_lokaal'] ['id'] = 'field_vak_lokaal';
	$handler->display->display_options ['fields'] ['field_vak_lokaal'] ['table'] = 'field_data_field_vak_lokaal';
	$handler->display->display_options ['fields'] ['field_vak_lokaal'] ['field'] = 'field_vak_lokaal';
	$handler->display->display_options ['fields'] ['field_vak_lokaal'] ['settings'] = array (
			'link' => 1 
	);
	/* Veld: Inhoud: Evaluatie */
	$handler->display->display_options ['fields'] ['field_vak_evaluatie'] ['id'] = 'field_vak_evaluatie';
	$handler->display->display_options ['fields'] ['field_vak_evaluatie'] ['table'] = 'field_data_field_vak_evaluatie';
	$handler->display->display_options ['fields'] ['field_vak_evaluatie'] ['field'] = 'field_vak_evaluatie';
	$handler->display->display_options ['fields'] ['field_vak_evaluatie'] ['type'] = 'editable';
	$handler->display->display_options ['fields'] ['field_vak_evaluatie'] ['settings'] = array (
			'click_to_edit' => 0,
			'click_to_edit_style' => 'hover',
			'empty_text' => '',
			'fallback_format' => 'list_default' 
	);
	$handler->display->display_options ['fields'] ['field_vak_evaluatie'] ['delta_offset'] = '0';
	/* Veld: Inhoud: ID (Skore) */
	$handler->display->display_options ['fields'] ['field_vak_skore_id'] ['id'] = 'field_vak_skore_id';
	$handler->display->display_options ['fields'] ['field_vak_skore_id'] ['table'] = 'field_data_field_vak_skore_id';
	$handler->display->display_options ['fields'] ['field_vak_skore_id'] ['field'] = 'field_vak_skore_id';
	/* Veld: Inhoud: ID (Untis) */
	$handler->display->display_options ['fields'] ['field_vak_untis_id'] ['id'] = 'field_vak_untis_id';
	$handler->display->display_options ['fields'] ['field_vak_untis_id'] ['table'] = 'field_data_field_vak_untis_id';
	$handler->display->display_options ['fields'] ['field_vak_untis_id'] ['field'] = 'field_vak_untis_id';
	$handler->display->display_options ['defaults'] ['filter_groups'] = FALSE;
	$handler->display->display_options ['defaults'] ['filters'] = FALSE;
	/* Filtercriterium: Inhoud: Gepubliceerd */
	$handler->display->display_options ['filters'] ['status'] ['id'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['status'] ['field'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['value'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['expose'] ['operator'] = FALSE;
	/* Filtercriterium: Inhoud: Type */
	$handler->display->display_options ['filters'] ['type'] ['id'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['type'] ['field'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['value'] = array (
			'vak' => 'vak' 
	);
	/* Filtercriterium: Inhoud: Afkorting (field_vak_afkorting) */
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['id'] = 'field_vak_afkorting_value';
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['table'] = 'field_data_field_vak_afkorting';
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['field'] = 'field_vak_afkorting_value';
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['operator'] = 'contains';
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['expose'] ['operator_id'] = 'field_vak_afkorting_value_op';
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['expose'] ['label'] = 'Afkorting';
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['expose'] ['operator'] = 'field_vak_afkorting_value_op';
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['expose'] ['identifier'] = 'field_vak_afkorting_value';
	$handler->display->display_options ['filters'] ['field_vak_afkorting_value'] ['expose'] ['remember_roles'] = array ();
	/* Filtercriterium: Inhoud: Beschrijving (field_vak_beschrijving) */
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['id'] = 'field_vak_beschrijving_value';
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['table'] = 'field_data_field_vak_beschrijving';
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['field'] = 'field_vak_beschrijving_value';
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['operator'] = 'contains';
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['expose'] ['operator_id'] = 'field_vak_beschrijving_value_op';
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['expose'] ['label'] = 'Beschrijving';
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['expose'] ['operator'] = 'field_vak_beschrijving_value_op';
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['expose'] ['identifier'] = 'field_vak_beschrijving_value';
	$handler->display->display_options ['filters'] ['field_vak_beschrijving_value'] ['expose'] ['remember_roles'] = array ();
	/* Filtercriterium: Inhoud: Lokaal (field_vak_lokaal) */
	$handler->display->display_options ['filters'] ['field_vak_lokaal_target_id'] ['id'] = 'field_vak_lokaal_target_id';
	$handler->display->display_options ['filters'] ['field_vak_lokaal_target_id'] ['table'] = 'field_data_field_vak_lokaal';
	$handler->display->display_options ['filters'] ['field_vak_lokaal_target_id'] ['field'] = 'field_vak_lokaal_target_id';
	$handler->display->display_options ['filters'] ['field_vak_lokaal_target_id'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_vak_lokaal_target_id'] ['expose'] ['operator_id'] = 'field_vak_lokaal_target_id_op';
	$handler->display->display_options ['filters'] ['field_vak_lokaal_target_id'] ['expose'] ['label'] = 'Lokaal';
	$handler->display->display_options ['filters'] ['field_vak_lokaal_target_id'] ['expose'] ['operator'] = 'field_vak_lokaal_target_id_op';
	$handler->display->display_options ['filters'] ['field_vak_lokaal_target_id'] ['expose'] ['identifier'] = 'field_vak_lokaal_target_id';
	$handler->display->display_options ['filters'] ['field_vak_lokaal_target_id'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['path'] = 'vakken/overzicht/admin';
	$handler->display->display_options ['menu'] ['type'] = 'normal';
	$handler->display->display_options ['menu'] ['title'] = 'Vakken: persoonlijk';
	if (menu_load ( 'menu-modules' )) {
		$menu = 'menu-modules';
	} else {
		$menu = 'navigation';
	}
	$handler->display->display_options ['menu'] ['name'] = $menu;
	
	/* Display: Selectielijst: vakken - gepersonaliseerd */
	$handler = $view->new_display ( 'entityreference', 'Selectielijst: vakken - gepersonaliseerd', 'entityreference_vakken_persoonlijk' );
	$handler->display->display_options ['defaults'] ['title'] = FALSE;
	$handler->display->display_options ['defaults'] ['group_by'] = FALSE;
	$handler->display->display_options ['group_by'] = TRUE;
	$handler->display->display_options ['pager'] ['type'] = 'none';
	$handler->display->display_options ['pager'] ['options'] ['offset'] = '0';
	$handler->display->display_options ['defaults'] ['style_plugin'] = FALSE;
	$handler->display->display_options ['style_plugin'] = 'entityreference_style';
	$handler->display->display_options ['style_options'] ['search_fields'] = array (
			'nid' => 'nid',
			'field_vak_afkorting' => 0,
			'field_vak_beschrijving' => 0,
			'field_vak_lokaal' => 0,
			'field_vak_skore_id' => 0,
			'field_vak_untis_id' => 0 
	);
	$handler->display->display_options ['defaults'] ['style_options'] = FALSE;
	$handler->display->display_options ['defaults'] ['row_plugin'] = FALSE;
	$handler->display->display_options ['row_plugin'] = 'entityreference_fields';
	$handler->display->display_options ['defaults'] ['row_options'] = FALSE;
	$handler->display->display_options ['defaults'] ['relationships'] = FALSE;
	/* Relatie: Referentie naar een entiteit: Refererende entiteit */
	$handler->display->display_options ['relationships'] ['reverse_field_uurrooster_les_vak_node'] ['id'] = 'reverse_field_uurrooster_les_vak_node';
	$handler->display->display_options ['relationships'] ['reverse_field_uurrooster_les_vak_node'] ['table'] = 'node';
	$handler->display->display_options ['relationships'] ['reverse_field_uurrooster_les_vak_node'] ['field'] = 'reverse_field_uurrooster_les_vak_node';
	$handler->display->display_options ['defaults'] ['fields'] = FALSE;
	/* Veld: Inhoud: Nid */
	$handler->display->display_options ['fields'] ['nid'] ['id'] = 'nid';
	$handler->display->display_options ['fields'] ['nid'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['nid'] ['field'] = 'nid';
	$handler->display->display_options ['fields'] ['nid'] ['label'] = '';
	$handler->display->display_options ['fields'] ['nid'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['nid'] ['element_label_colon'] = FALSE;
	/* Veld: Inhoud: Afkorting */
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['id'] = 'field_vak_afkorting';
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['table'] = 'field_data_field_vak_afkorting';
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['field'] = 'field_vak_afkorting';
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['label'] = '';
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['alter'] ['make_link'] = TRUE;
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['alter'] ['path'] = 'node/[nid]';
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['alter'] ['absolute'] = TRUE;
	$handler->display->display_options ['fields'] ['field_vak_afkorting'] ['element_label_colon'] = FALSE;
	/* Veld: Inhoud: Beschrijving */
	$handler->display->display_options ['fields'] ['field_vak_beschrijving'] ['id'] = 'field_vak_beschrijving';
	$handler->display->display_options ['fields'] ['field_vak_beschrijving'] ['table'] = 'field_data_field_vak_beschrijving';
	$handler->display->display_options ['fields'] ['field_vak_beschrijving'] ['field'] = 'field_vak_beschrijving';
	$handler->display->display_options ['fields'] ['field_vak_beschrijving'] ['label'] = '';
	$handler->display->display_options ['fields'] ['field_vak_beschrijving'] ['element_label_colon'] = FALSE;
	$handler->display->display_options ['defaults'] ['arguments'] = FALSE;
	/* Contextueel filter: Inhoud: Leerkracht (field_uurrooster_les_leerkracht) */
	$handler->display->display_options ['arguments'] ['field_uurrooster_les_leerkracht_target_id'] ['id'] = 'field_uurrooster_les_leerkracht_target_id';
	$handler->display->display_options ['arguments'] ['field_uurrooster_les_leerkracht_target_id'] ['table'] = 'field_data_field_uurrooster_les_leerkracht';
	$handler->display->display_options ['arguments'] ['field_uurrooster_les_leerkracht_target_id'] ['field'] = 'field_uurrooster_les_leerkracht_target_id';
	$handler->display->display_options ['arguments'] ['field_uurrooster_les_leerkracht_target_id'] ['relationship'] = 'reverse_field_uurrooster_les_vak_node';
	$handler->display->display_options ['arguments'] ['field_uurrooster_les_leerkracht_target_id'] ['default_action'] = 'default';
	$handler->display->display_options ['arguments'] ['field_uurrooster_les_leerkracht_target_id'] ['exception'] ['title'] = 'Alle';
	$handler->display->display_options ['arguments'] ['field_uurrooster_les_leerkracht_target_id'] ['default_argument_type'] = 'current_user';
	$handler->display->display_options ['arguments'] ['field_uurrooster_les_leerkracht_target_id'] ['summary'] ['number_of_records'] = '0';
	$handler->display->display_options ['arguments'] ['field_uurrooster_les_leerkracht_target_id'] ['summary'] ['format'] = 'default_summary';
	$handler->display->display_options ['arguments'] ['field_uurrooster_les_leerkracht_target_id'] ['summary_options'] ['items_per_page'] = '25';
	$handler->display->display_options ['defaults'] ['filter_groups'] = FALSE;
	$handler->display->display_options ['defaults'] ['filters'] = FALSE;
	/* Filtercriterium: Inhoud: Gepubliceerd */
	$handler->display->display_options ['filters'] ['status'] ['id'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['status'] ['field'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['value'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['expose'] ['operator'] = FALSE;
	/* Filtercriterium: Inhoud: Type */
	$handler->display->display_options ['filters'] ['type'] ['id'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['type'] ['field'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['value'] = array (
			'vak' => 'vak' 
	);
	$handler->display->display_options ['filters'] ['type'] ['group'] = 1;
	$handler->display->display_options ['qtip_instance'] = 'standaard';
	$translatables ['vakken'] = array (
			t ( 'Master' ),
			t ( 'Vakken' ),
			t ( 'meer' ),
			t ( 'Toepassen' ),
			t ( 'Opnieuw instellen' ),
			t ( 'Sorteren op' ),
			t ( 'Oplopend' ),
			t ( 'Aflopend' ),
			t ( 'Items per pagina' ),
			t ( '- Alle -' ),
			t ( 'Startpunt' ),
			t ( '« eerste' ),
			t ( '‹ vorige' ),
			t ( 'volgende ›' ),
			t ( 'laatste »' ),
			t ( 'Afkorting' ),
			t ( 'Beschrijving' ),
			t ( 'Lokaal' ),
			t ( 'ID (Skore)' ),
			t ( 'ID (Untis)' ),
			t ( 'Overzicht van alle vakken die onderricht worden.' ),
			t ( 'Selectielijst: vakken' ),
			t ( 'Vakken - adminoverzicht' ),
			t ( 'Administratieoverzicht van alle vakken die onderricht worden.' ),
			t ( 'Evaluatie' ),
			t ( 'Selectielijst: vakken - gepersonaliseerd' ),
			t ( 'Inhoud referencing Inhoud from field_uurrooster_les_vak' ),
			t ( 'Alle' ) 
	);
	
	$views [$view->name] = $view;
	return $views;
}