<?php
/*
 * Copyright (C) 2017 bartgysens
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* Drupal Hooks */

/**
 * Implements hook_node_info().
 */
function argus_deliberaties_node_info() {
	$items = array (
			'lvs_deliberatie' => array (
					'name' => t ( 'LVS - Deliberatie' ),
					'base' => 'node_content',
					'description' => t ( 'De <em>deliberatie</em>-gegevens kunnen vanuit Smartschool worden geïmporteerd via de Smartschool Synchronisatie.
Deze gegevens worden gebruikt om het totaalbeeld van de leerling te maken bij het gebruikersprofiel.
Je kan eventueel de gegevens ook manueel bijwerken of ingeven.' ),
					'has_title' => '1',
					'title_label' => t ( 'Titel' ),
					'help' => '' 
			) 
	);
	drupal_alter ( 'node_info', $items );
	return $items;
}

/**
 * Implement hook_form()
 */
function argus_deliberaties_form($node, $form_state) {
	return node_content_form ( $node, $form_state );
}

/**
 * Implementation of hook_views_api().
 */
function argus_deliberaties_views_api() {
	return array (
			'api' => 3.0,
			'path' => drupal_get_path ( 'module', 'argus_deliberaties' ) 
	) // replace demo with your content type
;
}

/**
 * Implementation of hook_views_default_views().
 *
 * Views export creates code that you have to paste in this function.
 *
 * Administration > Structure > Views : click the button behind the view you need and export
 * /admin/structure/views
 */
function argus_deliberaties_views_default_views() {
	$view = new view ();
	$view->name = 'lvs_deliberaties';
	$view->description = '';
	$view->tag = 'default';
	$view->base_table = 'node';
	$view->human_name = 'LVS - Deliberaties';
	$view->core = 7;
	$view->api_version = '3.0';
	$view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */
	
	/* Display: Master */
	$handler = $view->new_display ( 'default', 'Master', 'default' );
	$handler->display->display_options ['title'] = 'LVS - Deliberaties';
	$handler->display->display_options ['use_more_always'] = FALSE;
	$handler->display->display_options ['use_more_text'] = 'meer';
	$handler->display->display_options ['group_by'] = TRUE;
	$handler->display->display_options ['access'] ['type'] = 'perm';
	$handler->display->display_options ['cache'] ['type'] = 'views_content_cache';
	$handler->display->display_options ['cache'] ['results_min_lifespan'] = '-1';
	$handler->display->display_options ['cache'] ['results_max_lifespan'] = '518400';
	$handler->display->display_options ['cache'] ['output_min_lifespan'] = '-1';
	$handler->display->display_options ['cache'] ['output_max_lifespan'] = '518400';
	$handler->display->display_options ['cache'] ['keys'] = array (
			'comment' => array (
					'changed' => 0 
			),
			'node' => array (
					'lvs_deliberatie' => 'lvs_deliberatie' 
			),
			'node_only' => array (
					'node_changed' => 'node_changed' 
			) 
	);
	$handler->display->display_options ['query'] ['type'] = 'views_query';
	$handler->display->display_options ['exposed_form'] ['type'] = 'better_exposed_filters';
	$handler->display->display_options ['exposed_form'] ['options'] ['submit_button'] = 'Toepassen';
	$handler->display->display_options ['exposed_form'] ['options'] ['reset_button'] = TRUE;
	$handler->display->display_options ['exposed_form'] ['options'] ['reset_button_label'] = 'Opnieuw instellen';
	$handler->display->display_options ['exposed_form'] ['options'] ['exposed_sorts_label'] = 'Sorteren op';
	$handler->display->display_options ['exposed_form'] ['options'] ['sort_asc_label'] = 'Oplopend';
	$handler->display->display_options ['exposed_form'] ['options'] ['sort_desc_label'] = 'Aflopend';
	$handler->display->display_options ['exposed_form'] ['options'] ['autosubmit'] = FALSE;
	$handler->display->display_options ['exposed_form'] ['options'] ['bef'] = array (
			'general' => array (
					'allow_secondary' => 0,
					'secondary_label' => 'Uitgebreide opties' 
			),
			'field_lvs_deliberatie_attest_value' => array (
					'bef_format' => 'bef',
					'more_options' => array (
							'bef_select_all_none' => 0,
							'bef_collapsible' => 0,
							'is_secondary' => 0,
							'any_label' => '',
							'bef_filter_description' => '',
							'tokens' => array (
									'available' => array (
											0 => 'global_types' 
									) 
							),
							'rewrite' => array (
									'filter_rewrite_values' => '' 
							) 
					) 
			),
			'field_lvs_deliberatie_klas_target_id' => array (
					'bef_format' => 'default',
					'slider_options' => array (
							'bef_slider_min' => '0',
							'bef_slider_max' => '99999',
							'bef_slider_step' => '1',
							'bef_slider_animate' => '',
							'bef_slider_orientation' => 'horizontal' 
					),
					'more_options' => array (
							'is_secondary' => 0,
							'any_label' => '',
							'bef_filter_description' => '',
							'tokens' => array (
									'available' => array (
											0 => 'global_types' 
									) 
							),
							'rewrite' => array (
									'filter_rewrite_values' => '' 
							) 
					) 
			),
			'field_lvs_deliberatie_leerling_target_id' => array (
					'bef_format' => 'default',
					'slider_options' => array (
							'bef_slider_min' => '0',
							'bef_slider_max' => '99999',
							'bef_slider_step' => '1',
							'bef_slider_animate' => '',
							'bef_slider_orientation' => 'horizontal' 
					),
					'more_options' => array (
							'is_secondary' => 0,
							'any_label' => '',
							'bef_filter_description' => '',
							'tokens' => array (
									'available' => array (
											0 => 'global_types' 
									) 
							),
							'rewrite' => array (
									'filter_rewrite_values' => '' 
							) 
					) 
			),
			'field_lvs_deliberatie_schooljaar_value' => array (
					'bef_format' => 'default',
					'more_options' => array (
							'bef_select_all_none' => FALSE,
							'bef_collapsible' => 0,
							'is_secondary' => 0,
							'any_label' => '',
							'bef_filter_description' => '',
							'tokens' => array (
									'available' => array (
											0 => 'global_types' 
									) 
							),
							'rewrite' => array (
									'filter_rewrite_values' => '' 
							) 
					) 
			) 
	);
	$handler->display->display_options ['pager'] ['type'] = 'full';
	$handler->display->display_options ['pager'] ['options'] ['items_per_page'] = '25';
	$handler->display->display_options ['pager'] ['options'] ['offset'] = '0';
	$handler->display->display_options ['pager'] ['options'] ['id'] = '0';
	$handler->display->display_options ['pager'] ['options'] ['quantity'] = '9';
	$handler->display->display_options ['pager'] ['options'] ['expose'] ['items_per_page_label'] = 'Items per pagina';
	$handler->display->display_options ['pager'] ['options'] ['expose'] ['items_per_page_options_all_label'] = '- Alle -';
	$handler->display->display_options ['pager'] ['options'] ['expose'] ['offset_label'] = 'Startpunt';
	$handler->display->display_options ['pager'] ['options'] ['tags'] ['first'] = '« eerste';
	$handler->display->display_options ['pager'] ['options'] ['tags'] ['previous'] = '‹ vorige';
	$handler->display->display_options ['pager'] ['options'] ['tags'] ['next'] = 'volgende ›';
	$handler->display->display_options ['pager'] ['options'] ['tags'] ['last'] = 'laatste »';
	$handler->display->display_options ['style_plugin'] = 'table';
	$handler->display->display_options ['style_options'] ['grouping'] = array (
			0 => array (
					'field' => 'title',
					'rendered' => 1,
					'rendered_strip' => 0 
			) 
	);
	$handler->display->display_options ['style_options'] ['columns'] = array (
			'title' => 'title',
			'realname' => 'realname',
			'field_lvs_deliberatie_attest' => 'field_lvs_deliberatie_attest',
			'field_lvs_deliberatie_at_uitgest' => 'field_lvs_deliberatie_at_uitgest',
			'field_lvs_deliberatie_diplomas' => 'field_lvs_deliberatie_diplomas',
			'field_lvs_deliberatie_advies' => 'field_lvs_deliberatie_advies',
			'field_lvs_deliberatie_motief' => 'field_lvs_deliberatie_motief',
			'field_lvs_deliberatie_stemming' => 'field_lvs_deliberatie_stemming',
			'field_lvs_deliberatie_waarschuw' => 'field_lvs_deliberatie_waarschuw',
			'field_lvs_deliberatie_vakantie' => 'field_lvs_deliberatie_vakantie' 
	);
	$handler->display->display_options ['style_options'] ['default'] = '-1';
	$handler->display->display_options ['style_options'] ['info'] = array (
			'title' => array (
					'sortable' => 1,
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'realname' => array (
					'sortable' => 1,
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_lvs_deliberatie_attest' => array (
					'sortable' => 1,
					'default_sort_order' => 'asc',
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_lvs_deliberatie_at_uitgest' => array (
					'sortable' => 1,
					'default_sort_order' => 'asc',
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_lvs_deliberatie_diplomas' => array (
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_lvs_deliberatie_advies' => array (
					'sortable' => 1,
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_lvs_deliberatie_motief' => array (
					'sortable' => 1,
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_lvs_deliberatie_stemming' => array (
					'sortable' => 1,
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_lvs_deliberatie_waarschuw' => array (
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_lvs_deliberatie_vakantie' => array (
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			) 
	);
	$handler->display->display_options ['style_options'] ['sticky'] = TRUE;
	/* Kop: Algemeen: Samenvatting van het resultaat */
	$handler->display->display_options ['header'] ['result'] ['id'] = 'result';
	$handler->display->display_options ['header'] ['result'] ['table'] = 'views';
	$handler->display->display_options ['header'] ['result'] ['field'] = 'result';
	$handler->display->display_options ['header'] ['result'] ['content'] = 'Getoond @start - @end van @total';
	/* Relatie: Referentie naar een entiteit: Gerefereerde entiteit */
	$handler->display->display_options ['relationships'] ['field_lvs_deliberatie_leerling_target_id'] ['id'] = 'field_lvs_deliberatie_leerling_target_id';
	$handler->display->display_options ['relationships'] ['field_lvs_deliberatie_leerling_target_id'] ['table'] = 'field_data_field_lvs_deliberatie_leerling';
	$handler->display->display_options ['relationships'] ['field_lvs_deliberatie_leerling_target_id'] ['field'] = 'field_lvs_deliberatie_leerling_target_id';
	/* Relatie: Referentie naar een entiteit: Gerefereerde entiteit */
	$handler->display->display_options ['relationships'] ['field_lvs_deliberatie_klas_target_id'] ['id'] = 'field_lvs_deliberatie_klas_target_id';
	$handler->display->display_options ['relationships'] ['field_lvs_deliberatie_klas_target_id'] ['table'] = 'field_data_field_lvs_deliberatie_klas';
	$handler->display->display_options ['relationships'] ['field_lvs_deliberatie_klas_target_id'] ['field'] = 'field_lvs_deliberatie_klas_target_id';
	/* Veld: Inhoud: Titel */
	$handler->display->display_options ['fields'] ['title'] ['id'] = 'title';
	$handler->display->display_options ['fields'] ['title'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['title'] ['field'] = 'title';
	$handler->display->display_options ['fields'] ['title'] ['relationship'] = 'field_lvs_deliberatie_klas_target_id';
	$handler->display->display_options ['fields'] ['title'] ['label'] = 'Klas';
	$handler->display->display_options ['fields'] ['title'] ['exclude'] = TRUE;
	/* Veld: Echte naam: Werkelijke naam */
	$handler->display->display_options ['fields'] ['realname'] ['id'] = 'realname';
	$handler->display->display_options ['fields'] ['realname'] ['table'] = 'realname';
	$handler->display->display_options ['fields'] ['realname'] ['field'] = 'realname';
	$handler->display->display_options ['fields'] ['realname'] ['relationship'] = 'field_lvs_deliberatie_leerling_target_id';
	$handler->display->display_options ['fields'] ['realname'] ['label'] = 'Leerling';
	/* Veld: Inhoud: Attest */
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_attest'] ['id'] = 'field_lvs_deliberatie_attest';
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_attest'] ['table'] = 'field_data_field_lvs_deliberatie_attest';
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_attest'] ['field'] = 'field_lvs_deliberatie_attest';
	/* Veld: Inhoud: Attest (na uitgestelde proef) */
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_at_uitgest'] ['id'] = 'field_lvs_deliberatie_at_uitgest';
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_at_uitgest'] ['table'] = 'field_data_field_lvs_deliberatie_at_uitgest';
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_at_uitgest'] ['field'] = 'field_lvs_deliberatie_at_uitgest';
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_at_uitgest'] ['label'] = 'Attest (augustus)';
	/* Veld: Inhoud: Diplomas */
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_diplomas'] ['id'] = 'field_lvs_deliberatie_diplomas';
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_diplomas'] ['table'] = 'field_data_field_lvs_deliberatie_diplomas';
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_diplomas'] ['field'] = 'field_lvs_deliberatie_diplomas';
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_diplomas'] ['group_column'] = 'entity_id';
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_diplomas'] ['delta_offset'] = '0';
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_diplomas'] ['separator'] = '<br />';
	/* Veld: Inhoud: Advies */
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_advies'] ['id'] = 'field_lvs_deliberatie_advies';
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_advies'] ['table'] = 'field_data_field_lvs_deliberatie_advies';
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_advies'] ['field'] = 'field_lvs_deliberatie_advies';
	/* Veld: Inhoud: Motief */
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_motief'] ['id'] = 'field_lvs_deliberatie_motief';
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_motief'] ['table'] = 'field_data_field_lvs_deliberatie_motief';
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_motief'] ['field'] = 'field_lvs_deliberatie_motief';
	/* Veld: Inhoud: Stemming */
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_stemming'] ['id'] = 'field_lvs_deliberatie_stemming';
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_stemming'] ['table'] = 'field_data_field_lvs_deliberatie_stemming';
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_stemming'] ['field'] = 'field_lvs_deliberatie_stemming';
	/* Veld: Inhoud: Waarschuwingen */
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_waarschuw'] ['id'] = 'field_lvs_deliberatie_waarschuw';
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_waarschuw'] ['table'] = 'field_data_field_lvs_deliberatie_waarschuw';
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_waarschuw'] ['field'] = 'field_lvs_deliberatie_waarschuw';
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_waarschuw'] ['group_column'] = 'entity_id';
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_waarschuw'] ['delta_offset'] = '0';
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_waarschuw'] ['separator'] = '<br />';
	/* Veld: Inhoud: Vakantietaken */
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_vakantie'] ['id'] = 'field_lvs_deliberatie_vakantie';
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_vakantie'] ['table'] = 'field_data_field_lvs_deliberatie_vakantie';
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_vakantie'] ['field'] = 'field_lvs_deliberatie_vakantie';
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_vakantie'] ['group_column'] = 'entity_id';
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_vakantie'] ['delta_offset'] = '0';
	$handler->display->display_options ['fields'] ['field_lvs_deliberatie_vakantie'] ['separator'] = '<br/>';
	/* Sorteercriterium: Inhoud: Titel */
	$handler->display->display_options ['sorts'] ['title'] ['id'] = 'title';
	$handler->display->display_options ['sorts'] ['title'] ['table'] = 'node';
	$handler->display->display_options ['sorts'] ['title'] ['field'] = 'title';
	$handler->display->display_options ['sorts'] ['title'] ['relationship'] = 'field_lvs_deliberatie_klas_target_id';
	/* Sorteercriterium: Echte naam: Werkelijke naam */
	$handler->display->display_options ['sorts'] ['realname'] ['id'] = 'realname';
	$handler->display->display_options ['sorts'] ['realname'] ['table'] = 'realname';
	$handler->display->display_options ['sorts'] ['realname'] ['field'] = 'realname';
	$handler->display->display_options ['sorts'] ['realname'] ['relationship'] = 'field_lvs_deliberatie_leerling_target_id';
	$handler->display->display_options ['sorts'] ['realname'] ['expose'] ['label'] = 'Werkelijke naam';
	/* Filtercriterium: Inhoud: Gepubliceerd */
	$handler->display->display_options ['filters'] ['status'] ['id'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['status'] ['field'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['value'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['expose'] ['operator'] = FALSE;
	/* Filtercriterium: Inhoud: Type */
	$handler->display->display_options ['filters'] ['type'] ['id'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['type'] ['field'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['value'] = array (
			'lvs_deliberatie' => 'lvs_deliberatie' 
	);
	$handler->display->display_options ['filters'] ['type'] ['group'] = 1;
	/* Filtercriterium: Inhoud: Schooljaar (field_lvs_deliberatie_schooljaar) */
	$handler->display->display_options ['filters'] ['field_lvs_deliberatie_schooljaar_value'] ['id'] = 'field_lvs_deliberatie_schooljaar_value';
	$handler->display->display_options ['filters'] ['field_lvs_deliberatie_schooljaar_value'] ['table'] = 'field_data_field_lvs_deliberatie_schooljaar';
	$handler->display->display_options ['filters'] ['field_lvs_deliberatie_schooljaar_value'] ['field'] = 'field_lvs_deliberatie_schooljaar_value';
	$handler->display->display_options ['filters'] ['field_lvs_deliberatie_schooljaar_value'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['field_lvs_deliberatie_schooljaar_value'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_lvs_deliberatie_schooljaar_value'] ['expose'] ['operator_id'] = 'field_lvs_deliberatie_schooljaar_value_op';
	$handler->display->display_options ['filters'] ['field_lvs_deliberatie_schooljaar_value'] ['expose'] ['label'] = 'Schooljaar (field_lvs_deliberatie_schooljaar)';
	$handler->display->display_options ['filters'] ['field_lvs_deliberatie_schooljaar_value'] ['expose'] ['operator'] = 'field_lvs_deliberatie_schooljaar_value_op';
	$handler->display->display_options ['filters'] ['field_lvs_deliberatie_schooljaar_value'] ['expose'] ['identifier'] = 'field_lvs_deliberatie_schooljaar_value';
	$handler->display->display_options ['filters'] ['field_lvs_deliberatie_schooljaar_value'] ['is_grouped'] = TRUE;
	$handler->display->display_options ['filters'] ['field_lvs_deliberatie_schooljaar_value'] ['group_info'] ['label'] = 'Schooljaar';
	$handler->display->display_options ['filters'] ['field_lvs_deliberatie_schooljaar_value'] ['group_info'] ['identifier'] = 'field_lvs_deliberatie_schooljaar_value';
	$handler->display->display_options ['filters'] ['field_lvs_deliberatie_schooljaar_value'] ['group_info'] ['optional'] = FALSE;
	$handler->display->display_options ['filters'] ['field_lvs_deliberatie_schooljaar_value'] ['group_info'] ['default_group'] = '2';
	$handler->display->display_options ['filters'] ['field_lvs_deliberatie_schooljaar_value'] ['group_info'] ['group_items'] = array (
			1 => array (
					'title' => '2014-2015',
					'operator' => '=',
					'value' => '2014-2015' 
			),
			2 => array (
					'title' => '2013-2014',
					'operator' => '=',
					'value' => '2013-2014' 
			),
			3 => array (
					'title' => '2012-2013',
					'operator' => '=',
					'value' => '2012-2013' 
			),
			4 => array (
					'title' => '2011-2012',
					'operator' => '=',
					'value' => '2011-2012' 
			) 
	);
	/* Filtercriterium: Inhoud: Titel */
	$handler->display->display_options ['filters'] ['title'] ['id'] = 'title';
	$handler->display->display_options ['filters'] ['title'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['title'] ['field'] = 'title';
	$handler->display->display_options ['filters'] ['title'] ['relationship'] = 'field_lvs_deliberatie_klas_target_id';
	$handler->display->display_options ['filters'] ['title'] ['operator'] = 'contains';
	$handler->display->display_options ['filters'] ['title'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['title'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['title'] ['expose'] ['operator_id'] = 'title_op';
	$handler->display->display_options ['filters'] ['title'] ['expose'] ['label'] = 'Klas';
	$handler->display->display_options ['filters'] ['title'] ['expose'] ['operator'] = 'title_op';
	$handler->display->display_options ['filters'] ['title'] ['expose'] ['identifier'] = 'title';
	$handler->display->display_options ['filters'] ['title'] ['expose'] ['remember_roles'] = array ();
	/* Filtercriterium: Gebruiker: Naam (onbewerkt) */
	$handler->display->display_options ['filters'] ['name'] ['id'] = 'name';
	$handler->display->display_options ['filters'] ['name'] ['table'] = 'users';
	$handler->display->display_options ['filters'] ['name'] ['field'] = 'name';
	$handler->display->display_options ['filters'] ['name'] ['relationship'] = 'field_lvs_deliberatie_leerling_target_id';
	$handler->display->display_options ['filters'] ['name'] ['operator'] = 'contains';
	$handler->display->display_options ['filters'] ['name'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['name'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['name'] ['expose'] ['operator_id'] = 'name_op';
	$handler->display->display_options ['filters'] ['name'] ['expose'] ['label'] = 'Leerling';
	$handler->display->display_options ['filters'] ['name'] ['expose'] ['operator'] = 'name_op';
	$handler->display->display_options ['filters'] ['name'] ['expose'] ['identifier'] = 'name';
	$handler->display->display_options ['filters'] ['name'] ['expose'] ['remember_roles'] = array ();
	/* Filtercriterium: Inhoud: Attest (field_lvs_deliberatie_attest) */
	$handler->display->display_options ['filters'] ['field_lvs_deliberatie_attest_value'] ['id'] = 'field_lvs_deliberatie_attest_value';
	$handler->display->display_options ['filters'] ['field_lvs_deliberatie_attest_value'] ['table'] = 'field_data_field_lvs_deliberatie_attest';
	$handler->display->display_options ['filters'] ['field_lvs_deliberatie_attest_value'] ['field'] = 'field_lvs_deliberatie_attest_value';
	$handler->display->display_options ['filters'] ['field_lvs_deliberatie_attest_value'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['field_lvs_deliberatie_attest_value'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_lvs_deliberatie_attest_value'] ['expose'] ['operator_id'] = 'field_lvs_deliberatie_attest_value_op';
	$handler->display->display_options ['filters'] ['field_lvs_deliberatie_attest_value'] ['expose'] ['label'] = 'Attest';
	$handler->display->display_options ['filters'] ['field_lvs_deliberatie_attest_value'] ['expose'] ['operator'] = 'field_lvs_deliberatie_attest_value_op';
	$handler->display->display_options ['filters'] ['field_lvs_deliberatie_attest_value'] ['expose'] ['identifier'] = 'field_lvs_deliberatie_attest_value';
	$handler->display->display_options ['filters'] ['field_lvs_deliberatie_attest_value'] ['expose'] ['multiple'] = TRUE;
	$handler->display->display_options ['filters'] ['field_lvs_deliberatie_attest_value'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['filters'] ['field_lvs_deliberatie_attest_value'] ['reduce_duplicates'] = TRUE;
	
	/* Display: LVS - Deliberaties */
	$handler = $view->new_display ( 'page', 'LVS - Deliberaties', 'deliberaties_overzicht' );
	$handler->display->display_options ['display_description'] = 'Overzicht van de behaalde diploma\'s, attesten, vakantietaken en andere deliberatiegegevens.';
	$handler->display->display_options ['exposed_block'] = TRUE;
	$handler->display->display_options ['path'] = 'deliberaties/overzicht';
	$handler->display->display_options ['menu'] ['type'] = 'normal';
	$handler->display->display_options ['menu'] ['title'] = 'Deliberaties';
	if (menu_load ( 'menu-modules' )) {
		$menu = 'menu-modules';
	} else {
		$menu = 'navigation';
	}
	$handler->display->display_options ['menu'] ['name'] = $menu;
	$translatables ['lvs_deliberaties'] = array (
			t ( 'Master' ),
			t ( 'LVS - Deliberaties' ),
			t ( 'meer' ),
			t ( 'Toepassen' ),
			t ( 'Opnieuw instellen' ),
			t ( 'Sorteren op' ),
			t ( 'Oplopend' ),
			t ( 'Aflopend' ),
			t ( 'Uitgebreide opties' ),
			t ( 'Items per pagina' ),
			t ( '- Alle -' ),
			t ( 'Startpunt' ),
			t ( '« eerste' ),
			t ( '‹ vorige' ),
			t ( 'volgende ›' ),
			t ( 'laatste »' ),
			t ( 'Getoond @start - @end van @total' ),
			t ( 'Gebruiker entiteit gerefereerd vanaf field_lvs_deliberatie_leerling' ),
			t ( 'Inhoud entiteit gerefereerd vanaf field_lvs_deliberatie_klas' ),
			t ( 'Klas' ),
			t ( 'Leerling' ),
			t ( 'Attest' ),
			t ( 'Attest (augustus)' ),
			t ( 'Diplomas' ),
			t ( 'Advies' ),
			t ( 'Motief' ),
			t ( 'Stemming' ),
			t ( 'Waarschuwingen' ),
			t ( 'Vakantietaken' ),
			t ( 'Werkelijke naam' ),
			t ( 'Schooljaar (field_lvs_deliberatie_schooljaar)' ),
			t ( 'Schooljaar' ),
			t ( 'Overzicht van de behaalde diploma\'s, attesten, vakantietaken en andere deliberatiegegevens.' ) 
	);
	
	$views [$view->name] = $view;
	return $views;
}