<?php
/**
 * @file
 * argus_acties.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function argus_acties_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_status'.
  $field_bases['field_status'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_status',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'nieuw' => 'nieuw',
        'in behandeling' => 'in behandeling',
        'afgehandeld' => 'afgehandeld',
        'geannuleerd' => 'geannuleerd',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  return $field_bases;
}
