<?php
/*
 * Copyright (C) 2016 bartgysens
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* Drupal Hooks */

/**
 * Implements argus_hrm_menu().
 */
function argus_hrm_menu() {
	if (menu_load('menu-modules')){
		$menu = 'menu-modules';
	} else {
		$menu = 'navigation';
	}
	
	$items = array ();
	$items ['admin/config/argus/hrm'] = array (
			'title' => 'HRM: workload',
			'description' => 'Parameters instellen voor het berekenen van de workload per personeelslid',
			'page callback' => 'drupal_get_form',
			'page arguments' => array (
					'argus_hrm_workload_setup_form' 
			),
			'access arguments' => array (
					'access administration pages' 
			),
			'type' => MENU_NORMAL_ITEM,
			'weight' => 1 
	);
	$items ['hrm/workload'] = array (
			'title' => t ( 'Belasting' ),
			'description' => 'Bereken hoeveel elk personeelslid wordt ingeschakeld per functie.',
			'page callback' => 'argus_hrm_workload_overview',
			'access arguments' => array (
					'access argus_hrm content' 
			),
			'type' => MENU_NORMAL_ITEM,
			'menu_name' => $menu 
	);
	return $items;
}

/**
 * Implement hook_theme()
 */
function argus_hrm_theme() {
	return array (
			'argus_hrm--overview_workload' => array (
					'template' => 'templates/argus_hrm--overview_workload' 
			) 
	);
}

/**
 * Implements hook_permission().
 */
function argus_hrm_permission() {
	return array (
			'access argus_hrm content' => array (
					'title' => t ( 'Belasting van personeelsleden bekijken' ) 
			) 
	);
}

/**
 * Implements hook_ctools_plugin_api().
 */
function argus_hrm_ctools_plugin_api($module = NULL, $api = NULL) {
	// paste all plugins which are used for your Features based module version
	if ($module == "field_group" && $api == "field_group") {
		return array (
				"version" => "1" 
		);
	}
}

/**
 * Implements hook_node_info()
 */
function argus_hrm_node_info() {
	$items = array (
			'hrm_evaluatiegesprek' => array (
					'name' => t ( 'HRM - Evaluatiegesprek' ),
					'base' => 'node_content',
					'description' => t ( 'Stel een gedetailleerde beoordeling op van je personeelslid aan de hand van het <em>evaluatiegesprek</em>.' ),
					'has_title' => '1',
					'title_label' => t ( 'Title' ),
					'help' => '' 
			),
			'hrm_flitsbezoek' => array (
					'name' => t ( 'HRM - Flitsbezoek' ),
					'base' => 'node_content',
					'description' => t ( 'Tijdens een flitsbezoek richt u zich op de onderwijspraktijk van de leraar: welke keuzes en beslissingen maakt de leraar met betrekking tot de activiteiten en interventies in relatie tot het leerdoel? Met de daaraan gekoppelde reflectieve dialoog ontwikkelt u bij de leraar een reflectieve houding. U stimuleert de leraar om bewust na te denken over zijn onderwijspraktijk en over zijn eigen gedrag. Hierdoor ontstaat een continue cyclus van zelfanalyse en verbetering. Flitsbezoek levert een positieve bijdrage aan uw onderwijskundig leiderschap en aan het handelen van de leraren.' ),
					'has_title' => '1',
					'title_label' => t ( 'Title' ),
					'help' => '' 
			),
			'hrm_functioneringsgesprek' => array (
					'name' => t ( 'HRM - Functioneringsgesprek' ),
					'base' => 'node_content',
					'description' => t ( 'Om je personeelslid goed te kunnen begeleiden, worden afspraken geformaliseerd tijdens een <em>functioneringsgesprek</em>.' ),
					'has_title' => '1',
					'title_label' => t ( 'Title' ),
					'help' => '' 
			),
			'hrm_klasbezoek' => array (
					'name' => t ( 'HRM - Klasbezoek' ),
					'base' => 'node_content',
					'description' => t ( 'Begeleid je medewerkers via een <em>klasbezoek</em>; aan de hand van een structuur gebaseerd op de DOKK-tool. Dit is geen evaluatie-instrument, maar legt de nadruk op observeren, analyseren en feedback geven in een ontwikkelend perspectief. De professionele ontwikkeling van de leerkracht staat centraal, niet de evaluatie. (http://pro.g-o.be/blog/Documents/20150305_DOKK-tool_so.pdf)' ),
					'has_title' => '1',
					'title_label' => t ( 'Title' ),
					'help' => '' 
			),
			'hrm_planningsgesprek' => array (
					'name' => t ( 'HRM - Planningsgesprek' ),
					'base' => 'node_content',
					'description' => t ( 'Als onderdeel van het evaluatietraject van personeelsleden, is het <em>planningsgesprek</em> de eerste stap in de start van deze procedure.' ),
					'has_title' => '1',
					'title_label' => t ( 'Title' ),
					'help' => '' 
			) 
	);
	drupal_alter ( 'node_info', $items );
	return $items;
}

/**
 * Implement hook_form()
 */
function argus_hrm_form($node, $form_state) {
	return node_content_form ( $node, $form_state );
}

/**
 * Implementation of hook_views_api().
 */
function argus_hrm_views_api() {
	return array (
			'api' => 3.0,
			'path' => drupal_get_path ( 'module', 'argus_hrm' ) 
	) // replace demo with your content type
;
}

/**
 * Implementation of hook_views_default_views().
 *
 * Views export creates code that you have to paste in this function.
 *
 * Administration > Structure > Views : click the button behind the view you need and export
 * /admin/structure/views
 */
function argus_hrm_views_default_views() {
	$view = new view ();
	$view->name = 'hrm';
	$view->description = '';
	$view->tag = 'default';
	$view->base_table = 'node';
	$view->human_name = 'HRM';
	$view->core = 7;
	$view->api_version = '3.0';
	$view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */
	
	/* Display: Master */
	$handler = $view->new_display ( 'default', 'Master', 'default' );
	$handler->display->display_options ['title'] = 'HRM';
	$handler->display->display_options ['use_more_always'] = FALSE;
	$handler->display->display_options ['use_more_text'] = 'meer';
	$handler->display->display_options ['access'] ['type'] = 'role';
	$handler->display->display_options ['access'] ['role'] = array ();
	$handler->display->display_options ['cache'] ['type'] = 'views_content_cache';
	$handler->display->display_options ['cache'] ['results_min_lifespan'] = '-1';
	$handler->display->display_options ['cache'] ['results_max_lifespan'] = '518400';
	$handler->display->display_options ['cache'] ['output_min_lifespan'] = '-1';
	$handler->display->display_options ['cache'] ['output_max_lifespan'] = '518400';
	$handler->display->display_options ['cache'] ['keys'] = array (
			'comment' => array (
					'changed' => 0 
			),
			'node' => array (
					'hrm_klasbezoek' => 'hrm_klasbezoek',
					'hrm_evaluatiegesprek' => 'hrm_evaluatiegesprek',
					'hrm_flitsbezoek' => 'hrm_flitsbezoek',
					'hrm_functioneringsgesprek' => 'hrm_functioneringsgesprek',
					'hrm_planningsgesprek' => 'hrm_planningsgesprek' 
			),
			'node_only' => array (
					'node_changed' => 'node_changed' 
			) 
	);
	$handler->display->display_options ['query'] ['type'] = 'views_query';
	$handler->display->display_options ['exposed_form'] ['type'] = 'basic';
	$handler->display->display_options ['exposed_form'] ['options'] ['submit_button'] = 'Toepassen';
	$handler->display->display_options ['exposed_form'] ['options'] ['reset_button'] = TRUE;
	$handler->display->display_options ['exposed_form'] ['options'] ['reset_button_label'] = 'Opnieuw instellen';
	$handler->display->display_options ['exposed_form'] ['options'] ['exposed_sorts_label'] = 'Sorteren op';
	$handler->display->display_options ['exposed_form'] ['options'] ['sort_asc_label'] = 'Oplopend';
	$handler->display->display_options ['exposed_form'] ['options'] ['sort_desc_label'] = 'Aflopend';
	$handler->display->display_options ['exposed_form'] ['options'] ['autosubmit'] = FALSE;
	$handler->display->display_options ['pager'] ['type'] = 'full';
	$handler->display->display_options ['pager'] ['options'] ['items_per_page'] = '50';
	$handler->display->display_options ['pager'] ['options'] ['expose'] ['items_per_page_label'] = 'Items per pagina';
	$handler->display->display_options ['pager'] ['options'] ['expose'] ['items_per_page_options_all_label'] = '- Alle -';
	$handler->display->display_options ['pager'] ['options'] ['expose'] ['offset_label'] = 'Startpunt';
	$handler->display->display_options ['pager'] ['options'] ['tags'] ['first'] = '« eerste';
	$handler->display->display_options ['pager'] ['options'] ['tags'] ['previous'] = '‹ vorige';
	$handler->display->display_options ['pager'] ['options'] ['tags'] ['next'] = 'volgende ›';
	$handler->display->display_options ['pager'] ['options'] ['tags'] ['last'] = 'laatste »';
	$handler->display->display_options ['style_plugin'] = 'table';
	$handler->display->display_options ['style_options'] ['columns'] = array (
			'nid' => 'nid',
			'counter' => 'counter',
			'field_personeelslid' => 'field_personeelslid',
			'field_tijdstip' => 'field_tijdstip',
			'field_functioneringsg_status' => 'field_functioneringsg_status',
			'field_planningsgesprek_status_1' => 'field_planningsgesprek_status_1',
			'field_evaluatiegesprek_status' => 'field_evaluatiegesprek_status',
			'nothing_1' => 'nothing_1',
			'type' => 'type',
			'edit_node' => 'edit_node',
			'nothing' => 'nothing' 
	);
	$handler->display->display_options ['style_options'] ['default'] = '-1';
	$handler->display->display_options ['style_options'] ['info'] = array (
			'nid' => array (
					'sortable' => 0,
					'default_sort_order' => 'asc',
					'align' => '',
					'separator' => '',
					'empty_column' => 0 
			),
			'counter' => array (
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_personeelslid' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_tijdstip' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_functioneringsg_status' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_planningsgesprek_status_1' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_evaluatiegesprek_status' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			),
			'nothing_1' => array (
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			),
			'type' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			),
			'edit_node' => array (
					'align' => 'views-align-right',
					'separator' => '',
					'empty_column' => 0 
			),
			'nothing' => array (
					'align' => 'views-align-right',
					'separator' => '',
					'empty_column' => 0 
			) 
	);
	$handler->display->display_options ['style_options'] ['sticky'] = TRUE;
	/* Kop: Algemeen: Tekstveld */
	$handler->display->display_options ['header'] ['area'] ['id'] = 'area';
	$handler->display->display_options ['header'] ['area'] ['table'] = 'views';
	$handler->display->display_options ['header'] ['area'] ['field'] = 'area';
	$handler->display->display_options ['header'] ['area'] ['empty'] = TRUE;
	$handler->display->display_options ['header'] ['area'] ['content'] = '<a href="/node/add/hrm-evaluatiegesprek">Een evaluatiegesprek toevoegen</a>';
	$handler->display->display_options ['header'] ['area'] ['format'] = 'filtered_html';
	/* Voet: Algemeen: Samenvatting van het resultaat */
	$handler->display->display_options ['footer'] ['result'] ['id'] = 'result';
	$handler->display->display_options ['footer'] ['result'] ['table'] = 'views';
	$handler->display->display_options ['footer'] ['result'] ['field'] = 'result';
	$handler->display->display_options ['footer'] ['result'] ['content'] = 'Getoond @start - @end van @total';
	/* Voet: Algemeen: Tekstveld */
	$handler->display->display_options ['footer'] ['area'] ['id'] = 'area';
	$handler->display->display_options ['footer'] ['area'] ['table'] = 'views';
	$handler->display->display_options ['footer'] ['area'] ['field'] = 'area';
	$handler->display->display_options ['footer'] ['area'] ['content'] = '<a href="/node/add/hrm-evaluatiegesprek">Een evaluatiegesprek toevoegen</a>';
	$handler->display->display_options ['footer'] ['area'] ['format'] = 'filtered_html';
	/* Relatie: Referentie naar een entiteit: Gerefereerde entiteit */
	$handler->display->display_options ['relationships'] ['field_personeelslid_target_id'] ['id'] = 'field_personeelslid_target_id';
	$handler->display->display_options ['relationships'] ['field_personeelslid_target_id'] ['table'] = 'field_data_field_personeelslid';
	$handler->display->display_options ['relationships'] ['field_personeelslid_target_id'] ['field'] = 'field_personeelslid_target_id';
	/* Veld: Inhoud: Nid */
	$handler->display->display_options ['fields'] ['nid'] ['id'] = 'nid';
	$handler->display->display_options ['fields'] ['nid'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['nid'] ['field'] = 'nid';
	$handler->display->display_options ['fields'] ['nid'] ['label'] = '';
	$handler->display->display_options ['fields'] ['nid'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['nid'] ['element_label_colon'] = FALSE;
	/* Veld: Algemeen: Resultatenteller weergeven */
	$handler->display->display_options ['fields'] ['counter'] ['id'] = 'counter';
	$handler->display->display_options ['fields'] ['counter'] ['table'] = 'views';
	$handler->display->display_options ['fields'] ['counter'] ['field'] = 'counter';
	$handler->display->display_options ['fields'] ['counter'] ['label'] = 'Nr.';
	$handler->display->display_options ['fields'] ['counter'] ['counter_start'] = '1';
	$handler->display->display_options ['fields'] ['counter'] ['reverse'] = 0;
	/* Veld: Inhoud: Personeelslid */
	$handler->display->display_options ['fields'] ['field_personeelslid'] ['id'] = 'field_personeelslid';
	$handler->display->display_options ['fields'] ['field_personeelslid'] ['table'] = 'field_data_field_personeelslid';
	$handler->display->display_options ['fields'] ['field_personeelslid'] ['field'] = 'field_personeelslid';
	$handler->display->display_options ['fields'] ['field_personeelslid'] ['settings'] = array (
			'link' => '1',
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Inhoud: Tijdstip */
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['id'] = 'field_tijdstip';
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['table'] = 'field_data_field_tijdstip';
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['field'] = 'field_tijdstip';
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['alter'] ['alter_text'] = TRUE;
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['alter'] ['make_link'] = TRUE;
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['alter'] ['path'] = 'node/[nid]';
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['alter'] ['absolute'] = TRUE;
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['settings'] = array (
			'format_type' => 'long',
			'fromto' => 'both',
			'multiple_number' => '',
			'multiple_from' => '',
			'multiple_to' => '',
			'show_remaining_days' => 0,
			'show_repeat_rule' => 'show',
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: status - functioneringsgesprek */
	$handler->display->display_options ['fields'] ['field_functioneringsg_status'] ['id'] = 'field_functioneringsg_status';
	$handler->display->display_options ['fields'] ['field_functioneringsg_status'] ['table'] = 'field_data_field_functioneringsg_status';
	$handler->display->display_options ['fields'] ['field_functioneringsg_status'] ['field'] = 'field_functioneringsg_status';
	$handler->display->display_options ['fields'] ['field_functioneringsg_status'] ['ui_name'] = 'status - functioneringsgesprek';
	$handler->display->display_options ['fields'] ['field_functioneringsg_status'] ['label'] = '';
	$handler->display->display_options ['fields'] ['field_functioneringsg_status'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['field_functioneringsg_status'] ['element_label_colon'] = FALSE;
	$handler->display->display_options ['fields'] ['field_functioneringsg_status'] ['settings'] = array (
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: status - planningsgesprek */
	$handler->display->display_options ['fields'] ['field_planningsgesprek_status_1'] ['id'] = 'field_planningsgesprek_status_1';
	$handler->display->display_options ['fields'] ['field_planningsgesprek_status_1'] ['table'] = 'field_data_field_planningsgesprek_status';
	$handler->display->display_options ['fields'] ['field_planningsgesprek_status_1'] ['field'] = 'field_planningsgesprek_status';
	$handler->display->display_options ['fields'] ['field_planningsgesprek_status_1'] ['ui_name'] = 'status - planningsgesprek';
	$handler->display->display_options ['fields'] ['field_planningsgesprek_status_1'] ['label'] = '';
	$handler->display->display_options ['fields'] ['field_planningsgesprek_status_1'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['field_planningsgesprek_status_1'] ['element_label_colon'] = FALSE;
	$handler->display->display_options ['fields'] ['field_planningsgesprek_status_1'] ['settings'] = array (
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: status - evaluatiegesprek */
	$handler->display->display_options ['fields'] ['field_evaluatiegesprek_status'] ['id'] = 'field_evaluatiegesprek_status';
	$handler->display->display_options ['fields'] ['field_evaluatiegesprek_status'] ['table'] = 'field_data_field_evaluatiegesprek_status';
	$handler->display->display_options ['fields'] ['field_evaluatiegesprek_status'] ['field'] = 'field_evaluatiegesprek_status';
	$handler->display->display_options ['fields'] ['field_evaluatiegesprek_status'] ['ui_name'] = 'status - evaluatiegesprek';
	$handler->display->display_options ['fields'] ['field_evaluatiegesprek_status'] ['label'] = '';
	$handler->display->display_options ['fields'] ['field_evaluatiegesprek_status'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['field_evaluatiegesprek_status'] ['element_label_colon'] = FALSE;
	$handler->display->display_options ['fields'] ['field_evaluatiegesprek_status'] ['settings'] = array (
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Algemeen: Aangepaste tekst */
	$handler->display->display_options ['fields'] ['nothing_1'] ['id'] = 'nothing_1';
	$handler->display->display_options ['fields'] ['nothing_1'] ['table'] = 'views';
	$handler->display->display_options ['fields'] ['nothing_1'] ['field'] = 'nothing';
	$handler->display->display_options ['fields'] ['nothing_1'] ['label'] = 'Status';
	$handler->display->display_options ['fields'] ['nothing_1'] ['alter'] ['text'] = '[field_functioneringsg_status][field_planningsgesprek_status_1][field_evaluatiegesprek_status]';
	/* Veld: Inhoud: Type */
	$handler->display->display_options ['fields'] ['type'] ['id'] = 'type';
	$handler->display->display_options ['fields'] ['type'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['type'] ['field'] = 'type';
	/* Veld: Inhoud: Bewerkingslink */
	$handler->display->display_options ['fields'] ['edit_node'] ['id'] = 'edit_node';
	$handler->display->display_options ['fields'] ['edit_node'] ['table'] = 'views_entity_node';
	$handler->display->display_options ['fields'] ['edit_node'] ['field'] = 'edit_node';
	$handler->display->display_options ['fields'] ['edit_node'] ['label'] = '';
	$handler->display->display_options ['fields'] ['edit_node'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['edit_node'] ['element_label_colon'] = FALSE;
	/* Veld: Algemeen: Aangepaste tekst */
	$handler->display->display_options ['fields'] ['nothing'] ['id'] = 'nothing';
	$handler->display->display_options ['fields'] ['nothing'] ['table'] = 'views';
	$handler->display->display_options ['fields'] ['nothing'] ['field'] = 'nothing';
	$handler->display->display_options ['fields'] ['nothing'] ['label'] = 'Acties';
	$handler->display->display_options ['fields'] ['nothing'] ['alter'] ['text'] = '[edit_node] - <a href="/documenten_generator.get/BRF_HRM_Planningsgesprek_uitnodiging/id=[nid]">uitnodiging</a> - <a href="/documenten_generator.get/VSG_HRM_Planningsgesprek/id=[nid]">verslag</a>';
	/* Sorteercriterium: Inhoud: Datum van inzending */
	$handler->display->display_options ['sorts'] ['created'] ['id'] = 'created';
	$handler->display->display_options ['sorts'] ['created'] ['table'] = 'node';
	$handler->display->display_options ['sorts'] ['created'] ['field'] = 'created';
	$handler->display->display_options ['sorts'] ['created'] ['order'] = 'DESC';
	/* Filtercriterium: Inhoud: Gepubliceerd */
	$handler->display->display_options ['filters'] ['status'] ['id'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['status'] ['field'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['value'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['expose'] ['operator'] = FALSE;
	/* Filtercriterium: Inhoud: Type */
	$handler->display->display_options ['filters'] ['type'] ['id'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['type'] ['field'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['value'] = array (
			'hrm_evaluatiegesprek' => 'hrm_evaluatiegesprek',
			'hrm_functioneringsgesprek' => 'hrm_functioneringsgesprek',
			'hrm_planningsgesprek' => 'hrm_planningsgesprek' 
	);
	/* Filtercriterium: Echte naam: Naam */
	$handler->display->display_options ['filters'] ['realname'] ['id'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['table'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['field'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['relationship'] = 'field_personeelslid_target_id';
	$handler->display->display_options ['filters'] ['realname'] ['operator'] = 'contains';
	$handler->display->display_options ['filters'] ['realname'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['operator_id'] = 'realname_op';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['label'] = 'Personeelslid';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['operator'] = 'realname_op';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['identifier'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_items'] = '10';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_min_chars'] = '0';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_raw_suggestion'] = '1';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_raw_dropdown'] = '1';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_dependent'] = 0;
	$handler->display->display_options ['qtip_instance'] = 'standaard';
	
	/* Display: Planningsgesprekken */
	$handler = $view->new_display ( 'page', 'Planningsgesprekken', 'hrm_planningsgesprekken_overview' );
	$handler->display->display_options ['defaults'] ['title'] = FALSE;
	$handler->display->display_options ['title'] = 'Planningsgesprekken';
	$handler->display->display_options ['defaults'] ['style_plugin'] = FALSE;
	$handler->display->display_options ['style_plugin'] = 'table';
	$handler->display->display_options ['style_options'] ['columns'] = array (
			'counter' => 'counter',
			'field_personeelslid' => 'field_personeelslid',
			'field_tijdstip' => 'field_tijdstip',
			'field_planningsgesprek_status' => 'field_planningsgesprek_status',
			'type' => 'type',
			'nid' => 'nid',
			'edit_node' => 'edit_node',
			'nothing' => 'nothing' 
	);
	$handler->display->display_options ['style_options'] ['default'] = '-1';
	$handler->display->display_options ['style_options'] ['info'] = array (
			'counter' => array (
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_personeelslid' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_tijdstip' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_planningsgesprek_status' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			),
			'type' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			),
			'nid' => array (
					'sortable' => 0,
					'default_sort_order' => 'asc',
					'align' => '',
					'separator' => '',
					'empty_column' => 0 
			),
			'edit_node' => array (
					'align' => '',
					'separator' => '',
					'empty_column' => 0 
			),
			'nothing' => array (
					'align' => 'views-align-right',
					'separator' => '',
					'empty_column' => 0 
			) 
	);
	$handler->display->display_options ['style_options'] ['sticky'] = TRUE;
	$handler->display->display_options ['defaults'] ['style_options'] = FALSE;
	$handler->display->display_options ['defaults'] ['row_plugin'] = FALSE;
	$handler->display->display_options ['defaults'] ['row_options'] = FALSE;
	$handler->display->display_options ['exposed_block'] = TRUE;
	$handler->display->display_options ['defaults'] ['header'] = FALSE;
	/* Kop: Algemeen: Tekstveld */
	$handler->display->display_options ['header'] ['area'] ['id'] = 'area';
	$handler->display->display_options ['header'] ['area'] ['table'] = 'views';
	$handler->display->display_options ['header'] ['area'] ['field'] = 'area';
	$handler->display->display_options ['header'] ['area'] ['empty'] = TRUE;
	$handler->display->display_options ['header'] ['area'] ['content'] = '<a href="/node/add/hrm-planningsgesprek">Een planningsgesprek toevoegen</a>';
	$handler->display->display_options ['header'] ['area'] ['format'] = 'filtered_html';
	$handler->display->display_options ['defaults'] ['footer'] = FALSE;
	/* Voet: Algemeen: Samenvatting van het resultaat */
	$handler->display->display_options ['footer'] ['result'] ['id'] = 'result';
	$handler->display->display_options ['footer'] ['result'] ['table'] = 'views';
	$handler->display->display_options ['footer'] ['result'] ['field'] = 'result';
	$handler->display->display_options ['footer'] ['result'] ['content'] = 'Getoond @start - @end van @total';
	/* Voet: Algemeen: Tekstveld */
	$handler->display->display_options ['footer'] ['area'] ['id'] = 'area';
	$handler->display->display_options ['footer'] ['area'] ['table'] = 'views';
	$handler->display->display_options ['footer'] ['area'] ['field'] = 'area';
	$handler->display->display_options ['footer'] ['area'] ['content'] = '<a href="/node/add/hrm-planningsgesprek">Een planningsgesprek toevoegen</a>';
	$handler->display->display_options ['footer'] ['area'] ['format'] = 'filtered_html';
	$handler->display->display_options ['defaults'] ['fields'] = FALSE;
	/* Veld: Inhoud: Nid */
	$handler->display->display_options ['fields'] ['nid'] ['id'] = 'nid';
	$handler->display->display_options ['fields'] ['nid'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['nid'] ['field'] = 'nid';
	$handler->display->display_options ['fields'] ['nid'] ['label'] = '';
	$handler->display->display_options ['fields'] ['nid'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['nid'] ['element_label_colon'] = FALSE;
	/* Veld: Algemeen: Resultatenteller weergeven */
	$handler->display->display_options ['fields'] ['counter'] ['id'] = 'counter';
	$handler->display->display_options ['fields'] ['counter'] ['table'] = 'views';
	$handler->display->display_options ['fields'] ['counter'] ['field'] = 'counter';
	$handler->display->display_options ['fields'] ['counter'] ['label'] = 'Nr.';
	$handler->display->display_options ['fields'] ['counter'] ['counter_start'] = '1';
	$handler->display->display_options ['fields'] ['counter'] ['reverse'] = 0;
	/* Veld: Inhoud: Personeelslid */
	$handler->display->display_options ['fields'] ['field_personeelslid'] ['id'] = 'field_personeelslid';
	$handler->display->display_options ['fields'] ['field_personeelslid'] ['table'] = 'field_data_field_personeelslid';
	$handler->display->display_options ['fields'] ['field_personeelslid'] ['field'] = 'field_personeelslid';
	$handler->display->display_options ['fields'] ['field_personeelslid'] ['settings'] = array (
			'link' => '1',
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Inhoud: Tijdstip */
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['id'] = 'field_tijdstip';
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['table'] = 'field_data_field_tijdstip';
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['field'] = 'field_tijdstip';
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['alter'] ['alter_text'] = TRUE;
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['alter'] ['make_link'] = TRUE;
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['alter'] ['path'] = 'node/[nid]';
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['alter'] ['absolute'] = TRUE;
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['settings'] = array (
			'format_type' => 'long',
			'fromto' => 'both',
			'multiple_number' => '',
			'multiple_from' => '',
			'multiple_to' => '',
			'show_remaining_days' => 0,
			'show_repeat_rule' => 'show',
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Inhoud: Status */
	$handler->display->display_options ['fields'] ['field_planningsgesprek_status'] ['id'] = 'field_planningsgesprek_status';
	$handler->display->display_options ['fields'] ['field_planningsgesprek_status'] ['table'] = 'field_data_field_planningsgesprek_status';
	$handler->display->display_options ['fields'] ['field_planningsgesprek_status'] ['field'] = 'field_planningsgesprek_status';
	$handler->display->display_options ['fields'] ['field_planningsgesprek_status'] ['settings'] = array (
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Inhoud: Type */
	$handler->display->display_options ['fields'] ['type'] ['id'] = 'type';
	$handler->display->display_options ['fields'] ['type'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['type'] ['field'] = 'type';
	/* Veld: Inhoud: Bewerkingslink */
	$handler->display->display_options ['fields'] ['edit_node'] ['id'] = 'edit_node';
	$handler->display->display_options ['fields'] ['edit_node'] ['table'] = 'views_entity_node';
	$handler->display->display_options ['fields'] ['edit_node'] ['field'] = 'edit_node';
	$handler->display->display_options ['fields'] ['edit_node'] ['label'] = '';
	$handler->display->display_options ['fields'] ['edit_node'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['edit_node'] ['element_label_colon'] = FALSE;
	/* Veld: Algemeen: Aangepaste tekst */
	$handler->display->display_options ['fields'] ['nothing'] ['id'] = 'nothing';
	$handler->display->display_options ['fields'] ['nothing'] ['table'] = 'views';
	$handler->display->display_options ['fields'] ['nothing'] ['field'] = 'nothing';
	$handler->display->display_options ['fields'] ['nothing'] ['label'] = 'Acties';
	$handler->display->display_options ['fields'] ['nothing'] ['alter'] ['text'] = '[edit_node] - <a href="/documenten_generator.get/BRF_HRM_Planningsgesprek_uitnodiging/id=[nid]">uitnodiging</a> - <a href="/documenten_generator.get/VSG_HRM_Planningsgesprek/id=[nid]">verslag</a>';
	$handler->display->display_options ['defaults'] ['filter_groups'] = FALSE;
	$handler->display->display_options ['defaults'] ['filters'] = FALSE;
	/* Filtercriterium: Inhoud: Gepubliceerd */
	$handler->display->display_options ['filters'] ['status'] ['id'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['status'] ['field'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['value'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['expose'] ['operator'] = FALSE;
	/* Filtercriterium: Inhoud: Type */
	$handler->display->display_options ['filters'] ['type'] ['id'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['type'] ['field'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['value'] = array (
			'hrm_planningsgesprek' => 'hrm_planningsgesprek' 
	);
	/* Filtercriterium: Echte naam: Naam */
	$handler->display->display_options ['filters'] ['realname'] ['id'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['table'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['field'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['relationship'] = 'field_personeelslid_target_id';
	$handler->display->display_options ['filters'] ['realname'] ['operator'] = 'contains';
	$handler->display->display_options ['filters'] ['realname'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['operator_id'] = 'realname_op';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['label'] = 'Personeelslid';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['operator'] = 'realname_op';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['identifier'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_items'] = '10';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_min_chars'] = '0';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_raw_suggestion'] = '1';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_raw_dropdown'] = '1';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_dependent'] = 0;
	$handler->display->display_options ['qtip_instance'] = 'standaard';
	$handler->display->display_options ['path'] = 'hrm/planningsgesprekken';
	$handler->display->display_options ['menu'] ['type'] = 'normal';
	$handler->display->display_options ['menu'] ['title'] = 'Planningsgesprekken';
	$handler->display->display_options ['menu'] ['weight'] = '0';
	if (menu_load ( 'menu-modules' )) {
		$menu = 'menu-modules';
	} else {
		$menu = 'navigation';
	}
	$handler->display->display_options ['menu'] ['name'] = $menu;
	$handler->display->display_options ['menu'] ['context'] = 0;
	$handler->display->display_options ['menu'] ['context_only_inline'] = 0;
	
	/* Display: Functioneringsgesprekken */
	$handler = $view->new_display ( 'page', 'Functioneringsgesprekken', 'hrm_functioneringsgesprekken_overview' );
	$handler->display->display_options ['defaults'] ['title'] = FALSE;
	$handler->display->display_options ['title'] = 'Functioneringsgesprekken';
	$handler->display->display_options ['defaults'] ['style_plugin'] = FALSE;
	$handler->display->display_options ['style_plugin'] = 'table';
	$handler->display->display_options ['style_options'] ['columns'] = array (
			'counter' => 'counter',
			'field_personeelslid' => 'field_personeelslid',
			'field_tijdstip' => 'field_tijdstip',
			'field_functioneringsg_status' => 'field_functioneringsg_status',
			'type' => 'type',
			'nid' => 'nid',
			'edit_node' => 'edit_node',
			'nothing' => 'nothing' 
	);
	$handler->display->display_options ['style_options'] ['default'] = '-1';
	$handler->display->display_options ['style_options'] ['info'] = array (
			'counter' => array (
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_personeelslid' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_tijdstip' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_functioneringsg_status' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			),
			'type' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			),
			'nid' => array (
					'sortable' => 0,
					'default_sort_order' => 'asc',
					'align' => '',
					'separator' => '',
					'empty_column' => 0 
			),
			'edit_node' => array (
					'align' => '',
					'separator' => '',
					'empty_column' => 0 
			),
			'nothing' => array (
					'align' => 'views-align-right',
					'separator' => '',
					'empty_column' => 0 
			) 
	);
	$handler->display->display_options ['style_options'] ['sticky'] = TRUE;
	$handler->display->display_options ['defaults'] ['style_options'] = FALSE;
	$handler->display->display_options ['defaults'] ['row_plugin'] = FALSE;
	$handler->display->display_options ['defaults'] ['row_options'] = FALSE;
	$handler->display->display_options ['exposed_block'] = TRUE;
	$handler->display->display_options ['defaults'] ['header'] = FALSE;
	/* Kop: Algemeen: Tekstveld */
	$handler->display->display_options ['header'] ['area'] ['id'] = 'area';
	$handler->display->display_options ['header'] ['area'] ['table'] = 'views';
	$handler->display->display_options ['header'] ['area'] ['field'] = 'area';
	$handler->display->display_options ['header'] ['area'] ['empty'] = TRUE;
	$handler->display->display_options ['header'] ['area'] ['content'] = '<a href="/node/add/hrm-functioneringsgesprek">Een functioneringsgesprek toevoegen</a>';
	$handler->display->display_options ['header'] ['area'] ['format'] = 'filtered_html';
	$handler->display->display_options ['defaults'] ['footer'] = FALSE;
	/* Voet: Algemeen: Samenvatting van het resultaat */
	$handler->display->display_options ['footer'] ['result'] ['id'] = 'result';
	$handler->display->display_options ['footer'] ['result'] ['table'] = 'views';
	$handler->display->display_options ['footer'] ['result'] ['field'] = 'result';
	$handler->display->display_options ['footer'] ['result'] ['content'] = 'Getoond @start - @end van @total';
	/* Voet: Algemeen: Tekstveld */
	$handler->display->display_options ['footer'] ['area'] ['id'] = 'area';
	$handler->display->display_options ['footer'] ['area'] ['table'] = 'views';
	$handler->display->display_options ['footer'] ['area'] ['field'] = 'area';
	$handler->display->display_options ['footer'] ['area'] ['content'] = '<a href="/node/add/hrm-functioneringsgesprek">Een functioneringsgesprek toevoegen</a>';
	$handler->display->display_options ['footer'] ['area'] ['format'] = 'filtered_html';
	$handler->display->display_options ['defaults'] ['fields'] = FALSE;
	/* Veld: Inhoud: Nid */
	$handler->display->display_options ['fields'] ['nid'] ['id'] = 'nid';
	$handler->display->display_options ['fields'] ['nid'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['nid'] ['field'] = 'nid';
	$handler->display->display_options ['fields'] ['nid'] ['label'] = '';
	$handler->display->display_options ['fields'] ['nid'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['nid'] ['element_label_colon'] = FALSE;
	/* Veld: Algemeen: Resultatenteller weergeven */
	$handler->display->display_options ['fields'] ['counter'] ['id'] = 'counter';
	$handler->display->display_options ['fields'] ['counter'] ['table'] = 'views';
	$handler->display->display_options ['fields'] ['counter'] ['field'] = 'counter';
	$handler->display->display_options ['fields'] ['counter'] ['label'] = 'Nr.';
	$handler->display->display_options ['fields'] ['counter'] ['counter_start'] = '1';
	$handler->display->display_options ['fields'] ['counter'] ['reverse'] = 0;
	/* Veld: Inhoud: Personeelslid */
	$handler->display->display_options ['fields'] ['field_personeelslid'] ['id'] = 'field_personeelslid';
	$handler->display->display_options ['fields'] ['field_personeelslid'] ['table'] = 'field_data_field_personeelslid';
	$handler->display->display_options ['fields'] ['field_personeelslid'] ['field'] = 'field_personeelslid';
	$handler->display->display_options ['fields'] ['field_personeelslid'] ['settings'] = array (
			'link' => '1',
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Inhoud: Tijdstip */
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['id'] = 'field_tijdstip';
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['table'] = 'field_data_field_tijdstip';
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['field'] = 'field_tijdstip';
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['alter'] ['make_link'] = TRUE;
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['alter'] ['path'] = 'node/[nid]';
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['alter'] ['absolute'] = TRUE;
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['settings'] = array (
			'format_type' => 'long',
			'fromto' => 'both',
			'multiple_number' => '',
			'multiple_from' => '',
			'multiple_to' => '',
			'show_remaining_days' => 0,
			'show_repeat_rule' => 'show',
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Inhoud: Status */
	$handler->display->display_options ['fields'] ['field_functioneringsg_status'] ['id'] = 'field_functioneringsg_status';
	$handler->display->display_options ['fields'] ['field_functioneringsg_status'] ['table'] = 'field_data_field_functioneringsg_status';
	$handler->display->display_options ['fields'] ['field_functioneringsg_status'] ['field'] = 'field_functioneringsg_status';
	$handler->display->display_options ['fields'] ['field_functioneringsg_status'] ['settings'] = array (
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Inhoud: Type */
	$handler->display->display_options ['fields'] ['type'] ['id'] = 'type';
	$handler->display->display_options ['fields'] ['type'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['type'] ['field'] = 'type';
	/* Veld: Inhoud: Bewerkingslink */
	$handler->display->display_options ['fields'] ['edit_node'] ['id'] = 'edit_node';
	$handler->display->display_options ['fields'] ['edit_node'] ['table'] = 'views_entity_node';
	$handler->display->display_options ['fields'] ['edit_node'] ['field'] = 'edit_node';
	$handler->display->display_options ['fields'] ['edit_node'] ['label'] = '';
	$handler->display->display_options ['fields'] ['edit_node'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['edit_node'] ['element_label_colon'] = FALSE;
	/* Veld: Algemeen: Aangepaste tekst */
	$handler->display->display_options ['fields'] ['nothing'] ['id'] = 'nothing';
	$handler->display->display_options ['fields'] ['nothing'] ['table'] = 'views';
	$handler->display->display_options ['fields'] ['nothing'] ['field'] = 'nothing';
	$handler->display->display_options ['fields'] ['nothing'] ['label'] = 'Acties';
	$handler->display->display_options ['fields'] ['nothing'] ['alter'] ['text'] = '[edit_node] - <a href="/documenten_generator.get/BRF_HRM_Functioneringsgesprek_uitnodiging/id=[nid]">uitnodiging</a> - <a href="/documenten_generator.get/VSG_HRM_Functioneringsgesprek/id=[nid]">verslag</a>';
	$handler->display->display_options ['defaults'] ['filter_groups'] = FALSE;
	$handler->display->display_options ['defaults'] ['filters'] = FALSE;
	/* Filtercriterium: Inhoud: Gepubliceerd */
	$handler->display->display_options ['filters'] ['status'] ['id'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['status'] ['field'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['value'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['expose'] ['operator'] = FALSE;
	/* Filtercriterium: Inhoud: Type */
	$handler->display->display_options ['filters'] ['type'] ['id'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['type'] ['field'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['value'] = array (
			'hrm_functioneringsgesprek' => 'hrm_functioneringsgesprek' 
	);
	/* Filtercriterium: Echte naam: Naam */
	$handler->display->display_options ['filters'] ['realname'] ['id'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['table'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['field'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['relationship'] = 'field_personeelslid_target_id';
	$handler->display->display_options ['filters'] ['realname'] ['operator'] = 'contains';
	$handler->display->display_options ['filters'] ['realname'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['operator_id'] = 'realname_op';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['label'] = 'Personeelslid';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['operator'] = 'realname_op';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['identifier'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_items'] = '10';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_min_chars'] = '0';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_raw_suggestion'] = '1';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_raw_dropdown'] = '1';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_dependent'] = 0;
	$handler->display->display_options ['qtip_instance'] = 'standaard';
	$handler->display->display_options ['path'] = 'hrm/functioneringsgesprekken';
	$handler->display->display_options ['menu'] ['type'] = 'normal';
	$handler->display->display_options ['menu'] ['title'] = 'Functioneringsgesprekken';
	$handler->display->display_options ['menu'] ['weight'] = '0';
	if (menu_load ( 'menu-modules' )) {
		$menu = 'menu-modules';
	} else {
		$menu = 'navigation';
	}
	$handler->display->display_options ['menu'] ['name'] = $menu;
	$handler->display->display_options ['menu'] ['context'] = 0;
	$handler->display->display_options ['menu'] ['context_only_inline'] = 0;
	
	/* Display: Evaluatiegesprekken */
	$handler = $view->new_display ( 'page', 'Evaluatiegesprekken', 'hrm_evaluatiegesprekken_overview' );
	$handler->display->display_options ['defaults'] ['title'] = FALSE;
	$handler->display->display_options ['title'] = 'Evaluatiegesprekken';
	$handler->display->display_options ['defaults'] ['access'] = FALSE;
	$handler->display->display_options ['access'] ['type'] = 'role';
	$handler->display->display_options ['access'] ['role'] = array ();
	$handler->display->display_options ['defaults'] ['style_plugin'] = FALSE;
	$handler->display->display_options ['style_plugin'] = 'table';
	$handler->display->display_options ['style_options'] ['columns'] = array (
			'counter' => 'counter',
			'field_personeelslid' => 'field_personeelslid',
			'field_tijdstip' => 'field_tijdstip',
			'field_evaluatiegesprek_status' => 'field_evaluatiegesprek_status',
			'type' => 'type',
			'nid' => 'nid',
			'edit_node' => 'edit_node',
			'nothing' => 'nothing' 
	);
	$handler->display->display_options ['style_options'] ['default'] = '-1';
	$handler->display->display_options ['style_options'] ['info'] = array (
			'counter' => array (
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_personeelslid' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_tijdstip' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_evaluatiegesprek_status' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			),
			'type' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			),
			'nid' => array (
					'sortable' => 0,
					'default_sort_order' => 'asc',
					'align' => '',
					'separator' => '',
					'empty_column' => 0 
			),
			'edit_node' => array (
					'align' => '',
					'separator' => '',
					'empty_column' => 0 
			),
			'nothing' => array (
					'align' => 'views-align-right',
					'separator' => '',
					'empty_column' => 0 
			) 
	);
	$handler->display->display_options ['style_options'] ['sticky'] = TRUE;
	$handler->display->display_options ['defaults'] ['style_options'] = FALSE;
	$handler->display->display_options ['defaults'] ['row_plugin'] = FALSE;
	$handler->display->display_options ['defaults'] ['row_options'] = FALSE;
	$handler->display->display_options ['exposed_block'] = TRUE;
	$handler->display->display_options ['defaults'] ['header'] = FALSE;
	/* Kop: Algemeen: Tekstveld */
	$handler->display->display_options ['header'] ['area'] ['id'] = 'area';
	$handler->display->display_options ['header'] ['area'] ['table'] = 'views';
	$handler->display->display_options ['header'] ['area'] ['field'] = 'area';
	$handler->display->display_options ['header'] ['area'] ['empty'] = TRUE;
	$handler->display->display_options ['header'] ['area'] ['content'] = '<a href="/node/add/hrm-evaluatiegesprek">Een evaluatiegesprek toevoegen</a>';
	$handler->display->display_options ['header'] ['area'] ['format'] = 'filtered_html';
	$handler->display->display_options ['defaults'] ['fields'] = FALSE;
	/* Veld: Inhoud: Nid */
	$handler->display->display_options ['fields'] ['nid'] ['id'] = 'nid';
	$handler->display->display_options ['fields'] ['nid'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['nid'] ['field'] = 'nid';
	$handler->display->display_options ['fields'] ['nid'] ['label'] = '';
	$handler->display->display_options ['fields'] ['nid'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['nid'] ['element_label_colon'] = FALSE;
	/* Veld: Algemeen: Resultatenteller weergeven */
	$handler->display->display_options ['fields'] ['counter'] ['id'] = 'counter';
	$handler->display->display_options ['fields'] ['counter'] ['table'] = 'views';
	$handler->display->display_options ['fields'] ['counter'] ['field'] = 'counter';
	$handler->display->display_options ['fields'] ['counter'] ['label'] = 'Nr.';
	$handler->display->display_options ['fields'] ['counter'] ['counter_start'] = '1';
	$handler->display->display_options ['fields'] ['counter'] ['reverse'] = 0;
	/* Veld: Inhoud: Personeelslid */
	$handler->display->display_options ['fields'] ['field_personeelslid'] ['id'] = 'field_personeelslid';
	$handler->display->display_options ['fields'] ['field_personeelslid'] ['table'] = 'field_data_field_personeelslid';
	$handler->display->display_options ['fields'] ['field_personeelslid'] ['field'] = 'field_personeelslid';
	$handler->display->display_options ['fields'] ['field_personeelslid'] ['settings'] = array (
			'link' => '1',
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Inhoud: Tijdstip */
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['id'] = 'field_tijdstip';
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['table'] = 'field_data_field_tijdstip';
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['field'] = 'field_tijdstip';
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['alter'] ['make_link'] = TRUE;
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['alter'] ['path'] = 'node/[nid]';
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['alter'] ['absolute'] = TRUE;
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['settings'] = array (
			'format_type' => 'long',
			'fromto' => 'both',
			'multiple_number' => '',
			'multiple_from' => '',
			'multiple_to' => '',
			'show_remaining_days' => 0,
			'show_repeat_rule' => 'show',
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Inhoud: Status */
	$handler->display->display_options ['fields'] ['field_evaluatiegesprek_status'] ['id'] = 'field_evaluatiegesprek_status';
	$handler->display->display_options ['fields'] ['field_evaluatiegesprek_status'] ['table'] = 'field_data_field_evaluatiegesprek_status';
	$handler->display->display_options ['fields'] ['field_evaluatiegesprek_status'] ['field'] = 'field_evaluatiegesprek_status';
	$handler->display->display_options ['fields'] ['field_evaluatiegesprek_status'] ['settings'] = array (
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Inhoud: Type */
	$handler->display->display_options ['fields'] ['type'] ['id'] = 'type';
	$handler->display->display_options ['fields'] ['type'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['type'] ['field'] = 'type';
	/* Veld: Inhoud: Bewerkingslink */
	$handler->display->display_options ['fields'] ['edit_node'] ['id'] = 'edit_node';
	$handler->display->display_options ['fields'] ['edit_node'] ['table'] = 'views_entity_node';
	$handler->display->display_options ['fields'] ['edit_node'] ['field'] = 'edit_node';
	$handler->display->display_options ['fields'] ['edit_node'] ['label'] = '';
	$handler->display->display_options ['fields'] ['edit_node'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['edit_node'] ['element_label_colon'] = FALSE;
	/* Veld: Algemeen: Aangepaste tekst */
	$handler->display->display_options ['fields'] ['nothing'] ['id'] = 'nothing';
	$handler->display->display_options ['fields'] ['nothing'] ['table'] = 'views';
	$handler->display->display_options ['fields'] ['nothing'] ['field'] = 'nothing';
	$handler->display->display_options ['fields'] ['nothing'] ['label'] = 'Acties';
	$handler->display->display_options ['fields'] ['nothing'] ['alter'] ['text'] = '[edit_node] - <a href="/documenten_generator.get/BRF_HRM_Evaluatiegesprek_uitnodiging/id=[nid]">uitnodiging</a> - <a href="/documenten_generator.get/VSG_HRM_Evaluatiegesprek/id=[nid]">verslag</a>';
	$handler->display->display_options ['defaults'] ['filter_groups'] = FALSE;
	$handler->display->display_options ['defaults'] ['filters'] = FALSE;
	/* Filtercriterium: Inhoud: Gepubliceerd */
	$handler->display->display_options ['filters'] ['status'] ['id'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['status'] ['field'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['value'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['expose'] ['operator'] = FALSE;
	/* Filtercriterium: Inhoud: Type */
	$handler->display->display_options ['filters'] ['type'] ['id'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['type'] ['field'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['value'] = array (
			'hrm_evaluatiegesprek' => 'hrm_evaluatiegesprek' 
	);
	/* Filtercriterium: Echte naam: Naam */
	$handler->display->display_options ['filters'] ['realname'] ['id'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['table'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['field'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['relationship'] = 'field_personeelslid_target_id';
	$handler->display->display_options ['filters'] ['realname'] ['operator'] = 'contains';
	$handler->display->display_options ['filters'] ['realname'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['operator_id'] = 'realname_op';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['label'] = 'Personeelslid';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['operator'] = 'realname_op';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['identifier'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_items'] = '10';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_min_chars'] = '0';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_raw_suggestion'] = '1';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_raw_dropdown'] = '1';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_dependent'] = 0;
	$handler->display->display_options ['qtip_instance'] = 'standaard';
	$handler->display->display_options ['path'] = 'hrm/evaluatiegesprekken';
	$handler->display->display_options ['menu'] ['type'] = 'normal';
	$handler->display->display_options ['menu'] ['title'] = 'Evaluatiegesprekken';
	$handler->display->display_options ['menu'] ['weight'] = '0';
	if (menu_load ( 'menu-modules' )) {
		$menu = 'menu-modules';
	} else {
		$menu = 'navigation';
	}
	$handler->display->display_options ['menu'] ['name'] = $menu;
	$handler->display->display_options ['menu'] ['context'] = 0;
	$handler->display->display_options ['menu'] ['context_only_inline'] = 0;
	
	/* Display: Flitsbezoeken */
	$handler = $view->new_display ( 'page', 'Flitsbezoeken', 'hrm_flitsbezoeken_overzicht' );
	$handler->display->display_options ['defaults'] ['title'] = FALSE;
	$handler->display->display_options ['title'] = 'Flitsbezoeken';
	$handler->display->display_options ['defaults'] ['access'] = FALSE;
	$handler->display->display_options ['access'] ['type'] = 'role';
	$handler->display->display_options ['access'] ['role'] = array ();
	$handler->display->display_options ['defaults'] ['style_plugin'] = FALSE;
	$handler->display->display_options ['style_plugin'] = 'table';
	$handler->display->display_options ['style_options'] ['columns'] = array (
			'counter' => 'counter',
			'field_personeelslid' => 'field_personeelslid',
			'field_tijdstip' => 'field_tijdstip',
			'field_evaluatiegesprek_status' => 'field_evaluatiegesprek_status',
			'type' => 'type',
			'nid' => 'nid',
			'edit_node' => 'edit_node',
			'nothing' => 'nothing' 
	);
	$handler->display->display_options ['style_options'] ['default'] = '-1';
	$handler->display->display_options ['style_options'] ['info'] = array (
			'counter' => array (
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_personeelslid' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_tijdstip' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_evaluatiegesprek_status' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			),
			'type' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			),
			'nid' => array (
					'sortable' => 0,
					'default_sort_order' => 'asc',
					'align' => '',
					'separator' => '',
					'empty_column' => 0 
			),
			'edit_node' => array (
					'align' => '',
					'separator' => '',
					'empty_column' => 0 
			),
			'nothing' => array (
					'align' => 'views-align-right',
					'separator' => '',
					'empty_column' => 0 
			) 
	);
	$handler->display->display_options ['style_options'] ['sticky'] = TRUE;
	$handler->display->display_options ['defaults'] ['style_options'] = FALSE;
	$handler->display->display_options ['defaults'] ['row_plugin'] = FALSE;
	$handler->display->display_options ['defaults'] ['row_options'] = FALSE;
	$handler->display->display_options ['exposed_block'] = TRUE;
	$handler->display->display_options ['defaults'] ['header'] = FALSE;
	/* Kop: Algemeen: Tekstveld */
	$handler->display->display_options ['header'] ['area'] ['id'] = 'area';
	$handler->display->display_options ['header'] ['area'] ['table'] = 'views';
	$handler->display->display_options ['header'] ['area'] ['field'] = 'area';
	$handler->display->display_options ['header'] ['area'] ['empty'] = TRUE;
	$handler->display->display_options ['header'] ['area'] ['content'] = '<a href="/node/add/hrm-flitsbezoek">Een flitsbezoek toevoegen</a>';
	$handler->display->display_options ['header'] ['area'] ['format'] = 'filtered_html';
	$handler->display->display_options ['defaults'] ['footer'] = FALSE;
	/* Voet: Algemeen: Samenvatting van het resultaat */
	$handler->display->display_options ['footer'] ['result'] ['id'] = 'result';
	$handler->display->display_options ['footer'] ['result'] ['table'] = 'views';
	$handler->display->display_options ['footer'] ['result'] ['field'] = 'result';
	$handler->display->display_options ['footer'] ['result'] ['content'] = 'Getoond @start - @end van @total';
	/* Voet: Algemeen: Tekstveld */
	$handler->display->display_options ['footer'] ['area'] ['id'] = 'area';
	$handler->display->display_options ['footer'] ['area'] ['table'] = 'views';
	$handler->display->display_options ['footer'] ['area'] ['field'] = 'area';
	$handler->display->display_options ['footer'] ['area'] ['content'] = '<a href="/node/add/hrm-flitsbezoek">Een flitsbezoek toevoegen</a>';
	$handler->display->display_options ['footer'] ['area'] ['format'] = 'filtered_html';
	$handler->display->display_options ['defaults'] ['fields'] = FALSE;
	/* Veld: Inhoud: Nid */
	$handler->display->display_options ['fields'] ['nid'] ['id'] = 'nid';
	$handler->display->display_options ['fields'] ['nid'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['nid'] ['field'] = 'nid';
	$handler->display->display_options ['fields'] ['nid'] ['label'] = '';
	$handler->display->display_options ['fields'] ['nid'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['nid'] ['element_label_colon'] = FALSE;
	/* Veld: Algemeen: Resultatenteller weergeven */
	$handler->display->display_options ['fields'] ['counter'] ['id'] = 'counter';
	$handler->display->display_options ['fields'] ['counter'] ['table'] = 'views';
	$handler->display->display_options ['fields'] ['counter'] ['field'] = 'counter';
	$handler->display->display_options ['fields'] ['counter'] ['label'] = 'Nr.';
	$handler->display->display_options ['fields'] ['counter'] ['counter_start'] = '1';
	$handler->display->display_options ['fields'] ['counter'] ['reverse'] = 0;
	/* Veld: Inhoud: Personeelslid */
	$handler->display->display_options ['fields'] ['field_personeelslid'] ['id'] = 'field_personeelslid';
	$handler->display->display_options ['fields'] ['field_personeelslid'] ['table'] = 'field_data_field_personeelslid';
	$handler->display->display_options ['fields'] ['field_personeelslid'] ['field'] = 'field_personeelslid';
	$handler->display->display_options ['fields'] ['field_personeelslid'] ['settings'] = array (
			'link' => '1',
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Inhoud: Tijdstip */
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['id'] = 'field_tijdstip';
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['table'] = 'field_data_field_tijdstip';
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['field'] = 'field_tijdstip';
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['alter'] ['make_link'] = TRUE;
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['alter'] ['path'] = 'node/[nid]';
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['alter'] ['absolute'] = TRUE;
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['settings'] = array (
			'format_type' => 'long',
			'fromto' => 'both',
			'multiple_number' => '',
			'multiple_from' => '',
			'multiple_to' => '',
			'show_remaining_days' => 0,
			'show_repeat_rule' => 'show',
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Inhoud: Bewerkingslink */
	$handler->display->display_options ['fields'] ['edit_node'] ['id'] = 'edit_node';
	$handler->display->display_options ['fields'] ['edit_node'] ['table'] = 'views_entity_node';
	$handler->display->display_options ['fields'] ['edit_node'] ['field'] = 'edit_node';
	$handler->display->display_options ['fields'] ['edit_node'] ['label'] = '';
	$handler->display->display_options ['fields'] ['edit_node'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['edit_node'] ['element_label_colon'] = FALSE;
	/* Veld: Algemeen: Aangepaste tekst */
	$handler->display->display_options ['fields'] ['nothing'] ['id'] = 'nothing';
	$handler->display->display_options ['fields'] ['nothing'] ['table'] = 'views';
	$handler->display->display_options ['fields'] ['nothing'] ['field'] = 'nothing';
	$handler->display->display_options ['fields'] ['nothing'] ['label'] = 'Acties';
	$handler->display->display_options ['fields'] ['nothing'] ['alter'] ['text'] = '[edit_node] - <a href="/documenten_generator.get/VSG_HRM_Flitsbezoek/id=[nid]">verslag</a>';
	$handler->display->display_options ['defaults'] ['filter_groups'] = FALSE;
	$handler->display->display_options ['defaults'] ['filters'] = FALSE;
	/* Filtercriterium: Inhoud: Gepubliceerd */
	$handler->display->display_options ['filters'] ['status'] ['id'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['status'] ['field'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['value'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['expose'] ['operator'] = FALSE;
	/* Filtercriterium: Inhoud: Type */
	$handler->display->display_options ['filters'] ['type'] ['id'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['type'] ['field'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['value'] = array (
			'hrm_flitsbezoek' => 'hrm_flitsbezoek' 
	);
	/* Filtercriterium: Echte naam: Naam */
	$handler->display->display_options ['filters'] ['realname'] ['id'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['table'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['field'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['relationship'] = 'field_personeelslid_target_id';
	$handler->display->display_options ['filters'] ['realname'] ['operator'] = 'contains';
	$handler->display->display_options ['filters'] ['realname'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['operator_id'] = 'realname_op';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['label'] = 'Personeelslid';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['operator'] = 'realname_op';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['identifier'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_items'] = '10';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_min_chars'] = '0';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_raw_suggestion'] = '1';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_raw_dropdown'] = '1';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_dependent'] = 0;
	$handler->display->display_options ['qtip_instance'] = 'standaard';
	$handler->display->display_options ['path'] = 'hrm/flitsbezoeken';
	$handler->display->display_options ['menu'] ['type'] = 'normal';
	$handler->display->display_options ['menu'] ['title'] = 'Flitsbezoeken';
	$handler->display->display_options ['menu'] ['weight'] = '0';
	if (menu_load ( 'menu-modules' )) {
		$menu = 'menu-modules';
	} else {
		$menu = 'navigation';
	}
	$handler->display->display_options ['menu'] ['name'] = $menu;
	$handler->display->display_options ['menu'] ['context'] = 0;
	$handler->display->display_options ['menu'] ['context_only_inline'] = 0;
	
	/* Display: Klasbezoeken */
	$handler = $view->new_display ( 'page', 'Klasbezoeken', 'hrm_klasbezoeken_overzicht' );
	$handler->display->display_options ['defaults'] ['title'] = FALSE;
	$handler->display->display_options ['title'] = 'Klasbezoeken';
	$handler->display->display_options ['defaults'] ['access'] = FALSE;
	$handler->display->display_options ['access'] ['type'] = 'role';
	$handler->display->display_options ['access'] ['role'] = array ();
	$handler->display->display_options ['defaults'] ['style_plugin'] = FALSE;
	$handler->display->display_options ['style_plugin'] = 'table';
	$handler->display->display_options ['style_options'] ['columns'] = array (
			'counter' => 'counter',
			'field_personeelslid' => 'field_personeelslid',
			'field_tijdstip' => 'field_tijdstip',
			'field_evaluatiegesprek_status' => 'field_evaluatiegesprek_status',
			'type' => 'type',
			'nid' => 'nid',
			'edit_node' => 'edit_node',
			'nothing' => 'nothing' 
	);
	$handler->display->display_options ['style_options'] ['default'] = '-1';
	$handler->display->display_options ['style_options'] ['info'] = array (
			'counter' => array (
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_personeelslid' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_tijdstip' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_evaluatiegesprek_status' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			),
			'type' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			),
			'nid' => array (
					'sortable' => 0,
					'default_sort_order' => 'asc',
					'align' => '',
					'separator' => '',
					'empty_column' => 0 
			),
			'edit_node' => array (
					'align' => '',
					'separator' => '',
					'empty_column' => 0 
			),
			'nothing' => array (
					'align' => 'views-align-right',
					'separator' => '',
					'empty_column' => 0 
			) 
	);
	$handler->display->display_options ['style_options'] ['sticky'] = TRUE;
	$handler->display->display_options ['defaults'] ['style_options'] = FALSE;
	$handler->display->display_options ['defaults'] ['row_plugin'] = FALSE;
	$handler->display->display_options ['defaults'] ['row_options'] = FALSE;
	$handler->display->display_options ['exposed_block'] = TRUE;
	$handler->display->display_options ['defaults'] ['header'] = FALSE;
	/* Kop: Algemeen: Tekstveld */
	$handler->display->display_options ['header'] ['area'] ['id'] = 'area';
	$handler->display->display_options ['header'] ['area'] ['table'] = 'views';
	$handler->display->display_options ['header'] ['area'] ['field'] = 'area';
	$handler->display->display_options ['header'] ['area'] ['empty'] = TRUE;
	$handler->display->display_options ['header'] ['area'] ['content'] = '<a href="/node/add/hrm-klasbezoek">Een klasbezoek toevoegen</a>';
	$handler->display->display_options ['header'] ['area'] ['format'] = 'filtered_html';
	$handler->display->display_options ['defaults'] ['footer'] = FALSE;
	/* Voet: Algemeen: Samenvatting van het resultaat */
	$handler->display->display_options ['footer'] ['result'] ['id'] = 'result';
	$handler->display->display_options ['footer'] ['result'] ['table'] = 'views';
	$handler->display->display_options ['footer'] ['result'] ['field'] = 'result';
	$handler->display->display_options ['footer'] ['result'] ['content'] = 'Getoond @start - @end van @total';
	/* Voet: Algemeen: Tekstveld */
	$handler->display->display_options ['footer'] ['area'] ['id'] = 'area';
	$handler->display->display_options ['footer'] ['area'] ['table'] = 'views';
	$handler->display->display_options ['footer'] ['area'] ['field'] = 'area';
	$handler->display->display_options ['footer'] ['area'] ['content'] = '<a href="/node/add/hrm-klasbezoek">Een klasbezoek toevoegen</a>';
	$handler->display->display_options ['footer'] ['area'] ['format'] = 'filtered_html';
	$handler->display->display_options ['defaults'] ['fields'] = FALSE;
	/* Veld: Inhoud: Nid */
	$handler->display->display_options ['fields'] ['nid'] ['id'] = 'nid';
	$handler->display->display_options ['fields'] ['nid'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['nid'] ['field'] = 'nid';
	$handler->display->display_options ['fields'] ['nid'] ['label'] = '';
	$handler->display->display_options ['fields'] ['nid'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['nid'] ['element_label_colon'] = FALSE;
	/* Veld: Algemeen: Resultatenteller weergeven */
	$handler->display->display_options ['fields'] ['counter'] ['id'] = 'counter';
	$handler->display->display_options ['fields'] ['counter'] ['table'] = 'views';
	$handler->display->display_options ['fields'] ['counter'] ['field'] = 'counter';
	$handler->display->display_options ['fields'] ['counter'] ['label'] = 'Nr.';
	$handler->display->display_options ['fields'] ['counter'] ['counter_start'] = '1';
	$handler->display->display_options ['fields'] ['counter'] ['reverse'] = 0;
	/* Veld: Inhoud: Personeelslid */
	$handler->display->display_options ['fields'] ['field_personeelslid'] ['id'] = 'field_personeelslid';
	$handler->display->display_options ['fields'] ['field_personeelslid'] ['table'] = 'field_data_field_personeelslid';
	$handler->display->display_options ['fields'] ['field_personeelslid'] ['field'] = 'field_personeelslid';
	$handler->display->display_options ['fields'] ['field_personeelslid'] ['settings'] = array (
			'link' => '1',
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Inhoud: Tijdstip */
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['id'] = 'field_tijdstip';
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['table'] = 'field_data_field_tijdstip';
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['field'] = 'field_tijdstip';
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['alter'] ['make_link'] = TRUE;
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['alter'] ['path'] = 'node/[nid]';
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['alter'] ['absolute'] = TRUE;
	$handler->display->display_options ['fields'] ['field_tijdstip'] ['settings'] = array (
			'format_type' => 'long',
			'fromto' => 'both',
			'multiple_number' => '',
			'multiple_from' => '',
			'multiple_to' => '',
			'show_remaining_days' => 0,
			'show_repeat_rule' => 'show',
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Inhoud: Didactische competenties */
	$handler->display->display_options ['fields'] ['field_klasbezoek_did_comp'] ['id'] = 'field_klasbezoek_did_comp';
	$handler->display->display_options ['fields'] ['field_klasbezoek_did_comp'] ['table'] = 'field_data_field_klasbezoek_did_comp';
	$handler->display->display_options ['fields'] ['field_klasbezoek_did_comp'] ['field'] = 'field_klasbezoek_did_comp';
	$handler->display->display_options ['fields'] ['field_klasbezoek_did_comp'] ['settings'] = array (
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	$handler->display->display_options ['fields'] ['field_klasbezoek_did_comp'] ['delta_offset'] = '0';
	/* Veld: Inhoud: Organisatorische competenties */
	$handler->display->display_options ['fields'] ['field_klasbezoek_org_comp'] ['id'] = 'field_klasbezoek_org_comp';
	$handler->display->display_options ['fields'] ['field_klasbezoek_org_comp'] ['table'] = 'field_data_field_klasbezoek_org_comp';
	$handler->display->display_options ['fields'] ['field_klasbezoek_org_comp'] ['field'] = 'field_klasbezoek_org_comp';
	$handler->display->display_options ['fields'] ['field_klasbezoek_org_comp'] ['settings'] = array (
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	$handler->display->display_options ['fields'] ['field_klasbezoek_org_comp'] ['delta_offset'] = '0';
	/* Veld: Inhoud: Pedagogische competenties */
	$handler->display->display_options ['fields'] ['field_klasbezoek_ped_comp'] ['id'] = 'field_klasbezoek_ped_comp';
	$handler->display->display_options ['fields'] ['field_klasbezoek_ped_comp'] ['table'] = 'field_data_field_klasbezoek_ped_comp';
	$handler->display->display_options ['fields'] ['field_klasbezoek_ped_comp'] ['field'] = 'field_klasbezoek_ped_comp';
	$handler->display->display_options ['fields'] ['field_klasbezoek_ped_comp'] ['settings'] = array (
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	$handler->display->display_options ['fields'] ['field_klasbezoek_ped_comp'] ['delta_offset'] = '0';
	/* Veld: Inhoud: Taalcompetenties */
	$handler->display->display_options ['fields'] ['field_klasbezoek_taalcomp'] ['id'] = 'field_klasbezoek_taalcomp';
	$handler->display->display_options ['fields'] ['field_klasbezoek_taalcomp'] ['table'] = 'field_data_field_klasbezoek_taalcomp';
	$handler->display->display_options ['fields'] ['field_klasbezoek_taalcomp'] ['field'] = 'field_klasbezoek_taalcomp';
	/* Veld: Inhoud: Andere focus */
	$handler->display->display_options ['fields'] ['field_klasbezoek_andere_focus'] ['id'] = 'field_klasbezoek_andere_focus';
	$handler->display->display_options ['fields'] ['field_klasbezoek_andere_focus'] ['table'] = 'field_data_field_klasbezoek_andere_focus';
	$handler->display->display_options ['fields'] ['field_klasbezoek_andere_focus'] ['field'] = 'field_klasbezoek_andere_focus';
	$handler->display->display_options ['fields'] ['field_klasbezoek_andere_focus'] ['settings'] = array (
			'conditions' => array (
					0 => array (
							'condition' => '' 
					) 
			) 
	);
	/* Veld: Inhoud: Bewerkingslink */
	$handler->display->display_options ['fields'] ['edit_node'] ['id'] = 'edit_node';
	$handler->display->display_options ['fields'] ['edit_node'] ['table'] = 'views_entity_node';
	$handler->display->display_options ['fields'] ['edit_node'] ['field'] = 'edit_node';
	$handler->display->display_options ['fields'] ['edit_node'] ['label'] = '';
	$handler->display->display_options ['fields'] ['edit_node'] ['exclude'] = TRUE;
	$handler->display->display_options ['fields'] ['edit_node'] ['element_label_colon'] = FALSE;
	/* Veld: Algemeen: Aangepaste tekst */
	$handler->display->display_options ['fields'] ['nothing'] ['id'] = 'nothing';
	$handler->display->display_options ['fields'] ['nothing'] ['table'] = 'views';
	$handler->display->display_options ['fields'] ['nothing'] ['field'] = 'nothing';
	$handler->display->display_options ['fields'] ['nothing'] ['label'] = 'Acties';
	$handler->display->display_options ['fields'] ['nothing'] ['alter'] ['text'] = '[edit_node] - <a href="/documenten_generator.get/VSG_HRM_Klasbezoek/id=[nid]">verslag</a>';
	$handler->display->display_options ['defaults'] ['filter_groups'] = FALSE;
	$handler->display->display_options ['defaults'] ['filters'] = FALSE;
	/* Filtercriterium: Inhoud: Gepubliceerd */
	$handler->display->display_options ['filters'] ['status'] ['id'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['status'] ['field'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['value'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['expose'] ['operator'] = FALSE;
	/* Filtercriterium: Inhoud: Type */
	$handler->display->display_options ['filters'] ['type'] ['id'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['type'] ['field'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['value'] = array (
			'hrm_klasbezoek' => 'hrm_klasbezoek' 
	);
	/* Filtercriterium: Echte naam: Naam */
	$handler->display->display_options ['filters'] ['realname'] ['id'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['table'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['field'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['relationship'] = 'field_personeelslid_target_id';
	$handler->display->display_options ['filters'] ['realname'] ['operator'] = 'contains';
	$handler->display->display_options ['filters'] ['realname'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['operator_id'] = 'realname_op';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['label'] = 'Personeelslid';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['operator'] = 'realname_op';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['identifier'] = 'realname';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_items'] = '10';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_min_chars'] = '0';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_raw_suggestion'] = '1';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_raw_dropdown'] = '1';
	$handler->display->display_options ['filters'] ['realname'] ['expose'] ['autocomplete_dependent'] = 0;
	$handler->display->display_options ['qtip_instance'] = 'standaard';
	$handler->display->display_options ['path'] = 'hrm/klasbezoeken';
	$handler->display->display_options ['menu'] ['type'] = 'normal';
	$handler->display->display_options ['menu'] ['title'] = 'Klasbezoeken';
	$handler->display->display_options ['menu'] ['weight'] = '0';
	if (menu_load ( 'menu-modules' )) {
		$menu = 'menu-modules';
	} else {
		$menu = 'navigation';
	}
	$handler->display->display_options ['menu'] ['name'] = $menu;
	$handler->display->display_options ['menu'] ['context'] = 0;
	$handler->display->display_options ['menu'] ['context_only_inline'] = 0;
	$translatables ['hrm'] = array (
			t ( 'Master' ),
			t ( 'HRM' ),
			t ( 'meer' ),
			t ( 'Toepassen' ),
			t ( 'Opnieuw instellen' ),
			t ( 'Sorteren op' ),
			t ( 'Oplopend' ),
			t ( 'Aflopend' ),
			t ( 'Items per pagina' ),
			t ( '- Alle -' ),
			t ( 'Startpunt' ),
			t ( '« eerste' ),
			t ( '‹ vorige' ),
			t ( 'volgende ›' ),
			t ( 'laatste »' ),
			t ( '<a href="/node/add/hrm-evaluatiegesprek">Een evaluatiegesprek toevoegen</a>' ),
			t ( 'Getoond @start - @end van @total' ),
			t ( 'Gebruiker entity referenced from field_personeelslid' ),
			t ( 'Nr.' ),
			t ( 'Personeelslid' ),
			t ( 'Tijdstip' ),
			t ( 'Status' ),
			t ( '[field_functioneringsg_status][field_planningsgesprek_status_1][field_evaluatiegesprek_status]' ),
			t ( 'Type' ),
			t ( 'Acties' ),
			t ( '[edit_node] - <a href="/documenten_generator.get/BRF_HRM_Planningsgesprek_uitnodiging/id=[nid]">uitnodiging</a> - <a href="/documenten_generator.get/VSG_HRM_Planningsgesprek/id=[nid]">verslag</a>' ),
			t ( 'Planningsgesprekken' ),
			t ( '<a href="/node/add/hrm-planningsgesprek">Een planningsgesprek toevoegen</a>' ),
			t ( 'Functioneringsgesprekken' ),
			t ( '<a href="/node/add/hrm-functioneringsgesprek">Een functioneringsgesprek toevoegen</a>' ),
			t ( '[edit_node] - <a href="/documenten_generator.get/BRF_HRM_Functioneringsgesprek_uitnodiging/id=[nid]">uitnodiging</a> - <a href="/documenten_generator.get/VSG_HRM_Functioneringsgesprek/id=[nid]">verslag</a>' ),
			t ( 'Evaluatiegesprekken' ),
			t ( '[edit_node] - <a href="/documenten_generator.get/BRF_HRM_Evaluatiegesprek_uitnodiging/id=[nid]">uitnodiging</a> - <a href="/documenten_generator.get/VSG_HRM_Evaluatiegesprek/id=[nid]">verslag</a>' ),
			t ( 'Flitsbezoeken' ),
			t ( '<a href="/node/add/hrm-flitsbezoek">Een flitsbezoek toevoegen</a>' ),
			t ( '[edit_node] - <a href="/documenten_generator.get/VSG_HRM_Flitsbezoek/id=[nid]">verslag</a>' ),
			t ( 'Klasbezoeken' ),
			t ( '<a href="/node/add/hrm-klasbezoek">Een klasbezoek toevoegen</a>' ),
			t ( 'Didactische competenties' ),
			t ( 'Organisatorische competenties' ),
			t ( 'Pedagogische competenties' ),
			t ( 'Taalcompetenties' ),
			t ( 'Andere focus' ),
			t ( '[edit_node] - <a href="/documenten_generator.get/VSG_HRM_Klasbezoek/id=[nid]">verslag</a>' ) 
	);
	
	$views [$view->name] = $view;
	return $views;
}

/**
 * Page callback: HRM - workload instellingen
 *
 * @see argus_hrm_workload_setup_form()
 */
function argus_hrm_workload_setup_form($form, &$form_state) {
	$form ['general'] = array (
			'#type' => 'fieldset',
			'#title' => t ( 'Algemeen' ),
			'#description' => t ( 'Voor de berekening van de score wordt er rekening gehouden met het aantal leerlingen per groep. Het aantal minuten wordt verrekend per <strong>schooljaar</strong>.' ),
			'#collapsible' => TRUE,
			'#collapsed' => FALSE 
	);
	
	$form ['general'] ['argus_hrm_workload_roles'] = array (
			'#type' => 'select',
			'#title' => t ( 'Selecteer enkel de gebruikers van onderstaande groep' ),
			'#options' => user_roles (),
			'#multiple' => TRUE,
			'#size' => 10,
			'#default_value' => variable_get ( 'argus_hrm_workload_roles', 0 ),
			'#description' => t ( 'Als de score wordt berekend, zal er enkel naar de mensen uit deze groep(en) gekeken worden.' ) 
	);
	
	$form ['general'] ['roles'] = array (
			'#type' => 'fieldset',
			'#title' => t ( 'Rollen' ),
			'#description' => t ( 'Stel het gewicht van elke rol in. Deze factor houdt rekening met een gemiddelde groep (in het geval van begeleiding) van 10 leerlingen.<br /><small><u>Opgelet</u>: als je het gewicht ingeeft bij een specifieke module (zie verder), dan kan je best hier de waarde op 0 zetten, anders wordt dit dubbel gerekend voor de score.</small>' ),
			'#collapsible' => TRUE,
			'#collapsed' => TRUE 
	);
	
	$roles = user_roles ();
	foreach ( $roles as $rid => $role ) {
		$form ['general'] ['roles'] ['argus_hrm_workload_role-' . $rid] = array (
				'#type' => 'textfield',
				'#title' => $role,
				'#field_suffix' => t ( 'minuten' ),
				'#default_value' => variable_get ( 'argus_hrm_workload_role-' . $rid, 0 ),
				'#required' => TRUE,
				'#size' => 10 
		);
	}
	
	if (module_exists ( 'argus_uurrooster' )) {
		$form ['argus_uurrooster'] = array (
				'#type' => 'fieldset',
				'#title' => t ( 'Module Uurroosters' ),
				'#collapsible' => TRUE,
				'#collapsed' => FALSE,
				'#description' => t ( 'Voor de toezichten en permanenties kan je apart de gemiddelde tijd per opdracht ingeven. Meerdere toezichten of permanenties worden verrekend door het systeem.' ) 
		);
		
		$form ['argus_uurrooster'] ['argus_hrm_workload_springuren'] = array (
				'#type' => 'textfield',
				'#title' => t ( 'Springuren' ),
				'#description' => t ( 'Een springuur is in principe de tijd van een lesuur, maar kan ook als minder gewicht worden ingesteld.<br /><small><u>Opgelet</u>: een springuur wordt ook gezien als een verlichting van de werkdruk, bvb. bij een dag van 8 lesuren.</small>' ),
				'#field_suffix' => t ( 'minuten' ),
				'#default_value' => variable_get ( 'argus_hrm_workload_springuren', 50 ),
				'#required' => TRUE,
				'#size' => 10 
		);
		
		$form ['argus_uurrooster'] ['argus_hrm_workload_plage-uren'] = array (
				'#type' => 'textfield',
				'#title' => t ( 'Plage-uren' ),
				'#description' => t ( 'Een plage-uur is in principe de tijd van een lesuur, maar kan ook als minder gewicht worden ingesteld.<br /><small><u>Opgelet</u>: een plage-uur kan ook worden in rekening gebracht bij het opgeven van toezichten en permanentie.</small>' ),
				'#field_suffix' => t ( 'minuten' ),
				'#default_value' => variable_get ( 'argus_hrm_workload_plage-uren', 50 ),
				'#required' => TRUE,
				'#size' => 10 
		);
		
		$form ['argus_uurrooster'] ['argus_hrm_workload_substitutes'] = array (
				'#type' => 'textfield',
				'#title' => t ( 'Permanenties' ),
				'#description' => t ( 'Een permanentieuur is in het rooster opgenomen als vast vervangingsuur.<br /><small><u>Opgelet</u>: dit kan in sommige gevallen niet overeenkomen met de echte situatie als er bvb. vervangingen door een afdeling worden opgevangen.</small>' ),
				'#field_suffix' => t ( 'minuten' ),
				'#default_value' => variable_get ( 'argus_hrm_workload_substitutes', 30 ),
				'#required' => TRUE,
				'#size' => 10 
		);
		
		$form ['argus_uurrooster'] ['supervisions'] = array (
				'#type' => 'fieldset',
				'#title' => t ( 'Toezichten' ),
				'#collapsible' => TRUE,
				'#collapsed' => FALSE,
				'#description' => t ( 'Stel het gewicht van elk type toezicht in.' ) 
		);
		$form ['argus_uurrooster'] ['supervisions'] ['argus_hrm_workload_toezicht-kort-effectief'] = array (
				'#type' => 'textfield',
				'#title' => t ( 'Kort - effectief' ),
				'#description' => t ( 'Dit toezicht is een effectief toezicht en wordt elke week uitgevoerd.' ),
				'#field_suffix' => t ( 'minuten' ),
				'#default_value' => variable_get ( 'argus_hrm_workload_toezicht-kort-effectief', 30 ),
				'#required' => TRUE,
				'#size' => 10 
		);
		$form ['argus_uurrooster'] ['supervisions'] ['argus_hrm_workload_toezicht-kort-vervanger'] = array (
				'#type' => 'textfield',
				'#title' => t ( 'Kort - vervanger' ),
				'#description' => t ( 'Een vervanger staat als reserve op en zal het toezicht sporadisch uitvoeren.' ),
				'#field_suffix' => t ( 'minuten' ),
				'#default_value' => variable_get ( 'argus_hrm_workload_toezicht-kort-vervanger', 5 ),
				'#required' => TRUE,
				'#size' => 10 
		);
		$form ['argus_uurrooster'] ['supervisions'] ['argus_hrm_workload_toezicht-lang-effectief'] = array (
				'#type' => 'textfield',
				'#title' => t ( 'Lang - effectief' ),
				'#description' => t ( 'Dit toezicht is een effectief toezicht en wordt elke week uitgevoerd.' ),
				'#field_suffix' => t ( 'minuten' ),
				'#default_value' => variable_get ( 'argus_hrm_workload_toezicht-lang-effectief', 30 ),
				'#required' => TRUE,
				'#size' => 10 
		);
		$form ['argus_uurrooster'] ['supervisions'] ['argus_hrm_workload_toezicht-lang-vervanger'] = array (
				'#type' => 'textfield',
				'#title' => t ( 'Lang - vervanger' ),
				'#description' => t ( 'Een vervanger staat als reserve op en zal het toezicht sporadisch uitvoeren.' ),
				'#field_suffix' => t ( 'minuten' ),
				'#default_value' => variable_get ( 'argus_hrm_workload_toezicht-lang-vervanger', 15 ),
				'#required' => TRUE,
				'#size' => 10 
		);
	}
	
	if (module_exists ( 'argus_klasbeheer' )) {
		$form ['argus_klasbeheer'] = array (
				'#type' => 'fieldset',
				'#title' => t ( 'Module Klasbeheer' ),
				'#collapsible' => TRUE,
				'#collapsed' => FALSE,
				'#description' => t ( 'Stel het gewicht van elke rol in.' ) 
		);
		
		$form ['argus_klasbeheer'] ['argus_hrm_workload_ktt'] = array (
				'#type' => 'textfield',
				'#title' => t ( 'Klastitularis' ),
				'#description' => t ( 'De rol van de klastitularis wordt berekend per leerling; geef daarom hier de tijd die nodig is voor een gemiddelde leerling.' ),
				'#field_suffix' => t ( 'minuten per leerling' ),
				'#default_value' => variable_get ( 'argus_hrm_workload_ktt', 120 ),
				'#required' => TRUE,
				'#size' => 10 
		);
		
		$form ['argus_klasbeheer'] ['argus_hrm_workload_hktt'] = array (
				'#type' => 'textfield',
				'#title' => t ( 'Hulpklastitularis' ),
				'#description' => t ( 'De rol van de hulpklastitularis wordt berekend per leerling; geef daarom hier de tijd die nodig is voor een gemiddelde leerling.' ),
				'#field_suffix' => t ( 'minuten per leerling' ),
				'#default_value' => variable_get ( 'argus_hrm_workload_hktt', 30 ),
				'#required' => TRUE,
				'#size' => 10 
		);
	}
	
	if (module_exists ( 'argus_stages' )) {
		$form ['argus_stages'] = array (
				'#type' => 'fieldset',
				'#title' => t ( 'Module Stages' ),
				'#collapsible' => TRUE,
				'#collapsed' => FALSE,
				'#description' => t ( 'Indien de stagebegeleiders worden vrijgesteld via BPT-uren, dan moet je het gewicht van deze factor eventueel verlagen of op 0 zetten.' ) 
		);
		
		$form ['argus_stages'] ['argus_hrm_workload_stages'] = array (
				'#type' => 'textfield',
				'#title' => t ( 'Stagebegeleider' ),
				'#description' => t ( 'De rol van de stagebegeleider (zoals toegekend in de stagedossiers!) wordt berekend per leerling; geef daarom hier de tijd die nodig is voor een gemiddelde leerling.' ),
				'#field_suffix' => t ( 'minuten per leerling' ),
				'#default_value' => variable_get ( 'argus_hrm_workload_stages', 270 ),
				'#required' => TRUE,
				'#size' => 10 
		);
	}
	
	return system_settings_form ( $form );
}

/**
 * Page callback: Overzicht van de totale workload, afhankelijk van de instellingen en de geinstalleerde modules
 *
 *
 *
 * @return array
 */
function argus_hrm_workload_overview() {
	$schoolyear = ( array ) argus_schoolyear ( 0, 'Y-m-d' );
	
	drupal_add_css ( drupal_get_path ( 'module', 'argus_hrm' ) . '/css/argus_hrm.css' );
	
	$data = array ();
	
	$relevant_roles = variable_get ( 'argus_hrm_workload_roles', false );
	
	if (! $relevant_roles) {
		global $base_url;
		argus_report ( 'Module HRM: workload is not correctly set; please visit the <a href="' . $base_url . '/admin/config/argus/hrm-workload">admin-pages</a>.' );
	}
	
	// Get all prospected users
	$default_user = array (
			'name' => null,
			'springuren' => 0,
			'plage-uren' => 0,
			'substitute' => false,
			'supervision_kort-effectief' => 0,
			'supervision_kort-vervanger' => 0,
			'supervision_lang-effectief' => 0,
			'supervision_lang-vervanger' => 0,
			'ktt' => 0,
			'ktt_lln' => 0,
			'hktt' => 0,
			'hktt_lln' => 0,
			'stages' => 0,
			'roles' => array (),
			'roles_count' => 0,
			'score' => 0 
	);
	
	$data ['users'] = array ();
	$query = 'SELECT DISTINCT(u.uid) AS id ' . 'FROM {users} AS u ' . 'INNER JOIN {users_roles} AS ur ON u.uid = ur.uid ' . 'WHERE ur.rid IN (:rids) AND status = 1';
	$result = array_keys ( db_query ( $query, array (
			':rids' => $relevant_roles 
	) )->fetchAllAssoc ( 'id', PDO::FETCH_NAMED ) );
	
	foreach ( $result as $uid ) {
		$data ['users'] [$uid] = $default_user;
		$data ['users'] [$uid] ['name'] = argus_get_user_realname ( $uid );
	}
	
	// Data related to roles and their value
	$roles = user_roles ();
	foreach ( $roles as $rid => $role ) {
		$skore = variable_get ( 'argus_hrm_workload_role-' . $rid, 0 );
		if ($skore) {
			$role = user_role_load ( $rid );
			$query = 'SELECT uid FROM {users_roles} WHERE rid = :rid';
			$users = db_query ( $query, array (
					':rid' => $rid 
			) )->fetchAllAssoc ( 'uid' );
			foreach ( $users as $uid => $d ) {
				if (array_key_exists ( $uid, $data ['users'] )) {
					$data ['users'] [$uid] ['score'] += $skore;
					$data ['users'] [$uid] ['roles'] [] = $role->name;
					$data ['users'] [$uid] ['roles_count'] = count ( $data ['users'] [$uid] ['roles'] );
				}
			}
		}
	}
	
	// Data related to module 'argus - Uurroosters'
	if (module_exists ( 'argus_uurrooster' )) {
		// Get users 'springuren'
		foreach ( $data ['users'] as $uid => $username ) {
			$factor = argus_uurrooster_get_springuren ( $uid );
			$data ['users'] [$uid] ['springuren'] = $factor;
			$data ['users'] [$uid] ['score'] += $factor * variable_get ( 'argus_hrm_workload_springuren', 50 );
			
			$assignment = argus_uurrooster_get_assignment ( $uid );
			$data ['users'] [$uid] ['plage-uren'] = $assignment ['plage'];
			$data ['users'] [$uid] ['score'] += $factor * variable_get ( 'argus_hrm_workload_plage-uren', 50 );
		}
		
		// Get user candidate substitutes
		$query = 'SELECT DISTINCT(u.uid) AS id ' . 'FROM {users} AS u ' . 'INNER JOIN {users_roles} AS ur ON u.uid = ur.uid ' . 'WHERE u.uid NOT IN (:uidsNOK) AND ur.rid IN (:rids) AND status = 1';
		$data ['availableSubstitutes'] = array_keys ( db_query ( $query, array (
				':uidsNOK' => variable_get ( 'argus_uurrooster_substitutions_exemptions' ),
				':rids' => variable_get ( 'argus_uurrooster_substitutions_roles' ) 
		) )->fetchAllAssoc ( 'id', PDO::FETCH_NAMED ) );
		
		// Get user candidate supervisors
		$query = 'SELECT DISTINCT(u.uid) AS id ' . 'FROM {users} AS u ' . 'INNER JOIN {users_roles} AS ur ON u.uid = ur.uid ' . 'WHERE u.uid NOT IN (:uidsNOK) AND ur.rid IN (:rids) AND status = 1';
		$data ['availableSupervisors'] = array_keys ( db_query ( $query, array (
				':uidsNOK' => variable_get ( 'argus_uurrooster_supervisions_exemptions' ),
				':rids' => variable_get ( 'argus_uurrooster_supervisions_roles' ) 
		) )->fetchAllAssoc ( 'id', PDO::FETCH_NAMED ) );
		
		// Get all substitutions
		$query = 'SELECT DISTINCT(u.field_uurrooster_perm_vervanger_target_id) AS id ' . 'FROM {field_data_field_uurrooster_perm_vervanger} AS u';
		$result = array_keys ( db_query ( $query )->fetchAllAssoc ( 'id', PDO::FETCH_NAMED ) );
		foreach ( $data ['users'] as $uid => $username ) {
			if (in_array ( $uid, $result )) {
				$data ['users'] [$uid] ['substitute'] = true;
				$data ['users'] [$uid] ['score'] += variable_get ( 'argus_hrm_workload_substitutes', 50 );
			}
		}
		
		// Get all supervisions, short and fixed
		foreach ( array (
				'kort',
				'lang' 
		) as $tl ) {
			foreach ( array (
					'effectief',
					'vervanger' 
			) as $tt ) {
				$query = 'SELECT u.field_uurrooster_toez_toezichter_target_id AS id, COUNT(u.field_uurrooster_toez_toezichter_target_id) AS amount ' . 'FROM {field_data_field_uurrooster_toez_toezichter} AS u ' . 'INNER JOIN {field_data_field_uurrooster_toez_locatie} AS l ON l.entity_id = u.entity_id ' . 'INNER JOIN {field_data_field_uurrooster_toez_type} AS tt ON tt.entity_id = l.field_uurrooster_toez_locatie_target_id ' . 'INNER JOIN {field_data_field_uurrooster_toez_lengte} AS tl ON tl.entity_id = l.field_uurrooster_toez_locatie_target_id ' . 'WHERE tt.field_uurrooster_toez_type_value = :type AND tl.field_uurrooster_toez_lengte_value = :lengte ' . 'GROUP BY u.field_uurrooster_toez_toezichter_target_id';
				$result = db_query ( $query, array (
						':type' => $tt,
						':lengte' => $tl 
				) )->fetchAllAssoc ( 'id', PDO::FETCH_NAMED );
				
				foreach ( $data ['users'] as $uid => $username ) {
					if (array_key_exists ( $uid, $result )) {
						switch (array (
								$tl,
								$tt 
						)) {
							case array (
									'kort',
									'effectief' 
							) :
								$data ['users'] [$uid] ['supervision_kort-effectief'] = $result [$uid] ['amount'];
								$data ['users'] [$uid] ['score'] += $result [$uid] ['amount'] * variable_get ( 'argus_hrm_workload_toezicht-kort-effectief', 10 );
								break;
							case array (
									'kort',
									'vervanger' 
							) :
								$data ['users'] [$uid] ['supervision_kort-vervanger'] = $result [$uid] ['amount'];
								$data ['users'] [$uid] ['score'] += $result [$uid] ['amount'] * variable_get ( 'argus_hrm_workload_toezicht-kort-vervanger', 5 );
								break;
							case array (
									'lang',
									'effectief' 
							) :
								$data ['users'] [$uid] ['supervision_lang-effectief'] = $result [$uid] ['amount'];
								$data ['users'] [$uid] ['score'] += $result [$uid] ['amount'] * variable_get ( 'argus_hrm_workload_toezicht-lang-effectief', 30 );
								break;
							case array (
									'lang',
									'vervanger' 
							) :
								$data ['users'] [$uid] ['supervision_lang-vervanger'] = $result [$uid] ['amount'];
								$data ['users'] [$uid] ['score'] += $result [$uid] ['amount'] * variable_get ( 'argus_hrm_workload_toezicht-lang-vervanger', 15 );
								break;
						}
					}
				}
			}
		}
	}
	
	// Data related to module 'argus - Klasbeheer' (roles KTT & HKTT)
	if (module_exists ( 'argus_klasbeheer' )) {
		$query = 'SELECT DISTINCT n.nid AS cid, ktt.field_klas_klastitularis_target_id AS uid, COUNT(l.field_klas_leerlingen_target_id) AS lln ' . 'FROM {field_data_field_klas_klastitularis} AS ktt ' . 'INNER JOIN {node} AS n ON ktt.entity_id = n.nid ' . 'INNER JOIN {field_data_field_klas_leerlingen} AS l ON ktt.entity_id = l.entity_id ' . 'WHERE n.status ' . 'GROUP BY n.nid';
		$result = db_query ( $query, array () )->fetchAll ();
		foreach ( $result as $d ) {
			if (array_key_exists ( $d->uid, $data ['users'] )) {
				$data ['users'] [$d->uid] ['ktt'] ++;
				$data ['users'] [$d->uid] ['ktt_lln'] += $d->lln;
				$data ['users'] [$d->uid] ['score'] += $d->lln * variable_get ( 'argus_hrm_workload_ktt', 120 );
			}
		}
		
		$query = 'SELECT DISTINCT n.nid AS cid, hktt.field_klas_hulpklastitularis_target_id AS uid, COUNT(l.field_klas_leerlingen_target_id) AS lln ' . 'FROM {field_data_field_klas_hulpklastitularis} AS hktt ' . 'INNER JOIN {node} AS n ON hktt.entity_id = n.nid ' . 'INNER JOIN {field_data_field_klas_leerlingen} AS l ON hktt.entity_id = l.entity_id ' . 'WHERE n.status ' . 'GROUP BY n.nid';
		$result = db_query ( $query, array () )->fetchAll ();
		foreach ( $result as $d ) {
			if (array_key_exists ( $d->uid, $data ['users'] )) {
				$data ['users'] [$d->uid] ['hktt'] ++;
				$data ['users'] [$d->uid] ['hktt_lln'] += $d->lln;
				$data ['users'] [$d->uid] ['score'] += $d->lln * variable_get ( 'argus_hrm_workload_hktt', 30 );
			}
		}
	}
	
	// Data related to module 'argus - Stages
	if (module_exists ( 'argus_stages' )) {
		$query = 'SELECT l.field_leerkracht_target_id AS id, COUNT(n.nid) AS amount ' . 'FROM {field_data_field_leerkracht} AS l ' . 'INNER JOIN {node} AS n ON l.entity_id = n.nid ' . 'INNER JOIN {field_data_field_stage_periode} AS p ON p.entity_id = n.nid ' . 'INNER JOIN {field_data_field_tijdstip} AS t ON p.field_stage_periode_target_id = t.entity_id ' . 'WHERE n.status AND l.bundle = :bundle AND t.field_tijdstip_value BETWEEN :startdate AND :enddate ' . 'GROUP BY l.field_leerkracht_target_id';
		$result = db_query ( $query, array (
				':bundle' => 'stage',
				':startdate' => $schoolyear ['start'],
				':enddate' => $schoolyear ['end'] 
		) )->fetchAllKeyed ( 0, 1 );
		foreach ( $result as $uid => $amount ) {
			if (array_key_exists ( $uid, $data ['users'] )) {
				$data ['users'] [$uid] ['stages'] = $amount;
				$data ['users'] [$uid] ['score'] += $amount * variable_get ( 'argus_hrm_workload_stages', 270 );
			}
		}
	}
	
	// Sort the data as requested
	$data ['order'] = 'ASC';
	if (isset ( $_GET ['order'] )) {
		if ($_GET ['order'] == 'DESC') {
			$data ['order'] = 'DESC';
		}
	}
	
	if ($data ['order'] == 'ASC') {
		asort ( $data ['users'] );
	} else {
		arsort ( $data ['users'] );
	}
	
	// Set first index as sorting index
	$data ['orderBy'] = 'name';
	if (isset ( $_GET ['s'] )) {
		if (array_key_exists ( $_GET ['s'], $default_user )) {
			$data ['orderBy'] = $_GET ['s'];
		}
	}
	
	// Sort the array by given key
	argus_engine_sortBy ( $data ['orderBy'], $data ['users'], $data ['order'] );
	
	return theme ( 'argus_hrm--overview_workload', $data );
}

/**
 * Custom module functionality
 */

/**
 * Retrieve 'plage-uren' for user
 *
 * @param
 *        	uid integer
 *        	Get reports for specified user
 *        	
 *        	
 * @return int
 */
function argus_hrm_get_plage_uren($uid) {
	$query = 'SELECT n.nid AS id, o.field_lvs_melding_onderwerp_value AS title, d.field_lvs_melding_datum_feit_value AS factdate, un.field_user_sms_naam_value AS name, uv.field_user_sms_voornaam_value AS firstname ' . 'FROM {node} AS n ' . 'LEFT JOIN {field_data_field_uurrooster_periode_periode} AS pp ON n.nid = pp.entity_id ' . 'WHERE n.type = :type AND l.field_lvs_melding_leerling_target_id = :uid AND pp.field_uurrooster_periode_periode_value > 1 ' . 'ORDER BY field_lvs_melding_datum_feit_value DESC';
	$result = db_query ( $query, array (
			':uid' => $uid,
			':type' => 'uurrooster_les' 
	) )->fetchAll ();
	dpm ( $result );
	return 1;
}
