<?php

/**
 * @file
 * Install, update, and uninstall functions for the Aankoopdossiers module.
 */

/**
 * Implementation of hook_install().
 */
function argus_hrm_install() {
	// Rebuild and define new content type
	node_types_rebuild ();
	$types = node_type_get_types ();
	
	// Add the body field with specified label
	node_add_body_field ( $types ['hrm_klasbezoek'], $label = t ( 'Verslag' ) ); // replace your label or remove if no body-field necessary
	                                                                         
	// Add field bases which are copied from your Features-based module
	// More details function argus_hrm_field_default_field_bases()
	foreach ( argus_hrm_field_default_field_bases () as $field_name => $field ) {
		if (! field_info_field ( $field_name )) {
			field_create_field ( $field );
		}
	}
	
	// Add field instances which are copied from your Features-based module
	// More details function argus_hrm_field_default_field_instances()
	foreach ( argus_hrm_field_default_field_instances () as $fieldinstance ) {
		field_create_instance ( $fieldinstance );
	}
	
	if (function_exists ( 'argus_hrm_field_group_info' )) {
		// Add field groups which are copied from your Features-based module
		// More details function argus_hrm_field_group_info()
		foreach ( argus_hrm_field_group_info () as $fieldgroup ) {
			$fieldgroup->label = $fieldgroup->data ['label'];
			$fieldgroup->weight = $fieldgroup->data ['weight'];
			$fieldgroup->children = $fieldgroup->data ['children'];
			$fieldgroup->format_type = $fieldgroup->data ['format_type'];
			$fieldgroup->format_settings = $fieldgroup->data ['format_settings'];
			
			field_group_group_save ( $fieldgroup );
		}
	}
	
	// Enable some standard blocks
	$theme = variable_get ( 'theme_default', NULL );
	$blocks = array (
			array (
					'module' => 'views',
					'delta' => 'ed7ff909669710a4abd99019aa723d85', // copy this id from your blocks definition url (/admin/structure/block/manage/views/.../configure)
					'theme' => $theme,
					'status' => 1,
					'weight' => - 10,
					'region' => 'sidebar_first', // replace with the target region for your theme
					'visibility' => BLOCK_VISIBILITY_LISTED,
					'pages' => 'hrm/evaluatiegesprekken' . chr ( 13 ) . 'hrm/evaluatiegesprekken/*', // replace with your list of pages
					'cache' => DRUPAL_CACHE_GLOBAL,
					'title' => 'Filter' 
			),
			array (
					'module' => 'views',
					'delta' => '5ad5dbd723dab77467b23ea69ce9547e', // copy this id from your blocks definition url (/admin/structure/block/manage/views/.../configure)
					'theme' => $theme,
					'status' => 1,
					'weight' => - 10,
					'region' => 'sidebar_first', // replace with the target region for your theme
					'visibility' => BLOCK_VISIBILITY_LISTED,
					'pages' => 'hrm/functioneringsgesprekken' . chr ( 13 ) . 'hrm/functioneringsgesprekken/*', // replace with your list of pages
					'cache' => DRUPAL_CACHE_GLOBAL,
					'title' => 'Filter' 
			),
			array (
					'module' => 'views',
					'delta' => 'ec940a358bbd9ac192953a7ee9ee0c01', // copy this id from your blocks definition url (/admin/structure/block/manage/views/.../configure)
					'theme' => $theme,
					'status' => 1,
					'weight' => - 10,
					'region' => 'sidebar_first', // replace with the target region for your theme
					'visibility' => BLOCK_VISIBILITY_LISTED,
					'pages' => 'hrm/flitsbezoeken' . chr ( 13 ) . 'hrm/flitsbezoeken/*', // replace with your list of pages
					'cache' => DRUPAL_CACHE_GLOBAL,
					'title' => 'Filter' 
			),
			array (
					'module' => 'views',
					'delta' => '70584c1635f813d71c2631cf69611af1', // copy this id from your blocks definition url (/admin/structure/block/manage/views/.../configure)
					'theme' => $theme,
					'status' => 1,
					'weight' => - 10,
					'region' => 'sidebar_first', // replace with the target region for your theme
					'visibility' => BLOCK_VISIBILITY_LISTED,
					'pages' => 'hrm/klasbezoeken' . chr ( 13 ) . 'hrm/klasbezoeken/*', // replace with your list of pages
					'cache' => DRUPAL_CACHE_GLOBAL,
					'title' => 'Filter' 
			),
			array (
					'module' => 'views',
					'delta' => '39990a46e29d39fe99eef5ca5d5646ef', // copy this id from your blocks definition url (/admin/structure/block/manage/views/.../configure)
					'theme' => $theme,
					'status' => 1,
					'weight' => - 10,
					'region' => 'sidebar_first', // replace with the target region for your theme
					'visibility' => BLOCK_VISIBILITY_LISTED,
					'pages' => 'hrm/planningsgesprekken' . chr ( 13 ) . 'hrm/planningsgesprekken/*', // replace with your list of pages
					'cache' => DRUPAL_CACHE_GLOBAL,
					'title' => 'Filter' 
			),
	);
	
	foreach ( $blocks as $block ) {
		db_merge ( 'block' )->key ( array (
				'module' => $block ['module'],
				'delta' => $block ['delta'],
				'theme' => $block ['theme'] 
		) )->fields ( array (
				'status' => $block ['status'],
				'weight' => $block ['weight'],
				'region' => $block ['region'],
				'visibility' => $block ['visibility'],
				'pages' => $block ['pages'],
				'cache' => $block ['cache'],
				'title' => $block ['title'] 
		) )->execute ();
	}
}

/**
 * Implementation of hook_uninstall().
 */
function argus_hrm_uninstall() {
	$newTypes = array (
			'hrm_klasbezoek',
			'hrm_flitsbezoek',
			'hrm_planningsgesprek',
			'hrm_functioneringsgesprek',
			'hrm_evaluatiegesprek' 
	);
	
	foreach ( $newTypes as $type ) {
		// Remove all nodes of new content type
		$sql = 'SELECT nid FROM {node} n WHERE n.type = :type';
		$result = db_query ( $sql, array (
				':type' => $type 
		) );
		$nodeids = array ();
		foreach ( $result as $row ) {
			$nodeids [] = $row->nid;
		}
		node_delete_multiple ( $nodeids );
	}
	
	// Delete all related fields
	foreach ( argus_hrm_field_default_field_bases () as $field_name => $field ) {
		$field_info = field_info_field ( $field_name );
		if (count ( $field_info ['bundles'] ['node'] ) < 2) { // Check if field is enabled for other modules
			field_delete_field ( $field_name );
		}
	}
	
	foreach ( $newTypes as $type ) {
		$instances = field_info_instances ( 'node', $type );
		foreach ( $instances as $instance_name => $fieldinstance ) {
			field_delete_instance ( $fieldinstance );
		}
	}
	
	if (function_exists ( 'argus_hrm_field_group_info' )) {
		// Delete all field-groups
		foreach ( argus_hrm_field_group_info () as $fieldgroup ) {
			$fieldgroup = field_group_load_field_group_by_identifier ( $fieldgroup->identifier );
			if ($fieldgroup) {
				field_group_group_export_delete ( $fieldgroup );
			}
		}
	}
	
	foreach ( $newTypes as $type ) {
		// Remove new content type
		node_type_delete ( $type );
	}
	
	// Remove blocks
	if (db_table_exists ( 'block' )) {
		db_delete ( 'block' )->condition ( 'module', 'argus_hrm' )->execute ();
	}
}

/**
 * Implements hook_field_default_field_bases().
 *
 * This function is copied from the file generated by the Features module: demo.features.field_base.inc
 */
function argus_hrm_field_default_field_bases() {
	$field_bases = array ();
	
	// Exported field_base: 'field_bijlage'.
	$field_bases ['field_bijlage'] = array (
			'active' => 1,
			'cardinality' => - 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_bijlage',
			'field_permissions' => array (
					'type' => 1 
			),
			'indexes' => array (
					'fid' => array (
							0 => 'fid' 
					) 
			),
			'locked' => 0,
			'module' => 'file',
			'settings' => array (
					'display_default' => 0,
					'display_field' => 0,
					'uri_scheme' => 'private' 
			),
			'translatable' => 0,
			'type' => 'file' 
	);
	
	// Exported field_base: 'field_datum'.
	$field_bases ['field_datum'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_datum',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (),
			'locked' => 0,
			'module' => 'date',
			'settings' => array (
					'cache_count' => 4,
					'cache_enabled' => 0,
					'granularity' => array (
							'day' => 'day',
							'hour' => 0,
							'minute' => 0,
							'month' => 'month',
							'second' => 0,
							'year' => 'year' 
					),
					'repeat' => 0,
					'timezone_db' => '',
					'todate' => 'optional',
					'tz_handling' => 'none' 
			),
			'translatable' => 0,
			'type' => 'datetime' 
	);
	
	// Exported field_base: 'field_eg1_positieve_observaties'.
	$field_bases ['field_eg1_positieve_observaties'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_eg1_positieve_observaties',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_eg1_werkpunten_afspraken'.
	$field_bases ['field_eg1_werkpunten_afspraken'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_eg1_werkpunten_afspraken',
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_eg2_positieve_observaties'.
	$field_bases ['field_eg2_positieve_observaties'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_eg2_positieve_observaties',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_eg2_werkpunten_afspraken'.
	$field_bases ['field_eg2_werkpunten_afspraken'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_eg2_werkpunten_afspraken',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_eg3_positieve_observaties'.
	$field_bases ['field_eg3_positieve_observaties'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_eg3_positieve_observaties',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_eg3_werkpunten_afspraken'.
	$field_bases ['field_eg3_werkpunten_afspraken'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_eg3_werkpunten_afspraken',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_eg4_positieve_observaties'.
	$field_bases ['field_eg4_positieve_observaties'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_eg4_positieve_observaties',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_eg4_werkpunten_afspraken'.
	$field_bases ['field_eg4_werkpunten_afspraken'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_eg4_werkpunten_afspraken',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_eg5_positieve_observaties'.
	$field_bases ['field_eg5_positieve_observaties'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_eg5_positieve_observaties',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_eg5_werkpunten_afspraken'.
	$field_bases ['field_eg5_werkpunten_afspraken'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_eg5_werkpunten_afspraken',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_eg6_positieve_observaties'.
	$field_bases ['field_eg6_positieve_observaties'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_eg6_positieve_observaties',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_eg6_werkpunten_afspraken'.
	$field_bases ['field_eg6_werkpunten_afspraken'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_eg6_werkpunten_afspraken',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_eg7_positieve_observaties'.
	$field_bases ['field_eg7_positieve_observaties'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_eg7_positieve_observaties',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_eg7_werkpunten_afspraken'.
	$field_bases ['field_eg7_werkpunten_afspraken'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_eg7_werkpunten_afspraken',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_eg8_positieve_observaties'.
	$field_bases ['field_eg8_positieve_observaties'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_eg8_positieve_observaties',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_eg8_werkpunten_afspraken'.
	$field_bases ['field_eg8_werkpunten_afspraken'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_eg8_werkpunten_afspraken',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_eg9_positieve_observaties'.
	$field_bases ['field_eg9_positieve_observaties'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_eg9_positieve_observaties',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_eg9_werkpunten_afspraken'.
	$field_bases ['field_eg9_werkpunten_afspraken'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_eg9_werkpunten_afspraken',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_eg_beoordeling'.
	$field_bases ['field_eg_beoordeling'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_eg_beoordeling',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'value' => array (
							0 => 'value' 
					) 
			),
			'locked' => 0,
			'module' => 'list',
			'settings' => array (
					'allowed_values' => array (
							'voldoende' => 'voldoende',
							'onvoldoende' => 'onvoldoende' 
					),
					'allowed_values_function' => '' 
			),
			'translatable' => 0,
			'type' => 'list_text' 
	);
	
	// Exported field_base: 'field_eg_eindconclusie'.
	$field_bases ['field_eg_eindconclusie'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_eg_eindconclusie',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_evaluatiegesprek_status'.
	$field_bases ['field_evaluatiegesprek_status'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_evaluatiegesprek_status',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'value' => array (
							0 => 'value' 
					) 
			),
			'locked' => 0,
			'module' => 'list',
			'settings' => array (
					'allowed_values' => array (
							'nieuw' => 'nieuw',
							'uitnodiging verstuurd' => 'uitnodiging verstuurd',
							'ontvangst uitnodiging bevestigd' => 'ontvangst uitnodiging bevestigd',
							'uitgevoerd' => 'uitgevoerd',
							'bezwaar ontvangen' => 'bezwaar ontvangen',
							'dossier bijgewerkt' => 'dossier bijgewerkt',
							'verslag verstuurd naar RvB van de SGR' => 'verslag verstuurd naar RvB van de SGR' 
					),
					'allowed_values_function' => '' 
			),
			'translatable' => 0,
			'type' => 'list_text' 
	);
	
	// Exported field_base: 'field_flitsbezoek_interventies'.
	$field_bases ['field_flitsbezoek_interventies'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_flitsbezoek_interventies',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_flitsbezoek_leerdoel'.
	$field_bases ['field_flitsbezoek_leerdoel'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_flitsbezoek_leerdoel',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_flitsbezoek_leerlingen'.
	$field_bases ['field_flitsbezoek_leerlingen'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_flitsbezoek_leerlingen',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_flitsbezoek_lokaal'.
	$field_bases ['field_flitsbezoek_lokaal'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_flitsbezoek_lokaal',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_flitsbezoek_preventie'.
	$field_bases ['field_flitsbezoek_preventie'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_flitsbezoek_preventie',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_functioneringsg_status'.
	$field_bases ['field_functioneringsg_status'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_functioneringsg_status',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'value' => array (
							0 => 'value' 
					) 
			),
			'locked' => 0,
			'module' => 'list',
			'settings' => array (
					'allowed_values' => array (
							'nieuw' => 'nieuw',
							'uitnodiging verstuurd' => 'uitnodiging verstuurd',
							'ontvangst uitnodiging bevestigd' => 'ontvangst uitnodiging bevestigd',
							'uitgevoerd' => 'uitgevoerd',
							'dossier bijgewerkt' => 'dossier bijgewerkt' 
					),
					'allowed_values_function' => '' 
			),
			'translatable' => 0,
			'type' => 'list_text' 
	);
	
	// Exported field_base: 'field_inhoud_van_dit_gesprek'.
	$field_bases ['field_inhoud_van_dit_gesprek'] = array (
			'active' => 1,
			'cardinality' => - 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_inhoud_van_dit_gesprek',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'value' => array (
							0 => 'value' 
					) 
			),
			'locked' => 0,
			'module' => 'list',
			'settings' => array (
					'allowed_values' => array (
							'Bespreking functiebeschrijving' => 'Bespreking functiebeschrijving',
							'Bespreking extra taken' => 'Bespreking extra taken',
							'Eventuele problemen en oplossingen' => 'Eventuele problemen en oplossingen' 
					),
					'allowed_values_function' => '' 
			),
			'translatable' => 0,
			'type' => 'list_text' 
	);
	
	// Exported field_base: 'field_klasbezoek_activiteit'.
	$field_bases ['field_klasbezoek_activiteit'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_klasbezoek_activiteit',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (
					'max_length' => 255 
			),
			'translatable' => 0,
			'type' => 'text' 
	);
	
	// Exported field_base: 'field_klasbezoek_afspraken'.
	$field_bases ['field_klasbezoek_afspraken'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_klasbezoek_afspraken',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_with_summary' 
	);
	
	// Exported field_base: 'field_klasbezoek_andere_focus'.
	$field_bases ['field_klasbezoek_andere_focus'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_klasbezoek_andere_focus',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (
					'max_length' => 255 
			),
			'translatable' => 0,
			'type' => 'text' 
	);
	
	// Exported field_base: 'field_klasbezoek_did_comp'.
	$field_bases ['field_klasbezoek_did_comp'] = array (
			'active' => 1,
			'cardinality' => - 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_klasbezoek_did_comp',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'value' => array (
							0 => 'value' 
					) 
			),
			'locked' => 0,
			'module' => 'list',
			'settings' => array (
					'allowed_values' => array (
							'Keuze en hanteren van de leerplandoelstellingen en inhouden' => 'Keuze en hanteren van de leerplandoelstellingen en inhouden',
							'Keuze en hanteren van werkvormen' => 'Keuze en hanteren van werkvormen',
							'Keuze en hanteren van de leermiddelen' => 'Keuze en hanteren van de leermiddelen',
							'Keuze en praktijk van evaluatie, reflectie en rapporteren' => 'Keuze en praktijk van evaluatie, reflectie en rapporteren',
							'Omgaan met verschillen' => 'Omgaan met verschillen' 
					),
					'allowed_values_function' => '' 
			),
			'translatable' => 0,
			'type' => 'list_text' 
	);
	
	// Exported field_base: 'field_klasbezoek_org_comp'.
	$field_bases ['field_klasbezoek_org_comp'] = array (
			'active' => 1,
			'cardinality' => - 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_klasbezoek_org_comp',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'value' => array (
							0 => 'value' 
					) 
			),
			'locked' => 0,
			'module' => 'list',
			'settings' => array (
					'allowed_values' => array (
							'Algemeen klasmanagement' => 'Algemeen klasmanagement',
							'De klas inrichten en aankleden' => 'De klas inrichten en aankleden' 
					),
					'allowed_values_function' => '' 
			),
			'translatable' => 0,
			'type' => 'list_text' 
	);
	
	// Exported field_base: 'field_klasbezoek_ped_comp'.
	$field_bases ['field_klasbezoek_ped_comp'] = array (
			'active' => 1,
			'cardinality' => - 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_klasbezoek_ped_comp',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'value' => array (
							0 => 'value' 
					) 
			),
			'locked' => 0,
			'module' => 'list',
			'settings' => array (
					'allowed_values' => array (
							'Een positief en veilig leerklimaat' => 'Een positief en veilig leerklimaat',
							'Leerlingenparticipatie' => 'Leerlingenparticipatie',
							'Leerbegeleiding' => 'Leerbegeleiding',
							'Waarden en normen' => 'Waarden en normen',
							'Gender' => 'Gender' 
					),
					'allowed_values_function' => '' 
			),
			'translatable' => 0,
			'type' => 'list_text' 
	);
	
	// Exported field_base: 'field_klasbezoek_taalcomp'.
	$field_bases ['field_klasbezoek_taalcomp'] = array (
			'active' => 1,
			'cardinality' => - 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_klasbezoek_taalcomp',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'value' => array (
							0 => 'value' 
					) 
			),
			'locked' => 0,
			'module' => 'list',
			'settings' => array (
					'allowed_values' => array (
							'Vakinhoud en context' => 'Vakinhoud en context',
							'Vak en interactie' => 'Vak en interactie',
							'Vak en taalsteun' => 'Vak en taalsteun' 
					),
					'allowed_values_function' => '' 
			),
			'translatable' => 0,
			'type' => 'list_text' 
	);
	
	// Exported field_base: 'field_klasbezoek_vorigeafspraken'.
	$field_bases ['field_klasbezoek_vorigeafspraken'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_klasbezoek_vorigeafspraken',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_klasbezoek_zelfreflectie'.
	$field_bases ['field_klasbezoek_zelfreflectie'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_klasbezoek_zelfreflectie',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_with_summary' 
	);
	
	// Exported field_base: 'field_personeelslid'.
	$field_bases ['field_personeelslid'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_personeelslid',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'target_id' => array (
							0 => 'target_id' 
					) 
			),
			'locked' => 0,
			'module' => 'entityreference',
			'settings' => array (
					'handler' => 'views',
					'handler_settings' => array (
							'behaviors' => array (
									'views-select-list' => array (
											'status' => 0 
									) 
							),
							'view' => array (
									'args' => array (),
									'display_name' => 'users_personeel',
									'view_name' => 'gebruikers' 
							) 
					),
					'target_type' => 'user' 
			),
			'translatable' => 0,
			'type' => 'entityreference' 
	);
	
	// Exported field_base: 'field_pg_eventuele_oplossing'.
	$field_bases ['field_pg_eventuele_oplossing'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_pg_eventuele_oplossing',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_pg_probleemidentificatie'.
	$field_bases ['field_pg_probleemidentificatie'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_pg_probleemidentificatie',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_planningsgesprek_status'.
	$field_bases ['field_planningsgesprek_status'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_planningsgesprek_status',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'value' => array (
							0 => 'value' 
					) 
			),
			'locked' => 0,
			'module' => 'list',
			'settings' => array (
					'allowed_values' => array (
							'nieuw' => 'nieuw',
							'uitnodiging verstuurd' => 'uitnodiging verstuurd',
							'ontvangst uitnodiging bevestigd' => 'ontvangst uitnodiging bevestigd',
							'uitgevoerd' => 'uitgevoerd',
							'dossier bijgewerkt' => 'dossier bijgewerkt' 
					),
					'allowed_values_function' => '' 
			),
			'translatable' => 0,
			'type' => 'list_text' 
	);
	
	// Exported field_base: 'field_prioriteiten_volgens_evalu'.
	$field_bases ['field_prioriteiten_volgens_evalu'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_prioriteiten_volgens_evalu',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_tijdstip'.
	$field_bases ['field_tijdstip'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_tijdstip',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (),
			'locked' => 0,
			'module' => 'date',
			'settings' => array (
					'cache_count' => 4,
					'cache_enabled' => 0,
					'granularity' => array (
							'day' => 'day',
							'hour' => 'hour',
							'minute' => 'minute',
							'month' => 'month',
							'second' => 0,
							'year' => 'year' 
					),
					'repeat' => 0,
					'timezone_db' => '',
					'todate' => 'required',
					'tz_handling' => 'none' 
			),
			'translatable' => 0,
			'type' => 'datetime' 
	);
	
	// Exported field_base: 'field_voorgestelde_punten_evalua'.
	$field_bases ['field_voorgestelde_punten_evalua'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_voorgestelde_punten_evalua',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	// Exported field_base: 'field_voorgestelde_punten_person'.
	$field_bases ['field_voorgestelde_punten_person'] = array (
			'active' => 1,
			'cardinality' => 1,
			'deleted' => 0,
			'entity_types' => array (),
			'field_name' => 'field_voorgestelde_punten_person',
			'field_permissions' => array (
					'type' => 0 
			),
			'indexes' => array (
					'format' => array (
							0 => 'format' 
					) 
			),
			'locked' => 0,
			'module' => 'text',
			'settings' => array (),
			'translatable' => 0,
			'type' => 'text_long' 
	);
	
	return $field_bases;
}

/**
 * Implements hook_field_default_field_instances().
 *
 * This function is copied from the file generated by the Features module: demo.features.field_base.inc
 */
function argus_hrm_field_default_field_instances() {
	$field_instances = array ();
	
	// Exported field_instance: 'node-hrm_evaluatiegesprek-field_datum'.
	$field_instances ['node-hrm_evaluatiegesprek-field_datum'] = array (
			'bundle' => 'hrm_evaluatiegesprek',
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'date',
							'settings' => array (
									'conditions' => array (),
									'format_type' => 'long',
									'fromto' => 'both',
									'multiple_from' => '',
									'multiple_number' => '',
									'multiple_to' => '',
									'show_remaining_days' => FALSE,
									'show_repeat_rule' => 'show' 
							),
							'type' => 'date_default',
							'weight' => 16 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_datum',
			'label' => 'Periode van toepassing',
			'required' => 0,
			'settings' => array (
					'default_value' => 'now',
					'default_value2' => 'same',
					'default_value_code' => '',
					'default_value_code2' => '',
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'date',
					'settings' => array (
							'display_all_day' => 0,
							'increment' => 15,
							'input_format' => 'd/m/Y - H:i:s',
							'input_format_custom' => '',
							'label_position' => 'above',
							'no_fieldset' => 0,
							'repeat_collapsed' => 0,
							'text_parts' => array (),
							'year_range' => '-3:+3' 
					),
					'type' => 'date_popup',
					'weight' => 3 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_evaluatiegesprek-field_eg1_positieve_observaties'.
	$field_instances ['node-hrm_evaluatiegesprek-field_eg1_positieve_observaties'] = array (
			'bundle' => 'hrm_evaluatiegesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 2 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_eg1_positieve_observaties',
			'label' => 'Positieve observaties',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 7 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_evaluatiegesprek-field_eg1_werkpunten_afspraken'.
	$field_instances ['node-hrm_evaluatiegesprek-field_eg1_werkpunten_afspraken'] = array (
			'bundle' => 'hrm_evaluatiegesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 16 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_eg1_werkpunten_afspraken',
			'label' => 'Werkpunten en afspraken',
			'required' => FALSE,
			'settings' => array (
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 9 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_evaluatiegesprek-field_eg2_positieve_observaties'.
	$field_instances ['node-hrm_evaluatiegesprek-field_eg2_positieve_observaties'] = array (
			'bundle' => 'hrm_evaluatiegesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 4 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_eg2_positieve_observaties',
			'label' => 'Positieve observaties',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 9 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_evaluatiegesprek-field_eg2_werkpunten_afspraken'.
	$field_instances ['node-hrm_evaluatiegesprek-field_eg2_werkpunten_afspraken'] = array (
			'bundle' => 'hrm_evaluatiegesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 15 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_eg2_werkpunten_afspraken',
			'label' => 'Werkpunten en afspraken',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 10 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_evaluatiegesprek-field_eg3_positieve_observaties'.
	$field_instances ['node-hrm_evaluatiegesprek-field_eg3_positieve_observaties'] = array (
			'bundle' => 'hrm_evaluatiegesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 5 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_eg3_positieve_observaties',
			'label' => 'Positieve observaties',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 10 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_evaluatiegesprek-field_eg3_werkpunten_afspraken'.
	$field_instances ['node-hrm_evaluatiegesprek-field_eg3_werkpunten_afspraken'] = array (
			'bundle' => 'hrm_evaluatiegesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 17 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_eg3_werkpunten_afspraken',
			'label' => 'Werkpunten en afspraken',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 11 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_evaluatiegesprek-field_eg4_positieve_observaties'.
	$field_instances ['node-hrm_evaluatiegesprek-field_eg4_positieve_observaties'] = array (
			'bundle' => 'hrm_evaluatiegesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 6 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_eg4_positieve_observaties',
			'label' => 'Positieve observaties',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 12 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_evaluatiegesprek-field_eg4_werkpunten_afspraken'.
	$field_instances ['node-hrm_evaluatiegesprek-field_eg4_werkpunten_afspraken'] = array (
			'bundle' => 'hrm_evaluatiegesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 20 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_eg4_werkpunten_afspraken',
			'label' => 'Werkpunten en afspraken',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 13 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_evaluatiegesprek-field_eg5_positieve_observaties'.
	$field_instances ['node-hrm_evaluatiegesprek-field_eg5_positieve_observaties'] = array (
			'bundle' => 'hrm_evaluatiegesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 7 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_eg5_positieve_observaties',
			'label' => 'Positieve observaties',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 13 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_evaluatiegesprek-field_eg5_werkpunten_afspraken'.
	$field_instances ['node-hrm_evaluatiegesprek-field_eg5_werkpunten_afspraken'] = array (
			'bundle' => 'hrm_evaluatiegesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 19 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_eg5_werkpunten_afspraken',
			'label' => 'Werkpunten en afspraken',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 14 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_evaluatiegesprek-field_eg6_positieve_observaties'.
	$field_instances ['node-hrm_evaluatiegesprek-field_eg6_positieve_observaties'] = array (
			'bundle' => 'hrm_evaluatiegesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 8 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_eg6_positieve_observaties',
			'label' => 'Positieve observaties',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 14 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_evaluatiegesprek-field_eg6_werkpunten_afspraken'.
	$field_instances ['node-hrm_evaluatiegesprek-field_eg6_werkpunten_afspraken'] = array (
			'bundle' => 'hrm_evaluatiegesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 21 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_eg6_werkpunten_afspraken',
			'label' => 'Werkpunten en afspraken',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 15 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_evaluatiegesprek-field_eg7_positieve_observaties'.
	$field_instances ['node-hrm_evaluatiegesprek-field_eg7_positieve_observaties'] = array (
			'bundle' => 'hrm_evaluatiegesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 9 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_eg7_positieve_observaties',
			'label' => 'Positieve observaties',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 15 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_evaluatiegesprek-field_eg7_werkpunten_afspraken'.
	$field_instances ['node-hrm_evaluatiegesprek-field_eg7_werkpunten_afspraken'] = array (
			'bundle' => 'hrm_evaluatiegesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 22 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_eg7_werkpunten_afspraken',
			'label' => 'Werkpunten en afspraken',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 16 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_evaluatiegesprek-field_eg8_positieve_observaties'.
	$field_instances ['node-hrm_evaluatiegesprek-field_eg8_positieve_observaties'] = array (
			'bundle' => 'hrm_evaluatiegesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 10 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_eg8_positieve_observaties',
			'label' => 'Positieve observaties',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 16 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_evaluatiegesprek-field_eg8_werkpunten_afspraken'.
	$field_instances ['node-hrm_evaluatiegesprek-field_eg8_werkpunten_afspraken'] = array (
			'bundle' => 'hrm_evaluatiegesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 18 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_eg8_werkpunten_afspraken',
			'label' => 'Werkpunten en afspraken',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 18 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_evaluatiegesprek-field_eg9_positieve_observaties'.
	$field_instances ['node-hrm_evaluatiegesprek-field_eg9_positieve_observaties'] = array (
			'bundle' => 'hrm_evaluatiegesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 11 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_eg9_positieve_observaties',
			'label' => 'Positieve observaties',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 17 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_evaluatiegesprek-field_eg9_werkpunten_afspraken'.
	$field_instances ['node-hrm_evaluatiegesprek-field_eg9_werkpunten_afspraken'] = array (
			'bundle' => 'hrm_evaluatiegesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 12 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_eg9_werkpunten_afspraken',
			'label' => 'Werkpunten en afspraken',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 18 
			) 
	);
	
	// Exported field_instance: 'node-hrm_evaluatiegesprek-field_eg_beoordeling'.
	$field_instances ['node-hrm_evaluatiegesprek-field_eg_beoordeling'] = array (
			'bundle' => 'hrm_evaluatiegesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'list',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'list_default',
							'weight' => 24 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_eg_beoordeling',
			'label' => 'Beoordeling',
			'required' => 0,
			'settings' => array (
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'options',
					'settings' => array (
							'apply_chosen' => '' 
					),
					'type' => 'options_buttons',
					'weight' => 13 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_evaluatiegesprek-field_eg_eindconclusie'.
	$field_instances ['node-hrm_evaluatiegesprek-field_eg_eindconclusie'] = array (
			'bundle' => 'hrm_evaluatiegesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 23 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_eg_eindconclusie',
			'label' => 'Eindconclusie',
			'required' => 0,
			'settings' => array (
					'display_summary' => 0,
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 1,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 20,
							'summary_rows' => 5 
					),
					'type' => 'text_textarea_with_summary',
					'weight' => 12 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_evaluatiegesprek-field_evaluatiegesprek_status'.
	$field_instances ['node-hrm_evaluatiegesprek-field_evaluatiegesprek_status'] = array (
			'bundle' => 'hrm_evaluatiegesprek',
			'default_value' => array (
					0 => array (
							'value' => 'nieuw' 
					) 
			),
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'list',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'list_default',
							'weight' => 0 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_evaluatiegesprek_status',
			'label' => 'Status',
			'required' => 1,
			'settings' => array (
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'options',
					'settings' => array (
							'apply_chosen' => '' 
					),
					'type' => 'options_select',
					'weight' => 2 
			) 
	);
	
	// Exported field_instance: 'node-hrm_evaluatiegesprek-field_personeelslid'.
	$field_instances ['node-hrm_evaluatiegesprek-field_personeelslid'] = array (
			'bundle' => 'hrm_evaluatiegesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'entityreference',
							'settings' => array (
									'conditions' => array (),
									'link' => FALSE 
							),
							'type' => 'entityreference_label',
							'weight' => 1 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_personeelslid',
			'label' => 'Personeelslid',
			'required' => 1,
			'settings' => array (
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'entityreference',
					'settings' => array (
							'match_operator' => 'CONTAINS',
							'path' => '',
							'size' => 60 
					),
					'type' => 'entityreference_autocomplete',
					'weight' => 0 
			) 
	);
	
	// Exported field_instance: 'node-hrm_evaluatiegesprek-field_tijdstip'.
	$field_instances ['node-hrm_evaluatiegesprek-field_tijdstip'] = array (
			'bundle' => 'hrm_evaluatiegesprek',
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'date',
							'settings' => array (
									'conditions' => array (),
									'format_type' => 'long',
									'fromto' => 'both',
									'multiple_from' => '',
									'multiple_number' => '',
									'multiple_to' => '',
									'show_remaining_days' => FALSE,
									'show_repeat_rule' => 'show' 
							),
							'type' => 'date_default',
							'weight' => 3 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_tijdstip',
			'label' => 'Tijdstip',
			'required' => 1,
			'settings' => array (
					'default_value' => 'now',
					'default_value2' => 'same',
					'default_value_code' => '',
					'default_value_code2' => '',
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'date',
					'settings' => array (
							'display_all_day' => 0,
							'increment' => 15,
							'input_format' => 'd/m/Y - H:i:s',
							'input_format_custom' => '',
							'label_position' => 'above',
							'no_fieldset' => 0,
							'repeat_collapsed' => 0,
							'text_parts' => array (),
							'year_range' => '-3:+3' 
					),
					'type' => 'date_popup',
					'weight' => 1 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_flitsbezoek-field_flitsbezoek_interventies'.
	$field_instances ['node-hrm_flitsbezoek-field_flitsbezoek_interventies'] = array (
			'bundle' => 'hrm_flitsbezoek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => 'Welke interventies doet de leerkracht om te zorgen dat alle leerlingen het leerdoel behalen?',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 5 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_flitsbezoek_interventies',
			'label' => 'Interventies',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 7 
			) 
	);
	
	// Exported field_instance: 'node-hrm_flitsbezoek-field_flitsbezoek_leerdoel'.
	$field_instances ['node-hrm_flitsbezoek-field_flitsbezoek_leerdoel'] = array (
			'bundle' => 'hrm_flitsbezoek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => 'Wat is het leerdoel van de les en in hoeverre zijn de lesactiviteiten in lijn met dit doel?',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 4 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_flitsbezoek_leerdoel',
			'label' => 'Leerdoel',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 6 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_flitsbezoek-field_flitsbezoek_leerlingen'.
	$field_instances ['node-hrm_flitsbezoek-field_flitsbezoek_leerlingen'] = array (
			'bundle' => 'hrm_flitsbezoek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => 'Doen de leerlingen wat ze moeten doen?',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 3 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_flitsbezoek_leerlingen',
			'label' => 'Leerlingen',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 5 
			) 
	);
	
	// Exported field_instance: 'node-hrm_flitsbezoek-field_flitsbezoek_lokaal'.
	$field_instances ['node-hrm_flitsbezoek-field_flitsbezoek_lokaal'] = array (
			'bundle' => 'hrm_flitsbezoek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => 'Muren scannen: wat hangt er allemaal in het leslokaal dat bijdraagt (of juist niet) aan de lessen?',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 6 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_flitsbezoek_lokaal',
			'label' => 'Lokaal',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 8 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_flitsbezoek-field_flitsbezoek_preventie'.
	$field_instances ['node-hrm_flitsbezoek-field_flitsbezoek_preventie'] = array (
			'bundle' => 'hrm_flitsbezoek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => 'Zijn er bijzonderheden op het gebied van veiligheid en gezondheid?',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 7 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_flitsbezoek_preventie',
			'label' => 'Preventie',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 9 
			) 
	);
	
	// Exported field_instance: 'node-hrm_flitsbezoek-field_personeelslid'.
	$field_instances ['node-hrm_flitsbezoek-field_personeelslid'] = array (
			'bundle' => 'hrm_flitsbezoek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'inline',
							'module' => 'entityreference',
							'settings' => array (
									'conditions' => array (),
									'link' => 1 
							),
							'type' => 'entityreference_label',
							'weight' => 1 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_personeelslid',
			'label' => 'Personeelslid',
			'required' => 1,
			'settings' => array (
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'entityreference',
					'settings' => array (
							'match_operator' => 'CONTAINS',
							'path' => '',
							'size' => 60 
					),
					'type' => 'entityreference_autocomplete',
					'weight' => 3 
			) 
	);
	
	// Exported field_instance: 'node-hrm_flitsbezoek-field_tijdstip'.
	$field_instances ['node-hrm_flitsbezoek-field_tijdstip'] = array (
			'bundle' => 'hrm_flitsbezoek',
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'inline',
							'module' => 'date',
							'settings' => array (
									'conditions' => array (),
									'format_type' => 'long',
									'fromto' => 'both',
									'multiple_from' => '',
									'multiple_number' => '',
									'multiple_to' => '',
									'show_remaining_days' => FALSE,
									'show_repeat_rule' => 'show' 
							),
							'type' => 'date_default',
							'weight' => 2 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_tijdstip',
			'label' => 'Tijdstip',
			'required' => 1,
			'settings' => array (
					'default_value' => 'now',
					'default_value2' => 'same',
					'default_value_code' => '',
					'default_value_code2' => '',
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'date',
					'settings' => array (
							'display_all_day' => 0,
							'increment' => 15,
							'input_format' => 'd/m/Y - H:i:s',
							'input_format_custom' => '',
							'label_position' => 'above',
							'no_fieldset' => 0,
							'repeat_collapsed' => 0,
							'text_parts' => array (),
							'year_range' => '-3:+3' 
					),
					'type' => 'date_popup',
					'weight' => 4 
			) 
	);
	
	// Exported field_instance: 'node-hrm_functioneringsgesprek-field_datum'.
	$field_instances ['node-hrm_functioneringsgesprek-field_datum'] = array (
			'bundle' => 'hrm_functioneringsgesprek',
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'date',
							'settings' => array (
									'conditions' => array (),
									'format_type' => 'long',
									'fromto' => 'both',
									'multiple_from' => '',
									'multiple_number' => '',
									'multiple_to' => '',
									'show_remaining_days' => FALSE,
									'show_repeat_rule' => 'show' 
							),
							'type' => 'date_default',
							'weight' => 8 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_datum',
			'label' => 'Periode van toepassing',
			'required' => 0,
			'settings' => array (
					'default_value' => 'now',
					'default_value2' => 'same',
					'default_value_code' => '',
					'default_value_code2' => '',
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'date',
					'settings' => array (
							'display_all_day' => 0,
							'increment' => 15,
							'input_format' => 'd/m/Y - H:i:s',
							'input_format_custom' => '',
							'label_position' => 'above',
							'no_fieldset' => 0,
							'repeat_collapsed' => 0,
							'text_parts' => array (),
							'year_range' => '-3:+3' 
					),
					'type' => 'date_popup',
					'weight' => 3 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_functioneringsgesprek-field_functioneringsg_status'.
	$field_instances ['node-hrm_functioneringsgesprek-field_functioneringsg_status'] = array (
			'bundle' => 'hrm_functioneringsgesprek',
			'default_value' => array (
					0 => array (
							'value' => 'nieuw' 
					) 
			),
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'list',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'list_default',
							'weight' => 5 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_functioneringsg_status',
			'label' => 'Status',
			'required' => 1,
			'settings' => array (
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'options',
					'settings' => array (
							'apply_chosen' => '' 
					),
					'type' => 'options_select',
					'weight' => 2 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_functioneringsgesprek-field_personeelslid'.
	$field_instances ['node-hrm_functioneringsgesprek-field_personeelslid'] = array (
			'bundle' => 'hrm_functioneringsgesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'entityreference',
							'settings' => array (
									'conditions' => array (),
									'link' => FALSE 
							),
							'type' => 'entityreference_label',
							'weight' => 2 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_personeelslid',
			'label' => 'Personeelslid',
			'required' => 0,
			'settings' => array (
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'entityreference',
					'settings' => array (
							'match_operator' => 'CONTAINS',
							'path' => '',
							'size' => 60 
					),
					'type' => 'entityreference_autocomplete',
					'weight' => 0 
			) 
	);
	
	// Exported field_instance: 'node-hrm_functioneringsgesprek-field_tijdstip'.
	$field_instances ['node-hrm_functioneringsgesprek-field_tijdstip'] = array (
			'bundle' => 'hrm_functioneringsgesprek',
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'date',
							'settings' => array (
									'conditions' => array (),
									'format_type' => 'long',
									'fromto' => 'both',
									'multiple_from' => '',
									'multiple_number' => '',
									'multiple_to' => '',
									'show_remaining_days' => FALSE,
									'show_repeat_rule' => 'show' 
							),
							'type' => 'date_default',
							'weight' => 4 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_tijdstip',
			'label' => 'Tijdstip',
			'required' => 1,
			'settings' => array (
					'default_value' => 'now',
					'default_value2' => 'same',
					'default_value_code' => '',
					'default_value_code2' => '',
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'date',
					'settings' => array (
							'display_all_day' => 0,
							'increment' => 15,
							'input_format' => 'd/m/Y - H:i:s',
							'input_format_custom' => '',
							'label_position' => 'above',
							'no_fieldset' => 0,
							'repeat_collapsed' => 0,
							'text_parts' => array (),
							'year_range' => '-3:+3' 
					),
					'type' => 'date_popup',
					'weight' => 1 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_functioneringsgesprek-field_voorgestelde_punten_evalua'.
	$field_instances ['node-hrm_functioneringsgesprek-field_voorgestelde_punten_evalua'] = array (
			'bundle' => 'hrm_functioneringsgesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 7 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_voorgestelde_punten_evalua',
			'label' => 'Voorgestelde punten evaluator',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 4 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_functioneringsgesprek-field_voorgestelde_punten_person'.
	$field_instances ['node-hrm_functioneringsgesprek-field_voorgestelde_punten_person'] = array (
			'bundle' => 'hrm_functioneringsgesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 6 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_voorgestelde_punten_person',
			'label' => 'Voorgestelde punten personeelslid',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 3 
			) 
	);
	
	// Exported field_instance: 'node-hrm_klasbezoek-field_bijlage'.
	$field_instances ['node-hrm_klasbezoek-field_bijlage'] = array (
			'bundle' => 'hrm_klasbezoek',
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'inline',
							'module' => 'file',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'file_default',
							'weight' => 8 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_bijlage',
			'label' => 'Bijlage',
			'required' => 0,
			'settings' => array (
					'description_field' => 0,
					'file_directory' => 'hrm/klasbezoeken',
					'file_extensions' => 'txt pdf doc docx xls xlsx',
					'max_filesize' => 10,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'file',
					'settings' => array (
							'filefield_sources' => array (
									'filefield_sources' => array (
											'attach' => 0,
											'clipboard' => 0,
											'imce' => 0,
											'reference' => 0,
											'remote' => 0,
											'upload' => 'upload' 
									),
									'source_attach' => array (
											'absolute' => 0,
											'attach_mode' => 'move',
											'path' => 'file_attach' 
									),
									'source_imce' => array (
											'imce_mode' => 0 
									),
									'source_reference' => array (
											'autocomplete' => 0,
											'search_all_fields' => 0 
									) 
							),
							'progress_indicator' => 'throbber' 
					),
					'type' => 'file_generic',
					'weight' => 8 
			) 
	);
	
	// Exported field_instance: 'node-hrm_klasbezoek-field_klasbezoek_activiteit'.
	$field_instances ['node-hrm_klasbezoek-field_klasbezoek_activiteit'] = array (
			'bundle' => 'hrm_klasbezoek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'inline',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 2 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_klasbezoek_activiteit',
			'label' => 'Activiteit',
			'required' => 1,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'size' => 100 
					),
					'type' => 'text_textfield',
					'weight' => 2 
			) 
	);
	
	// Exported field_instance: 'node-hrm_klasbezoek-field_klasbezoek_afspraken'.
	$field_instances ['node-hrm_klasbezoek-field_klasbezoek_afspraken'] = array (
			'bundle' => 'hrm_klasbezoek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 7 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_klasbezoek_afspraken',
			'label' => 'Afspraken',
			'required' => 0,
			'settings' => array (
					'display_summary' => 0,
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 1,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 20,
							'summary_rows' => 5 
					),
					'type' => 'text_textarea_with_summary',
					'weight' => 7 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_klasbezoek-field_klasbezoek_andere_focus'.
	$field_instances ['node-hrm_klasbezoek-field_klasbezoek_andere_focus'] = array (
			'bundle' => 'hrm_klasbezoek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 11 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_klasbezoek_andere_focus',
			'label' => 'Andere focus',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'size' => 100 
					),
					'type' => 'text_textfield',
					'weight' => 10 
			) 
	);
	
	// Exported field_instance: 'node-hrm_klasbezoek-field_klasbezoek_did_comp'.
	$field_instances ['node-hrm_klasbezoek-field_klasbezoek_did_comp'] = array (
			'bundle' => 'hrm_klasbezoek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '<p>In deze kijkwijzer staan de didactische competenties van de leraar centraal.</p>
<p>De kijkwijzer geeft een idee in welke mate de leraar aandacht heeft voor enkele belangrijke didactische aspecten van het leraarschap, met name: de keuze en het hanteren van de leerplandoelstellingen en de leerinhouden, de werkvormen, het gebruik van leermiddelen, de evaluatie, reflectie en registratie en tot slot belichten we het differentiëren in de klas.</p>

<p><strong>Keuze en hanteren van de leerplandoelstellingen en de leerinhouden</strong></p>
<p>Voor leraren zijn leerplannen een leidraad bij de vormgeving van de concrete lespraktijk. Het leerplan bevat leerplandoelstellingen die de leraar dient te realiseren met zijn leerlingen.</p>
<p>Hierbij is het vertalen van de leerplandoelstellingen naar concrete en operationele lesdoelstellingen -waarbij de leraar rekening houdt met de beginsituatie van de leerlingen- cruciaal.</p>
<p>De keuze en correctheid van de leerinhouden bepalen de kwaliteit van de aangeboden leerstof.</p>

<p><strong>Keuze en hanteren van de werkvormen</strong></p>
<p>Door de werkvormen te variëren, speelt een leerkracht in op de verschillende leerstijlen van de leerlingen.1 Dit vereist van de leerkracht dat hij beschikt over een arsenaal van zulke werkvormen, dat hij de leerlingen goed kent en dat hij in staat is een bij de leerling passende werkvorm te kiezen.</p>
<p>Gezien dit een niet zo een eenvoudige opdracht is, gaan leerkrachten bij de introductie van nieuwe leerstof verschillende werkvormen combineren of gelijktijdig hanteren, in de hoop dat elke leerling oppikt wat hij nodig heeft.</p>
<p>Bij de verwerking van de leerstof via opdrachten kan de leerkracht dan nagaan welke leerlingen nog een aanvullende instructie via een andere werkvorm nodig hebben.</p>

<p><strong>Keuze en hanteren van de leermiddelen</strong></p>
<p>De keuze van een leermiddel ontslaat de leraar niet van de verplichting een goedgekeurd leerplan te gebruiken. Integendeel, waar een leermiddel een hulpmiddel kan zijn, is het leerplan de enige waarborg om te voldoen aan de regelgeving van de overheid wiens taak het is om (specifieke) eindtermen en ontwikkelingsdoelen te bewaken.</p>
<p>Uitgevers van leermiddelen worden op regelmatige basis geïnformeerd over de achterliggende visie, de inhouden en de ontwikkelingen van nieuwe leerplannen. Toch is het belangrijk dat wanneer de leraar een keuze van leermiddelen heeft gemaakt hij/zij kritisch nagaat of alle leerplandoelstellingen ook werkelijk gerealiseerd worden.</p>

<p><strong>Keuze en praktijk van evaluatie – reflectie - rapporteren</strong></p>
<p>De school is verantwoordelijk voor het realiseren van de doelstellingen opgenomen in de gehanteerde leerplannen. Evaluatie is een het middel om na te gaan in hoeverre deze doelstellingen bij de leerlingen bereikt zijn.</p>
<p>Evalueren zien we dan ook als een permanente activiteit die aan de hand van concrete vaststellingen door de leraar, de lerarengroep, de leerling … gegevens aanreikt over het leren.</p>

<p><strong>Omgaan met verschillen – differentiatie</strong></p>
<p>Omgaan met verschillen is één van de uitdagingen waar het onderwijs vandaag mee te maken heeft. Vanaf de eerste schooldag verschillen leerlingen van elkaar in mogelijkheden, kennis, vaardigheden, attitudes en motivatie over wat onderwezen gaat worden.</p>
<p>Ondanks het feit dat differentiatie in de klas een manier is waarop een leerkracht kan omgaan met de verschillen tussen leerlingen in de klas geven leraren vaak les alsof er geen verschillen tussen de leerlingen zijn. Men kan differentiëren op alle momenten van de les en op verschillende manieren nl. naar inhoud, tempo, instructie en evaluatie. Ook het genderbewust(er) lesgeven zien we als een manier om om te gaan met verschillen. Recent onderzoek heeft immers uitgewezen dat gender nog steeds een grote rol speelt bij leerkracht-leerling interacties.</p>
<p>Elke mens is uiteindelijk verschillend. Leerlingen leren op school niet alleen omgaan met verschillen in anderen, maar ook met hun eigen anders-zijn. Gelijkwaardigheid impliceert dat iedereen gelijke kansen krijgt. En soms is daarvoor een ongelijke behandeling nodig.</p>',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'list',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'list_default',
							'weight' => 8 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_klasbezoek_did_comp',
			'label' => 'Didactische competenties',
			'required' => 0,
			'settings' => array (
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'options',
					'settings' => array (),
					'type' => 'options_buttons',
					'weight' => 7 
			) 
	);
	
	// Exported field_instance: 'node-hrm_klasbezoek-field_klasbezoek_org_comp'.
	$field_instances ['node-hrm_klasbezoek-field_klasbezoek_org_comp'] = array (
			'bundle' => 'hrm_klasbezoek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '<p>Een goede organisatie is een voorwaarde voor het leren. De organisatorische competenties van de leraar omvatten enerzijds een goed beheer van tijd en ruimte enerzijds en een effectief klasmanagement anderzijds. We behandelen beide aspecten in deze kijkwijzer.</p>

<p><strong>Algemeen klasmanagement</strong></p>
<p>Hier gaat het over orde houden in de klas: de manier waarop de leraar de leiding neemt, of omgaat met ongewenst en storend gedrag, efficiënt gebruik van de beschikbare tijd …</p>

<p><strong>De klas inrichten en aankleden</strong></p>
<p>De leraar is verantwoordelijk voor een ruimtelijke organisatie die leren en (samen)werken mogelijk maakt. De leraar creëert een stimulerende leeromgeving en een ruimte waar verschillende werkvormen mogelijk zijn. De veiligheid is gewaarborgd.</p>',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'list',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'list_default',
							'weight' => 9 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_klasbezoek_org_comp',
			'label' => 'Organisatorische competenties',
			'required' => 0,
			'settings' => array (
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'options',
					'settings' => array (),
					'type' => 'options_buttons',
					'weight' => 8 
			) 
	);
	
	// Exported field_instance: 'node-hrm_klasbezoek-field_klasbezoek_ped_comp'.
	$field_instances ['node-hrm_klasbezoek-field_klasbezoek_ped_comp'] = array (
			'bundle' => 'hrm_klasbezoek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '<p>In deze kijkwijzer staan de pedagogische competenties van de leraar centraal. Deze kijkwijzer geeft een idee over in welke mate de leraar aandacht heeft voor enkele belangrijke pedagogische aspecten van het leraarschap, met name: een positief en veilig leerklimaat, leerlingenparticipatie, zorg voor leerlingen, waarden en normen en tot slot vestigen we de focus ook nog op de genderproblematiek.</p>

<p><strong>Een positief en veilig leerklimaat</strong></p>
<p>Een positief leer- of klasklimaat is een klassfeer die opvoedt en uitnodigt tot verantwoordelijkheid en betrokkenheid. De leraar zorgt voor een atmosfeer die niet alleen bij de leerlingen het beste naar boven haalt, maar ook bijdraagt tot het ontstaan van persoonskenmerken die een verantwoordelijke en geëngageerde instelling mogelijk maken. In een positief en veilig leerklimaat zorgt de leraar onder meer voor een positief zelfbeeld bij de leerlingen, goede intermenselijke verhoudingen, bouwt de leraar succeservaringen in, bevestigt de leraar de leerlingen gepast, geeft hij of zij blijk van hoge verwachtingen ten aanzien van de leerlingen, bevordert hij of zij de autonomie en toont de leraar begrip.</p>

<p><strong>Leerlingenparticipatie</strong></p>
<p>Een goede manier om leerlingen verantwoordelijkheid te geven, is ze te laten participeren. Er bestaat niet één manier om leerlingen te laten participeren. Verschillende vormen van participatie zijn mogelijk in een continuüm waarbij initiatieven of beslissingen meer in handen van volwassenen dan wel in handen van de leerlingen zelf liggen: van louter informeren van leerlingen, naar laten adviseren, mee laten beslissen, samen ondernemen, begeleiden tot het zelf laten organiseren.</p>
<p>Leerlingen laten participeren kan door open te staan voor hun bijdragen. Ruimte voor eigen inbreng is mogelijk ten aanzien van bijvoorbeeld het dagelijkse bestuur van de school of klas, regels en het eigen leren. Dit betekent dat je de leerlingen kan laten participeren bij het samenstellen van lessen of themareeksen, het opstellen van een schoolreglement, het organiseren van buitenschoolse activiteiten ... Participatie van de leerling in de keuze en het bepalen van de doelstellingen verhoogt zijn betrokkenheid en maakt duidelijk waarheen hij op weg is.</p>

<p><strong>Leerbegeleiding</strong></p>
<p>Onder leerbegeleiding verstaan we de manier waarop de school het leren van leerlingen ondersteunt om de vooropgestelde leerdoelen te bereiken of na te streven. De school zorgt er door haar leerbegeleiding voor dat zoveel mogelijk leerlingen de leerdoelen bereiken. Daarvoor neemt zij preventieve en/of remediërende maatregelen. Bovendien heeft de leerbegeleiding als doel dat zoveel mogelijk leerlingen de competenties ontwikkelen die ze nodig zullen hebben om met een toenemende autonomie hun talenten te ontwikkelen (levenslang leren).</p>
<p>In de zorg voor leerlingen kan een aantal fasen onderscheiden worden die op een zorgcontinuüm geplaatst worden. Leerbegeleiding krijgt in de eerste plaats vorm in een goede klaspraktijk. Schoolteams zetten daarbij een pedagogisch-didactisch proces op om al hun leerlingen zo goed mogelijk te begeleiden en te ondersteunen in hun leer- en ontwikkelingsproces. In de brede basiszorg stimuleert de school de ontwikkeling van alle leerlingen, via een krachtige leeromgeving. Pas in een volgende fase, de fase van verhoogde zorg, wanneer de basiszorg onvoldoende ondersteuning biedt, kiest het schoolteam voor een bijkomende begeleiding afgestemd op de onderwijsbehoeften van de leerling, bv. in de vorm van STICORDI-maatregelen.</p>

<p><strong>Waarden en normen</strong></p>
<p>De school vervult een belangrijke functie in de waardeopvoeding van leerlingen. Het pedagogisch project van het GO! (PPGO) en de vertaling hiervan in het pedagogisch project van de school zijn hierbij richtinggevend. De leraar stimuleert de ontwikkeling van democratische waarden bij de leerling. De leraar leert jongeren betekenisvolle en verantwoorde keuzes te maken en leert hen aandacht te hebben voor de consequenties van die keuze voor hun handelen. Afspraken en regels zijn afgeleiden van waarden.</p>
<p>Regels concretiseren de waarden naar de specifieke school- en klascontext en maken deel uit van de opvoeding.</p>

<p><strong>Gender</strong></p>
<p>Jongens en meisjes beleven de school anders. Uit onderzoek blijkt dat jongens vaker achterop geraken, meer blijven zitten, mindere resultaten halen en vaker de school verlaten zonder diploma dan meisjes. Er heerst vaker een antischoolcultuur bij jongens. Onder antischoolcultuur verstaan we zaken zoals een lagere studiemotivatie, een lager engagement op school, minder belang hechten aan punten, minder tijd besteden aan huiswerk of vaker storend gedrag vertonen zoals agressie, ongehoorzaamheid en vandalisme. Dat het vooral jongens zijn die anti-schoolse culturen ontwikkelen kan deels verklaard worden door verschillen die er zijn in de interactie met de leraar. Leraren blijken hogere academische en normatieve verwachtingen te hebben voor meisjes dan voor jongens.</p>
<p>Afhankelijk van hun verwachtingen vertonen leerkrachten vervolgens verschillend gedrag naar jongens en meisjes toe en leerlingen gaan zich naar de verwachtingen gedragen.</p>
<p>Heel wat materialen en activiteiten binnen het curriculum zijn gunstiger voor meisjes dan voor jongens, bijvoorbeeld door het bieden van vaste structuren en een meer talige aanpak. Daarom is het belangrijk dat leraren niet alleen oog hebben voor verschillen tussen jongens en meisjes, maar vooral ook voor individuele gelijkenissen en verschillen (om stereotypering te voorkomen).</p>',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'list',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'list_default',
							'weight' => 7 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_klasbezoek_ped_comp',
			'label' => 'Pedagogische competenties',
			'required' => 0,
			'settings' => array (
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'options',
					'settings' => array (),
					'type' => 'options_buttons',
					'weight' => 6 
			) 
	);
	
	// Exported field_instance: 'node-hrm_klasbezoek-field_klasbezoek_taalcomp'.
	$field_instances ['node-hrm_klasbezoek-field_klasbezoek_taalcomp'] = array (
			'bundle' => 'hrm_klasbezoek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '<p>Deze kijkwijzer is bedoeld om te observeren in welke mate de vakleraar aandacht heeft voor taalgericht vakonderwijs, m.a.w. in welke mate hij bij het realiseren van zijn vakdoelstellingen ook werkt aan het ontwikkelen van de verschillende taalvaardigheden, zoals bijv. gericht luisteren en kijken, begrijpend lezen, formuleren en beantwoorden van vragen, functioneel schrijven en presenteren.</p>
<p>De kijkwijzer voor taalgericht vakonderwijs is gestructureerd op basis van de drie pijlers van taalgericht vakonderwijs:<ol><li>context en vakinhoud;</li><li>interactie;</li><li>taalsteun.</li></ol></p>
<p>Context en interactie vind je ook terug in de algemene didactiek (zie kijkwijzer didactische competenties). Bij taalgericht vakonderwijs zijn ze uiterst belangrijk, niet alleen om de leerlingen te motiveren of te activeren, maar vooral ook om de leerlingen in staat te stellen de taal van het vak te leren ( gebruiken). Om die reden zijn context en interactie ook in deze kijkwijzer over talige competenties opgenomen.</p>

<p><strong>Contextrijk vakonderwijs</strong></p>
<p>Contexten geven betekenis aan het leerproces: de leerling kan zich een beeld vormen van de situatie waarin vakinhouden worden aangeboden. Het is nodig de context te verkennen, want de gebruikte contexten zijn niet bij iedereen bekend. Daarnaast is het van belang dat de leraar de talige aspecten van de context toegankelijk maakt voor de leerlingen.</p>

<p><strong>Veel interactie</strong></p>
<p>Leren is een interactief proces: kennis komt tot stand doordat je er met anderen over praat. Het actief gebruiken van de taal stimuleert de taalontwikkeling. Leerlingen moeten kunnen praten en schrijven in de les. De leraar heeft hierbij een stimulerende functie door het gesprek op gang te brengen en te begeleiden en te reageren op de inbreng van leerlingen.</p>
<p>Verder kunnen leerlingen veel taal leren door in groepjes of in duo’s samen te werken en te praten over de vakinhouden.</p>

<p><strong>Taalsteun</strong></p>
<p>Taalsteun betekent steun bij het begrijpen en produceren van taal.</p>
<p>Taalsteun kan op diverse manieren geboden worden: steun bij teksten en nieuwe woorden, steun bij het zelf praten en schrijven, en soms steun in de vorm van taallesjes, zoals taaloefeningen rondom nieuwe formuleringen in vaktaal.</p>
',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'list',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'list_default',
							'weight' => 10 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_klasbezoek_taalcomp',
			'label' => 'Taalcompetenties',
			'required' => 0,
			'settings' => array (
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'options',
					'settings' => array (),
					'type' => 'options_buttons',
					'weight' => 9 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_klasbezoek-field_klasbezoek_vorigeafspraken'.
	$field_instances ['node-hrm_klasbezoek-field_klasbezoek_vorigeafspraken'] = array (
			'bundle' => 'hrm_klasbezoek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '(eventueel)',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 3 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_klasbezoek_vorigeafspraken',
			'label' => 'Vorige afspraken',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 3 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_klasbezoek-field_klasbezoek_zelfreflectie'.
	$field_instances ['node-hrm_klasbezoek-field_klasbezoek_zelfreflectie'] = array (
			'bundle' => 'hrm_klasbezoek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 6 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_klasbezoek_zelfreflectie',
			'label' => 'Zelfreflectie door de leerkracht',
			'required' => 0,
			'settings' => array (
					'display_summary' => 0,
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 1,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 20,
							'summary_rows' => 5 
					),
					'type' => 'text_textarea_with_summary',
					'weight' => 6 
			) 
	);
	
	// Exported field_instance: 'node-hrm_klasbezoek-field_personeelslid'.
	$field_instances ['node-hrm_klasbezoek-field_personeelslid'] = array (
			'bundle' => 'hrm_klasbezoek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'inline',
							'module' => 'entityreference',
							'settings' => array (
									'conditions' => array (),
									'link' => 1 
							),
							'type' => 'entityreference_label',
							'weight' => 0 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_personeelslid',
			'label' => 'Personeelslid',
			'required' => 1,
			'settings' => array (
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'entityreference',
					'settings' => array (
							'match_operator' => 'CONTAINS',
							'path' => '',
							'size' => 60 
					),
					'type' => 'entityreference_autocomplete',
					'weight' => 0 
			) 
	);
	
	// Exported field_instance: 'node-hrm_klasbezoek-field_tijdstip'.
	$field_instances ['node-hrm_klasbezoek-field_tijdstip'] = array (
			'bundle' => 'hrm_klasbezoek',
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'inline',
							'module' => 'date',
							'settings' => array (
									'conditions' => array (),
									'format_type' => 'long',
									'fromto' => 'both',
									'multiple_from' => '',
									'multiple_number' => '',
									'multiple_to' => '',
									'show_remaining_days' => FALSE,
									'show_repeat_rule' => 'show' 
							),
							'type' => 'date_default',
							'weight' => 1 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_tijdstip',
			'label' => 'Tijdstip',
			'required' => 1,
			'settings' => array (
					'default_value' => 'now',
					'default_value2' => 'same',
					'default_value_code' => '',
					'default_value_code2' => '',
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'date',
					'settings' => array (
							'display_all_day' => 0,
							'increment' => 15,
							'input_format' => 'd/m/Y - H:i:s',
							'input_format_custom' => '',
							'label_position' => 'above',
							'no_fieldset' => 0,
							'repeat_collapsed' => 0,
							'text_parts' => array (),
							'year_range' => '-3:+3' 
					),
					'type' => 'date_popup',
					'weight' => 1 
			) 
	);
	
	// Exported field_instance: 'node-hrm_planningsgesprek-field_bijlage'.
	$field_instances ['node-hrm_planningsgesprek-field_bijlage'] = array (
			'bundle' => 'hrm_planningsgesprek',
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'file',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'file_default',
							'weight' => 8 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_bijlage',
			'label' => 'Bijlage',
			'required' => 0,
			'settings' => array (
					'description_field' => 0,
					'file_directory' => 'HRM/planningsgesprekken',
					'file_extensions' => 'txt pdf doc docx ppt pptx xls xlsx',
					'max_filesize' => '',
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'file',
					'settings' => array (
							'filefield_sources' => array (
									'filefield_sources' => array (
											'attach' => 0,
											'clipboard' => 0,
											'imce' => 0,
											'reference' => 0,
											'remote' => 0,
											'upload' => 'upload' 
									),
									'source_attach' => array (
											'absolute' => 0,
											'attach_mode' => 'move',
											'path' => 'file_attach' 
									),
									'source_imce' => array (
											'imce_mode' => 0 
									),
									'source_reference' => array (
											'autocomplete' => 0,
											'search_all_fields' => 0 
									) 
							),
							'progress_indicator' => 'throbber' 
					),
					'type' => 'file_generic',
					'weight' => 7 
			) 
	);
	
	// Exported field_instance: 'node-hrm_planningsgesprek-field_datum'.
	$field_instances ['node-hrm_planningsgesprek-field_datum'] = array (
			'bundle' => 'hrm_planningsgesprek',
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'inline',
							'module' => 'date',
							'settings' => array (
									'conditions' => array (),
									'format_type' => 'long',
									'fromto' => 'both',
									'multiple_from' => '',
									'multiple_number' => '',
									'multiple_to' => '',
									'show_remaining_days' => FALSE,
									'show_repeat_rule' => 'show' 
							),
							'type' => 'date_default',
							'weight' => 3 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_datum',
			'label' => 'Periode van toepassing',
			'required' => 1,
			'settings' => array (
					'default_value' => 'now',
					'default_value2' => 'same',
					'default_value_code' => '',
					'default_value_code2' => '',
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'date',
					'settings' => array (
							'display_all_day' => 0,
							'increment' => 15,
							'input_format' => 'd/m/Y - H:i:s',
							'input_format_custom' => '',
							'label_position' => 'above',
							'no_fieldset' => 0,
							'repeat_collapsed' => 0,
							'text_parts' => array (),
							'year_range' => '-3:+3' 
					),
					'type' => 'date_popup',
					'weight' => 3 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_planningsgesprek-field_inhoud_van_dit_gesprek'.
	$field_instances ['node-hrm_planningsgesprek-field_inhoud_van_dit_gesprek'] = array (
			'bundle' => 'hrm_planningsgesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'list',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'list_default',
							'weight' => 4 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_inhoud_van_dit_gesprek',
			'label' => 'Inhoud van dit gesprek',
			'required' => 0,
			'settings' => array (
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'options',
					'settings' => array (
							'apply_chosen' => '' 
					),
					'type' => 'options_buttons',
					'weight' => 4 
			) 
	);
	
	// Exported field_instance: 'node-hrm_planningsgesprek-field_personeelslid'.
	$field_instances ['node-hrm_planningsgesprek-field_personeelslid'] = array (
			'bundle' => 'hrm_planningsgesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'inline',
							'module' => 'entityreference',
							'settings' => array (
									'conditions' => array (),
									'link' => 1 
							),
							'type' => 'entityreference_label',
							'weight' => 0 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_personeelslid',
			'label' => 'Personeelslid',
			'required' => 1,
			'settings' => array (
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'entityreference',
					'settings' => array (
							'match_operator' => 'CONTAINS',
							'path' => '',
							'size' => 60 
					),
					'type' => 'entityreference_autocomplete',
					'weight' => 0 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_planningsgesprek-field_pg_eventuele_oplossing'.
	$field_instances ['node-hrm_planningsgesprek-field_pg_eventuele_oplossing'] = array (
			'bundle' => 'hrm_planningsgesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 7 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_pg_eventuele_oplossing',
			'label' => 'Eventuele oplossing',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 15 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_planningsgesprek-field_pg_probleemidentificatie'.
	$field_instances ['node-hrm_planningsgesprek-field_pg_probleemidentificatie'] = array (
			'bundle' => 'hrm_planningsgesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 6 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_pg_probleemidentificatie',
			'label' => 'Probleemidentificatie',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 12 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_planningsgesprek-field_planningsgesprek_status'.
	$field_instances ['node-hrm_planningsgesprek-field_planningsgesprek_status'] = array (
			'bundle' => 'hrm_planningsgesprek',
			'default_value' => array (
					0 => array (
							'value' => 'nieuw' 
					) 
			),
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'inline',
							'module' => 'list',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'list_default',
							'weight' => 1 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_planningsgesprek_status',
			'label' => 'Status',
			'required' => 1,
			'settings' => array (
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'options',
					'settings' => array (
							'apply_chosen' => '' 
					),
					'type' => 'options_select',
					'weight' => 2 
			) 
	);
	
	// Exported field_instance:
	// 'node-hrm_planningsgesprek-field_prioriteiten_volgens_evalu'.
	$field_instances ['node-hrm_planningsgesprek-field_prioriteiten_volgens_evalu'] = array (
			'bundle' => 'hrm_planningsgesprek',
			'default_value' => NULL,
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'above',
							'module' => 'text',
							'settings' => array (
									'conditions' => array () 
							),
							'type' => 'text_default',
							'weight' => 5 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_prioriteiten_volgens_evalu',
			'label' => 'Prioriteiten volgens evaluator',
			'required' => 0,
			'settings' => array (
					'linkit' => array (
							'button_text' => 'Zoeken',
							'enable' => 0,
							'profile' => '' 
					),
					'text_processing' => 0,
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'text',
					'settings' => array (
							'rows' => 5 
					),
					'type' => 'text_textarea',
					'weight' => 5 
			) 
	);
	
	// Exported field_instance: 'node-hrm_planningsgesprek-field_tijdstip'.
	$field_instances ['node-hrm_planningsgesprek-field_tijdstip'] = array (
			'bundle' => 'hrm_planningsgesprek',
			'deleted' => 0,
			'description' => '',
			'display' => array (
					'default' => array (
							'label' => 'inline',
							'module' => 'date',
							'settings' => array (
									'conditions' => array (),
									'format_type' => 'long',
									'fromto' => 'both',
									'multiple_from' => '',
									'multiple_number' => '',
									'multiple_to' => '',
									'show_remaining_days' => FALSE,
									'show_repeat_rule' => 'show' 
							),
							'type' => 'date_default',
							'weight' => 2 
					),
					'teaser' => array (
							'label' => 'above',
							'settings' => array (),
							'type' => 'hidden',
							'weight' => 0 
					) 
			),
			'entity_type' => 'node',
			'field_name' => 'field_tijdstip',
			'label' => 'Tijdstip',
			'required' => 1,
			'settings' => array (
					'default_value' => 'now',
					'default_value2' => 'same',
					'default_value_code' => '',
					'default_value_code2' => '',
					'user_register_form' => FALSE 
			),
			'widget' => array (
					'active' => 1,
					'module' => 'date',
					'settings' => array (
							'display_all_day' => 0,
							'increment' => 15,
							'input_format' => 'd/m/Y - H:i:s',
							'input_format_custom' => '',
							'label_position' => 'above',
							'no_fieldset' => 0,
							'repeat_collapsed' => 0,
							'text_parts' => array (),
							'year_range' => '-3:+3' 
					),
					'type' => 'date_popup',
					'weight' => 1 
			) 
	);
	
	// Translatables
	// Included for use with string extractors like potx.
	t ( '(eventueel)' );
	t ( '(positieve punten en groeikansen)' );
	t ( '<p>Deze kijkwijzer is bedoeld om te observeren in welke mate de vakleraar aandacht heeft voor taalgericht vakonderwijs, m.a.w. in welke mate hij bij het realiseren van zijn vakdoelstellingen ook werkt aan het ontwikkelen van de verschillende taalvaardigheden, zoals bijv. gericht luisteren en kijken, begrijpend lezen, formuleren en beantwoorden van vragen, functioneel schrijven en presenteren.</p>
<p>De kijkwijzer voor taalgericht vakonderwijs is gestructureerd op basis van de drie pijlers van taalgericht vakonderwijs:<ol><li>context en vakinhoud;</li><li>interactie;</li><li>taalsteun.</li></ol></p>
<p>Context en interactie vind je ook terug in de algemene didactiek (zie kijkwijzer didactische competenties). Bij taalgericht vakonderwijs zijn ze uiterst belangrijk, niet alleen om de leerlingen te motiveren of te activeren, maar vooral ook om de leerlingen in staat te stellen de taal van het vak te leren ( gebruiken). Om die reden zijn context en interactie ook in deze kijkwijzer over talige competenties opgenomen.</p>

<p><strong>Contextrijk vakonderwijs</strong></p>
<p>Contexten geven betekenis aan het leerproces: de leerling kan zich een beeld vormen van de situatie waarin vakinhouden worden aangeboden. Het is nodig de context te verkennen, want de gebruikte contexten zijn niet bij iedereen bekend. Daarnaast is het van belang dat de leraar de talige aspecten van de context toegankelijk maakt voor de leerlingen.</p>

<p><strong>Veel interactie</strong></p>
<p>Leren is een interactief proces: kennis komt tot stand doordat je er met anderen over praat. Het actief gebruiken van de taal stimuleert de taalontwikkeling. Leerlingen moeten kunnen praten en schrijven in de les. De leraar heeft hierbij een stimulerende functie door het gesprek op gang te brengen en te begeleiden en te reageren op de inbreng van leerlingen.</p>
<p>Verder kunnen leerlingen veel taal leren door in groepjes of in duo’s samen te werken en te praten over de vakinhouden.</p>

<p><strong>Taalsteun</strong></p>
<p>Taalsteun betekent steun bij het begrijpen en produceren van taal.</p>
<p>Taalsteun kan op diverse manieren geboden worden: steun bij teksten en nieuwe woorden, steun bij het zelf praten en schrijven, en soms steun in de vorm van taallesjes, zoals taaloefeningen rondom nieuwe formuleringen in vaktaal.</p>
' );
	t ( '<p>Een goede organisatie is een voorwaarde voor het leren. De organisatorische competenties van de leraar omvatten enerzijds een goed beheer van tijd en ruimte enerzijds en een effectief klasmanagement anderzijds. We behandelen beide aspecten in deze kijkwijzer.</p>

<p><strong>Algemeen klasmanagement</strong></p>
<p>Hier gaat het over orde houden in de klas: de manier waarop de leraar de leiding neemt, of omgaat met ongewenst en storend gedrag, efficiënt gebruik van de beschikbare tijd …</p>

<p><strong>De klas inrichten en aankleden</strong></p>
<p>De leraar is verantwoordelijk voor een ruimtelijke organisatie die leren en (samen)werken mogelijk maakt. De leraar creëert een stimulerende leeromgeving en een ruimte waar verschillende werkvormen mogelijk zijn. De veiligheid is gewaarborgd.</p>' );
	t ( '<p>In deze kijkwijzer staan de didactische competenties van de leraar centraal.</p>
<p>De kijkwijzer geeft een idee in welke mate de leraar aandacht heeft voor enkele belangrijke didactische aspecten van het leraarschap, met name: de keuze en het hanteren van de leerplandoelstellingen en de leerinhouden, de werkvormen, het gebruik van leermiddelen, de evaluatie, reflectie en registratie en tot slot belichten we het differentiëren in de klas.</p>

<p><strong>Keuze en hanteren van de leerplandoelstellingen en de leerinhouden</strong></p>
<p>Voor leraren zijn leerplannen een leidraad bij de vormgeving van de concrete lespraktijk. Het leerplan bevat leerplandoelstellingen die de leraar dient te realiseren met zijn leerlingen.</p>
<p>Hierbij is het vertalen van de leerplandoelstellingen naar concrete en operationele lesdoelstellingen -waarbij de leraar rekening houdt met de beginsituatie van de leerlingen- cruciaal.</p>
<p>De keuze en correctheid van de leerinhouden bepalen de kwaliteit van de aangeboden leerstof.</p>

<p><strong>Keuze en hanteren van de werkvormen</strong></p>
<p>Door de werkvormen te variëren, speelt een leerkracht in op de verschillende leerstijlen van de leerlingen.1 Dit vereist van de leerkracht dat hij beschikt over een arsenaal van zulke werkvormen, dat hij de leerlingen goed kent en dat hij in staat is een bij de leerling passende werkvorm te kiezen.</p>
<p>Gezien dit een niet zo een eenvoudige opdracht is, gaan leerkrachten bij de introductie van nieuwe leerstof verschillende werkvormen combineren of gelijktijdig hanteren, in de hoop dat elke leerling oppikt wat hij nodig heeft.</p>
<p>Bij de verwerking van de leerstof via opdrachten kan de leerkracht dan nagaan welke leerlingen nog een aanvullende instructie via een andere werkvorm nodig hebben.</p>

<p><strong>Keuze en hanteren van de leermiddelen</strong></p>
<p>De keuze van een leermiddel ontslaat de leraar niet van de verplichting een goedgekeurd leerplan te gebruiken. Integendeel, waar een leermiddel een hulpmiddel kan zijn, is het leerplan de enige waarborg om te voldoen aan de regelgeving van de overheid wiens taak het is om (specifieke) eindtermen en ontwikkelingsdoelen te bewaken.</p>
<p>Uitgevers van leermiddelen worden op regelmatige basis geïnformeerd over de achterliggende visie, de inhouden en de ontwikkelingen van nieuwe leerplannen. Toch is het belangrijk dat wanneer de leraar een keuze van leermiddelen heeft gemaakt hij/zij kritisch nagaat of alle leerplandoelstellingen ook werkelijk gerealiseerd worden.</p>

<p><strong>Keuze en praktijk van evaluatie – reflectie - rapporteren</strong></p>
<p>De school is verantwoordelijk voor het realiseren van de doelstellingen opgenomen in de gehanteerde leerplannen. Evaluatie is een het middel om na te gaan in hoeverre deze doelstellingen bij de leerlingen bereikt zijn.</p>
<p>Evalueren zien we dan ook als een permanente activiteit die aan de hand van concrete vaststellingen door de leraar, de lerarengroep, de leerling … gegevens aanreikt over het leren.</p>

<p><strong>Omgaan met verschillen – differentiatie</strong></p>
<p>Omgaan met verschillen is één van de uitdagingen waar het onderwijs vandaag mee te maken heeft. Vanaf de eerste schooldag verschillen leerlingen van elkaar in mogelijkheden, kennis, vaardigheden, attitudes en motivatie over wat onderwezen gaat worden.</p>
<p>Ondanks het feit dat differentiatie in de klas een manier is waarop een leerkracht kan omgaan met de verschillen tussen leerlingen in de klas geven leraren vaak les alsof er geen verschillen tussen de leerlingen zijn. Men kan differentiëren op alle momenten van de les en op verschillende manieren nl. naar inhoud, tempo, instructie en evaluatie. Ook het genderbewust(er) lesgeven zien we als een manier om om te gaan met verschillen. Recent onderzoek heeft immers uitgewezen dat gender nog steeds een grote rol speelt bij leerkracht-leerling interacties.</p>
<p>Elke mens is uiteindelijk verschillend. Leerlingen leren op school niet alleen omgaan met verschillen in anderen, maar ook met hun eigen anders-zijn. Gelijkwaardigheid impliceert dat iedereen gelijke kansen krijgt. En soms is daarvoor een ongelijke behandeling nodig.</p>' );
	t ( '<p>In deze kijkwijzer staan de pedagogische competenties van de leraar centraal. Deze kijkwijzer geeft een idee over in welke mate de leraar aandacht heeft voor enkele belangrijke pedagogische aspecten van het leraarschap, met name: een positief en veilig leerklimaat, leerlingenparticipatie, zorg voor leerlingen, waarden en normen en tot slot vestigen we de focus ook nog op de genderproblematiek.</p>

<p><strong>Een positief en veilig leerklimaat</strong></p>
<p>Een positief leer- of klasklimaat is een klassfeer die opvoedt en uitnodigt tot verantwoordelijkheid en betrokkenheid. De leraar zorgt voor een atmosfeer die niet alleen bij de leerlingen het beste naar boven haalt, maar ook bijdraagt tot het ontstaan van persoonskenmerken die een verantwoordelijke en geëngageerde instelling mogelijk maken. In een positief en veilig leerklimaat zorgt de leraar onder meer voor een positief zelfbeeld bij de leerlingen, goede intermenselijke verhoudingen, bouwt de leraar succeservaringen in, bevestigt de leraar de leerlingen gepast, geeft hij of zij blijk van hoge verwachtingen ten aanzien van de leerlingen, bevordert hij of zij de autonomie en toont de leraar begrip.</p>

<p><strong>Leerlingenparticipatie</strong></p>
<p>Een goede manier om leerlingen verantwoordelijkheid te geven, is ze te laten participeren. Er bestaat niet één manier om leerlingen te laten participeren. Verschillende vormen van participatie zijn mogelijk in een continuüm waarbij initiatieven of beslissingen meer in handen van volwassenen dan wel in handen van de leerlingen zelf liggen: van louter informeren van leerlingen, naar laten adviseren, mee laten beslissen, samen ondernemen, begeleiden tot het zelf laten organiseren.</p>
<p>Leerlingen laten participeren kan door open te staan voor hun bijdragen. Ruimte voor eigen inbreng is mogelijk ten aanzien van bijvoorbeeld het dagelijkse bestuur van de school of klas, regels en het eigen leren. Dit betekent dat je de leerlingen kan laten participeren bij het samenstellen van lessen of themareeksen, het opstellen van een schoolreglement, het organiseren van buitenschoolse activiteiten ... Participatie van de leerling in de keuze en het bepalen van de doelstellingen verhoogt zijn betrokkenheid en maakt duidelijk waarheen hij op weg is.</p>

<p><strong>Leerbegeleiding</strong></p>
<p>Onder leerbegeleiding verstaan we de manier waarop de school het leren van leerlingen ondersteunt om de vooropgestelde leerdoelen te bereiken of na te streven. De school zorgt er door haar leerbegeleiding voor dat zoveel mogelijk leerlingen de leerdoelen bereiken. Daarvoor neemt zij preventieve en/of remediërende maatregelen. Bovendien heeft de leerbegeleiding als doel dat zoveel mogelijk leerlingen de competenties ontwikkelen die ze nodig zullen hebben om met een toenemende autonomie hun talenten te ontwikkelen (levenslang leren).</p>
<p>In de zorg voor leerlingen kan een aantal fasen onderscheiden worden die op een zorgcontinuüm geplaatst worden. Leerbegeleiding krijgt in de eerste plaats vorm in een goede klaspraktijk. Schoolteams zetten daarbij een pedagogisch-didactisch proces op om al hun leerlingen zo goed mogelijk te begeleiden en te ondersteunen in hun leer- en ontwikkelingsproces. In de brede basiszorg stimuleert de school de ontwikkeling van alle leerlingen, via een krachtige leeromgeving. Pas in een volgende fase, de fase van verhoogde zorg, wanneer de basiszorg onvoldoende ondersteuning biedt, kiest het schoolteam voor een bijkomende begeleiding afgestemd op de onderwijsbehoeften van de leerling, bv. in de vorm van STICORDI-maatregelen.</p>

<p><strong>Waarden en normen</strong></p>
<p>De school vervult een belangrijke functie in de waardeopvoeding van leerlingen. Het pedagogisch project van het GO! (PPGO) en de vertaling hiervan in het pedagogisch project van de school zijn hierbij richtinggevend. De leraar stimuleert de ontwikkeling van democratische waarden bij de leerling. De leraar leert jongeren betekenisvolle en verantwoorde keuzes te maken en leert hen aandacht te hebben voor de consequenties van die keuze voor hun handelen. Afspraken en regels zijn afgeleiden van waarden.</p>
<p>Regels concretiseren de waarden naar de specifieke school- en klascontext en maken deel uit van de opvoeding.</p>

<p><strong>Gender</strong></p>
<p>Jongens en meisjes beleven de school anders. Uit onderzoek blijkt dat jongens vaker achterop geraken, meer blijven zitten, mindere resultaten halen en vaker de school verlaten zonder diploma dan meisjes. Er heerst vaker een antischoolcultuur bij jongens. Onder antischoolcultuur verstaan we zaken zoals een lagere studiemotivatie, een lager engagement op school, minder belang hechten aan punten, minder tijd besteden aan huiswerk of vaker storend gedrag vertonen zoals agressie, ongehoorzaamheid en vandalisme. Dat het vooral jongens zijn die anti-schoolse culturen ontwikkelen kan deels verklaard worden door verschillen die er zijn in de interactie met de leraar. Leraren blijken hogere academische en normatieve verwachtingen te hebben voor meisjes dan voor jongens.</p>
<p>Afhankelijk van hun verwachtingen vertonen leerkrachten vervolgens verschillend gedrag naar jongens en meisjes toe en leerlingen gaan zich naar de verwachtingen gedragen.</p>
<p>Heel wat materialen en activiteiten binnen het curriculum zijn gunstiger voor meisjes dan voor jongens, bijvoorbeeld door het bieden van vaste structuren en een meer talige aanpak. Daarom is het belangrijk dat leraren niet alleen oog hebben voor verschillen tussen jongens en meisjes, maar vooral ook voor individuele gelijkenissen en verschillen (om stereotypering te voorkomen).</p>' );
	t ( 'Activiteit' );
	t ( 'Afspraken' );
	t ( 'Andere focus' );
	t ( 'Beoordeling' );
	t ( 'Bijlage' );
	t ( 'Comment' );
	t ( 'Didactische competenties' );
	t ( 'Doen de leerlingen wat ze moeten doen?' );
	t ( 'Eindconclusie' );
	t ( 'Eventuele oplossing' );
	t ( 'Inhoud van dit gesprek' );
	t ( 'Interventies' );
	t ( 'Leerdoel' );
	t ( 'Leerlingen' );
	t ( 'Lokaal' );
	t ( 'Muren scannen: wat hangt er allemaal in het leslokaal dat bijdraagt (of juist niet) aan de lessen?' );
	t ( 'Organisatorische competenties' );
	t ( 'Pedagogische competenties' );
	t ( 'Periode van toepassing' );
	t ( 'Personeelslid' );
	t ( 'Positieve observaties' );
	t ( 'Preventie' );
	t ( 'Prioriteiten volgens evaluator' );
	t ( 'Probleemidentificatie' );
	t ( 'Status' );
	t ( 'Taalcompetenties' );
	t ( 'Tijdstip' );
	t ( 'Verslag' );
	t ( 'Voorgestelde punten evaluator' );
	t ( 'Voorgestelde punten personeelslid' );
	t ( 'Vorige afspraken' );
	t ( 'Wat is het leerdoel van de les en in hoeverre zijn de lesactiviteiten in lijn met dit doel?' );
	t ( 'Welke interventies doet de leerkracht om te zorgen dat alle leerlingen het leerdoel behalen?' );
	t ( 'Werkpunten en afspraken' );
	t ( 'Zelfreflectie door de leerkracht' );
	t ( 'Zijn er bijzonderheden op het gebied van veiligheid en gezondheid?' );
	
	return $field_instances;
}

/**
 * Implements hook_field_group_info().
 *
 * This function is copied from the file generated by the Features module: demo.field_group.inc
 */
function argus_hrm_field_group_info() {
	$field_groups = array ();
	
	$field_group = new stdClass ();
	$field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
	$field_group->api_version = 1;
	$field_group->identifier = 'group_focus|node|hrm_klasbezoek|default';
	$field_group->group_name = 'group_focus';
	$field_group->entity_type = 'node';
	$field_group->bundle = 'hrm_klasbezoek';
	$field_group->mode = 'default';
	$field_group->parent_name = '';
	$field_group->data = array (
			'label' => 'Focus',
			'weight' => '4',
			'children' => array (
					0 => 'field_klasbezoek_ped_comp',
					1 => 'field_klasbezoek_did_comp',
					2 => 'field_klasbezoek_taalcomp',
					3 => 'field_klasbezoek_org_comp',
					4 => 'field_klasbezoek_andere_focus' 
			),
			'format_type' => 'fieldset',
			'format_settings' => array (
					'formatter' => 'collapsible',
					'instance_settings' => array (
							'description' => '',
							'classes' => 'group-focus field-group-fieldset',
							'id' => '' 
					) 
			) 
	);
	$field_groups ['group_focus|node|hrm_klasbezoek|default'] = $field_group;
	
	$field_group = new stdClass ();
	$field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
	$field_group->api_version = 1;
	$field_group->identifier = 'group_focus|node|hrm_klasbezoek|form';
	$field_group->group_name = 'group_focus';
	$field_group->entity_type = 'node';
	$field_group->bundle = 'hrm_klasbezoek';
	$field_group->mode = 'form';
	$field_group->parent_name = '';
	$field_group->data = array (
			'label' => 'Focus',
			'weight' => '4',
			'children' => array (
					0 => 'field_klasbezoek_ped_comp',
					1 => 'field_klasbezoek_did_comp',
					2 => 'field_klasbezoek_taalcomp',
					3 => 'field_klasbezoek_org_comp',
					4 => 'field_klasbezoek_andere_focus' 
			),
			'format_type' => 'fieldset',
			'format_settings' => array (
					'formatter' => 'collapsible',
					'instance_settings' => array (
							'description' => '',
							'classes' => 'group-focus field-group-fieldset',
							'required_fields' => 1,
							'id' => '' 
					) 
			) 
	);
	$field_groups ['group_focus|node|hrm_klasbezoek|form'] = $field_group;
	
	$field_group = new stdClass ();
	$field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
	$field_group->api_version = 1;
	$field_group->identifier = 'group_g1|node|hrm_evaluatiegesprek|default';
	$field_group->group_name = 'group_g1';
	$field_group->entity_type = 'node';
	$field_group->bundle = 'hrm_evaluatiegesprek';
	$field_group->mode = 'default';
	$field_group->parent_name = '';
	$field_group->data = array (
			'label' => '1. Plannen en voorbereiden van de lessen',
			'weight' => '3',
			'children' => array (
					0 => 'field_eg1_positieve_observaties',
					1 => 'field_eg1_werkpunten_afspraken' 
			),
			'format_type' => 'fieldset',
			'format_settings' => array (
					'formatter' => 'collapsible',
					'instance_settings' => array (
							'description' => '',
							'classes' => 'group-g1 field-group-fieldset',
							'id' => '' 
					) 
			) 
	);
	$field_groups ['group_g1|node|hrm_evaluatiegesprek|default'] = $field_group;
	
	$field_group = new stdClass ();
	$field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
	$field_group->api_version = 1;
	$field_group->identifier = 'group_g1|node|hrm_evaluatiegesprek|form';
	$field_group->group_name = 'group_g1';
	$field_group->entity_type = 'node';
	$field_group->bundle = 'hrm_evaluatiegesprek';
	$field_group->mode = 'form';
	$field_group->parent_name = '';
	$field_group->data = array (
			'label' => '1. Plannen en voorbereiden van de lessen',
			'weight' => '4',
			'children' => array (
					0 => 'field_eg1_positieve_observaties',
					1 => 'field_eg1_werkpunten_afspraken' 
			),
			'format_type' => 'fieldset',
			'format_settings' => array (
					'formatter' => 'collapsible',
					'instance_settings' => array (
							'description' => '',
							'classes' => 'group-g1 field-group-fieldset',
							'required_fields' => 1,
							'id' => '' 
					) 
			) 
	);
	$field_groups ['group_g1|node|hrm_evaluatiegesprek|form'] = $field_group;
	
	$field_group = new stdClass ();
	$field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
	$field_group->api_version = 1;
	$field_group->identifier = 'group_g2|node|hrm_evaluatiegesprek|default';
	$field_group->group_name = 'group_g2';
	$field_group->entity_type = 'node';
	$field_group->bundle = 'hrm_evaluatiegesprek';
	$field_group->mode = 'default';
	$field_group->parent_name = '';
	$field_group->data = array (
			'label' => '2. Efficiënt en leerlinggericht lesgeven',
			'weight' => '4',
			'children' => array (
					0 => 'field_eg2_positieve_observaties',
					1 => 'field_eg2_werkpunten_afspraken' 
			),
			'format_type' => 'fieldset',
			'format_settings' => array (
					'formatter' => 'collapsible',
					'instance_settings' => array (
							'description' => '',
							'classes' => 'group-g2 field-group-fieldset',
							'id' => '' 
					) 
			) 
	);
	$field_groups ['group_g2|node|hrm_evaluatiegesprek|default'] = $field_group;
	
	$field_group = new stdClass ();
	$field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
	$field_group->api_version = 1;
	$field_group->identifier = 'group_g2|node|hrm_evaluatiegesprek|form';
	$field_group->group_name = 'group_g2';
	$field_group->entity_type = 'node';
	$field_group->bundle = 'hrm_evaluatiegesprek';
	$field_group->mode = 'form';
	$field_group->parent_name = '';
	$field_group->data = array (
			'label' => '2. Efficiënt en leerlinggericht lesgeven',
			'weight' => '5',
			'children' => array (
					0 => 'field_eg2_positieve_observaties',
					1 => 'field_eg2_werkpunten_afspraken' 
			),
			'format_type' => 'fieldset',
			'format_settings' => array (
					'formatter' => 'collapsible',
					'instance_settings' => array (
							'description' => '',
							'classes' => 'group-g2 field-group-fieldset',
							'required_fields' => 1,
							'id' => '' 
					) 
			) 
	);
	$field_groups ['group_g2|node|hrm_evaluatiegesprek|form'] = $field_group;
	
	$field_group = new stdClass ();
	$field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
	$field_group->api_version = 1;
	$field_group->identifier = 'group_g3|node|hrm_evaluatiegesprek|default';
	$field_group->group_name = 'group_g3';
	$field_group->entity_type = 'node';
	$field_group->bundle = 'hrm_evaluatiegesprek';
	$field_group->mode = 'default';
	$field_group->parent_name = '';
	$field_group->data = array (
			'label' => '3. Begeleiden van de leerlingen',
			'weight' => '5',
			'children' => array (
					0 => 'field_eg3_positieve_observaties',
					1 => 'field_eg3_werkpunten_afspraken' 
			),
			'format_type' => 'fieldset',
			'format_settings' => array (
					'formatter' => 'collapsible',
					'instance_settings' => array (
							'description' => '',
							'classes' => 'group-g3 field-group-fieldset',
							'id' => '' 
					) 
			) 
	);
	$field_groups ['group_g3|node|hrm_evaluatiegesprek|default'] = $field_group;
	
	$field_group = new stdClass ();
	$field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
	$field_group->api_version = 1;
	$field_group->identifier = 'group_g3|node|hrm_evaluatiegesprek|form';
	$field_group->group_name = 'group_g3';
	$field_group->entity_type = 'node';
	$field_group->bundle = 'hrm_evaluatiegesprek';
	$field_group->mode = 'form';
	$field_group->parent_name = '';
	$field_group->data = array (
			'label' => '3. Begeleiden van de leerlingen',
			'weight' => '6',
			'children' => array (
					0 => 'field_eg3_positieve_observaties',
					1 => 'field_eg3_werkpunten_afspraken' 
			),
			'format_type' => 'fieldset',
			'format_settings' => array (
					'formatter' => 'collapsible',
					'instance_settings' => array (
							'description' => '',
							'classes' => 'group-g3 field-group-fieldset',
							'required_fields' => 1,
							'id' => '' 
					) 
			) 
	);
	$field_groups ['group_g3|node|hrm_evaluatiegesprek|form'] = $field_group;
	
	$field_group = new stdClass ();
	$field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
	$field_group->api_version = 1;
	$field_group->identifier = 'group_g4|node|hrm_evaluatiegesprek|default';
	$field_group->group_name = 'group_g4';
	$field_group->entity_type = 'node';
	$field_group->bundle = 'hrm_evaluatiegesprek';
	$field_group->mode = 'default';
	$field_group->parent_name = '';
	$field_group->data = array (
			'label' => '4. Evalueren van de leerlingen',
			'weight' => '6',
			'children' => array (
					0 => 'field_eg4_positieve_observaties',
					1 => 'field_eg4_werkpunten_afspraken' 
			),
			'format_type' => 'fieldset',
			'format_settings' => array (
					'formatter' => 'collapsible',
					'instance_settings' => array (
							'description' => '',
							'classes' => 'group-g4 field-group-fieldset',
							'id' => '' 
					) 
			) 
	);
	$field_groups ['group_g4|node|hrm_evaluatiegesprek|default'] = $field_group;
	
	$field_group = new stdClass ();
	$field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
	$field_group->api_version = 1;
	$field_group->identifier = 'group_g4|node|hrm_evaluatiegesprek|form';
	$field_group->group_name = 'group_g4';
	$field_group->entity_type = 'node';
	$field_group->bundle = 'hrm_evaluatiegesprek';
	$field_group->mode = 'form';
	$field_group->parent_name = '';
	$field_group->data = array (
			'label' => '4. Evalueren van de leerlingen',
			'weight' => '7',
			'children' => array (
					0 => 'field_eg4_positieve_observaties',
					1 => 'field_eg4_werkpunten_afspraken' 
			),
			'format_type' => 'fieldset',
			'format_settings' => array (
					'formatter' => 'collapsible',
					'instance_settings' => array (
							'description' => '',
							'classes' => 'group-g4 field-group-fieldset',
							'required_fields' => 1,
							'id' => '' 
					) 
			) 
	);
	$field_groups ['group_g4|node|hrm_evaluatiegesprek|form'] = $field_group;
	
	$field_group = new stdClass ();
	$field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
	$field_group->api_version = 1;
	$field_group->identifier = 'group_g5|node|hrm_evaluatiegesprek|default';
	$field_group->group_name = 'group_g5';
	$field_group->entity_type = 'node';
	$field_group->bundle = 'hrm_evaluatiegesprek';
	$field_group->mode = 'default';
	$field_group->parent_name = '';
	$field_group->data = array (
			'label' => '5. Opvoeden van de leerlingen',
			'weight' => '7',
			'children' => array (
					0 => 'field_eg5_positieve_observaties',
					1 => 'field_eg5_werkpunten_afspraken' 
			),
			'format_type' => 'fieldset',
			'format_settings' => array (
					'formatter' => 'collapsible',
					'instance_settings' => array (
							'description' => '',
							'classes' => 'group-g5 field-group-fieldset',
							'id' => '' 
					) 
			) 
	);
	$field_groups ['group_g5|node|hrm_evaluatiegesprek|default'] = $field_group;
	
	$field_group = new stdClass ();
	$field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
	$field_group->api_version = 1;
	$field_group->identifier = 'group_g5|node|hrm_evaluatiegesprek|form';
	$field_group->group_name = 'group_g5';
	$field_group->entity_type = 'node';
	$field_group->bundle = 'hrm_evaluatiegesprek';
	$field_group->mode = 'form';
	$field_group->parent_name = '';
	$field_group->data = array (
			'label' => '5. Opvoeden van de leerlingen',
			'weight' => '8',
			'children' => array (
					0 => 'field_eg5_positieve_observaties',
					1 => 'field_eg5_werkpunten_afspraken' 
			),
			'format_type' => 'fieldset',
			'format_settings' => array (
					'formatter' => 'collapsible',
					'instance_settings' => array (
							'description' => '',
							'classes' => 'group-g5 field-group-fieldset',
							'required_fields' => 1,
							'id' => '' 
					) 
			) 
	);
	$field_groups ['group_g5|node|hrm_evaluatiegesprek|form'] = $field_group;
	
	$field_group = new stdClass ();
	$field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
	$field_group->api_version = 1;
	$field_group->identifier = 'group_g6|node|hrm_evaluatiegesprek|default';
	$field_group->group_name = 'group_g6';
	$field_group->entity_type = 'node';
	$field_group->bundle = 'hrm_evaluatiegesprek';
	$field_group->mode = 'default';
	$field_group->parent_name = '';
	$field_group->data = array (
			'label' => '6. Meewerken aan de uitbouw van de school als organisatie',
			'weight' => '8',
			'children' => array (
					0 => 'field_eg6_positieve_observaties',
					1 => 'field_eg6_werkpunten_afspraken' 
			),
			'format_type' => 'fieldset',
			'format_settings' => array (
					'formatter' => 'collapsible',
					'instance_settings' => array (
							'description' => '',
							'classes' => 'group-g6 field-group-fieldset',
							'id' => '' 
					) 
			) 
	);
	$field_groups ['group_g6|node|hrm_evaluatiegesprek|default'] = $field_group;
	
	$field_group = new stdClass ();
	$field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
	$field_group->api_version = 1;
	$field_group->identifier = 'group_g6|node|hrm_evaluatiegesprek|form';
	$field_group->group_name = 'group_g6';
	$field_group->entity_type = 'node';
	$field_group->bundle = 'hrm_evaluatiegesprek';
	$field_group->mode = 'form';
	$field_group->parent_name = '';
	$field_group->data = array (
			'label' => '6. Meewerken aan de uitbouw van de school als organisatie',
			'weight' => '9',
			'children' => array (
					0 => 'field_eg6_positieve_observaties',
					1 => 'field_eg6_werkpunten_afspraken' 
			),
			'format_type' => 'fieldset',
			'format_settings' => array (
					'formatter' => 'collapsible',
					'instance_settings' => array (
							'description' => '',
							'classes' => 'group-g6 field-group-fieldset',
							'required_fields' => 1,
							'id' => '' 
					) 
			) 
	);
	$field_groups ['group_g6|node|hrm_evaluatiegesprek|form'] = $field_group;
	
	$field_group = new stdClass ();
	$field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
	$field_group->api_version = 1;
	$field_group->identifier = 'group_g7|node|hrm_evaluatiegesprek|default';
	$field_group->group_name = 'group_g7';
	$field_group->entity_type = 'node';
	$field_group->bundle = 'hrm_evaluatiegesprek';
	$field_group->mode = 'default';
	$field_group->parent_name = '';
	$field_group->data = array (
			'label' => '7. Overleggen en samenwerken',
			'weight' => '9',
			'children' => array (
					0 => 'field_eg7_positieve_observaties',
					1 => 'field_eg7_werkpunten_afspraken' 
			),
			'format_type' => 'fieldset',
			'format_settings' => array (
					'formatter' => 'collapsible',
					'instance_settings' => array (
							'description' => '',
							'classes' => 'group-g7 field-group-fieldset',
							'id' => '' 
					) 
			) 
	);
	$field_groups ['group_g7|node|hrm_evaluatiegesprek|default'] = $field_group;
	
	$field_group = new stdClass ();
	$field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
	$field_group->api_version = 1;
	$field_group->identifier = 'group_g7|node|hrm_evaluatiegesprek|form';
	$field_group->group_name = 'group_g7';
	$field_group->entity_type = 'node';
	$field_group->bundle = 'hrm_evaluatiegesprek';
	$field_group->mode = 'form';
	$field_group->parent_name = '';
	$field_group->data = array (
			'label' => '7. Overleggen en samenwerken',
			'weight' => '10',
			'children' => array (
					0 => 'field_eg7_positieve_observaties',
					1 => 'field_eg7_werkpunten_afspraken' 
			),
			'format_type' => 'fieldset',
			'format_settings' => array (
					'formatter' => 'collapsible',
					'instance_settings' => array (
							'description' => '',
							'classes' => 'group-g7 field-group-fieldset',
							'required_fields' => 1,
							'id' => '' 
					) 
			) 
	);
	$field_groups ['group_g7|node|hrm_evaluatiegesprek|form'] = $field_group;
	
	$field_group = new stdClass ();
	$field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
	$field_group->api_version = 1;
	$field_group->identifier = 'group_g8|node|hrm_evaluatiegesprek|default';
	$field_group->group_name = 'group_g8';
	$field_group->entity_type = 'node';
	$field_group->bundle = 'hrm_evaluatiegesprek';
	$field_group->mode = 'default';
	$field_group->parent_name = '';
	$field_group->data = array (
			'label' => '8. Uitvoeren van administratieve taken',
			'weight' => '10',
			'children' => array (
					0 => 'field_eg8_positieve_observaties',
					1 => 'field_eg8_werkpunten_afspraken' 
			),
			'format_type' => 'fieldset',
			'format_settings' => array (
					'formatter' => 'collapsible',
					'instance_settings' => array (
							'description' => '',
							'classes' => 'group-g8 field-group-fieldset',
							'id' => '' 
					) 
			) 
	);
	$field_groups ['group_g8|node|hrm_evaluatiegesprek|default'] = $field_group;
	
	$field_group = new stdClass ();
	$field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
	$field_group->api_version = 1;
	$field_group->identifier = 'group_g8|node|hrm_evaluatiegesprek|form';
	$field_group->group_name = 'group_g8';
	$field_group->entity_type = 'node';
	$field_group->bundle = 'hrm_evaluatiegesprek';
	$field_group->mode = 'form';
	$field_group->parent_name = '';
	$field_group->data = array (
			'label' => '8. Uitvoeren van administratieve taken',
			'weight' => '11',
			'children' => array (
					0 => 'field_eg8_positieve_observaties',
					1 => 'field_eg8_werkpunten_afspraken' 
			),
			'format_type' => 'fieldset',
			'format_settings' => array (
					'formatter' => 'collapsible',
					'instance_settings' => array (
							'description' => '',
							'classes' => 'group-g8 field-group-fieldset',
							'required_fields' => 1,
							'id' => '' 
					) 
			) 
	);
	$field_groups ['group_g8|node|hrm_evaluatiegesprek|form'] = $field_group;
	
	$field_group = new stdClass ();
	$field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
	$field_group->api_version = 1;
	$field_group->identifier = 'group_g9|node|hrm_evaluatiegesprek|default';
	$field_group->group_name = 'group_g9';
	$field_group->entity_type = 'node';
	$field_group->bundle = 'hrm_evaluatiegesprek';
	$field_group->mode = 'default';
	$field_group->parent_name = '';
	$field_group->data = array (
			'label' => '9. Nascholing',
			'weight' => '11',
			'children' => array (
					0 => 'field_eg9_positieve_observaties',
					1 => 'field_eg9_werkpunten_afspraken' 
			),
			'format_type' => 'fieldset',
			'format_settings' => array (
					'formatter' => 'collapsible',
					'instance_settings' => array (
							'description' => '',
							'classes' => 'group-g9 field-group-fieldset',
							'id' => '' 
					) 
			) 
	);
	$field_groups ['group_g9|node|hrm_evaluatiegesprek|default'] = $field_group;
	
	$field_group = new stdClass ();
	$field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
	$field_group->api_version = 1;
	$field_group->identifier = 'group_g9|node|hrm_evaluatiegesprek|form';
	$field_group->group_name = 'group_g9';
	$field_group->entity_type = 'node';
	$field_group->bundle = 'hrm_evaluatiegesprek';
	$field_group->mode = 'form';
	$field_group->parent_name = '';
	$field_group->data = array (
			'label' => '9. Nascholing',
			'weight' => '12',
			'children' => array (
					0 => 'field_eg9_positieve_observaties',
					1 => 'field_eg9_werkpunten_afspraken' 
			),
			'format_type' => 'fieldset',
			'format_settings' => array (
					'formatter' => 'collapsible',
					'instance_settings' => array (
							'description' => '',
							'classes' => 'group-g9 field-group-fieldset',
							'required_fields' => 1,
							'id' => '' 
					) 
			) 
	);
	$field_groups ['group_g9|node|hrm_evaluatiegesprek|form'] = $field_group;
	
	$field_group = new stdClass ();
	$field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
	$field_group->api_version = 1;
	$field_group->identifier = 'group_problemen_medewerkers|node|planningsgesprek|form';
	$field_group->group_name = 'group_problemen_medewerkers';
	$field_group->entity_type = 'node';
	$field_group->bundle = 'hrm_planningsgesprek';
	$field_group->mode = 'form';
	$field_group->parent_name = '';
	$field_group->data = array (
			'label' => 'Problemen medewerker',
			'weight' => '6',
			'children' => array (
					0 => 'field_pg_probleemidentificatie',
					1 => 'field_pg_eventuele_oplossing' 
			),
			'format_type' => 'fieldset',
			'format_settings' => array (
					'formatter' => 'collapsible',
					'instance_settings' => array (
							'description' => '',
							'classes' => 'group-problemen-medewerkers field-group-fieldset',
							'required_fields' => 1,
							'id' => '' 
					) 
			) 
	);
	$field_groups ['group_problemen_medewerkers|node|planningsgesprek|form'] = $field_group;
	
	// Translatables
	// Included for use with string extractors like potx.
	t ( '1. Plannen en voorbereiden van de lessen' );
	t ( '2. Efficiënt en leerlinggericht lesgeven' );
	t ( '3. Begeleiden van de leerlingen' );
	t ( '4. Evalueren van de leerlingen' );
	t ( '5. Opvoeden van de leerlingen' );
	t ( '6. Meewerken aan de uitbouw van de school als organisatie' );
	t ( '7. Overleggen en samenwerken' );
	t ( '8. Uitvoeren van administratieve taken' );
	t ( '9. Nascholing' );
	t ( 'Focus' );
	t ( 'Problemen medewerker' );
	
	return $field_groups;
}

