<?php
/*
 * Copyright (C) 2017 bartgysens
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* Drupal Hooks */

/**
 * Implements hook_ctools_plugin_api().
 */
function argus_lokalen_ctools_plugin_api($module = NULL, $api = NULL) {
	if ($module == "field_group" && $api == "field_group") {
		return array (
				"version" => "1" 
		);
	}
}

/**
 * Implements hook_node_info().
 */
function argus_lokalen_node_info() {
	$items = array (
			'lokaal' => array (
					'name' => t ( 'Lokaal' ),
					'base' => 'node_content',
					'description' => t ( 'Beheer je infrastructuur en je <em>lokalen</em>.' ),
					'has_title' => '1',
					'title_label' => t ( 'Title' ),
					'help' => '' 
			) 
	);
	drupal_alter ( 'node_info', $items );
	return $items;
}

/**
 * Implement hook_form()
 */
function argus_lokalen_form($node, $form_state) {
	return node_content_form ( $node, $form_state );
}

/**
 * Implementation of hook_views_api().
 */
function argus_lokalen_views_api() {
	return array (
			'api' => 3.0,
			'path' => drupal_get_path ( 'module', 'argus_lokalen' ) 
	) // replace demo with your content type
;
}

/**
 * Implementation of hook_views_default_views().
 *
 * Views export creates code that you have to paste in this function.
 *
 * Administration > Structure > Views : click the button behind the view you need and export
 * /admin/structure/views
 */
function argus_lokalen_views_default_views() {
	$view = new view ();
	$view->name = 'lokalen';
	$view->description = '';
	$view->tag = 'default';
	$view->base_table = 'node';
	$view->human_name = 'Lokalen';
	$view->core = 7;
	$view->api_version = '3.0';
	$view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */
	
	/* Display: Master */
	$handler = $view->new_display ( 'default', 'Master', 'default' );
	$handler->display->display_options ['title'] = 'Lokalen';
	$handler->display->display_options ['use_more_always'] = FALSE;
	$handler->display->display_options ['use_more_text'] = 'meer';
	$handler->display->display_options ['access'] ['type'] = 'perm';
	$handler->display->display_options ['cache'] ['type'] = 'views_content_cache';
	$handler->display->display_options ['cache'] ['results_min_lifespan'] = '-1';
	$handler->display->display_options ['cache'] ['results_max_lifespan'] = '518400';
	$handler->display->display_options ['cache'] ['output_min_lifespan'] = '-1';
	$handler->display->display_options ['cache'] ['output_max_lifespan'] = '518400';
	$handler->display->display_options ['cache'] ['keys'] = array (
			'comment' => array (
					'changed' => 0 
			),
			'node' => array (
					'lokaal' => 'lokaal' 
			),
			'node_only' => array (
					'node_changed' => 'node_changed' 
			) 
	);
	$handler->display->display_options ['query'] ['type'] = 'views_query';
	$handler->display->display_options ['exposed_form'] ['type'] = 'basic';
	$handler->display->display_options ['exposed_form'] ['options'] ['submit_button'] = 'Toepassen';
	$handler->display->display_options ['exposed_form'] ['options'] ['reset_button'] = TRUE;
	$handler->display->display_options ['exposed_form'] ['options'] ['reset_button_label'] = 'Opnieuw instellen';
	$handler->display->display_options ['exposed_form'] ['options'] ['exposed_sorts_label'] = 'Sorteren op';
	$handler->display->display_options ['exposed_form'] ['options'] ['sort_asc_label'] = 'Oplopend';
	$handler->display->display_options ['exposed_form'] ['options'] ['sort_desc_label'] = 'Aflopend';
	$handler->display->display_options ['exposed_form'] ['options'] ['autosubmit'] = FALSE;
	$handler->display->display_options ['pager'] ['type'] = 'none';
	$handler->display->display_options ['pager'] ['options'] ['offset'] = '0';
	$handler->display->display_options ['style_plugin'] = 'table';
	$handler->display->display_options ['style_options'] ['columns'] = array (
			'title' => 'title',
			'field_lokaal_afkorting' => 'field_lokaal_afkorting',
			'field_lokaal_beschrijving' => 'field_lokaal_beschrijving',
			'field_lokaal_capaciteit' => 'field_lokaal_capaciteit',
			'field_lokaal_type' => 'field_lokaal_type',
			'counter' => 'counter' 
	);
	$handler->display->display_options ['style_options'] ['default'] = 'title';
	$handler->display->display_options ['style_options'] ['info'] = array (
			'title' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_lokaal_afkorting' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_lokaal_beschrijving' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_lokaal_capaciteit' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			),
			'field_lokaal_type' => array (
					'sortable' => '1',
					'default_sort_order' => 'asc',
					'align' => 'views-align-left',
					'separator' => '',
					'empty_column' => 0 
			),
			'counter' => array (
					'align' => 'views-align-center',
					'separator' => '',
					'empty_column' => 0 
			) 
	);
	/* Veld: Algemeen: Resultatenteller weergeven */
	$handler->display->display_options ['fields'] ['counter'] ['id'] = 'counter';
	$handler->display->display_options ['fields'] ['counter'] ['table'] = 'views';
	$handler->display->display_options ['fields'] ['counter'] ['field'] = 'counter';
	$handler->display->display_options ['fields'] ['counter'] ['label'] = 'Nr.';
	$handler->display->display_options ['fields'] ['counter'] ['counter_start'] = '1';
	$handler->display->display_options ['fields'] ['counter'] ['reverse'] = 0;
	/* Veld: Inhoud: Titel */
	$handler->display->display_options ['fields'] ['title'] ['id'] = 'title';
	$handler->display->display_options ['fields'] ['title'] ['table'] = 'node';
	$handler->display->display_options ['fields'] ['title'] ['field'] = 'title';
	$handler->display->display_options ['fields'] ['title'] ['alter'] ['word_boundary'] = FALSE;
	$handler->display->display_options ['fields'] ['title'] ['alter'] ['ellipsis'] = FALSE;
	/* Veld: Inhoud: Afkorting */
	$handler->display->display_options ['fields'] ['field_lokaal_afkorting'] ['id'] = 'field_lokaal_afkorting';
	$handler->display->display_options ['fields'] ['field_lokaal_afkorting'] ['table'] = 'field_data_field_lokaal_afkorting';
	$handler->display->display_options ['fields'] ['field_lokaal_afkorting'] ['field'] = 'field_lokaal_afkorting';
	/* Veld: Inhoud: Beschrijving */
	$handler->display->display_options ['fields'] ['field_lokaal_beschrijving'] ['id'] = 'field_lokaal_beschrijving';
	$handler->display->display_options ['fields'] ['field_lokaal_beschrijving'] ['table'] = 'field_data_field_lokaal_beschrijving';
	$handler->display->display_options ['fields'] ['field_lokaal_beschrijving'] ['field'] = 'field_lokaal_beschrijving';
	/* Veld: Inhoud: Capaciteit */
	$handler->display->display_options ['fields'] ['field_lokaal_capaciteit'] ['id'] = 'field_lokaal_capaciteit';
	$handler->display->display_options ['fields'] ['field_lokaal_capaciteit'] ['table'] = 'field_data_field_lokaal_capaciteit';
	$handler->display->display_options ['fields'] ['field_lokaal_capaciteit'] ['field'] = 'field_lokaal_capaciteit';
	$handler->display->display_options ['fields'] ['field_lokaal_capaciteit'] ['settings'] = array (
			'thousand_separator' => ' ',
			'prefix_suffix' => 1 
	);
	/* Veld: Inhoud: Type */
	$handler->display->display_options ['fields'] ['field_lokaal_type'] ['id'] = 'field_lokaal_type';
	$handler->display->display_options ['fields'] ['field_lokaal_type'] ['table'] = 'field_data_field_lokaal_type';
	$handler->display->display_options ['fields'] ['field_lokaal_type'] ['field'] = 'field_lokaal_type';
	/* Sorteercriterium: Inhoud: Afkorting (field_lokaal_afkorting) */
	$handler->display->display_options ['sorts'] ['field_lokaal_afkorting_value'] ['id'] = 'field_lokaal_afkorting_value';
	$handler->display->display_options ['sorts'] ['field_lokaal_afkorting_value'] ['table'] = 'field_data_field_lokaal_afkorting';
	$handler->display->display_options ['sorts'] ['field_lokaal_afkorting_value'] ['field'] = 'field_lokaal_afkorting_value';
	/* Filtercriterium: Inhoud: Gepubliceerd */
	$handler->display->display_options ['filters'] ['status'] ['id'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['status'] ['field'] = 'status';
	$handler->display->display_options ['filters'] ['status'] ['value'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['group'] = 1;
	$handler->display->display_options ['filters'] ['status'] ['expose'] ['operator'] = FALSE;
	/* Filtercriterium: Inhoud: Type */
	$handler->display->display_options ['filters'] ['type'] ['id'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['table'] = 'node';
	$handler->display->display_options ['filters'] ['type'] ['field'] = 'type';
	$handler->display->display_options ['filters'] ['type'] ['value'] = array (
			'lokaal' => 'lokaal' 
	);
	/* Filtercriterium: Inhoud: Afkorting (field_lokaal_afkorting) */
	$handler->display->display_options ['filters'] ['field_lokaal_afkorting_value'] ['id'] = 'field_lokaal_afkorting_value';
	$handler->display->display_options ['filters'] ['field_lokaal_afkorting_value'] ['table'] = 'field_data_field_lokaal_afkorting';
	$handler->display->display_options ['filters'] ['field_lokaal_afkorting_value'] ['field'] = 'field_lokaal_afkorting_value';
	$handler->display->display_options ['filters'] ['field_lokaal_afkorting_value'] ['operator'] = 'contains';
	$handler->display->display_options ['filters'] ['field_lokaal_afkorting_value'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_lokaal_afkorting_value'] ['expose'] ['operator_id'] = 'field_lokaal_afkorting_value_op';
	$handler->display->display_options ['filters'] ['field_lokaal_afkorting_value'] ['expose'] ['label'] = 'Afkorting';
	$handler->display->display_options ['filters'] ['field_lokaal_afkorting_value'] ['expose'] ['operator'] = 'field_lokaal_afkorting_value_op';
	$handler->display->display_options ['filters'] ['field_lokaal_afkorting_value'] ['expose'] ['identifier'] = 'field_lokaal_afkorting_value';
	$handler->display->display_options ['filters'] ['field_lokaal_afkorting_value'] ['expose'] ['remember_roles'] = array ();
	/* Filtercriterium: Inhoud: Beschrijving (field_lokaal_beschrijving) */
	$handler->display->display_options ['filters'] ['field_lokaal_beschrijving_value'] ['id'] = 'field_lokaal_beschrijving_value';
	$handler->display->display_options ['filters'] ['field_lokaal_beschrijving_value'] ['table'] = 'field_data_field_lokaal_beschrijving';
	$handler->display->display_options ['filters'] ['field_lokaal_beschrijving_value'] ['field'] = 'field_lokaal_beschrijving_value';
	$handler->display->display_options ['filters'] ['field_lokaal_beschrijving_value'] ['operator'] = 'contains';
	$handler->display->display_options ['filters'] ['field_lokaal_beschrijving_value'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_lokaal_beschrijving_value'] ['expose'] ['operator_id'] = 'field_lokaal_beschrijving_value_op';
	$handler->display->display_options ['filters'] ['field_lokaal_beschrijving_value'] ['expose'] ['label'] = 'Beschrijving';
	$handler->display->display_options ['filters'] ['field_lokaal_beschrijving_value'] ['expose'] ['operator'] = 'field_lokaal_beschrijving_value_op';
	$handler->display->display_options ['filters'] ['field_lokaal_beschrijving_value'] ['expose'] ['identifier'] = 'field_lokaal_beschrijving_value';
	$handler->display->display_options ['filters'] ['field_lokaal_beschrijving_value'] ['expose'] ['remember_roles'] = array ();
	/* Filtercriterium: Inhoud: Capaciteit (field_lokaal_capaciteit) */
	$handler->display->display_options ['filters'] ['field_lokaal_capaciteit_value'] ['id'] = 'field_lokaal_capaciteit_value';
	$handler->display->display_options ['filters'] ['field_lokaal_capaciteit_value'] ['table'] = 'field_data_field_lokaal_capaciteit';
	$handler->display->display_options ['filters'] ['field_lokaal_capaciteit_value'] ['field'] = 'field_lokaal_capaciteit_value';
	$handler->display->display_options ['filters'] ['field_lokaal_capaciteit_value'] ['operator'] = 'between';
	$handler->display->display_options ['filters'] ['field_lokaal_capaciteit_value'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_lokaal_capaciteit_value'] ['expose'] ['operator_id'] = 'field_lokaal_capaciteit_value_op';
	$handler->display->display_options ['filters'] ['field_lokaal_capaciteit_value'] ['expose'] ['label'] = 'Capaciteit';
	$handler->display->display_options ['filters'] ['field_lokaal_capaciteit_value'] ['expose'] ['use_operator'] = TRUE;
	$handler->display->display_options ['filters'] ['field_lokaal_capaciteit_value'] ['expose'] ['operator_label'] = 'Vergelijking';
	$handler->display->display_options ['filters'] ['field_lokaal_capaciteit_value'] ['expose'] ['operator'] = 'field_lokaal_capaciteit_value_op';
	$handler->display->display_options ['filters'] ['field_lokaal_capaciteit_value'] ['expose'] ['identifier'] = 'field_lokaal_capaciteit_value';
	$handler->display->display_options ['filters'] ['field_lokaal_capaciteit_value'] ['expose'] ['remember_roles'] = array ();
	/* Filtercriterium: Inhoud: Type (field_lokaal_type) */
	$handler->display->display_options ['filters'] ['field_lokaal_type_value'] ['id'] = 'field_lokaal_type_value';
	$handler->display->display_options ['filters'] ['field_lokaal_type_value'] ['table'] = 'field_data_field_lokaal_type';
	$handler->display->display_options ['filters'] ['field_lokaal_type_value'] ['field'] = 'field_lokaal_type_value';
	$handler->display->display_options ['filters'] ['field_lokaal_type_value'] ['exposed'] = TRUE;
	$handler->display->display_options ['filters'] ['field_lokaal_type_value'] ['expose'] ['operator_id'] = 'field_lokaal_type_value_op';
	$handler->display->display_options ['filters'] ['field_lokaal_type_value'] ['expose'] ['label'] = 'Type';
	$handler->display->display_options ['filters'] ['field_lokaal_type_value'] ['expose'] ['operator'] = 'field_lokaal_type_value_op';
	$handler->display->display_options ['filters'] ['field_lokaal_type_value'] ['expose'] ['identifier'] = 'field_lokaal_type_value';
	$handler->display->display_options ['filters'] ['field_lokaal_type_value'] ['expose'] ['multiple'] = TRUE;
	$handler->display->display_options ['filters'] ['field_lokaal_type_value'] ['expose'] ['remember_roles'] = array ();
	$handler->display->display_options ['filters'] ['field_lokaal_type_value'] ['reduce_duplicates'] = TRUE;
	
	/* Display: Overzicht */
	$handler = $view->new_display ( 'page', 'Overzicht', 'lokaal_overzicht' );
	$handler->display->display_options ['display_description'] = 'Overzicht van alle lokalen.';
	$handler->display->display_options ['exposed_block'] = TRUE;
	$handler->display->display_options ['qtip_instance'] = 'standaard';
	$handler->display->display_options ['path'] = 'lokalen/overzicht';
	$handler->display->display_options ['menu'] ['type'] = 'normal';
	$handler->display->display_options ['menu'] ['title'] = 'Lokalen';
	if (menu_load ( 'menu-modules' )) {
		$menu = 'menu-modules';
	} else {
		$menu = 'navigation';
	}
	$handler->display->display_options ['menu'] ['name'] = $menu;
	$translatables ['lokalen'] = array (
			t ( 'Master' ),
			t ( 'Lokalen' ),
			t ( 'meer' ),
			t ( 'Toepassen' ),
			t ( 'Opnieuw instellen' ),
			t ( 'Sorteren op' ),
			t ( 'Oplopend' ),
			t ( 'Aflopend' ),
			t ( 'Nr.' ),
			t ( 'Titel' ),
			t ( 'Afkorting' ),
			t ( 'Beschrijving' ),
			t ( 'Capaciteit' ),
			t ( 'Type' ),
			t ( 'Vergelijking' ),
			t ( 'Overzicht' ),
			t ( 'Overzicht van alle lokalen.' ) 
	);
	
	$views [$view->name] = $view;
	return $views;
}